### PR TITLE
NSFS | NC | Remove Email from NSFS Account and Bucket in manage_nsfs (CLI)

### LINKED ISSUE #7766: NSFS | NC | CLI | Deprecate email from CLI
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. The following CLI commands require an account email address - 
Account's email address being used on account add/update - 

```
sudo node src/cmd/manage_nsfs account add --name account1 --email account1@noobaa.io --uid 0 --gid 0 --new_buckets_path /tmp/b1
```

```
sudo node src/cmd/manage_nsfs account update --name account1 --email account2@noobaa.io --uid 0 --gid 0 --new_buckets_path /tmp/b1
```

Bucket's owner email address also being used on bucket add/update - 
```
sudo node src/cmd/manage_nsfs bucket add  --name bucket2 --email account1@noobaa.io --path /tmp/b1
````

```
sudo node src/cmd/manage_nsfs bucket update  --name bucket2 --email account2@noobaa.io
```

We would like to remove these references and replace them with account name.
### Expected behavior
1. replace these email references with account's name.
This is the first step towards https://github.com/noobaa/noobaa-core/issues/7734 which is the full solution.

### Steps to reproduce
1. mentioned above.

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. Remove email from NSFS account and bucket mainly in manage CLI commands:
In account command - remove it
In bucket command replace it with the flag `--owner` and set the account name in it.
3. Remove tests related to email, and update existing tests.
4. Remove the email mentioned in the documentation related to manage NSFS.
5. Increase timeouts in `test_s3_encryption.js` (not related to this PR, but could not pass the CI).

### Issues: Fixed #7766 
1. Currently we use email as a flag in account add/update and bucket add/update, this code change is for fixing the issue (it is a temporary solution towards using only the account ID).

List of GAPs I'm aware of:
1. GAP - We would still have the email in the schema and it will be the output of json account (opened issue #7811).
2. GAP - After this change, we can improve the performance of `verify_bucket_owner` and lookup the `bucket_owner` has a config file (moved to use the account name).
3. GAP - in many places, I set the value of `system_owner` as the account name (there is open issue #7793).
4. GAP - in the documentation of NSFS NC we need to explain the account creation before bucket creation.

### Testing Instructions:
1. Manual test - now do not use `--flag` email, for example:
- First, create the `FS_ROOT` and a directory for a bucket: `mkdir -p /tmp/nsfs_root1/my-bucket` and give permissions `chmod 777 /tmp/nsfs_root1/my-bucket`.
This will be the argument for:
  - `new_buckets_path` flag  `/tmp/nsfs_root1` (that we will use in the account commands)
  - `path` in the buckets commands `/tmp/nsfs_root1/my-bucket` (that we will use in bucket commands).
- account add: `sudo node src/cmd/manage_nsfs account add --name <account-name> --new_buckets_path /tmp/nsfs_root1 --uid <uid> --gid <gid>` (no `--email` flag).
- bucket add: `sudo node src/cmd/manage_nsfs bucket add --name <bucket-name> --owner <account-name> --path /tmp/nsfs_root1/my-bucket`
2. For running tests that were updated, please run:
- `sudo npx jest test_nc_nsfs_account_cli.test.js`
- `sudo npx jest test_nc_nsfs_bucket_cli.test.js`
- `sudo node ./node_modules/.bin/_mocha src/test/unit_tests/test_nc_nsfs_cli.js`
- `npx jest test_nc_nsfs_account_schema_validation.test.js`
- `npx jest test_nc_nsfs_bucket_schema_validation.test.js`
3. For checking the NSFS NC as it run in the CI: `make run-nc-tests CONTAINER_PLATFORM=linux/arm64` (the env `CONTAINER_PLATFORM=linux/arm64` is used because I have Mac). If you wish to run only specific tests, for example:
- `sudo NC_CORETEST=true node ./node_modules/mocha/bin/mocha ./src/test/unit_tests/test_bucketspace_fs.js`
Note: run it without the NSFS server working (ctrl + C to sudo node src/cmd/nsfs).
- `sudo NC_CORETEST=true node ./node_modules/mocha/bin/mocha ./src/test/unit_tests/test_bucketspace.js` 

- [X] Doc updated
- [ ] Tests added

### CODE REVIEW

File: src/server/system_services/schemas/nsfs_account_schema.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ module.exports = {
     required: [
         '_id',
         'name',
-        'email',
+        'email', // temp, keep the email internally
```
Comment (romayalon) [inline src/server/system_services/schemas/nsfs_account_schema.js:10]: why do we still need to keep it internally?

File: src/test/unit_tests/test_nc_nsfs_cli.js [hunk 2]
```diff
@@ -315,17 +309,6 @@ mocha.describe('manage_nsfs cli', function() {
             }
         });
 
-        mocha.it('cli bucket update owner email', async function() {
```
Comment (romayalon) [inline src/test/unit_tests/test_nc_nsfs_cli.js:318]: can you keep it and just replace the email with owner? 
I see I added here a validation for the creation date not getting changed on update

Comment (shirady) [reply src/test/unit_tests/test_nc_nsfs_cli.js:318]: Sure, thanks, I changed it to owner update instead of email.
If you want we can create a test for the validation of the creation date not getting changed on update so it would be clear.

File: src/server/system_services/schemas/nsfs_account_schema.js (hunk 1 above)
Comment (shirady) [reply src/server/system_services/schemas/nsfs_account_schema.js:10]: I had issues with tests `test_bucketspace_fs.js`, `test_bucketspace.js`, and `NSFS Ceph S3 tests` when I removed the email from the account totally, so I decided to remove the email in steps. Since the schedule is tight I published the PR with the first step which is removing the email flag from the end user, and keeping it internally. I will try it again.

Comment (romayalon) [reply src/server/system_services/schemas/nsfs_account_schema.js:10]: alright, what was the issue you saw?

Comment (shirady) [reply src/server/system_services/schemas/nsfs_account_schema.js]: I fixed it, you can see that the tests are passing in the CI (the fix is in 2 separate commits, hopefully for easier code review).

File: src/endpoint/s3/s3_rest.js [hunk 3]
```diff
@@ -226,22 +226,23 @@ async function authorize_request_policy(req) {
     }
 
     const account = req.object_sdk.requesting_account;
-    const is_system_owner = account.email.unwrap() === system_owner.unwrap();
+    // in NSFS NC we don't use email as account identifier
+    const account_identifier = req.object_sdk.nsfs_config_root ? account.name.unwrap() : account.email.unwrap();
```
Comment (romayalon) [inline src/endpoint/s3/s3_rest.js:230]: I suspect that there are more places we will need to do that, for example, what about has_bucket_action_permission()?

Comment (shirady) [reply src/endpoint/s3/s3_rest.js:230]: Suspicion is good, we need to plan this change better.

In your example:
https://github.com/noobaa/noobaa-core/blob/32b799e778db9df2bff1ffeaab628d8442c11426/src/server/common_services/auth_server.js#L673-L698

There are a couple of lines that I don't understand how will they work with current configurations:
`bucket.system.owner.email.unwrap()` - in our NSFS NC bucket we don't have a system reference, but `system_owner` is a string, same with `bucket.owner_account.email.unwrap()` we don't have email as a property for the owner_account it is a string.

Comment (shirady) [reply src/endpoint/s3/s3_rest.js]: As discussed, I will remove the last 2 commits - the removal of email in schema and internal functions in noobaa will be a gap. In this PR I will only remove the email as a flag that I receive from the user.

**Review by romayalon — APPROVED** [review]

File: src/cmd/manage_nsfs.js [hunk 4]
```diff
@@ -212,7 +212,7 @@ async function add_bucket(data) {
 /** verify_bucket_owner will check if the bucket_owner has an account
  * after it finds one, it returns the account id, otherwise it would throw an error
  * (in case the action is add bucket it also checks that the owner has allow_bucket_creation)
- * @param {string} bucket_owner
+ * @param {string} bucket_owner account name
```
[the remark this answers is not in the document]
Comment (shirady) [reply src/cmd/manage_nsfs.js:226]: @naveenpaul1, it was not an accident, I added it to describe the variable.
But if it seems like an accident, it should be removed or refactored.
