### PR TITLE
Verify and upgrade k8s pool pod images on brain startup

### LINKED ISSUE #5772: k8s pool did not update image after brain upgrade
### Environment info
- NooBaa Version: **5.2.0**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1**

### Actual behavior
1. Upgrading the NooBaa brain (by changing the image for the brain) will not update the image for any pod that is part of k8s pool statefulset

### Expected behavior
1. Updating the brain image should update the image for all k8s pool statefulsets

### Steps to reproduce
1.

### PR DESCRIPTION
**Pull request by nb-ohad**
### Explain the changes
1.  Update the all k8s pool (hosts pool) statefulset on the pool server init to match the brain image.

### Issues: Fixed #xxx / Gap #xxx
1. fixes #5772 

### Testing Instructions:
1.

### CODE REVIEW

**Review by nimrod-becker — APPROVED** [review]

File: src/server/system_services/pool_controllers.js [hunk 1]
```diff
@@ -117,6 +121,26 @@ class ManagedStatefulSetPoolController extends PoolController {
...
+            'StatefulSet',
+            this._statefulset_name,
+            { spec: { template: { spec: { containers: [{ name: 'noobaa-agent', image }] } } } }
+        );
+
+        const pods = await this._list_pods();
+        await Promise.all(pods.map(async pod => {
+            const pod_name = pod.metadata.name;
+            return kube_utils.wait_for_condition('pod', pod_name, 'ready', 15 * 60 * 1000);
+        }));
```
Comment (dannyzaken) [inline src/server/system_services/pool_controllers.js]: do we really need to wait for the agents to be ready? this can block the entire server from starting in case there is a problem in one of the agents

Comment (dannyzaken) [reply src/server/system_services/pool_controllers.js]: never mind. I see now that pool_server init does not wait

**Review by dannyzaken — APPROVED** [review]
