### PR TITLE
Auth_server: create_auth will pass expiry option to make_auth_token

### LINKED ISSUE #6536: Auth token not expiring after reaching the expiry time .
### Environment info
[root@noobaa-28april-inf hpoapp]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210520
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0

Openshift version:
[root@noobaa-28april-inf hpoapp]# oc version
Client Version: 4.7.4
Server Version: 4.7.4
Kubernetes Version: v1.20.0+bafe72f

### Actual behavior
Setting the expiry time in create_auth Api. But the token is not getting expired after reaching the expiry time

### Expected behavior
1.Token should be expired after reaching  the expiry time. User  should not able to use the token after reaching the expiry time

### Steps to reproduce
1.Hit the create_auth rpc with expiry 60 seconds.
```
curl -k -i https://<hostname>:30366/rpc/ -d '{"api":"auth_api","method":"create_auth","params":{"email":"admin@noobaa.io","password":"<password>","role":"admin","system":"noobaa","expiry":60}}'
```

Response:
{"op":"res","reqid":"1@https://::ffff:10.254.16.1:1122(528cquk79u)","took":65.83754098415375,"reply":{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoiNjBhNzk0YzRiZGE2OWEwMDIyYThlMDQyIiwic3lzdGVtX2lkIjoiNjBhNzk0YzRiZGE2OWEwMDIyYThlMDQzIiwicm9sZSI6ImFkbWluIiwiYXV0aG9yaXplZF9ieSI6Im5vb2JhYSIsImlhdCI6MTYyMjEwOTQxNH0.GaWrdhpKuXzVuclh3g_26m5WjpszedLXnMGdv5_BUvw","info":{"authorized_by":"noobaa","role":"admin","account":{"name":"noobaa","email":"admin@noobaa.io"},"system":{"name":"noobaa"}}}}

2.Hit other API using this auth token .it works .
```
curl -k -i https://<hostname>:30366/rpc/ -d '{"api":"account_api","method":"list_accounts","auth_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoiNjBhNzk0YzRiZGE2OWEwMDIyYThlMDQyIiwic3lzdGVtX2lkIjoiNjBhNzk0YzRiZGE2OWEwMDIyYThlMDQzIiwicm9sZSI6ImFkbWluIiwiYXV0aG9yaXplZF9ieSI6Im5vb2JhYSIsImlhdCI6MTYyMjEwOTQxNH0.GaWrdhpKuXzVuclh3g_26m5WjpszedLXnMGdv5_BUvw","params":{"filter": {"fs_identity": {"uid":11,"gid":22}}}}'
```

3.After reaching the expiry time auth_token should be expired but it works. Hit other API after 1 minute gives the response.

```
curl -k -i https://<hostname>:30366/rpc/ -d '{"api":"account_api","method":"list_accounts","auth_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoiNjBhNzk0YzRiZGE2OWEwMDIyYThlMDQyIiwic3lzdGVtX2lkIjoiNjBhNzk0YzRiZGE2OWEwMDIyYThlMDQzIiwicm9sZSI6ImFkbWluIiwiYXV0aG9yaXplZF9ieSI6Im5vb2JhYSIsImlhdCI6MTYyMjEwOTQxNH0.GaWrdhpKuXzVuclh3g_26m5WjpszedLXnMGdv5_BUvw","params":{"filter": {"fs_identity": {"uid":11,"gid":22}}}}'

Response:
{"op":"res","reqid":"1@https://::ffff:10.254.16.1:30305(532akbukk7)","took":0.339044988155365,"reply":{"accounts":[{"name":"sumit11","email":"sumit11","access_keys":[{"access_key":"JEnMP7LIhpL8hiuTeGiZ","secret_key":"FVLEGM9+QBK4rJ9w3EZTgV9UyS/T+MU4h2T5WG0m"}],"has_login":false,"has_s3_access":true,"allowed_buckets":{"full_permission":true},"default_resource":"system-internal-storage-pool-60a794c4bda69a0022a8e043","can_create_buckets":true,"nsfs_account_config":{"uid":11,"gid":22,"new_buckets_path":"/dir/"},"systems":[{"name":"noobaa","roles":["admin"]}],"external_connections":{"count":0,"connections":[]},"preferences":{"ui_theme":"DARK"}}]}}
```

### PR DESCRIPTION
**Pull request by jackyalbo**
Signed-off-by: jackyalbo <jacky.albo@gmail.com>

### Explain the changes
1. 

### Issues: Fixed #xxx / Gap #xxx
1.  Fixed #6536 

### Testing Instructions:
1.

### CODE REVIEW

File: src/server/common_services/auth_server.js [hunk 1]
```diff
@@ -139,14 +139,15 @@ function create_auth(req) {
                 system_id: system && system._id,
                 role: role_name,
                 extra: req.rpc_params.extra,
+                expiry: req.rpc_params.expiry,
```
Comment (jeniawhite) [inline src/server/common_services/auth_server.js:142]: You have this declaration above at the beginning of the function:
```
    // var expiry = req.rpc_params.expiry;
```
Maybe remove it or use it?

**Review by jeniawhite — APPROVED** [review]

File: src/server/common_services/auth_server.js (hunk 1 above)
Comment (jackyalbo) [reply src/server/common_services/auth_server.js:141]: Will remove. Thanks
