### PR TITLE
delegation removal for s3

### LINKED ISSUE #5731: block_store_client delegation low performance
### Environment info
- NooBaa Version: **5.1.1**
- Platform: **OpenShift 4.1**
- CC: @shekharberry

### Actual behavior
1. The delegation flow always calls to the hosted agent in order to return a signed_url or sdk params and perform the usage updates, but this call is causing a major drop in throughput performance.
2. Single stream write throughput on a bucket with AWS S3 backing store is currently 20-40 MB/sec.
3. By hacking and removing this intermediate RPC call and also tweaking the pipeline watermarks to 50 (see below) a single stream write throughput got to 220 MB/sec which is more like what AWS S3 can provide from that host.

### Expected behavior
1. Should get rid of the intermediate RPC call of delegation.
2. Should tweak the pipeline watermarks of splitter + coder and coalescer to 50 and the watermark of the uploader to 4 (object_io::_upload_stream_internal)
3. Config IO_WRITE_CONCURRENCY_AGENT should split to PV agent and cloud agent - cloud should be 128

### Steps to reproduce
1. Run s3cat from within the server pod:
```
time node src/tools/s3cat.js --endpoint http://127.0.0.1:6001 --bucket testbucket --sig v2 --size 2000 --put
```

### PR DESCRIPTION
**Pull request by jackyalbo**
### Explain the changes
1. due to performance issues remove call to s3 delegations
2. replaced the call for delegation with one request for s3 params. to be later used for all next read/write operations
3. saving to io_usage in the block_store_client, periodically updating the agent 
4. other performance fixes like bigger watermarks and larger semaphore for s3 agents

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #5731

### Testing Instructions:
1. run the s3cat as seen in issue #5731 - observe better performance than in previous versions

### CODE REVIEW

File: src/agent/block_store_services/block_store_base.js [hunk 1]
```diff
@@ -326,11 +363,7 @@ class BlockStoreBase {
     }
 
     _get_block_internal_dir(block_id) {
-        let hex_str_regex = /^[0-9a-fA-f]+$/;
-        let internal_dir = hex_str_regex.test(block_id) ?
-            block_id.substring(block_id.length - 3) + '.blocks' :
-            'other.blocks';
-        return internal_dir;
+        return get_block_internal_dir(block_id);
```
Comment (guymguym) [inline src/agent/block_store_services/block_store_base.js]: how about getting rid of `this._get_block_internal_dir()` and replace any occurrences with `block_store_base.get_block_internal_dir()`

File: config.js [hunk 2]
```diff
@@ -287,6 +288,7 @@ config.STATISTICS_COLLECTOR_EXPIRATION = 31 * 24 * 60 * 60 * 1000; // 1 month
 config.SERVICES_TYPES = Object.freeze(['AWS', 'AZURE', 'S3_COMPATIBLE', 'GOOGLE', 'FLASHBLADE']);
 config.USAGE_AGGREGATOR_INTERVAL = 24 * 60 * 60 * 1000; // 24 hours
 
+config.USAGE_UPDATE_INTERVAL = 1 * 60 * 1000; // 1 minute
```
Comment (guymguym) [inline config.js]: I suggest a more specific name:
```suggestion
config.BLOCK_STORE_USAGE_INTERVAL = 1 * 60 * 1000; // 1 minute
```

File: src/agent/block_store_services/block_store_client.js [hunk 3]
```diff
@@ -120,52 +119,51 @@ class BlockStoreClient {
...
-                        };
-
-                        const res = await P.fromCallback(callback => request(req_options, callback));
-
-                        // if not OK parse the error and throw Error object
-                        if (res.statusCode !== 200) {
-                            await this._throw_s3_err(res);
-                        }
-
+                    if (!this.block_to_creds) {
```
Comment (guymguym) [inline src/agent/block_store_services/block_store_client.js]: This is a map that never expires....
We should change this to use `LRUCache`.

File: src/agent/block_store_services/block_store_client.js [hunk 4]
```diff
@@ -120,52 +119,51 @@ class BlockStoreClient {
         const { timeout = config.IO_WRITE_BLOCK_TIMEOUT } = options;
         const { block_md } = params;
         const data = params[RPC_BUFFERS].data;
+        let usage;
 
         return P.resolve()
```
Comment (guymguym) [inline src/agent/block_store_services/block_store_client.js]: Can you get rid of this and make the function async?

File: src/agent/block_store_services/block_store_client.js [hunk 5]
```diff
@@ -177,91 +175,90 @@ class BlockStoreClient {
...
                 }
             })
             .timeout(timeout);
 
     }
 
+    async _update_usage_stats(rpc_client, usage, options, read_or_write) {
+        const now = Date.now();
+        if (!this.report_interval) {
+            this.report_interval = setInterval(async () => {
```
Comment (guymguym) [inline src/agent/block_store_services/block_store_client.js]: Move to ctor

**Review by guymguym — CHANGES_REQUESTED** [review]
Also please convert block_store_azure and block_store_google to use this model, and cleanup the old delegation code.

**Review by dannyzaken — CHANGES_REQUESTED** [review]

File: src/agent/block_store_services/block_store_client.js (hunk 3 above)
Comment (dannyzaken) [reply src/agent/block_store_services/block_store_client.js]: does `LRUCache` really fit here? the block_to_creds also holds the usage counter, so before any invalidation, there is a need to send it to the block store, which makes it a bit more complicated. we don't expect to have too many cloud resources

File: src/agent/block_store_services/block_store_client.js [hunk 6]
```diff
@@ -120,52 +119,51 @@ class BlockStoreClient {
...
+                    usage = data_length ? {
+                        size: (block_md.is_preallocated ? 0 : data_length) + encoded_md.length,
+                        count: block_md.is_preallocated ? 0 : 1
+                    } : { size: 0, count: 0 };
+                    this._update_usage_stats(rpc_client, usage, options, 'WRITE');
                 } catch (err) {
-                    dbg.error('encountered error on _delegate_write_block_s3:', err);
-                    const error = _.pick(err, 'message', 'code');
-                    return rpc_client.block_store.handle_delegator_error({ error, usage, op_type: 'WRITE' }, options);
+                    dbg.error('BlockStoreS3 operation failed:', err, _.omit(this.block_to_creds[options.address], 'access_keys'));
```
Comment (dannyzaken) [inline src/agent/block_store_services/block_store_client.js]: on failures, and specifically `AccessDenied`, try to get the credentials again and retry

File: src/sdk/map_client.js [hunk 7]
```diff
@@ -294,7 +295,8 @@ class MapClient {
      * @param {Buffer} buffer
      */
     async write_block(block_md, buffer) {
-        await block_write_sem_agent.surround_key(String(block_md.node), async () =>
+        const write_sem_agent = block_md.node_type === 'BLOCK_STORE_S3' ? block_write_sem_agent_cloud : block_write_sem_agent;
```
[the remark this answers is not in the document]
Comment (jackyalbo) [reply src/sdk/map_client.js]: reversed the order

File: src/agent/block_store_services/block_store_client.js (hunk 3 above)
Comment (jackyalbo) [reply src/agent/block_store_services/block_store_client.js]: LRUCache for the creds, simple map for io_stats

File: src/agent/block_store_services/block_store_client.js [hunk 8]
```diff
@@ -177,91 +175,90 @@ class BlockStoreClient {
...
     }
 
+    async _update_usage_stats(rpc_client, usage, options, read_or_write) {
+        const now = Date.now();
+        if (!this.report_interval) {
+            this.report_interval = setInterval(async () => {
+                await this.send_usage_stats(rpc_client);
+            }, config.USAGE_UPDATE_INTERVAL).unref();
+        }
+        if (!this.last_update) this.last_update = now;
```
[the remark this answers is not in the document]
Comment (jackyalbo) [reply src/agent/block_store_services/block_store_client.js]: old leftovers - removed

File: src/agent/block_store_services/block_store_client.js (hunk 6 above)
Comment (jackyalbo) [reply src/agent/block_store_services/block_store_client.js]: for both AccessDenied and STORAGE_NOT_EXIST did a LRUCache invalidate_key

File: src/agent/block_store_services/block_store_azure.js [hunk 9]
```diff
@@ -53,6 +53,17 @@ class BlockStoreAzure extends BlockStoreBase {
...
+            connection_string: this.cloud_info.azure.connection_string,
+        };
+        return {
+            connection_params,
+            target_bucket: this.cloud_info.target_bucket,
+            blocks_path: this.blocks_path,
+        };
+    }
+
     _delegate_read_block(block_md) {
```
Comment (dannyzaken) [inline src/agent/block_store_services/block_store_azure.js]: do we still need the old `delegate_read_block` and `delegate_write_block`?

File: src/agent/block_store_services/block_store_client.js [hunk 10]
```diff
@@ -1,20 +1,28 @@
...
-const { RPC_BUFFERS } = require('../../rpc');
-
-
+const { RPC_BUFFERS, RpcError } = require('../../rpc');
+const { get_block_internal_dir } = require('../../agent/block_store_services/block_store_base');
+
+const block_store_info_cache = new LRUCache({
+    name: 'BlockStoreInfoCache',
+    max_usage: 1000,
+    expiry_ms: 2 * 60 * 1000,
```
Comment (dannyzaken) [inline src/agent/block_store_services/block_store_client.js]: I think we can allow more than 2 minutes before expiry. maybe 10? ✋🤚

File: src/agent/block_store_services/block_store_client.js [hunk 11]
```diff
@@ -48,218 +62,219 @@ class BlockStoreClient {
...
+            this.io_stats[address].read_bytes += usage.size;
+        } else {
+            throw new Error('_update_usage_stats should except READ or WRITE only');
+        }
+    }
 
+    async send_usage_stats() {
+        for (const address in this.io_stats) {
+            if (this.io_stats[address]) {
+                const io_stats = _.clone(this.io_stats[address]);
```
Comment (dannyzaken) [inline src/agent/block_store_services/block_store_client.js]: no need to use`_.clone`

**Review by dannyzaken — APPROVED** [review]

File: src/agent/block_store_services/block_store_client.js (hunk 10 above)
Comment (jackyalbo) [reply src/agent/block_store_services/block_store_client.js]: kept on 2... we'll see in the future

File: src/agent/block_store_services/block_store_azure.js (hunk 9 above)
Comment (jackyalbo) [reply src/agent/block_store_services/block_store_azure.js]: removed the old code

File: src/agent/block_store_services/block_store_client.js [hunk 12]
```diff
@@ -43,223 +60,354 @@ class BlockStoreClient {
...
                 return this._delegate_read_block_azure(rpc_client, params, options);
+            case 'BLOCK_STORE_GOOGLE':
+                return this._delegate_read_block_google(rpc_client, params, options);
             default:
                 return rpc_client.block_store.read_block(params, options);
         }
     }
 
-    _delegate_write_block_azure(rpc_client, params, options) {
+    _write_to_stream(writable, buf) {
```
Comment (guymguym) [inline src/agent/block_store_services/block_store_client.js]: Better move this to stream_utils.js or buffer_utils.js

File: src/agent/block_store_services/block_store_client.js [hunk 13]
```diff
@@ -43,223 +60,354 @@ class BlockStoreClient {
...
+        let bs_info;
+        let bucket;
+        return promise_utils.timeout(async () => {
+            try {
+                bs_info = await block_store_info_cache.get_with_cache({ options, rpc_client });
+                if (!bs_info) throw new Error('couldn\'t resolve cloud credentials');
+                const google_params = bs_info.connection_params;
+                const block_id = block_md.id;
+                const block_dir = get_block_internal_dir(block_id);
+                const google = new Storage({
```
Comment (guymguym) [inline src/agent/block_store_services/block_store_client.js]: Best move this to occur once in the cache load

File: src/agent/block_store_services/block_store_client.js [hunk 14]
```diff
@@ -43,223 +60,354 @@ class BlockStoreClient {
...
+    }
 
+    async send_usage_stats() {
+        for (const address in this.io_stats) {
+            if (this.io_stats[address]) {
+                const rpc_client = this.io_stats[address].rpc_client;
+                const io_stats = _.omit(this.io_stats[address], 'rpc_client');
+                this.io_stats[address] = null;
+                await rpc_client.block_store.update_store_usage(io_stats, { address });
+            }
```
Comment (guymguym) [inline src/agent/block_store_services/block_store_client.js]: Missing try catch. 
Also need to set to null after successful send. 
Also better delete from Map instead of setting to null, so better use Map instead of plain object.
Also since this iteration is doing async calls it is best to first loop through and prepare a list of updates and then send them in Promise.all.
I would consider rewriting this function.

**Review by guymguym — APPROVED** [review]
Still few new comments but approving to avoid locking the PR.

File: src/agent/block_store_services/block_store_client.js (hunk 13 above)
Comment (jackyalbo) [reply src/agent/block_store_services/block_store_client.js]: didn't change for now. on next PR.

**Comment by nimrod-becker** [comment]
Checks passed (re-run due to rebase), merging
