### PR TITLE
NSFS | NC | CLI | Change the `fs_context`

### LINKED ISSUE #7875: NSFS | NC | Inconsistent Use of `config_root_backend` In `native_fs_utils.get_process_fs_context` In manage_nsfs
### Environment info
- NooBaa Version: master
- Platform: NSFS | NC

### Actual behavior
1. Currently, our code is not consistent with using the variable `config_root_backend`:
- Sometimes it is used: `native_fs_utils.get_process_fs_context(config_root_backend);`
- And sometimes it is not: `native_fs_utils.get_process_fs_context();`.

### Expected behavior
1. Use the variable `config_root_backend` in all usages of `native_fs_utils.get_process_fs_context` or clarify the reason for not using it.

### Steps to reproduce
1. none, internal.

### More information - Screenshots / Logs / Other output
none

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. Change the `native_fs_utils.get_process_fs_context` argument according to the path that we use:
- `config_root_backend` for access that is related to the configuration.
- `fs_backend` for access that is related to the FS (for example `path` in a bucket, `new_buckets_path` in an account).
- no argument for other cases (`from_file` path).
2. Fix the arguemnt of `fs_context` in `native_fs_utils.get_fs_context` to the `fs_backend` instead of `config_root_backend` before using the `is_dir_rw_accessible`.
3. Rename the argument from `config_root_backend` to `fs_backend` in function `get_fs_context`.

### Issues: Fixed #7875
1. Currently, our code is not consistent with using the `native_fs_utils.get_process_fs_context` argument.
2. Fix the `fs_context` for `is_dir_rw_accessible` for `new_buckets_path`.
4. GAP - it was only changed in the file `manage_nsfs` (we might have it in `health` script).

### Testing Instructions:
1. none

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/cmd/manage_nsfs.js [hunk 1]
```diff
@@ -751,22 +755,24 @@ async function validate_bucket_args(data, action) {
...
+            throw_cli_error(ManageCLIError.InvalidStoragePath, data.path);
+        }
         if (data.s3_policy) {
             try {
                 await bucket_policy_utils.validate_s3_policy(data.s3_policy, data.name,
                     async principal => {
                         const account_config_path = get_config_file_path(accounts_dir_path, principal);
                         try {
-                            await nb_native().fs.stat(native_fs_utils.get_process_fs_context(), account_config_path);
+                            const fs_context_config_root_backend = native_fs_utils.get_process_fs_context(config_root);
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:774]:
```suggestion
                            const fs_context_config_root_backend = native_fs_utils.get_process_fs_context(config_root_backend);
```

**Review by romayalon — APPROVED** [review]

File: src/cmd/manage_nsfs.js [hunk 2]
```diff
@@ -814,8 +820,9 @@ async function validate_account_args(data, action) {
...
             return;
         }
-        const fs_context = native_fs_utils.get_process_fs_context();
-        const exists = await native_fs_utils.is_path_exists(fs_context, data.nsfs_account_config.new_buckets_path);
+        // in case we have the fs_backend it changes the fs_context that we use for the path
+        const fs_context_fs_backend = native_fs_utils.get_process_fs_context(data.fs_backend);
+        const exists = await native_fs_utils.is_path_exists(fs_context_fs_backend, data.nsfs_account_config.new_buckets_path);
         if (!exists) {
             throw_cli_error(ManageCLIError.InvalidAccountNewBucketsPath, data.nsfs_account_config.new_buckets_path);
         }
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:828]:
```suggestion
           const account_fs_context = await native_fs_utils.get_fs_context(data.nsfs_account_config, data.fs_backend);
```

File: src/cmd/manage_nsfs.js [hunk 3]
```diff
@@ -969,7 +976,7 @@ async function whitelist_ips_management(args) {
     try {
         const config_data = require(config_path);
         config_data.NSFS_WHITELIST = whitelist_ips;
-        const fs_context = native_fs_utils.get_process_fs_context();
+        const fs_context = native_fs_utils.get_process_fs_context(config_root);
```
[the remark this answers is not in the document]
Comment (shirady) [reply src/cmd/manage_nsfs.js]: Thanks

**Comment by shirady** [comment]
@romayalon After your approval, I added this change (from PR description): 

> Rename the argument from config_root_backend to fs_backend in function get_fs_context.

We mentioned this yesterday.
