### PR TITLE
avoid updating default resource for operator account when creating first resource

### LINKED ISSUE #5651: Operator account holds the first resource as default resource and the resource cannot be deleted
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. When the first resource is created in the system it is automatically assigned to all accounts as default resource, this includes the operator account.
2. A resource cannot be deleted if an account holds it as a default resource
3. No like other accounts, we cannot edit (from the FE) the default resource for the operator account because this account is filtered out from the FE.

### Expected behavior
1. The user must have a way to delete the first resource.

### Steps to reproduce
1. create a new system, then create a resource (pool or cloud).

### PR DESCRIPTION
**Pull request by dannyzaken**
### Explain the changes
1. when the first resource is created then the default resource of all accounts is changed to that resource.
2. this is also done for the operator account, but this account cannot be edited or deleted, which makes the first resource created undeletable.
3. for now, avoid updating the operator account. any buckets created by the operator (via the bucket provisioner) will be using the internal storage. in the future the operator will provide a better way to control the backing storage of the buckets.

### Issues: Fixed #xxx / Gap #xxx
1. Fixes #5651 

### Testing Instructions:
1.

### CODE REVIEW

**Review by jackyalbo — CHANGES_REQUESTED** [review]
unwarp

File: src/server/system_services/pool_server.js [hunk 1]
```diff
@@ -269,7 +269,7 @@ function updates_if_first_resource(req, pool) {
     if (pools.length) return;
     // so this is the first resource to be added to the system
     _.each(system_store.data.accounts, account => {
-        if (account.default_pool) {
+        if (account.default_pool && account.email.valueOf() !== config.OPERATOR_ACCOUNT_EMAIL) {
```
Comment (jackyalbo) [inline src/server/system_services/pool_server.js]:
```suggestion
        if (account.default_pool && account.email.unwrap() !== config.OPERATOR_ACCOUNT_EMAIL) {
```

**Review by jackyalbo — APPROVED** [review]
