### PR TITLE
Added a fix for event handling of different errors

### LINKED ISSUE #8199: NC | NSFS | CLI | Events Improvements
### Environment info
- NooBaa Version: noobaa-core-5.15.4-20240710-5.15.el9.x86_64.rpm (but probably relevant also in 5.17.0)
- Platform: NC

### Actual behavior
1. I had an account that was not deleted due to an error `InternalError`, and there was not created event for it.

### Expected behavior
1. To see an event when the account could not be deleted, even if the error is `InternalError`.

### Steps to reproduce
I don't have specific steps, but one should create a situation where the account cannot be deleted due to `InternalError` and check the `noobaa_events`.

### More information - Screenshots / Logs / Other output
I saw it during the investigation of account deletion in a loop.

Example of an account that was not deleted s3user-15793:
```bash
➜  app2-test1107_logs cat script-c83f1-app2.noobaa-core-5.15.0-20240710.el9.x86_64.test1107 | grep 'Failed to execute command for Account s3user-15793' -A 4 -B 14
Running Command /usr/lpp/mmfs/bin/mmlsconfig cesSharedRoot
CallerPath of File utils/utils.go
Running Command /usr/lpp/mmfs/bin/mmces service list
Running Command: env LC_ALL=C /usr/local/bin/noobaa-cli account delete --name s3user-15793 2>/dev/null
Execution of command failed:
Info: {
  "error": {
    "code": "InternalError",
    "message": "The server encountered an internal error. Please retry the request",
    "cause": "Error: No such file or directory"
  }
}

Error: exit status 1
Failed to execute command for Account s3user-15793: The server encountered an internal error. Please retry the request
Error Code: InternalError
  Error Details: <nil>

15793 is done
```

Example of an account that was not deleted s3user-15793 and s3user-15794 is an account that was deleted:
```bash
➜  ~ cat noobaa_events.log | grep s3user-15793
{"timestamp":"2024-07-11T05:51:22.795303-04:00","message":"{\"code\":\"noobaa_account_created\",\"message\":\"Account created\",\"description\":\"Noobaa Account created\",\"entity_type\":\"NODE\",\"event_type\":\"INFO\",\"scope\":\"NODE\",\"severity\":\"INFO\",\"state\":\"HEALTHY\",\"arguments\":{\"account\":\"s3user-15793\"},\"pid\":2748042}","host":"c83f1-app2","severity":"notice","facility":"local2","syslog-tag":"node[2748042]:","source":"node"}
➜  ~ cat /Users/shiradymnik/Downloads/test1107_logs/app2-test1107_logs/noobaa_events.log | grep s3user-15794
{"timestamp":"2024-07-11T05:51:31.409283-04:00","message":"{\"code\":\"noobaa_account_created\",\"message\":\"Account created\",\"description\":\"Noobaa Account created\",\"entity_type\":\"NODE\",\"event_type\":\"INFO\",\"scope\":\"NODE\",\"severity\":\"INFO\",\"state\":\"HEALTHY\",\"arguments\":{\"account\":\"s3user-15794\"},\"pid\":2749481}","host":"c83f1-app2","severity":"notice","facility":"local2","syslog-tag":"node[2749481]:","source":"node"}
{"timestamp":"2024-07-11T07:52:19.880822-04:00","message":"{\"code\":\"noobaa_account_deleted\",\"message\":\"Account deleted\",\"description\":\"Noobaa Account deleted\",\"entity_type\":\"NODE\",\"event_type\":\"INFO\",\"scope\":\"NODE\",\"severity\":\"INFO\",\"state\":\"HEALTHY\",\"arguments\":{\"account\":\"s3user-15794\"},\"pid\":3763051}","host":"c83f1-app2","severity":"notice","facility":"local2","syslog-tag":"node[3763051]:","source":"node"}
```

messages from the node doesn't contain any relevant data:
```bash
➜  ~ cat app2-test1107_logs/messages  | grep s3user-15793
Jul 11 05:51:47 c83f1-app2 mmsysmon[1534699]: [I] Event raised: S3 account s3user-15793 was found.
Jul 11 05:51:47 c83f1-app2 mmsysmon[1534699]: [I] Event raised: The state of S3_ACCOUNT s3user-15793 of the component S3 changed to CHECKING.
Jul 11 05:52:14 c83f1-app2 mmsysmon[1534699]: [I] Event raised: S3 account s3user-15793 is OK.
Jul 11 05:52:14 c83f1-app2 mmsysmon[1534699]: [I] Event raised: The state of S3_ACCOUNT s3user-15793 of the component S3 changed to HEALTHY.
```

### PR DESCRIPTION
**Pull request by aayushchouhan09**
### Describe the Problem
Previously, when an InternalError occurred during an operation, it was not recorded as an event.

### Explain the Changes
1.  Implemented a fix to ensure that InternalError and other error types are properly recorded as events.

### Issues: Fixed #xxx / Gap #xxx
1. Fix: #8199 

### Testing Instructions:
1.  Manual testing instructions:

- Use command `make rpm`  inside `noobaa-core` to create rpm, which will be found in dir `build/rpm/` after creation.
- Start Redhat UBI9 container and enter the shell using below commands:
`$ docker pull redhat/ubi9:latest`
`$ docker run --privileged -it --user root -d --platform=linux/amd64 redhat/ubi9 /usr/sbin/init`
`$ docker exec -it <container-id> bash`
- Copy rpm created in step 1 to the container from `noobaa-core`(update rpm name):
`$ docker cp build/rpm/noobaa-core-5.19.0-20250326.el9.x86_64.rpm <container-id>:tmp/`
- Install dependencies in the container using below commands:
`$ yum install -y rsyslog wget make initscripts`
`$ systemctl start rsyslog`
`$ wget https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/boost-system-1.75.0-8.el9.x86_64.rpm`
`$ wget https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/boost-thread-1.75.0-8.el9.x86_64.rpm`
`$ rpm -i boost-system-1.75.0-8.el9.x86_64.rpm`
`$ rpm -i boost-thread-1.75.0-8.el9.x86_64.rpm`
- Install noobaa rpm inside the container using below command(update rpm name):
`$ rpm -i tmp/noobaa-core-5.19.0-20250326.el9.x86_64.rpm`
`$ rpm -qa | grep noobaa` (check if noobaa installed or not)
- Do something in the noobaa code to throw `InternalError`, for example try adding this `throw ManageCLIError.InternalError;` as first line of function `delete_account()` in `manage_nsfs.js`. After that try creating and then deleting account using noobaa-cli and check the noobaa-events in the below steps --> new event for InternalError should be created.
- Check for noobaa-events using below command:
`$ cat var/log/noobaa_events.log`

> [root@8ccc29c3ce83 /]# cat var/log/noobaa_events.log 
Mar 20 16:09:57 8ccc29c3ce83 node[218]: {"timestamp":"2025-03-20T16:09:57.526Z","host":"8ccc29c3ce83","event":{"code":"noobaa_gpfslib_missing","message":"Noobaa GPFS library file is missing","description":"Noobaa GPFS library file is missing","entity_type":"NODE","event_type":"STATE_CHANGE","scope":"NODE","severity":"ERROR","state":"DEGRADED","arguments":{"gpfs_dl_path":"/usr/lpp/mmfs/lib/libgpfs.so"},"pid":218}}
Mar 20 16:09:58 8ccc29c3ce83 [218]: {"timestamp":"2025-03-20T16:09:58.009Z","host":"8ccc29c3ce83","event":{"code":"noobaa_started","message":"Noobaa started","description":"Noobaa started running","entity_type":"NODE","event_type":"STATE_CHANGE","scope":"NODE","severity":"INFO","state":"HEALTHY","pid":218}}
Mar 20 16:12:30 8ccc29c3ce83 node[274]: {"timestamp":"2025-03-20T16:12:30.399Z","host":"8ccc29c3ce83","event":{"code":"noobaa_account_created","message":"Account created","description":"Noobaa Account created","entity_type":"NODE","event_type":"INFO","scope":"NODE","severity":"INFO","state":"HEALTHY","arguments":{"account":"aayush"},"pid":274}}
Mar 21 14:38:54 8ccc29c3ce83 node[324]: {"timestamp":"2025-03-21T14:38:54.682Z","host":"8ccc29c3ce83","event":{"code":"noobaa_internal_error","message":"Noobaa action failed with internal error","description":"Noobaa action failed with internal error","entity_type":"NODE","event_type":"ERROR","scope":"NODE","severity":"ERROR","state":"HEALTHY","pid":324}}

- [ ] Tests added

### CODE REVIEW

File: src/cmd/manage_nsfs.js [hunk 1]
```diff
@@ -103,9 +103,7 @@ async function main(argv = minimist(process.argv.slice(2))) {
                 ...(ManageCLIError.FS_ERRORS_TO_MANAGE[err.code] ||
                 ManageCLIError.RPC_ERROR_TO_MANAGE[err.rpc_code] ||
                 ManageCLIError.InternalError), cause: err });
-        process.stdout.write(manage_err.to_string() + '\n', () => {
-            process.exit(1);
-        });
+        write_stdout_response(manage_err);
```
Comment (achouhan09) [inline src/cmd/manage_nsfs.js:106]: I think some of the events have been recorded two times with this. So, we can just create an event for `InternalError` only. wdyt?

Comment (romayalon) [inline src/cmd/manage_nsfs.js:106]: let's avoid mixing errors with valid responses
in the CLI errors are written using throw_cli_error() while this function also writes events 
write_stdout_response() are for valid responses

File: src/manage_nsfs/manage_nsfs_events_utils.js [hunk 2]
```diff
@@ -292,6 +292,26 @@ NoobaaEvent.BUCKET_ALREADY_EXISTS = Object.freeze({
...
 });
+NoobaaEvent.BUCKET_OWNER_NOT_EXISTS = Object.freeze({
+    event_code: 'bucket_owner_not_exists',
+    message: 'Bucket owner does not exist',
+    description: 'The specified bucket owner does not exist in the system',
+    entity_type: 'NODE',
+    event_type: 'ERROR',
+    scope: 'NODE',
+    severity: 'ERROR',
+    state: 'DEGRADED'
```
Comment (romayalon) [inline src/manage_nsfs/manage_nsfs_events_utils.js:303]: why state is DEGRADED?

File: src/manage_nsfs/manage_nsfs_cli_utils.js [hunk 3]
```diff
@@ -25,13 +25,13 @@ function throw_cli_error(error, detail, event_arg) {
 }
 
 function write_stdout_response(response_code, detail, event_arg) {
-    const response_event = NSFS_CLI_SUCCESS_EVENT_MAP[response_code.code];
+    const response_event = NSFS_CLI_SUCCESS_EVENT_MAP[response_code.code] || NSFS_CLI_ERROR_EVENT_MAP[response_code.code];
```
Comment (romayalon) [inline src/manage_nsfs/manage_nsfs_cli_utils.js:28]: error events are being written in throw_cli_error()

**Review by romayalon — CHANGES_REQUESTED** [review]

File: src/cmd/manage_nsfs.js (hunk 1 above)
Comment (achouhan09) [reply src/cmd/manage_nsfs.js:106]: I think we can create one more function to print/record/handle events for errors like `write_stdout_errors()` and in `throw_cli_error()` we can just throw the error instead of handling event. And we can call this function in catch block which also handles the `InternalError` if occurs. wdyt?

File: src/manage_nsfs/manage_nsfs_events_utils.js (hunk 2 above)
Comment (achouhan09) [reply src/manage_nsfs/manage_nsfs_events_utils.js:303]: As per my understanding, by `DEGRADED` state we are referring that the operation can still be performed by making some adjustments to the command(could be some permission issue). Please correct me if I am wrong

Comment (romayalon) [reply src/manage_nsfs/manage_nsfs_events_utils.js:303]: I think it affects the state of the cluster, @naveenpaul1 can you explain when event's state should be DEGRADED and when it should be HEALTHY?

Comment (naveenpaul1) [reply src/manage_nsfs/manage_nsfs_events_utils.js:303]: Yes @romayalon,  We have added DEGRADED stat to those events that could be the reason for potential I/O failers and core Noobaa config dir-related issue.

File: src/manage_nsfs/manage_nsfs_cli_utils.js [hunk 4]
```diff
@@ -25,13 +25,13 @@ function throw_cli_error(error, detail, event_arg) {
...
     if (response_event) {
         new NoobaaEvent(response_event).create_event(undefined, event_arg, undefined);
     }
     const res = new ManageCLIResponse(response_code).to_string(detail);
     process.stdout.write(res + '\n', () => {
-        process.exit(0);
+        process.exit(NSFS_CLI_ERROR_EVENT_MAP[response_code.code] ? 1 : 0);
```
Comment (naveenpaul1) [inline src/manage_nsfs/manage_nsfs_cli_utils.js:34]: @achouhan09 will it return the exit code of `1` for success response also?

File: src/manage_nsfs/manage_nsfs_events_utils.js (hunk 2 above)
Comment (romayalon) [reply src/manage_nsfs/manage_nsfs_events_utils.js:303]: @naveenpaul1 but does it do anything to the cluster? like ip movement etc? or it might happen only if health reported an error?

Comment (naveenpaul1) [reply src/manage_nsfs/manage_nsfs_events_utils.js:303]: @romayalon I also think this event should not have `DEGRADED` stat. For I/O events we added DEGRADED stat assuming could be because of some internal issue something related to cluster or storage itself.

Comment (achouhan09) [reply src/manage_nsfs/manage_nsfs_events_utils.js:303]: Thanks, I will update it to HEALTHY then.

**Review by romayalon — APPROVED** [review]
