### PR TITLE
NC | NSFS | revoking `--new_access_key` and fixing access key update issues

### LINKED ISSUE #7683: NSFS | NC | CLI | Account update script change access_key without new_access_key argument in config file.
### Environment info
- NooBaa Version: **master**

### Actual behavior
1. Account is updating with the wrong access_key. access_key in the config file got updated with the new access-key but the symlink file name remains the old name and it making the account corrupted.

### Expected behavior
1. access_key in config file change only when the `--new_access_key` added to command.

### Steps to reproduce
1.  ``` sudo node src/cmd/manage_nsfs account add --config_root /standalon/noobaa --name account1 --email z1@noobaa.com --new_buckets_path ../../standalon/nsfs_root/ --access_key Dwertyuiopasdfg12345 --secret_key Qwertyuiopasdfg12345Qwertyuiopasdfg12345 --uid 1000 --gid 1000```
2. ``` sudo node src/cmd/manage_nsfs account update --config_root /standalon/noobaa --name account1 --email z111ddddd@noobaa.com --access_key Hwertyuiopasdfg1234 ```

### LINKED ISSUE #7695: NSFS | NC | CLI | secret_key is not getting updated when using `--regenerate` flag
### Actual behavior
1. secret_key is not getting updated when using `--regenerate` flag

### PR DESCRIPTION
**Pull request by liranmauda**
### Explain the changes
1. revoking `--new_access_key`
2. fixing issue where `--regenerate` did not update the secret_key
3. fixing an issue where using `--access_key` without `--new_access_key` did not updated the symlink
4. updated the tests.

### Issues: Fixed #xxx / Gap #xxx
1. Fixes: https://github.com/noobaa/noobaa-core/issues/7695
2. Fixes: https://github.com/noobaa/noobaa-core/issues/7683

### Testing Instructions:
1. run sudo npx jest test_nc_nsfs_account_cli.test.js
2. run sudo node --allow-natives-syntax ./node_modules/.bin/_mocha src/test/unit_tests/test_nc_nsfs_cli.js

- [x] Doc (help) added/updated
- [x] Tests added

### CODE REVIEW

File: src/cmd/manage_nsfs.js [hunk 1]
```diff
@@ -400,23 +399,28 @@ function set_access_keys(argv, generate) {
...
-        if (argv.regenerate) {
-            const keys = set_access_keys(argv, true);
-            new_access_key = keys[0].access_key;
-        }
+    if (action === ACTIONS.ADD || action === ACTIONS.STATUS) {
+        access_keys = set_access_keys(argv, true);
+    } else if (action === ACTIONS.UPDATE) {
+        let regenerate = false;
+        if (argv.regenerate) regenerate = true;
+        access_keys = set_access_keys(argv, regenerate);
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:419]:
```suggestion
        access_keys = set_access_keys(argv, argv.regenerate && true);
```

File: src/test/unit_tests/test_nc_nsfs_cli.js [hunk 2]
```diff
@@ -475,64 +454,6 @@ mocha.describe('manage_nsfs cli', function() {
...
-            updating_options = { ...updating_options, name: update_options.new_name };
-            assert_response(action, type, update_response, updating_options);
-            account_options = { ...account_options, new_name: undefined, name: update_options.new_name };
-            const account_symlink = await read_config_file(config_root, access_keys_schema_dir, access_key, true);
-            assert_account(account_symlink, account_options);
-            const account = await read_config_file(config_root, accounts_schema_dir, account_options.name);
-            assert_account(account, account_options);
-        });
-
-        mocha.it('cli account update access key by name', async function() {
```
Comment (romayalon) [inline src/test/unit_tests/test_nc_nsfs_cli.js:497]: please instead of removing this test just replace new_access_key with access_key

File: src/test/unit_tests/test_nc_nsfs_cli.js [hunk 3]
```diff
@@ -475,64 +454,6 @@ mocha.describe('manage_nsfs cli', function() {
...
-            updating_options = { ...updating_options, access_key: update_options.new_access_key };
-            assert_response(action, type, update_response, updating_options);
-            account_options = { ...account_options, new_access_key: undefined, access_key: update_options.new_access_key };
-            const account_symlink = await read_config_file(config_root, access_keys_schema_dir, account_options.access_key, true);
-            assert_account(account_symlink, account_options);
-            const account = await read_config_file(config_root, accounts_schema_dir, account_options.name);
-            assert_account(account, account_options);
-        });
-
-        mocha.it('cli account update access key & new_name by name', async function() {
```
Comment (romayalon) [inline src/test/unit_tests/test_nc_nsfs_cli.js:514]: please instead of removing this test just replace new_access_key with access_key

File: src/test/unit_tests/test_nc_nsfs_cli.js (hunk 2 above)
Comment (liranmauda) [reply src/test/unit_tests/test_nc_nsfs_cli.js:497]: I was not removed It was moved into the jest tests. under `cli update account access_key and secret_key using flags`

File: src/test/unit_tests/test_nc_nsfs_cli.js (hunk 3 above)
Comment (liranmauda) [reply src/test/unit_tests/test_nc_nsfs_cli.js:514]: It was not removed it was moved into the jest test, under `cli account update access key, secret_key & new_name by name`

File: src/cmd/manage_nsfs.js (hunk 1 above)
Comment (liranmauda) [reply src/cmd/manage_nsfs.js:419]: It is not equivalent.
`argv.regenerate && true` will be undefined when the `--regenerate` flag will not pass. 
you can see it by running the following snippet:
```javascript
const minimist = require('minimist');

async function main(argv = minimist(process.argv.slice(2))) {
        console.log('test argv:', argv.regenerate);
        console.log('test argv:', argv.regenerate && true);
}

main();
```

and run it by:
$node a.js --regenerate
```
test argv: true
test argv: true
```
$ node a.js
```
test argv: undefined
test argv: undefined
```

File: src/test/unit_tests/jest_tests/test_nc_nsfs_account_cli.test.js [hunk 4]
```diff
@@ -190,29 +190,59 @@ describe('manage nsfs cli account flow', () => {
...
-            const account_symlink = await read_config_file(config_root, access_keys_schema_dir, new_access_key, true);
+            expect(account_details.access_keys[0].secret_key).not.toBe(new_account_details.access_keys[0].secret_key);
+            expect(new_account_details.access_keys[0].access_key).toBe(access_key);
+            const account_symlink = await read_config_file(config_root, access_keys_schema_dir, access_key, true);
             //fixing the new_account_details for compare. 
             new_account_details = { ...new_account_details, ...new_account_details.nsfs_account_config };
             assert_account(account_symlink, new_account_details);
         });
 
-        it('should fail - cli update account new access_key wrong complexity', async () => {
```
Comment (romayalon) [inline src/test/unit_tests/jest_tests/test_nc_nsfs_account_cli.test.js:209]: wait but now you don't have a "should fail wrong complexity test"

File: src/cmd/manage_nsfs.js (hunk 1 above)
Comment (romayalon) [reply src/cmd/manage_nsfs.js:418]: Do you mean that false is unequal to undefined? set_access_keys() checks if (generate) so both false and undefined should work the same

Comment (liranmauda) [reply src/cmd/manage_nsfs.js:418]: but it is "dirty", so I prefer passing false explicitly. 
more than that we explicitly define generate as boolean:
```
/**
 * set_access_keys will set the access keys either given as args or generated.
 * @param {{ access_key: any; secret_key: any; }} argv
 * @param {boolean} generate a flag for generating the access_keys automatically
 */
```

File: src/test/unit_tests/jest_tests/test_nc_nsfs_account_cli.test.js (hunk 4 above)
Comment (liranmauda) [reply src/test/unit_tests/jest_tests/test_nc_nsfs_account_cli.test.js:209]: no, as we dont have the `--new_access_key` flag anymore, we removing this test, and the error is removed with it.

We do have a `should fail - cli update account access_key wrong complexity` for `--access_key`
and `should fail - cli update account secret_key wrong complexity` for `--secret_key`

File: src/cmd/manage_nsfs.js (hunk 1 above)
Comment (romayalon) [reply src/cmd/manage_nsfs.js:418]: so add boolean casting - Boolean(argv.regenerate).

**Review by romayalon — APPROVED** [review]
