### PR TITLE
Chunked upload support for Namespace buckets

### LINKED ISSUE #6122: BadDigest error when accessing namespaced s3 bucket with Spark
### Environment info
- NooBaa Version: 5.5.0
- Platform: OKD 4.5
Using Minio (RELEASE.2020-08-07T01-23-07Z)  as a backend for a namespaced bucket.
### Actual behavior
Trying to write to the namespaced bucket using Apache Spark results in BadDigest errors. The user agent is `Hadoop 3.2.0, aws-sdk-java/1.11.375 Linux/5.6.19-300.fc32.x86_64 OpenJDK_64-Bit_Server_VM/25.262-b10 java/1.8.0_262 scala/2.12.10`

### Expected behavior
Spark can successfully write to the bucket. When accessing Minio directly everything works.

### Steps to reproduce
It is a rather big setup using Spark... If needed i can provide the necessary steps to reproduce, but if you can supply a commit which probably solves the issue i can build it myself and give feedback!

### More information - Screenshots / Logs / Other output
Log output:
```
[32mAug-11 7:23:48.271[35m [Endpoint/13][36m   [L0][39m core.endpoint.s3.s3_rest:: S3 REQUEST PUT /localtest/test/delta_jupyter_notebook10/part-00001-a77b6c14-a040-4104-8959-b249b4c172f4-c000.snappy.parquet op put_object request_id kdpmc7u5-7s0szz-u3b { host:[32m's3.noobaa-test.svc.cluster.local'[39m,[32m'x-amz-content-sha256'[39m:[32m'STREAMING-AWS4-HMAC-SHA256-PAYLOAD'[39m, authorization:[32m'AWS4-HMAC-SHA256 Credential=mCSmD1cZ4TOHuGw7zHOe/20200811/noobaa-test/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=0c1d55ae9da1ea90e1866421131cae73a34bd2ad20c83023f1d177433b3d2fb1'[39m,[32m'x-amz-date'[39m:[32m'20200811T072348Z'[39m,[32m'user-agent'[39m:[32m'Hadoop 3.2.0, aws-sdk-java/1.11.375 Linux/5.6.19-300.fc32.x86_64 OpenJDK_64-Bit_Server_VM/25.262-b10 java/1.8.0_262 scala/2.12.10'[39m,[32m'amz-sdk-invocation-id'[39m:[32m'8831093a-16b0-ba39-6578-47d765d84bd2'[39m,[32m'x-amz-decoded-content-length'[39m:[32m'476'[39m,[32m'amz-sdk-retry'[39m:[32m'7/5449/265'[39m,[32m'content-md5'[39m:[32m'D+Yd5Qi+McGB9ESbS/6VoQ=='[39m,[32m'content-type'[39m:[32m'application/octet-stream'[39m,[32m'content-length'[39m:[32m'650'[39m, connection:[32m'Keep-Alive'[39m, expect:[32m'100-continue'[39m }
[32mAug-11 7:23:48.271[35m [Endpoint/13][36m   [L0][39m core.endpoint.s3.ops.s3_put_object:: PUT OBJECT localtest test/delta_jupyter_notebook10/part-00001-a77b6c14-a040-4104-8959-b249b4c172f4-c000.snappy.parquet  
[32mAug-11 7:23:48.271[35m [Endpoint/13][36m   [L0][39m core.sdk.namespace_s3:: NamespaceS3.upload_object: localtest { bucket:[32m'localtest'[39m, key:[32m'test/delta_jupyter_notebook10/part-00001-a77b6c14-a040-4104-8959-b249b4c172f4-c000.snappy.parquet'[39m, content_type:[32m'application/octet-stream'[39m, chunked_content:[33mtrue[39m, copy_source:[90mundefined[39m, size:[33m476[39m, md5_b64:[32m'D+Yd5Qi+McGB9ESbS/6VoQ=='[39m, sha256_b64:[90mundefined[39m, md_conditions:[90mundefined[39m, source_md_conditions:[90mundefined[39m, xattr: {}, xattr_copy:[33mtrue[39m, tagging:[90mundefined[39m, tagging_copy:[33mtrue[39m, encryption:[90mundefined[39m, lock_settings:[90mundefined[39m }
[32mAug-11 7:23:48.279[35m [Endpoint/13][31m[ERROR][39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/localtest/test/delta_jupyter_notebook10/part-00001-a77b6c14-a040-4104-8959-b249b4c172f4-c000.snappy.parquet</Resource><RequestId>kdpmc7u5-7s0szz-u3b</RequestId></Error> PUT /localtest/test/delta_jupyter_notebook10/part-00001-a77b6c14-a040-4104-8959-b249b4c172f4-c000.snappy.parquet {"host":"s3.noobaa-test.svc.cluster.local","x-amz-content-sha256":"STREAMING-AWS4-HMAC-SHA256-PAYLOAD","authorization":"AWS4-HMAC-SHA256 Credential=mCSmD1cZ4TOHuGw7zHOe/20200811/noobaa-test/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=0c1d55ae9da1ea90e1866421131cae73a34bd2ad20c83023f1d177433b3d2fb1","x-amz-date":"20200811T072348Z","user-agent":"Hadoop 3.2.0, aws-sdk-java/1.11.375 Linux/5.6.19-300.fc32.x86_64 OpenJDK_64-Bit_Server_VM/25.262-b10 java/1.8.0_262 scala/2.12.10","amz-sdk-invocation-id":"8831093a-16b0-ba39-6578-47d765d84bd2","x-amz-decoded-content-length":"476","amz-sdk-retry":"7/5449/265","content-md5":"D+Yd5Qi+McGB9ESbS/6VoQ==","content-type":"application/octet-stream","content-length":"650","connection":"Keep-Alive","expect":"100-continue"} BadDigest: The Content-Md5 you specified did not match what we received.
    at Request.extractError (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/services/s3.js:835:35)
    at Request.callListeners (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /root/node_modules/noobaa-core/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /root/node_modules/noobaa-core/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/request.js:38:9)
[32mAug-11 7:23:49.807[35m [Endpoint/13][36m   [L0][39m core.util.signature_utils:: _string_to_sign_v4 method PUT pathname /localtest/test/delta_jupyter_notebook10/part-00000-6a2a5b1a-6d44-47eb-be72-93954a1d99e2-c000.snappy.parquet search  headers { Host:[32m's3.noobaa-test.svc.cluster.local'[39m,[32m'X-Amz-Content-Sha256'[39m:[32m'STREAMING-AWS4-HMAC-SHA256-PAYLOAD'[39m, Authorization:[32m'AWS4-HMAC-SHA256 Credential=mCSmD1cZ4TOHuGw7zHOe/20200811/noobaa-test/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=251cc06e2ed834a0b9ab2322f5540f739ff8f2d97b7593058d9bdfaefaa1185d'[39m,[32m'X-Amz-Date'[39m:[32m'20200811T072349Z'[39m,[32m'User-Agent'[39m:[32m'Hadoop 3.2.0, aws-sdk-java/1.11.375 Linux/5.6.19-300.fc32.x86_64 OpenJDK_64-Bit_Server_VM/25.262-b10 java/1.8.0_262 scala/2.12.10'[39m,[32m'Amz-Sdk-Invocation-Id'[39m:[32m'74d903a2-07ee-99b4-dbe4-0bbbeb7d0535'[39m,[32m'X-Amz-Decoded-Content-Length'[39m:[32m'471'[39m,[32m'Amz-Sdk-Retry'[39m:[32m'9/3123/255'[39m,[32m'Content-MD5'[39m:[32m'CvloSjXq2XDGiVvQrvMAOg=='[39m,[32m'Content-Type'[39m:[32m'application/octet-stream'[39m,[32m'Content-Length'[39m:[32m'645'[39m, Connection:[32m'Keep-Alive'[39m, Expect:[32m'100-continue'[39m } region noobaa-test canonical_str 
PUT
/localtest/test/delta_jupyter_notebook10/part-00000-6a2a5b1a-6d44-47eb-be72-93954a1d99e2-c000.snappy.parquet
amz-sdk-invocation-id:74d903a2-07ee-99b4-dbe4-0bbbeb7d0535
amz-sdk-retry:9/3123/255
content-length:645
content-md5:CvloSjXq2XDGiVvQrvMAOg==
content-type:application/octet-stream
host:s3.noobaa-test.svc.cluster.local
user-agent:Hadoop 3.2.0, aws-sdk-java/1.11.375 Linux/5.6.19-300.fc32.x86_64 OpenJDK_64-Bit_Server_VM/25.262-b10 java/1.8.0_262 scala/2.12.10
x-amz-content-sha256:STREAMING-AWS4-HMAC-SHA256-PAYLOAD
x-amz-date:20200811T072349Z
x-amz-decoded-content-length:471
amz-sdk-invocation-id;amz-sdk-retry;content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length
STREAMING-AWS4-HMAC-SHA256-PAYLOAD
 string_to_sign 
AWS4-HMAC-SHA256
20200811T072349Z
20200811/noobaa-test/s3/aws4_request
12eb6040f53ad8a7d7a55f28988891f21bd0e747c1c9a0744542d78d26c9207
```

### PR DESCRIPTION
**Pull request by romayalon**
Signed-off-by: Romy <romy2232@gmail.com>

### Explain the changes
1. Added chunked upload support for Namespace (currently just for regular upload, need to add it to multipart upload as well) 
2. Fixed head object when object is directory.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #6122 

### Testing Instructions:
1.

### CODE REVIEW

File: src/sdk/namespace_merge.js [hunk 1]
```diff
@@ -89,6 +90,13 @@ class NamespaceMerge {
     async upload_object(params, object_sdk) {
         const operation = 'ObjectCreated';
         const load_for_trigger = object_sdk.should_run_triggers({ active_triggers: this.active_triggers, operation });
+
+        if (params.chunked_content) {
+            const decoder = new ChunkedContentDecoder();
+            params.source_stream.pipe(decoder);
+            params.source_stream = decoder;
+        }
```
Comment (guymguym) [inline src/sdk/namespace_merge.js:98]: Why is this needed in namespace_merge?
I would expect to do that in namespace_nb, and that other namespaces will be able to propagate the same encoding?

File: src/sdk/namespace_s3.js [hunk 2]
```diff
@@ -139,13 +139,13 @@ class NamespaceS3 {
             // If set, part_number is positive integer from 1 to 10000.
             // Usually part number is not provided and then we read a small "inline" range
             // to reduce the double latency for small objects.
-            if (!params.part_number) {
+            if (!params.part_number && !request.Key.endsWith('/')) {
```
Comment (guymguym) [inline src/sdk/namespace_s3.js:142]: why is this the condition? why are keys ending with / should be different?
if needed, define this condition in a const boolean to avoid repeating it.

**Review by guymguym — CHANGES_REQUESTED** [review]
see comments

File: src/sdk/namespace_s3.js (hunk 2 above)
Comment (romayalon) [reply src/sdk/namespace_s3.js]: getObject when object is directory is failing because of invalid range, and I think that we can use headObject in this case instead.
WDYT?

Comment (guymguym) [reply src/sdk/namespace_s3.js]: what puzzles me is why getObject(0-4k) for dir fails? Does getObject(0-4k) for any 0 size object fail on invalid range like that too? or is it special for dirs?

File: src/sdk/namespace_s3.js [hunk 3]
```diff
@@ -139,13 +139,15 @@ class NamespaceS3 {
             // If set, part_number is positive integer from 1 to 10000.
             // Usually part number is not provided and then we read a small "inline" range
             // to reduce the double latency for small objects.
-            if (!params.part_number) {
+            const isDir = request.Key.endsWith('/');
+            if (!params.part_number && !isDir) {
```
Comment (guymguym) [inline src/sdk/namespace_s3.js:143]: I meant something like that -
```suggestion
            const can_use_get_inline = !params.part_number && !request.Key.endsWith('/');
            if (can_use_get_inline) {
```

File: src/sdk/namespace_s3.js (hunk 2 above)
Comment (romayalon) [reply src/sdk/namespace_s3.js]: @guymguym it's on 0 size objects too

Comment (guymguym) [reply src/sdk/namespace_s3.js]: oh that's not good.

Comment (guymguym) [reply src/sdk/namespace_s3.js]: We need to fix for 0 size objects too, we can't let that fail of course.
And for object sizes between 1-4095 (not 0) does it works ok although we request more than the object size? and only for 0 it doesn't? where did you test it? AWS?

Comment (romayalon) [reply src/sdk/namespace_s3.js]: yes, checked it on AWS.
and I tried it also with object of size 918 bytes and getObject works with range so this scenario is ok.

Comment (guymguym) [reply src/sdk/namespace_s3.js]: got it. any suggestions how to handle 0 size objects?

Comment (romayalon) [reply src/sdk/namespace_s3.js]: what about catch that error and try headObject instead?

Comment (guymguym) [reply src/sdk/namespace_s3.js]: can work... but perhaps it would be good to separate this whole change to another PR?
It's getting more complex to piggyback this PR.

File: src/sdk/namespace_merge.js (hunk 1 above)
Comment (romayalon) [reply src/sdk/namespace_merge.js:98]: when talking about S3 namespace - I couldn't find a way of using the node js aws sdk to propagate the encoded content, also using propagation solution would enforce me to find specific solution for namespace blob too (and other namespaces that are not S3). I think that this solution is the least complex.

Comment (guymguym) [reply src/sdk/namespace_merge.js:98]: Keep in mind that we don't want to enforce using namespace_merge for namespace_cache cases.
So we want that all of our namespaces get the source_stream decoded (at least until we find a way to optimize) but I think I would put it in the S3 ops layer instead (meaning in s3_put_object.js or s3_utils if need to share it to other ops).

Comment (romayalon) [reply src/sdk/namespace_merge.js]: right,
I moved the decoding to S3 ops layer (for multipart upload too).

File: src/sdk/namespace_s3.js (hunk 2 above)
Comment (romayalon) [reply src/sdk/namespace_s3.js]: it's a part of the spark fix (the spark session object that the reporter uses does headObject as part of its process)

File: src/sdk/object_io.js [hunk 4]
```diff
@@ -424,7 +422,6 @@ class ObjectIO {
 
         const pipeline = new Pipeline(params.source_stream);
 
-        if (params.chunked_content) pipeline.pipe(new ChunkedContentDecoder());
```
[the remark this answers is not in the document]
Comment (guymguym) [reply src/sdk/object_io.js:427]: Here is a sample gist that shows the problem - https://gist.github.com/guymguym/58e026b8b500594284c063412c9b59ec

File: src/sdk/namespace_s3.js [hunk 5]
```diff
@@ -139,14 +139,21 @@ class NamespaceS3 {
...
-            const res = params.part_number ? await this.s3.headObject(request).promise() : await this.s3.getObject(request).promise();
-
+            let res;
+            try {
+                res = can_use_get_inline ? await this.s3.getObject(request).promise() : await this.s3.headObject(request).promise();
+            } catch (err) {
+                if (err.code !== 'InvalidRange') {
+                    throw err;
+                }
+                res = await this.s3.headObject({ ...request, Range: undefined }).promise();
```
Comment (guymguym) [inline src/sdk/namespace_s3.js:155]: comment, explaination, something is very missing.

File: src/sdk/namespace_s3.js [hunk 6]
```diff
@@ -139,14 +139,21 @@ class NamespaceS3 {
             // If set, part_number is positive integer from 1 to 10000.
             // Usually part number is not provided and then we read a small "inline" range
             // to reduce the double latency for small objects.
-            if (!params.part_number) {
+            const can_use_get_inline = !params.part_number && !request.Key.endsWith('/');
```
Comment (guymguym) [inline src/sdk/namespace_s3.js:142]: also here - missing comment to explain these conditions and why they exist

File: src/endpoint/s3/s3_utils.js [hunk 7]
```diff
@@ -99,6 +100,12 @@ const OP_NAME_TO_ACTION = Object.freeze({
     put_object: { regular: "s3:putobject" },
 });
 
+function decode_chunked_upload(source_stream) {
+    const decoder = new ChunkedContentDecoder();
+    source_stream.pipe(decoder);
+    return decoder;
```
[the remark this answers is not in the document]
Comment (romayalon) [reply src/endpoint/s3/s3_utils.js]: fixed.

File: src/sdk/namespace_s3.js (hunk 5 above)
Comment (romayalon) [reply src/sdk/namespace_s3.js:157]: added comment.

File: src/sdk/namespace_s3.js (hunk 6 above)
Comment (romayalon) [reply src/sdk/namespace_s3.js:143]: added comment.

File: src/endpoint/s3/s3_utils.js [hunk 8]
```diff
@@ -99,6 +101,12 @@ const OP_NAME_TO_ACTION = Object.freeze({
     put_object: { regular: "s3:putobject" },
 });
 
+function decode_chunked_upload(source_stream) {
+    const decoder = new ChunkedContentDecoder();
+    stream.pipeline(source_stream, decoder, err => console.log('Error:', err));
```
Comment (guymguym) [inline src/endpoint/s3/s3_utils.js:106]:
```suggestion
    // pipeline will back-propagate errors from the decoder to stop streaming from the source,
    // so the error callback here is only needed for logging.
    stream.pipeline(source_stream, decoder, err => {
        console.log('decode_chunked_upload: pipeline error', err.stack || err);
    });
```

File: src/sdk/namespace_s3.js [hunk 9]
```diff
@@ -139,14 +139,23 @@ class NamespaceS3 {
...
                 request.Range = `bytes=0-${config.INLINE_MAX_SIZE - 1}`;
             }
             this._set_md_conditions(params, request);
             this._assign_encryption_to_request(params, request);
-
-            const res = params.part_number ? await this.s3.headObject(request).promise() : await this.s3.getObject(request).promise();
-
+            let res;
+            try {
+                res = can_use_get_inline ? await this.s3.getObject(request).promise() : await this.s3.headObject(request).promise();
```
Comment (guymguym) [inline src/sdk/namespace_s3.js:151]:
```suggestion
                res = can_use_get_inline ?
                    await this.s3.getObject(request).promise() :
                    await this.s3.headObject(request).promise();
```

**Review by guymguym — APPROVED** [review]

**Review by guymguym — APPROVED** [review]
two minor suggestions

File: src/endpoint/s3/s3_utils.js (hunk 8 above)
Comment (romayalon) [reply src/endpoint/s3/s3_utils.js]: cool thanks!

**Comment by guymguym** [comment]
@romayalon I think this PR is ready - can you rebase so we can merge?
