### PR TITLE
fixed issue #5567 - lamda triggers aws_config set with the wrong endpoint

### LINKED ISSUE #5567: lambda triggers fail because _make_aws_config in function_server uses the wrong endpoint for S3 access
### Environment info
- NooBaa Version: **4.0**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. when using a lambda function that uses AWS.S3 the AWS config is update with the wrong endpoint.
2. to get the IP we use `get_base_address` that returns the management service IP
3. to get the port we use `process.env.ENDPOINT_PORT` which is the internal port in the pod which the s3 server listens on.

### Expected behavior
1. endpoint for AWS config should be the S3 service IP and port

### Steps to reproduce
1. create a lambda function that uses AWS.S3

### More information - Screenshots / Logs / Other output

### PR DESCRIPTION
**Pull request by dannyzaken**
### Explain the changes
1.  The wrong endpoint was set in the AWS config that was sent to the lambda function. we used the management service instead of S3
2. changed make_aws_config to use the s3 service

### Issues: Fixed #xxx / Gap #xxx
1. Fixes #5567 

### Testing Instructions:
1. see issue

### CODE REVIEW

**Review by nimrod-becker — APPROVED** [review]

File: src/server/func_services/func_server.js [hunk 1]
```diff
@@ -417,21 +417,24 @@ function _make_rpc_options(req) {
...
+        service: 's3',
+        api: 's3',
+        protocol: 'https',
+    });
     const account = system_store.data.get_by_id(req.func.exec_account);
     const account_keys = account.access_keys[0];
     return {
         region: 'us-east-1',
-        endpoint: `http://${ep_host}:${ep_port}`,
+        endpoint: ep_addr.toString(),
```
Comment (guymguym) [inline src/server/func_services/func_server.js]: Why toString()? what is the type of ep_addr?

File: src/util/addr_utils.js [hunk 2]
```diff
@@ -7,10 +7,10 @@ const { construct_url } = require('./url_utils');
...
 const default_base_port = parseInt(process.env.SSL_PORT, 10) || 5443;
 const api_default_port_offset = {
-     mgmt: 0,
-     md: 1,
-     bg: 2,
-     'hosted_agents': 3
+    mgmt: 0,
+    md: 1,
+    bg: 2,
+    'hosted_agents': 3
```
Comment (guymguym) [inline src/util/addr_utils.js]: no need for the quotes

**Review by guymguym — APPROVED** [review]

File: src/server/func_services/func_server.js (hunk 1 above)
Comment (dannyzaken) [reply src/server/func_services/func_server.js]: ep_addr is URL

File: src/util/addr_utils.js (hunk 2 above)
Comment (dannyzaken) [reply src/util/addr_utils.js]: removed

File: src/server/func_services/func_server.js (hunk 1 above)
Comment (guymguym) [reply src/server/func_services/func_server.js]: ah ok, so I would suggest using href instead to get the url string because it is more explicit.
see https://nodejs.org/docs/latest-v10.x/api/url.html#url_url_href
```suggestion
        endpoint: ep_addr.href,
```

Comment (dannyzaken) [reply src/server/func_services/func_server.js]: 👍
