### PR TITLE
Lifecycle changes - Allow all actions in put lifecycle configuration

### LINKED ISSUE #8341: Bucket lifecycle rules should allow top level Prefix and NoncurrentVersionExpiration and AbortIncompleteMultipartUpload elements
### Environment info
- NooBaa Version: **5.16**
- Platform: **NC**

### Actual behavior
1. We currently reject rules with top level Prefix (outside the Filter), which is allowed on AWS.
2. We currently reject rules with actions NoncurrentVersionExpiration and AbortIncompleteMultipartUpload.

### Expected behavior
1. We need to allow these.
2. This is a followup to #8300

### Steps to reproduce
1. Try to put the following lifecycle policy file which is valid for AWS:

```json
{
    "Rules": [
        {
            "ID": "Expiration",
            "Status": "Enabled",
            "Prefix": "p1",
            "Expiration": { "Days": 1 },
            "NoncurrentVersionExpiration": { "NoncurrentDays": 2 },
            "AbortIncompleteMultipartUpload": { "DaysAfterInitiation": 10 }
        },
        {
            "ID": "NoncurrentVersionExpiration",
            "Status": "Enabled",
            "Filter": {
                "Prefix": "p2"
            },
            "NoncurrentVersionExpiration": { "NoncurrentDays": 2 }
        },
        {
            "ID": "AbortIncompleteMultipartUpload",
            "Status": "Enabled",
            "Filter": {
                "And": {
                    "Prefix": "p3",
                    "ObjectSizeGreaterThan": 11
                }
            },
            "AbortIncompleteMultipartUpload": { "DaysAfterInitiation": 10 }
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by dannyzaken**
### Explain the changes
* although not all of the actions are implemented in the lifecycle bg worker, we still want to store the provided configuration and not fail it
* in NC case, the lifecycle work is performed outside of noobaa, so we want to provide all fields
* In addition, for now, allow passing the deprecated Prefix field. This commit leaves a gap regarding validation of the configuration, which should be more aligned with what AWS allows

### Issues: Fixed #xxx / Gap #xxx
1. Fixes #8341
2. #8376
3. opened Gap #8426

### Testing Instructions:
1. 

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/endpoint/s3/ops/s3_put_bucket_lifecycle.js [hunk 1]
```diff
@@ -95,39 +101,54 @@ async function put_bucket_lifecycle(req) {
...
-            throw new S3Error(S3Error.NotImplemented);
+
+
+        if (rule.Expiration && rule.Expiration.length === 1) {
+            current_rule.expiration = parse_expiration(rule.Expiration[0]);
         }
-        if (rule.Transition) {
-            dbg.error('Transition is not implemented, rule:', rule);
-            throw new S3Error(S3Error.NotImplemented);
+        if (rule.AbortIncompleteMultipartUpload && rule.AbortIncompleteMultipartUpload.length === 1) {
```
Comment (romayalon) [inline src/endpoint/s3/ops/s3_put_bucket_lifecycle.js:124]: style, maybe worth in all the conditions make the conditions easier to read by using ? check - 
`if (rule?.AbortIncompleteMultipartUpload.length === 1)`

File: src/endpoint/s3/ops/s3_put_bucket_lifecycle.js [hunk 2]
```diff
@@ -95,39 +101,54 @@ async function put_bucket_lifecycle(req) {
...
-            throw new S3Error(S3Error.NotImplemented);
-        }
-        current_rule.expiration = parse_expiration(rule.Expiration[0]);
 
-        if (rule.AbortIncompleteMultipartUpload) {
-            dbg.error('AbortIncompleteMultipartUpload is not implemented, rule:', rule);
-            throw new S3Error(S3Error.NotImplemented);
+
+
+        if (rule.Expiration && rule.Expiration.length === 1) {
```
Comment (romayalon) [inline src/endpoint/s3/ops/s3_put_bucket_lifecycle.js:121]: expiration is still required in the schema, we probably want to remove it if it's not required anymore
same for filter

**Review by romayalon — APPROVED** [review]
