### PR TITLE
call and set new error type mapping of INVALID_BUCKET_STATE error

### LINKED ISSUE #3848: Uploading file to system-internal-storage returns 403 AccessDenied when pool has no space
### Environment info
- Version: **2.0.0-ba13da2**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. Uploading file to system-internal-storage returns 403 AccessDenied when pool has no space

### Preconditions
bucket with pool with not enough healthy nodes

### Expected behavior
1. Uploading success

### Steps to reproduce
1.  Upload file 

### Additional info
reproduced about ones in 20 times

bucket403

### Screenshots or Logs or other output that would be helpful
(If large, please upload as attachment)

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. deleted set_mongo_store_limit.
2. called new error type - INVALID_BUCKET_STATE instead of INTERNAL error
3.  mapped INVALID_BUCKET_STATE and NOT_ENOUGH_SPACE errors of rpc errors to INVALID_BUCKET_STATE of s3 error.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #3848 

### Testing Instructions:
1.

### CODE REVIEW

File: src/agent/block_store_services/block_store_mongo.js [hunk 1]
```diff
@@ -112,7 +112,7 @@ class BlockStoreMongo extends BlockStoreBase {
                     dbg.log0('found usage data usage_data = ', this._usage);
                 }
             })
-            .then(() => this.set_mongo_store_limit())
+            //.then(() => this.set_mongo_store_limit())
```
Comment (liranmauda) [inline src/agent/block_store_services/block_store_mongo.js]: better remove the line + it looks like it is the only place that set_mongo_store_limit() so we can also remove the function itself.

File: src/server/object_services/map_server.js [hunk 2]
```diff
@@ -121,7 +121,11 @@ class GetMapping {
                 map_reporter.add_event(`allocate_chunks(${bucket.name})`, total_size, Date.now() - start_alloc_time);
                 if (!done) {
                     retries += 1;
-                    if (retries > config.IO_WRITE_BLOCK_RETRIES) throw new Error('Couldn\'t allocate chunk - Will stop retries');
+                    if (retries > config.IO_WRITE_BLOCK_RETRIES) {
+                        let err = new Error('Couldn\'t allocate chunk - Will stop retries');
```
Comment (liranmauda) [inline src/server/object_services/map_server.js]: We can change the let to const

**Review by liranmauda — CHANGES_REQUESTED** [review]

**Review by liranmauda — APPROVED** [review]
