### PR TITLE
Fixing NSFS MP Complete

### LINKED ISSUE #6528: NSFS - upload failed for 1 GB file with ENOSPC
### Environment info
- NooBaa Version: master-20210519 
- Platform: OCP 4.6.16

### Actual behavior
1. s3 upload of 1 GB file is not reflecting in s3://bucket

### Expected behavior
1.s3 upload should be successful and it should reflect the object in s3://bucket

### Steps to reproduce
1. Create namespace resource
2. Create account with UID, GID parameters
3. Create s3 bucket bucket-3
4. Create a 1 GB file
5. Run command to upload it to this bucket-3

Bucket status:
  Bucket                 : bucket-3
  Type                   : NAMESPACE
  Mode                   : OPTIMAL
  Num Objects            : 0
  Data Size              : 0.000 B
  Data Size Reduced      : 0.000 B
  Data Space Avail       : 0.000 B
  
File size:
```
[root@hpo-node1 akshat]# du -sh small_chunk_1
977M    small_chunk_1
```

Upload using command
`s3u3 cp small_chunk_1 s3://bucket-3/`

Upload failed:

 ` upload failed: ./small_chunk_1 to s3://bucket-3/small_chunk_1 Read timeout on endpoint URL: "https://api.ocp-akshat-1.cp.fyre.ibm.com:8443/bucket-3/small_chunk_1?uploadId=33f65ae4-9f2f-464a-bdaf-257ce0f2537a"`

### More information - Screenshots / Logs / Other output

```
sh-4.4# du -sh /nsfs/parent/bucket-3/.noobaa-nsfs/
977M	/nsfs/parent/bucket-3/.noobaa-nsfs/
```

```
[root@ocp-akshat-1-inf ~]# cat endpoint_small_chunk  |grep "PUT OBJECT PART bucket-3 small_chunk_1"|wc -l
123
```

### LINKED ISSUE #6546: Endpoint crashed on 1 GB file upload
### Environment info
- NooBaa Version: master-20210531
- Platform: OCP 4.6.16

### Actual behavior
1. Endpoint pod crashed on doing upload operations on s3 bucket

### Expected behavior
1. Endpoint should not get crashed

### Steps to reproduce
1. Started upload operation of multiple files with sizes 977M using s3 cp command

Found o**nly 1 file got upload to bucket-1** and .noobaa_nsfs* size increased during this upload.

```
[root@hpo-node1 akshat]# s3u1 ls s3://bucket-1|grep small_chunk
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-06-01 23:23:01 1024000000 small_chunk_1
```

```
[root@hpo-node1 akshat]# du -sh small_chunk_*
977M    small_chunk_1
977M    small_chunk_10
977M    small_chunk_1_read
977M    small_chunk_1._read
977M    small_chunk_2
977M    small_chunk_3
977M    small_chunk_4
977M    small_chunk_5
977M    small_chunk_6
977M    small_chunk_7
977M    small_chunk_8
977M    small_chunk_9
```

Uploading this endpoint log and noobaa diagnose

### More information - Screenshots / Logs / Other output
```

Jun-2 6:45:03.736 [Endpoint/9]    [L0] core.sdk.object_sdk:: _load_bucket_namespace {
  _id: '60b672a8369502002280a0c3',
  name: SENSITIVE-f53e749d8f84e52b,
  active_triggers: [ [length]: 0 ],
  system_owner: SENSITIVE-9cf0fd89409efef8,
  bucket_owner: SENSITIVE-3d288e97f8a66631,
  bucket_info: { name: SENSITIVE-f53e749d8f84e52b, owner_account: { email: SENSITIVE-3d288e97f8a66631, id: '60b6713b369502002280a0bf' }, namespace: { write_resource: { resource: 'nsfs-nsr-1', path: '/bucket-1' }, read_resources: [ { resource: 'nsfs-nsr-1', path: '/bucket-1' }, [length]: 1 ], should_create_underlying_storage: true }, tag: '', num_objects: { value: 0, last_update: 1622569559747 }, writable: false, storage: { values: { used: 0, used_other: 0, total: 0, free: 0 }, last_update: 1622616205102 }, data: { size: 0, size_reduced: 0, free: 0, available_for_upload: 0, last_update: 1622616205102 }, usage_by_pool: { pools: [ [length]: 0 ], last_update: 1622569559747 }, stats_by_type: [ [length]: 0 ], mode: 'OPTIMAL', bucket_type: 'NAMESPACE', versioning: 'DISABLED', triggers: [ [length]: 0 ] },
  namespace: {
    write_resource: { resource: { fs_root_path: '/nsfs/parent', fs_backend: 'GPFS', id: '60b67114369502002280a0be', name: 'nsfs-nsr-1' }, path: '/bucket-1' },
    read_resources: [ { resource: { fs_root_path: '/nsfs/parent', fs_backend: 'GPFS', id: '60b67114369502002280a0be', name: 'nsfs-nsr-1' }, path: '/bucket-1' }, [length]: 1 ],
    should_create_underlying_storage: true
  }
}
Jun-2 6:45:03.737 [Endpoint/9]   [LOG] CONSOLE:: NamespaceFS: abort_object_upload /nsfs/parent/bucket-1/.noobaa-nsfs_60b672a8369502002280a0c3/multipart-uploads/38055c2a-c9f1-4b97-be41-1574e9a1046c
Jun-2 6:45:10.907 [Endpoint/9] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/bucket-1/small_chunk_10</Resource><RequestId>kpf3uueu-65vjp-qni</RequestId></Error> HEAD /bucket-1/small_chunk_10 {"accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-240.22.1.el8_3.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.cp","x-amz-date":"20210602T064510Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=p8S5WxzMgdcZfoKEpJdf/20210602/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=e51b7ce1acc22259803e2829258153666171d440a521215b2dc4abe5b33e87be","host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error: No such file or directory
Jun-2 6:49:48.578 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: 'b1ee45f6-4c95-4e6b-80de-15ccf0782dec', hostname: 'noobaa-endpoint-6ddfcbc794-gjbcz' }
Jun-2 6:53:21.186 [Endpoint/9]  [WARN] core.util.mongo_client:: got close mongodb://noobaa-db-0.noobaa-db/nbcore
Jun-2 6:58:21.187 [Endpoint/9] [ERROR] core.util.mongo_client:: Connection closed for more  300000 , quitting




######################################################################
Wed Jun  2 06:58:21 UTC 2021 NooBaa: Process exited RIP (RC=1)
######################################################################

```

```
sh-4.4# e[root@ocp-akshat-1-inf ~]# podn
NAME                                               READY   STATUS        RESTARTS   AGE
noobaa-core-0                                      1/1     Running       0          13h
noobaa-db-0                                        1/1     Running       1          13h
noobaa-default-backing-store-noobaa-pod-fe588510   0/1     Terminating   0          14s
noobaa-endpoint-6ddfcbc794-gjbcz                   0/1     Error         0          13h
noobaa-operator-7c9c876b8c-zp475                   1/1     Running       0          13h

[root@ocp-akshat-1-inf ~]# podn
NAME                                               READY   STATUS        RESTARTS   AGE
noobaa-core-0                                      1/1     Running       0          14h
noobaa-db-0                                        1/1     Running       1          14h
noobaa-default-backing-store-noobaa-pod-fe588510   0/1     Terminating   0          3s
noobaa-endpoint-6ddfcbc794-gjbcz                   1/1     Running       1          13h
noobaa-operator-7c9c876b8c-zp475                   1/1     Running       0          14h
```

### LINKED ISSUE #6560: Upload fails for big files, Error CompleteMultipartUpload operation
Hello @jeniawhite , @guymguym 

I took latest PR from build 20210607.

Upload of 10GB file failed multiple times:

`s3u1 cp medium_chunk_2 s3://bucket-21/`

resulted in:

`upload failed: ./medium_chunk_2 to s3://bucket-21/medium_chunk_2 An error occurred (NoSuchKey) when calling the CompleteMultipartUpload operation: The specified key does not exist.
`
From endpoint log:

```
Jun-8 7:21:13.472 [Endpoint/9] [ERROR] CONSOLE::  [Error: No such file or directory] { code: 'ENOENT' }
Jun-8 7:21:13.476 [Endpoint/9] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/bucket-21/medium_chunk_2?uploadId=bbf8bb2c-5268-4dab-8fc7-b3f193a440f4</Resource><RequestId>kpnprriv-4l61yc-19cc</RequestId></Error> POST /bucket-21/medium_chunk_2?uploadId=bbf8bb2c-5268-4dab-8fc7-b3f193a440f4 {"accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-305.3.1.el8_4.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.cp","x-amz-date":"20210608T072047Z","x-amz-content-sha256":"724c5e1855fb269e6b937c9869fc34c23fcf462938e73918aedbadd8d8563686","authorization":"AWS4-HMAC-SHA256 Credential=VdQhqra60t4VjbH1Z6gI/20210608/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=9c4396ab83da4c19c4db817f395a2153d37e394a7e468c41e738642d183c814c","content-length":"122810","host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error: No such file or directory
Jun-8 7:21:13.659 [Endpoint/9]    [L0] core.sdk.object_sdk:: _load_bucket_namespace {
  _id: '60bf0c44fb88b00022295013',
  name: SENSITIVE-4fb32e336f0d19ff,
  active_triggers: [ [length]: 0 ],
  system_owner: SENSITIVE-9cf0fd89409efef8,
  bucket_owner: SENSITIVE-3d288e97f8a66631,
  bucket_info: { name: SENSITIVE-4fb32e336f0d19ff, owner_account: { email: SENSITIVE-3d288e97f8a66631, id: '60b9eab981db7600272fde66' }, namespace: { write_resource: { resource: 'nsfs-nsr-1', path: '/bucket-21' }, read_resources: [ { resource: 'nsfs-nsr-1', path: '/bucket-21' }, [length]: 1 ], should_create_underlying_storage: true }, tag: '', num_objects: { value: 0, last_update: 1623133186130 }, writable: false, storage: { values: { used: 0, used_other: 0, total: 0, free: 0 }, last_update: 1623136755736 }, data: { size: 0, size_reduced: 0, free: 0, available_for_upload: 0, last_update: 1623136755736 }, usage_by_pool: { pools: [ [length]: 0 ], last_update: 1623133186130 }, stats_by_type: [ [length]: 0 ], mode: 'OPTIMAL', bucket_type: 'NAMESPACE', versioning: 'DISABLED', triggers: [ [length]: 0 ] },
  namespace: {
    write_resource: { resource: { fs_root_path: '/nsfs/nsfs-nsr-1', fs_backend: 'GPFS', id: '60b9e3f681db7600272fde65', name: 'nsfs-nsr-1' }, path: '/bucket-21' },
    read_resources: [ { resource: { fs_root_path: '/nsfs/nsfs-nsr-1', fs_backend: 'GPFS', id: '60b9e3f681db7600272fde65', name: 'nsfs-nsr-1' }, path: '/bucket-21' }, [length]: 1 ],
    should_create_underlying_storage: true
  }
}
Jun-8 7:21:13.660 [Endpoint/9]   [LOG] CONSOLE:: NamespaceFS: buffers_pool BuffersPool {
  buf_size: 8388608,
  buffers: [ <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 8388558 more bytes>, <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 8388558 more bytes> ],
  sem: Semaphore { _initial: 536870912, _value: 536870912, _waiting_value: 0, _wq: WaitQueue { _name: '_wq_', _q: <ref *1> LinkedList { next: '_lln_', prev: '_llp_', head: '_llh_', length: 0, _lln_: [Circular *1], _llp_: [Circular *1], _llh_: [Circular *1] } } }
}
Jun-8 7:21:13.662 [Endpoint/9] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.</Message><Resource>/bucket-21/medium_chunk_2?uploadId=bbf8bb2c-5268-4dab-8fc7-b3f193a440f4</Resource><RequestId>kpnpsb6o-cjp60j-121c</RequestId></Error> DELETE /bucket-21/medium_chunk_2?uploadId=bbf8bb2c-5268-4dab-8fc7-b3f193a440f4 {"accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-305.3.1.el8_4.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.cp","x-amz-date":"20210608T072113Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=VdQhqra60t4VjbH1Z6gI/20210608/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=89b14475f17ec03cb08eb900528040bcf5e7a3789b8d8dfd646d6c7430296567","content-length":"0","host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error: No such file or directory
(END)

```

_Originally posted by @akmithal in https://github.com/noobaa/noobaa-core/issues/6528#issuecomment-856526130_

### LINKED ISSUE #6565: s3 bucket to bucket copy operation failed, 1 GB files - Linking did not work
### Environment info
- NooBaa Version: master-20210607
- Platform: OCP 4.6.16

### Actual behavior
1. Copy operation from one bucket to another failed

### Expected behavior
1. Copy operation should not fail

### Steps to reproduce
1. Created 2 buckets - bucket-1, bucket-21.
2. Uploaded multiple 1GB files to s3://bucket-1
3. Attempted copy operation from s3://bucket-1 to s3://bucket-21

Few files got copied but got failure for others:

```
[root@hpo-node1 akshat]# s3u1 ls s3://bucket-1/
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-06-08 21:15:06 1024000000 small_chunk_1
2021-06-08 21:15:28 1024000000 small_chunk_1._read
2021-06-08 21:15:12 1024000000 small_chunk_10
2021-06-08 21:15:26 1024000000 small_chunk_10._read
2021-06-08 21:15:27 1024000000 small_chunk_1_read
2021-06-08 21:16:15 1024000000 small_chunk_2
2021-06-08 21:16:18 1024000000 small_chunk_2._read
2021-06-08 21:16:53 1024000000 small_chunk_3
2021-06-08 21:16:25 1024000000 small_chunk_3._read
2021-06-08 21:16:08 1024000000 small_chunk_4
2021-06-08 21:17:12 1024000000 small_chunk_4._read
2021-06-08 21:17:25 1024000000 small_chunk_5
2021-06-08 21:17:36 1024000000 small_chunk_5._read
2021-06-08 21:17:44 1024000000 small_chunk_6
2021-06-08 21:18:36 1024000000 small_chunk_6._read
2021-06-08 21:19:13 1024000000 small_chunk_7
2021-06-08 21:19:05 1024000000 small_chunk_7._read
2021-06-08 21:19:22 1024000000 small_chunk_8
2021-06-08 21:19:29 1024000000 small_chunk_8._read
2021-06-08 21:19:39 1024000000 small_chunk_9
2021-06-08 21:19:37 1024000000 small_chunk_9._read
[root@hpo-node1 akshat]# 
[root@hpo-node1 akshat]# 
[root@hpo-node1 akshat]# s3u1 ls s3://bucket-21/
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-06-08 21:30:55 1024000000 small_chunk_8
2021-06-08 21:30:55 1024000000 small_chunk_8._read
2021-06-08 21:30:55 1024000000 small_chunk_9
2021-06-08 21:30:55 1024000000 small_chunk_9._read
```

Command used to copy files:
`s3u1 cp --recursive s3://bucket-1 s3://bucket-21/`

Errors:
```
copy failed: s3://bucket-1/small_chunk_9 to s3://bucket-21/small_chunk_9 An error occurred (NoSuchKey) when calling the CompleteMultipartUpload operation (reached max retries: 2): The specified key does not exist.
copy failed: s3://bucket-1/small_chunk_8 to s3://bucket-21/small_chunk_8 An error occurred (NoSuchKey) when calling the CompleteMultipartUpload operation (reached max retries: 2): The specified key does not exist.
copy failed: s3://bucket-1/small_chunk_9._read to s3://bucket-21/small_chunk_9._read An error occurred (NoSuchKey) when calling the CompleteMultipartUpload operation (reached max retries: 2): The specified key does not exist.
```

### More information - Screenshots / Logs / Other output

```
Jun-9 4:29:35.711 [Endpoint/9]   [LOG] CONSOLE:: update_endpoint_stats. namespace_stats = []
Jun-9 4:30:05.205 [Endpoint/9]   [LOG] CONSOLE:: NamespaceFS: abort_object_upload /nsfs/nsfs-nsr-1/bucket-21/.noobaa-nsfs_60c0406ba0157e00233de2dc/multipart-uploads/f989c13a-82c4-40e7-b1ba-71162a3
def85
Jun-9 4:30:05.897 [Endpoint/9] [ERROR] CONSOLE::  [Error: No such file or directory] { code: 'ENOENT' }
Jun-9 4:30:05.897 [Endpoint/9] [ERROR] CONSOLE::  [Error: No such file or directory] { code: 'ENOENT' }
Jun-9 4:30:05.995 [Endpoint/9] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><R
esource>/bucket-21/small_chunk_4._read?uploadId=f989c13a-82c4-40e7-b1ba-71162a3def85</Resource><RequestId>kpoz3eu6-6rwwuk-1aal</RequestId></Error> POST /bucket-21/small_chunk_4._read?uploadId=f989
c13a-82c4-40e7-b1ba-71162a3def85 {"accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-305.3.1.el8_4.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.cp","x-amz-date":
"20210609T042933Z","x-amz-content-sha256":"cc82905fa5a8bc75908709678e6972231fe14ce147ac9ef3611ec94ac4575f9f","authorization":"AWS4-HMAC-SHA256 Credential=YrpJ6lYpmcU6u8ODljQG/20210609/us-east-1/s3
/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=fad4887a005b0cd9e9fe190aadbbc283719e3d4af452b41385d8c04b97cf428e","content-length":"11641","host":"s3-noobaa.apps.ocp-a
kshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;host=s3-noobaa.apps.ocp
-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error: No such file or directory
Jun-9 4:30:05.996 [Endpoint/9] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><R
esource>/bucket-21/small_chunk_4._read?uploadId=f989c13a-82c4-40e7-b1ba-71162a3def85</Resource><RequestId>kpoz2p77-313rnn-1076</RequestId></Error> POST /bucket-21/small_chunk_4._read?uploadId=f989
c13a-82c4-40e7-b1ba-71162a3def85 {"accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-305.3.1.el8_4.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.cp","x-amz-date":
"20210609T042901Z","x-amz-content-sha256":"cc82905fa5a8bc75908709678e6972231fe14ce147ac9ef3611ec94ac4575f9f","authorization":"AWS4-HMAC-SHA256 Credential=YrpJ6lYpmcU6u8ODljQG/20210609/us-east-1/s3
/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=886bd10e1ca6928f0e01cb53ed17f8675de6e6d42d8ab351484e2dbf3f25c192","content-length":"11641","host":"s3-noobaa.apps.ocp-a
kshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;host=s3-noobaa.apps.ocp
-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error: No such file or directory
Jun-9 4:30:12.901 [Endpoint/9]   [LOG] CONSOLE:: NamespaceFS: abort_object_upload /nsfs/nsfs-nsr-1/bucket-21/.noobaa-nsfs_60c0406ba0157e00233de2dc/multipart-uploads/c33a6269-c625-4d62-9d9c-1b34258
23bd3
Jun-9 4:30:13.298 [Endpoint/9] [ERROR] CONSOLE::  [Error: No such file or directory] { code: 'ENOENT' }
```

### PR DESCRIPTION
**Pull request by jeniawhite**
### Explain the changes
1. Align NSFS MP Complete to AWS spec

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #6560 
2. Fixed #6528 
4. Fixed #6546 

### Testing Instructions:
1.

### CODE REVIEW

File: src/sdk/namespace_fs.js [hunk 1]
```diff
@@ -778,6 +779,17 @@ class NamespaceFS {
                 read_file = await nb_native().fs.open(fs_account_config, part_path, undefined, get_umasked_mode(config.BASE_MODE_FILE));
                 let read_pos = 0;
                 for (;;) {
+                    if (!interval_body_update) {
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:782]: why is it inside the for loop? AFAIU the first if condition is for running it once so why not calling it before the loop and get rid of the first if condition?

Comment (jeniawhite) [reply src/sdk/namespace_fs.js:782]: Because we can fail at the opening (in theory) and it would be an AccessDenied error.
That way I want to have the failure as headers response and not body response since we did not start doing any actual work.

**Review by romayalon — APPROVED** [review]

**Comment by dannyzaken** [comment]
@jeniawhite following our discussion, I had another idea. 
we can perform the periodic body update in the s3 op level but start after an initial delay. if the operation is completed before we can send the correct status code. otherwise, we return 200, start the periodic update and send any potential error in the body.

WDYT?

**Comment by jeniawhite** [comment]
@dannyzaken 
What if it takes us a certain amount of time to reach the NS and it is above the delay that you've set?
We would send OK and then get a HEADER response from the NS.
I think playing with timeouts and delays is patchy.

**Comment by dannyzaken** [comment]
@jeniawhite I think the opposite. you don't want the client to timeout, so after a certain amount of time, if you don't get an answer you let the client know things are in progress. this is more consistent

**Review by guymguym — COMMENTED** [review]
Some small comments added. In general, as we already discussed, I agree with Danny that a generic timer in the s3 op would be an improvement to all namespaces, even though there might be corner cases where we would respond with a delayed error in the reply body and the statusCode will not represent it accurately, however this is still an improvement because currently if this happens the client gives up anyhow and will just be retrying without known there was an error.

**Comment by nimrod-becker** [comment]
@jeniawhite removed #6565 since we treat that as a linking issue and not MPUC

File: src/endpoint/s3/ops/s3_post_object_uploadId.js [hunk 2]
```diff
@@ -24,27 +25,53 @@ async function post_object_uploadId(req, res) {
...
+    // will be responded in BODY, we cannot rollback from that for pre HEADER failures
+    // instread of having a fine tuned way start of sending body to make sure that we won't respond by BODY on HEADER failures
+    const interval_body_update = setInterval(() => {
+        if (res.headersSent) {
+            // Keep the connection alive with white spaces
+            res.write(' ');
+        } else {
+            // Mark begining of BODY response
+            // Assuming that write automatically assigns 200 OK status
+            res.write('<?xml version="1.0" encoding="UTF-8"?>');
```
Comment (guymguym) [inline src/endpoint/s3/ops/s3_post_object_uploadId.js:39]: Can you move this string to a constant in xml_htils?

File: src/endpoint/s3/ops/s3_post_object_uploadId.js [hunk 3]
```diff
@@ -24,27 +25,53 @@ async function post_object_uploadId(req, res) {
...
+                Key: req.params.key,
+                ETag: `"${reply.etag}"`,
+                Location: req.originalUrl,
+            }
+        };
+    } catch (error) {
+        if (res.headersSent) dbg.error('Error during long complete_object_upload', error);
+        throw error;
+    } finally {
+        if (interval_body_update) clearInterval(interval_body_update);
```
Comment (guymguym) [inline src/endpoint/s3/ops/s3_post_object_uploadId.js:73]: if is unneeded
```suggestion
        clearInterval(interval_body_update);
```

File: src/endpoint/s3/ops/s3_post_object_uploadId.js [hunk 4]
```diff
@@ -24,27 +25,53 @@ async function post_object_uploadId(req, res) {
...
+            CompleteMultipartUploadResult: {
+                Bucket: req.params.bucket,
+                Key: req.params.key,
+                ETag: `"${reply.etag}"`,
+                Location: req.originalUrl,
+            }
+        };
+    } catch (error) {
+        if (res.headersSent) dbg.error('Error during long complete_object_upload', error);
+        throw error;
```
Comment (guymguym) [inline src/endpoint/s3/ops/s3_post_object_uploadId.js:71]: I would move this logging to http_utils.send_reply

File: src/endpoint/s3/ops/s3_post_object_uploadId.js [hunk 5]
```diff
@@ -24,27 +25,53 @@ async function post_object_uploadId(req, res) {
...
-        bucket: req.params.bucket,
-        key: req.params.key,
-        md_conditions: http_utils.get_md_conditions(req),
-        multiparts
-    });
+    // Write periodically to keep the connection alive
+    // TODO: Every complete above the S3_KEEP_ALIVE_WHITESPACE_INTERVAL
+    // will be responded in BODY, we cannot rollback from that for pre HEADER failures
+    // instread of having a fine tuned way start of sending body to make sure that we won't respond by BODY on HEADER failures
+    const interval_body_update = setInterval(() => {
```
Comment (guymguym) [inline src/endpoint/s3/ops/s3_post_object_uploadId.js:32]: I would hang this interval on the response object itself, and refactor this function to http_utils, like this:
```js
http_utils.set_keep_alive_whitespace_interval(res);
```

And would implement it like this:
```js
function set_keep_alive_whitespace_interval(res) {
    res.keep_alive_whitespace_interval = setInterval(() => {
        ...
    }, config.S3_KEEP_ALIVE_WHITESPACE_INTERVAL);
    res.keep_alive_whitespace_interval.unref();
    const clear = () => clearInterval(res.keep_alive_whitespace_interval);
    res.on('close', clear);
    res.on('finish', clear);
}
```

and then you don't need to explicitly handle removing the interval in case send_reply is called.

File: src/util/http_utils.js [hunk 6]
```diff
@@ -321,13 +321,17 @@ function send_reply(req, res, reply, options) {
...
+        // TODO: Refactor later on to support potential headers response and delayed XML body
+        // This is done for the complete since we assign the XML header only in body prior to responding
+        const xml_reply = xml_utils.encode_xml(xml_root, /* ignore_header */ res.headersSent);
         dbg.log1('HTTP REPLY XML', req.method, req.originalUrl,
             JSON.stringify(req.headers),
             xml_reply.length <= 2000 ?
             xml_reply : xml_reply.slice(0, 1000) + ' ... ' + xml_reply.slice(-1000));
-        res.setHeader('Content-Type', 'application/xml');
-        res.setHeader('Content-Length', Buffer.byteLength(xml_reply));
+        if (!res.headersSent) {
```
Comment (guymguym) [inline src/util/http_utils.js:331]: The same handling is needed in s3_rest handle error

**Review by guymguym — CHANGES_REQUESTED** [review]
Some comments. Most notable is that the same handling is needed in s3_rest handle_error() like you added to send_reply.

File: src/test/unit_tests/test_namespace_fs.js [hunk 7]
```diff
@@ -205,8 +205,8 @@ mocha.describe('namespace_fs', function() {
             console.log('create_object_upload response', inspect(create_res));
 
             const obj_id = create_res.obj_id;
-            const num_parts = 10;
-            const part_size = 1024 * 1024;
+            const num_parts = 100;
+            const part_size = 10 * 1024 * 1024;
```
Comment (guymguym) [inline src/test/unit_tests/test_namespace_fs.js:209]: I don't think this is a good idea for unit tests in memory. I would look for another way to test.

File: src/endpoint/s3/ops/s3_post_object_uploadId.js (hunk 4 above)
Comment (jeniawhite) [reply src/endpoint/s3/ops/s3_post_object_uploadId.js:71]: Send_reply only works in the happy case when the function succeeds and doesn't throw.
I think that if we want this we can add later on inside the handle_error function in s3_rest, but I will leave it for now.

File: src/endpoint/s3/s3_rest.js [hunk 8]
```diff
@@ -475,16 +441,18 @@ function handle_error(req, res, err) {
         req.method, req.originalUrl,
         JSON.stringify(req.headers),
         err.stack || err);
-    res.statusCode = s3err.http_code;
-    res.setHeader('Content-Type', 'application/xml');
-    res.setHeader('Content-Length', Buffer.byteLength(reply));
+    if (!res.headersSent) {
```
Comment (guymguym) [inline src/endpoint/s3/s3_rest.js:444]:
```suggestion
    if (res.headersSent) {
        dbg.log0('sending error xml in body, but too late for headers...');
    } else {
```

File: src/test/unit_tests/test_namespace_fs.js [hunk 9]
```diff
@@ -195,7 +195,7 @@ mocha.describe('namespace_fs', function() {
 
         const mpu_key = 'mpu_upload';
 
-        mocha.it('upload, read, delete a small multipart object', async function() {
+        mocha.it('upload, read, delete a multipart object', async function() {
```
Comment (guymguym) [inline src/test/unit_tests/test_namespace_fs.js:198]: clean this change?

File: src/util/http_utils.js [hunk 10]
```diff
@@ -321,13 +322,17 @@ function send_reply(req, res, reply, options) {
...
```
Comment (guymguym) [inline src/util/http_utils.js:332]:
```suggestion
        if (res.headersSent) {
            dbg.log0('sending  xml reply in body, bit too late for headers');
        } else {
```

File: src/util/http_utils.js [hunk 11]
```diff
@@ -444,6 +449,27 @@ function make_https_request(options, body, body_encoding) {
     });
 }
 
+// Write periodically to keep the connection alive
+// TODO: Every complete above the S3_KEEP_ALIVE_WHITESPACE_INTERVAL
+// will be responded in BODY, we cannot rollback from that for pre HEADER failures
+// instread of having a fine tuned way start of sending body to make sure that we won't respond by BODY on HEADER failures
+function set_keep_alive_whitespace_interval(res) {
+    res.keep_alive_whitespace_interval = setInterval(() => {
```
Comment (guymguym) [inline src/util/http_utils.js:457]: Worth adding a log print in the interval:
```suggestion
    let count = 0;
    res.keep_alive_whitespace_interval = setInterval(() => {
        count += 1;
        dbg.log0(`keep_alive_whitespace_interval headersSent=${headersSent} count=${count} `);
        if (res.headersSent) {
```

File: src/endpoint/s3/s3_rest.js [hunk 12]
```diff
@@ -446,18 +412,18 @@ function parse_op_name(req) {
...
+        new S3Error(S3Error.RPC_ERRORS_TO_S3[err.rpc_code] || S3Error.InternalError);
 
     if (s3err.code === 'MalformedPolicy') {
         s3err.message = err.message;
         s3err.detail = err.rpc_data.detail;
     }
 
     if (s3err.rpc_data) {
-        if (s3err.rpc_data.etag) {
+        if (s3err.rpc_data.etag && !res.headersSent) {
```
Comment (guymguym) [inline src/endpoint/s3/s3_rest.js:423]: I would avoid silent ignore at this stage, at least until we're sure that's OK:
```suggestion
        if (s3err.rpc_data.etag) {
            if (res.headersSent) {
                dbg.log0('...');
            } else {
```

Same for the last_modified header below too.

**Review by guymguym — APPROVED** [review]
Just requested some more log prints.
Otherwise looks good.
