### PR TITLE
Standalone | CLI | fix account list issues

### LINKED ISSUE #7548: Issues observed in Account List command
### Environment info

NooBaa Version: 5.15
Platform: Linux

### 1.All Account should be listed with all the details present in the manifest

https://github.com/noobaa/noobaa-core/issues/7587

### Actual Behaviour:
Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' } ]
### Expected Behaviour:
Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' ,config_root:/ibm/fs1/ces/s3-config,email:[<noobaa@gmail.com|noobaa@gmail.com](mailto:noobaa@gmail.com)>,new_buckets_path:/ibm/fs2  } ]

### 2. Account details should be listed with particular accountName

https://github.com/noobaa/noobaa-core/issues/7588

### Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' } ]

### Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config —name noobaa
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' ,config_root:/ibm/fs1/ces/s3-config,email:[noobaa@gmail.com](mailto:noobaa@gmail.com),new_buckets_path:/ibm/fs2  } ]

### LINKED ISSUE #7574: Create Account |  Uid and gid should be validated to accept only integers
@ ramya-c3

Actual Behaviour:
Command:
[root@ramya-sc-worker noobaa-core]#node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:38:34.010 [/2817991] [LOG] CONSOLE:: Resource created : a-abcdefghijklmn123456

Expected Behaviour:
Command:
[root@ramya-sc-worker noobaa-core]#node src/cmd/manage_nsfs account add --config_root /ibm/fs1/ces/s3-config --name noobaa --email [noobaa@gmail.com](mailto:noobaa@gmail.com) --new_buckets_path /ibm/fs2 --access_key a-abcdefghijklmn123456 --secret_key s-abcdefghijklmn123456 --uid test --gid test
Oct-25 22:38:34.010 [/2817991] [ERROR] CONSOLE:: Error: uid and gid must be integer

### LINKED ISSUE #7587: Accounts should be listed with all the details present in the manifest
### Environment info

NooBaa Version: 5.15
Platform: Linux

### All Account should be listed with all the details present in the manifest
Actual Behaviour:
Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' } ]
Expected Behaviour:
Command :
[root@ramya-sc-worker noobaa-core]# node src/cmd/manage_nsfs account list --config_root /ibm/fs1/ces/s3-config
Oct-25 23:17:32.074 [/2859127]   [LOG] CONSOLE::  [ { name: 'noobaa' ,config_root:/ibm/fs1/ces/s3-config,email:[<noobaa@gmail.com|noobaa@gmail.com](mailto:noobaa@gmail.com)>,new_buckets_path:/ibm/fs2  } ]

### PR DESCRIPTION
**Pull request by liranmauda**
### Explain the changes
- Status now listed with all the details present in the manifest, except for the access_keys and nsfs_account_config
- added --wide flag to list to show all the details present in the manifest per account (same as status)
- Verifying the UID and GID are a number

### Issues: Fixed #xxx / Gap #xxx
1. Fixes: #7548
2. Fixes #7574
3. Fixes: #7587

### CODE REVIEW

File: src/cmd/manage_nsfs.js [hunk 1]
```diff
@@ -417,26 +418,48 @@ async function manage_account_operations(action, data, config_root, config_root_
         await delete_account_config_file(data, account_path, config_root_backend);
     } else if (action === 'list') {
         const accounts = await list_config_file(account_path);
-        console.log(accounts);
+        if (data.name) {
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:421]: why do we need to support it? we have the account status command

File: src/cmd/manage_nsfs.js [hunk 2]
```diff
@@ -417,26 +418,48 @@ async function manage_account_operations(action, data, config_root, config_root_
...
 }
 
-async function get_create_config_file(resources_path, bucket_config_file_name) {
-    const full_path = path.join(resources_path, bucket_config_file_name);
+/**
+ * get_resource_data will get a json file and get the resource data from it
+ * @param {fs.PathLike} resource_path
+ * @param {string} config_file_name
+ */
+async function get_resource_data(resource_path, config_file_name) {
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:454]: can you please use config instead of resource?

File: src/cmd/manage_nsfs.js [hunk 3]
```diff
@@ -226,13 +233,9 @@ async function get_bucket_config_file_status(data, bucket_config_path, config_ro
...
     }
     try {
-        const raw_data = await fs.promises.readFile(path.join(bucket_config_path, data.name + '.json'));
-        const config_data = JSON.parse(raw_data.toString());
-        if (config_data) {
-            console.log(config_data);
-        } else {
-            console.log('Bucket do not exists with name : ' + data.name);
-        }
+        console.log('LMLM');
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:236]: remove print

File: src/cmd/manage_nsfs.js (hunk 1 above)
Comment (romayalon) [reply src/cmd/manage_nsfs.js:422]: as we discussed, let's remove this data.name

File: src/cmd/manage_nsfs.js [hunk 4]
```diff
@@ -416,27 +417,50 @@ async function manage_account_operations(action, data, config_root, config_root_
...
 
-async function get_create_config_file(resources_path, bucket_config_file_name) {
-    const full_path = path.join(resources_path, bucket_config_file_name);
+/**
+ * get_config_data will get a json file and get the resource data from it
+ * @param {fs.PathLike} config_file_path
+ * @param {string} config_file_name
+ */
+async function get_config_data(config_file_path, config_file_name) {
+    const full_path = path.join(config_file_path.toString(), config_file_name);
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:456]: let's replace it with get_config_file_path() call

File: src/cmd/manage_nsfs.js [hunk 5]
```diff
@@ -393,13 +396,8 @@ async function get_account_config_file_status(data, account_path, config_root_ba
...
     }
     try {
-        const raw_data = await fs.promises.readFile(path.join(account_path, data.access_keys[0].access_key + '.json'));
-        const config_data = JSON.parse(raw_data.toString());
-        if (config_data) {
-            console.log(config_data);
-        } else {
-            console.log('Account do not exists with access key : ' + data.access_keys[0].access_key);
-        }
+        const config_data = await get_config_data(account_path, data.access_keys[0].access_key + '.json');
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:399]: .json is already added in get_config_file()

**Review by romayalon — APPROVED** [review]
As discussed on slack, @liranmauda will add the relevant docs and unit tests on a follow up PR
