### PR TITLE
NC | NSFS | Add `stat` to `bucket_namespace_cache`

### LINKED ISSUE #8391: NC | NSFS | `bucket_namespace_cache` Is Not Updated Between Forks
### Environment info
- NooBaa Version: 5.18
- Platform: NC

### Actual behavior
1. When using child process configuration (`ENDPOINT_FORKS` in the `config.json`) the `bucket_namespace_cache` is not shared between the forks. Currently, we need to wait for one minute before the item is cleaned from the cache.

### Expected behavior
1. The cache will be updated and we will not have to wait.

### Steps to reproduce
This issue was raised as part of issue #8368 
1. Change the configuration to have more than 1 fork, for example: `sudo vi /etc/noobaa.conf.d/config.json` and `{"ENDPOINT_FORKS": 2}`).
2. Change the bucket configuration (for example change the existing bucket policy from: list object versions of a versioned bucket of all principals on the bucket and its objects to: allow get-object of a specific key with principal of account2).
3. Use the configuration as it was changed (try to get-object of this key by account2).

more details about the steps can be found in [this comment](https://github.com/noobaa/noobaa-core/issues/8368#issuecomment-2357765607).
It is not guaranteed that you will reproduce it since it might be that all the changes would be from the same child process.

### More information - Screenshots / Logs / Other output
 Example of policies:
from policy1:
 ```json
{
  "Version": "2012-10-17",
  "Statement": [ 
    { 
     "Effect": "Allow", 
     "Principal": { "*" }, 
     "Action": [ "s3:ListBucketVersions" ], 
     "Resource": [ "arn:aws:s3:::<bucket-name>/*", "arn:aws:s3:::<bucket-name>" ] 
    }
  ]
}
```

to policy2:
```json
{
  "Version": "2012-10-17",
  "Statement": [ 
    { 
     "Effect": "Allow", 
     "Principal": { "AWS": [ "<account name-2" ] }, 
     "Action": [ "s3:GetObject", "s3:GetObjectVersion" ], 
     "Resource": [ "arn:aws:s3:::<bucket-name>/<key-name>" ] 
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. Create config option `NC_ENABLE_BUCKET_NS_CACHE_STAT_VALIDATION` to enable/disable this addition.
2. Add in `read_bucket_sdk_info` inside bucketspace FS property `stat`, and add a method `stat_bucket` that would only implemented in FS (as we `stat` cofig files, and in NB with DB we don't need this).
3. Edit the `_validate_bucket_namespace` so before checking the validation by time, in case it is bucketspace FS we will compare the `stat` and return `false` (invalidate) in case the config file was changed.
4. Changes in `nc_coretest` create the functions `start_nsfs_process` and `stop_nsfs_process` based on existing implementation to allow us to restart nsfs.
5. Rename the function `check_bucket_config` to `check_stat_bucket_storage_path` that it would be less confusing.
6. Edit the printings of "Could not log bucket operation" to have the details of where they were printed.
7. Adding a basic test of running with a couple of forks (based on [this comment](https://github.com/noobaa/noobaa-core/pull/8527#discussion_r1842148932)).
8. Change the default number of forks in the Ceph NSFS tests in the CI to 2 (see [comment](https://github.com/noobaa/noobaa-core/pull/8527#discussion_r1848506858)).
9. Rename file `test_bucketspace.js` to `test_nsfs_integration.js` and the nc_core test log files from `src/logfile` to `nsfs_integration_test_log`.
10. Small changes in `s3_bucket_logging.js` regarding bucket deletion: bucket existed and bucket that did not exist  (see [comment](https://github.com/noobaa/noobaa-core/pull/8527#issuecomment-2485344631)) - see #8540.

Note: the changes are based on the suggestions written as a [comment](https://github.com/noobaa/noobaa-core/issues/8391#issuecomment-2410609077).

### Issues: Fixed #8391 
1. Currently, bucket configuration is saved in a file, but when using the `bucket_namespace_cache` it expires after 1 minute, see https://github.com/noobaa/noobaa-core/blob/e1bf29e82128a9e0d359b262978d208ccff228e5/config.js#L637-L638 We want to invalidate a bucket config not only by the time criteria.

GAPs:
1. We would probably want to do the same on `account_cache` and `account_id_cache`, but currently it has lower priority than the `bucket_namespace_cache`.
2. This PR is only in NC deployment, maybe we want something like that in Containerized (from what I understand we don't invalidate the items in the cache after every "make_changes" on bucket operation) see [MCGI-274](https://issues.redhat.com/browse/MCGI-274)

The renaming of `test_bucketspace.js` is a partial fix of #8056.

#### Automatic Test:
Please run: `sudo NC_CORETEST=true node ./node_modules/mocha/bin/mocha ./src/test/unit_tests/test_nc_with_a_couple_of_forks.js`
Note: if you want to check the setup changing and the restart please change this line: `coretest.setup(setup_options);
` to `coretest.setup({});`

#### Manual Test:
1. Create an account with the CLI: `sudo node src/cmd/manage_nsfs account add --name <account-name> --new_buckets_path /tmp/nsfs_root1 --access_key <access-key> --secret_key <secret-key> --uid <uid> --gid <gid>`
Note: before creating the account need to give permission to the `new_buckets_path`: `chmod 777 /tmp/nsfs_root1`.
2. Start the NSFS server with: `sudo node src/cmd/nsfs --debug 5`
Notes: 
- I Change the `config.NSFS_CHECK_BUCKET_BOUNDARIES = false; //SDSD` because I’m using the `/tmp/` and not `/private/tmp/`.
3. Create the alias for S3 service:`alias nc-user-1-s3=‘AWS_ACCESS_KEY_ID=<access-key> AWS_SECRET_ACCESS_KEY=<secret-key> aws --no-verify-ssl --endpoint-url https://localhost:6443’`.
4. Check the connection to the endpoint and try to list the buckets (should be empty): `nc-user-1-s3 s3 ls; echo $?`
5. Add bucket to the account using AWS CLI: `nc-user-1-s3 s3 mb s3://check-bucket` (`check-bucket` is the bucket name in this example)
6. Create the content for the body: `echo hello > mykey.txt`
7. Put object: `nc-user-1-s3 s3api put-object --bucket check-bucket --key mykey --body mykey.txt`.

Test changing bucket config file on the cache behavior:
8. Add the line: `console.log('SDSD config file was changed');` after `if (!same_stat) { // config file of bucket was changed` and restart the server (ctrl +c and rerun with `sudo node src/cmd/nsfs --debug 5`).
9. List the objects in the bucket (twice - we don't expect to see the added printings): `nc-user-1-s3 s3 ls s3://check-bucket`.
10. Edit the bucket config file, for example: `sudo node src/cmd/manage_nsfs bucket update --name check-bucket --fs_backend GPFS` (it was '' and we change it to GPFS).
11. List the objects in the bucket: `nc-user-1-s3 s3 ls s3://check-bucket` (we expect to see the added printings in the logs).
12. Change the `config. NC_ENABLE_BUCKET_NS_CACHE_STAT_VALIDATION = false;` and restart the server (ctrl +c and rerun with `sudo node src/cmd/nsfs --debug 5`).
13. List the objects in the bucket: `nc-user-1-s3 s3 ls s3://check-bucket`
14.  Edit the bucket config file, for example: `sudo node src/cmd/manage_nsfs bucket update --name check-bucket --fs_backend ''` (it was GPFS and we change it to '').
15. List the objects in the bucket: `nc-user-1-s3 s3 ls s3://check-bucket` (we don't expect to see the added printings in the logs).

Test bucket create and delete (due to initial failure in Ceph test `test_bucket_create_delete`):
16. Create a bucket: `nc-user-1-s3 s3 mb s3://bucket-del-01`
17. Delete the created bucket immediately: `nc-user-1-s3 s3 rb s3://bucket-del-01` (would see the printings "_validate_bucket_namespace got an error [Error: No such file or directory] { code: 'ENOENT', context: 'Stat _path=/etc/noobaa.conf.d/buckets/bucket-del-01.json ' } ignoring...") 

- [X] Doc added/updated
- [X] Tests added

### CODE REVIEW

File: src/sdk/object_sdk.js [hunk 1]
```diff
@@ -286,6 +286,24 @@ class ObjectSDK {
...
+        if (ns_allow_stat_bucket) {
+            let current_stat;
+            try {
+                current_stat = await this._get_bucketspace().stat_bucket(params.name);
+            } catch (err) {
+                // originally this part was added in case a bucket is created and then deleted
+                // and we would get ENOENT, but decide that on any error we will not use the stat
+                dbg.log4('_validate_bucket_namespace got an error', err, 'ignoring...');
+            }
+            if (current_stat) {
```
Comment (naveenpaul1) [inline src/sdk/object_sdk.js:300]: instead of adding the code in different if block can you add it inside try block where `stat_bucket()` throws error,

File: src/sdk/bucketspace_fs.js [hunk 2]
```diff
@@ -175,6 +176,19 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
         }
     }
 
+    /**
```
Comment (naveenpaul1) [inline src/sdk/bucketspace_fs.js:179]: please add return param

Comment (shirady) [reply src/sdk/bucketspace_fs.js:179]: I will add, thanks.

File: config.js [hunk 3]
```diff
@@ -637,6 +637,9 @@ config.INLINE_MAX_SIZE = 4096;
 // Object SDK bucket cache expiration time
 config.OBJECT_SDK_BUCKET_CACHE_EXPIRY_MS = 60000;
 
+// Object SDK bucket_namespace_cache allow stat of the config file
+config.ALLOW_BUCKET_NS_CACHE_STAT = true;
```
Comment (romayalon) [inline config.js:641]: I think we should mention here NC, because the stat is on config files and that it's for validation
```suggestion
config.NC_ENABLE_BUCKET_NS_CACHE_STAT_VALIDATION = true;
```

Comment (romayalon) [inline config.js:641]: @shirady regarding tests - 
1. Can you enable the ceph tests that should work now due to this fix
2. Can you think of unit/integration tests for checking it?

File: src/sdk/bucketspace_fs.js [hunk 4]
```diff
@@ -175,6 +176,21 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+     * stat_bucket will return the stat output on bucket config file
+     * @param {string} bucket_name
+     * @returns {Promise<nb.NativeFSStats>}
+     */
+    async stat_bucket(bucket_name) {
+        if (config.ALLOW_BUCKET_NS_CACHE_STAT) {
+            try {
+                const bucket_config_path = this.config_fs.get_bucket_path_by_name(bucket_name);
+                return nb_native().fs.stat(this.fs_context, bucket_config_path);
```
Comment (romayalon) [inline src/sdk/bucketspace_fs.js:188]: we should prefer interactions with config files inside config_fs, can you move it please? 
```
const bucket_config_path = this.config_fs.get_bucket_path_by_name(bucket_name);
return nb_native().fs.stat(this.fs_context, bucket_config_path);
```

File: src/sdk/bucketspace_fs.js [hunk 5]
```diff
@@ -155,6 +155,7 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
                     }
                 }
             }
+            bucket.stat = await this.stat_bucket(bucket.name.unwrap());
```
Comment (romayalon) [inline src/sdk/bucketspace_fs.js:158]: the name of the function is confusing a bit because this function is in bucketspace_fs and not in config_fs
stat also can be on the storage path of the bucket
this reminds me there is a very confusion in the function call in read_bucket_sdk_info - 
`const is_valid = await this.check_bucket_config(bucket);`
check_bucket_config() stats the bucket_storage_path
if you can fix this issue as part of this PR it'll be great

File: src/sdk/object_sdk.js [hunk 6]
```diff
@@ -286,6 +286,23 @@ class ObjectSDK {
 
     async _validate_bucket_namespace(data, params) {
         const time = Date.now();
+        // stat check (only in bucketspace FS)
+        const ns_allow_stat_bucket = Boolean(this._get_bucketspace().stat_bucket);
+        if (ns_allow_stat_bucket) {
+            try {
+                const current_stat = await this._get_bucketspace().stat_bucket(params.name);
+                if (current_stat) {
+                    const same_stat = current_stat.ino === data.stat.ino && current_stat.mtimeNsBigint === data.stat.mtimeNsBigint;
```
Comment (romayalon) [inline src/sdk/object_sdk.js:295]: this check is very bucketspace/config_fs related, please move it

File: src/sdk/object_sdk.js [hunk 7]
```diff
@@ -305,6 +322,7 @@ class ObjectSDK {
      *      ns: nb.Namespace;
      *      bucket: object;
      *      valid_until: number;
+     *      stat: object;
```
Comment (romayalon) [inline src/sdk/object_sdk.js:325]: why this is outside of the bucket if it's being hanged on the bucket object?

File: src/sdk/bucketspace_fs.js [hunk 8]
```diff
@@ -164,17 +165,58 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
         }
     }
 
+    /**
+     * check_bucket_config will change the bucket_storage_path
+     * and - TODO: Bucket owner check
+     * @param {object} bucket
+     * @returns {Promise<boolean>}
+     */
```
Comment (romayalon) [inline src/sdk/bucketspace_fs.js:173]: I meant that there is no reason to call this function check_bucket_config if it's checking the bucket storage path, there is no relation to the config here

File: src/sdk/object_sdk.js [hunk 9]
```diff
@@ -286,6 +286,24 @@ class ObjectSDK {
 
     async _validate_bucket_namespace(data, params) {
         const time = Date.now();
+        // stat check (only in bucketspace FS)
+        const bs = this._get_bucketspace();
+        const ns_allow_stat_bucket = Boolean(bs.stat_bucket_config_file);
```
[the remark this answers is not in the document]
Comment (shirady) [reply src/sdk/object_sdk.js]: I moved it, thanks.

File: src/sdk/bucketspace_fs.js (hunk 8 above)
Comment (shirady) [reply src/sdk/bucketspace_fs.js]: I changed it, I moved the TODO that was there that it won't be missed (we can open an issue with all the details if you want).

File: config.js (hunk 3 above)
Comment (shirady) [reply config.js]: Regarding the Ceph tests on NSFS - I think that running the tests with a higher number of forks makes the logs less readable (and in case one made a passing test to get failed we want it will be easiest to understand what happened.

I run the `make test-nsfs-cephs3 CONTAINER_PLATFORM=linux/arm64` with codes change:
1) Change the mount point
```diff
- export CEPH_TEST_LOGS_DIR=/logs/ceph-nsfs-test-logs
+ export CEPH_TEST_LOGS_DIR=./logs/ceph-nsfs-test-logs
```
 To avoid the error:

>  docker run  --privileged --user root --name noobaa_"aaeeb19"_"42" --env "SUPPRESS_LOGS=""" -v <>/noobaa-core/logs:/logs "noobaa-tester" "./src/test/system_tests/ceph_s3_tests/run_ceph_nsfs_test_on_test_container.sh"
> docker: Error response from daemon: error while creating mount source path '<>/noobaa-core/logs': chown <>/noobaa-core/logs: permission denied.
> ERRO[0000] error waiting for container:
> make: *** [test-nsfs-cephs3] Error 126

(Note: `<>` removed the internal path)


2) Set a higher number of forks
```diff
- config='{"ALLOW_HTTP":true}'
+ config='{"ALLOW_HTTP":true, "ENDPOINT_FORKS":16}'
```

I ran it twice and saw there are tests that failed (In those tests there is a versioning status change):
1) On current master:

> nsfs: merged config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 16 }
> ...
> Nov-17 6:47:39.255 [test_ceph_s3/275]  [INFO] CONSOLE:: CEPH TEST SUMMARY: Suite contains 801, ran 262 tests, Passed: 243, Skipped: 16, Failed: 3
> ...
> Nov-17 6:47:39.255 [test_ceph_s3/275] [ERROR] CONSOLE:: CEPH TEST FAILED TESTS SUMMARY: 3 failed tests
> s3tests_boto3/functional/test_s3.py::test_versioning_obj_plain_null_version_overwrite
> s3tests_boto3/functional/test_s3.py::test_versioning_obj_suspend_versions
> s3tests_boto3/functional/test_s3.py::test_versioning_obj_suspended_copy

2) On this branch (with code changes):

> nsfs: merged config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 16 }
> ...
> Nov-17 8:09:08.003 [test_ceph_s3/276]  [INFO] CONSOLE:: CEPH TEST SUMMARY: Suite contains 801, ran 262 tests, Passed: 246, Skipped: 16, Failed: 0

**Comment by shirady** [comment]
Hi,
@romayalon @jackyalbo 
After adding these changes we would see a printing of `Could not log bucket operation` in the action of "nsfs-ceph-s3-tests" (see [logs](https://github.com/noobaa/noobaa-core/actions/runs/11877243466/job/33096464042?pr=8527), for example).

```bash
➜  ~ grep 'Could not log bucket operation' ./Downloads/0_nsfs-ceph-s3-tests.txt | wc -l
     260
```

As I understand it happens since after every test, we delete the bucket, and now the item is invalid in the cache, and we fail in `get_bucket_by_name` during the `read_bucket_sdk_info` that happens in `send_bucket_op_logs`.

File: config.js (hunk 3 above)
Comment (shirady) [reply config.js]: Regarding the idea to run with more forks - I added it (in the last 2 commits).

File: src/sdk/config_fs.js [hunk 10]
```diff
@@ -885,6 +885,17 @@ class ConfigFS {
         return new_path;
     }
 
+    /**
+     * stat_bucket_config_file will return the stat output on bucket config file
+     * please notice that stat might throw an error - you should wrap it with try-catch and handle the error
+     * @param {string} bucket_name
+     * @returns {Promise<nb.NativeFSStats>}
+     */
+        stat_bucket_config_file(bucket_name) {
```
Comment (romayalon) [inline src/sdk/config_fs.js:894]: indentation

File: src/test/unit_tests/test_nc_with_a_couple_of_forks.js [hunk 11]
```diff
@@ -0,0 +1,60 @@
...
+const path = require('path');
+const P = require('../../util/promise');
+const mocha = require('mocha');
+const assert = require('assert');
+const fs_utils = require('../../util/fs_utils');
+const { TMP_PATH, generate_nsfs_account, get_new_buckets_path_by_test_env, generate_s3_client, get_coretest_path } = require('../system_tests/test_utils');
+
+const coretest_path = get_coretest_path();
+const coretest = require(coretest_path);
+coretest.setup({ forks: 2, debug: 5 });
```
Comment (romayalon) [inline src/test/unit_tests/test_nc_with_a_couple_of_forks.js:13]: this won't have any effect after coretest was already set up
why not setting forks=2 in the beforeAll and set it back to forks=1 instead of the new nc_index2.js and the makefile command?

File: src/sdk/bucketspace_fs.js [hunk 12]
```diff
@@ -164,17 +170,37 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+     * @returns Promise<{boolean>}
+     */
+    async check_same_stat(bucket_name, bucket_stat) {
+        try {
+            const current_stat = await this.config_fs.stat_bucket_config_file(bucket_name);
+            if (current_stat) {
+                return current_stat.ino === bucket_stat.ino && current_stat.mtimeNsBigint === bucket_stat.mtimeNsBigint;
+            }
+        } catch (err) {
+            dbg.log4('check_same_stat: current_stat got an error', err, 'ignoring...');
```
Comment (romayalon) [inline src/sdk/bucketspace_fs.js:201]: why dbg4? when having issues stating the config files it's not just info message IMHO

File: src/sdk/bucketspace_fs.js [hunk 13]
```diff
@@ -104,10 +104,11 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
             const bucket = await this.config_fs.get_bucket_by_name(name);
             nsfs_schema_utils.validate_bucket_schema(bucket);
 
-            const is_valid = await this.check_bucket_config(bucket);
+            const is_valid = await this.check_stat_bucket_storage_path(bucket.path);
             if (!is_valid) {
-                dbg.warn('BucketSpaceFS: one or more bucket config check is failed for bucket : ', name);
+                dbg.warn('BucketSpaceFS: invalid storage path for bucket : ', name);
             }
+            //TODO: Bucket owner check
```
Comment (romayalon) [inline src/sdk/bucketspace_fs.js:111]: I think you can remove it, we check that the bucket owner exists on line 135

Comment (shirady) [reply src/sdk/bucketspace_fs.js:111]: I will remove it, thanks.

File: src/sdk/bucketspace_fs.js (hunk 12 above)
Comment (shirady) [reply src/sdk/bucketspace_fs.js:201]: I didn't want this to create a lot of log, I will will change it to warn.

File: src/sdk/config_fs.js (hunk 10 above)
Comment (shirady) [reply src/sdk/config_fs.js:894]: I will change, thanks.

File: src/test/unit_tests/test_nc_with_a_couple_of_forks.js (hunk 11 above)
Comment (shirady) [reply src/test/unit_tests/test_nc_with_a_couple_of_forks.js:13]: I created the new files because I want to make sure the coretest_nc was not up, and only this test sets it with a number of forks.
I'm not sure I understand - by changing the number of forks we need to restart the nsfs server, the number of forks will not be changed just by setting the env or changing the config file.

Comment (shirady) [reply src/test/unit_tests/test_nc_with_a_couple_of_forks.js:13]: From what I tried by trying to restart the `nsfs_process` (kill it and rerun it) the whole nc_core test is finishing.

File: config.js (hunk 3 above)
Comment (romayalon) [reply config.js]: @nimrod-becker @liranmauda 
Shira and I are discussing if we should have 2 runs of ceph tests, one with a single process and one with multiple processes. WDYT? since we have limited resources

File: src/test/unit_tests/test_nc_with_a_couple_of_forks.js (hunk 11 above)
Comment (shirady) [reply src/test/unit_tests/test_nc_with_a_couple_of_forks.js:13]: we discussed it, and I changed the code.

**Comment by romayalon** [comment]
@shirady can you rename test_bucketspace.js to test_nsfs_integration.js and src/logfile to nsfs_integration_test_log?

File: config.js (hunk 3 above)
Comment (shirady) [reply config.js]: The decision is to change the existing CI to run with 2 forks.

**Comment by shirady** [comment]
> Regarding [comment1](https://github.com/noobaa/noobaa-core/pull/8527#issuecomment-2481195123) and [comment2](https://github.com/noobaa/noobaa-core/pull/8527#issuecomment-2485344631): I changed the printing of "Could not log bucket operation" so it will be easier to detect from where it came, and not we can see (in the [logs](https://github.com/noobaa/noobaa-core/actions/runs/11911968887/job/33194590082?pr=8527)):
> 
> ```
> ➜ ~ grep 'Could not log bucket operation' ./Downloads/logs_31062666344/0_nsfs-ceph-s3-tests.txt  | wc -l
>      260
> ➜  ~ grep 'Could not log bucket operation (after operation delete_bucket)' ./Downloads/logs_31062666344/0_nsfs-ceph-s3-tests.txt  | wc -l
>      255
> ➜  ~ grep 'Could not log bucket operation (after handle_error)' ./Downloads/logs_31062666344/0_nsfs-ceph-s3-tests.txt  | wc -l
>        5
> ```



After adding a small change in file `src/endpoint/s3/s3_bucket_logging.js` and increasing the number of forks, you can see in the logs "nsfs-ceph-s3-tests" ([link](https://github.com/noobaa/noobaa-core/actions/runs/11934141803/job/33262645351?pr=8527)):

1. The number of forks is 2:
```bash
➜  ~ grep -i forks /Users/shiradymnik/Downloads/logs_31118484677/0_nsfs-ceph-s3-tests.txt
2024-11-20T13:22:07.1211102Z + main@./src/test/system_tests/ceph_s3_tests/run_ceph_nsfs_test_on_test_container.sh:33 config='{"ALLOW_HTTP":true, "ENDPOINT_FORKS":2}'
2024-11-20T13:22:07.1212987Z + main@./src/test/system_tests/ceph_s3_tests/run_ceph_nsfs_test_on_test_container.sh:34 echo '{"ALLOW_HTTP":true, "ENDPOINT_FORKS":2}'
2024-11-20T13:22:07.2997467Z nsfs: config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 2 }
2024-11-20T13:22:07.2998430Z nsfs: merged config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 2 }
2024-11-20T13:22:08.8729005Z nsfs: setting up ... { fs_root: '', http_port: 80, https_port: 443, https_port_sts: -1, https_port_iam: -1, metrics_port: 7004, backend: '', forks: 2, access_key: undefined, secret_key: undefined, uid: 0, gid: 0, nsfs_config_root: '/etc/noobaa.conf.d' }
2024-11-20T13:22:09.1440036Z nsfs: config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 2 }
2024-11-20T13:22:09.1440725Z nsfs: merged config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 2 }
2024-11-20T13:22:09.1469722Z nsfs: config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 2 }
2024-11-20T13:22:09.1470321Z nsfs: merged config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 2 }
2024-11-20T13:22:10.9775549Z nsfs: setting up ... { fs_root: '', http_port: 80, https_port: 443, https_port_sts: -1, https_port_iam: -1, metrics_port: 7004, backend: '', forks: 2, access_key: undefined, secret_key: undefined, uid: 0, gid: 0, nsfs_config_root: '/etc/noobaa.conf.d' }
2024-11-20T13:22:10.9923585Z nsfs: setting up ... { fs_root: '', http_port: 80, https_port: 443, https_port_sts: -1, https_port_iam: -1, metrics_port: 7004, backend: '', forks: 2, access_key: undefined, secret_key: undefined, uid: 0, gid: 0, nsfs_config_root: '/etc/noobaa.conf.d' }
2024-11-20T13:22:17.2997377Z nsfs: config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 2 }
2024-11-20T13:22:17.2998127Z nsfs: merged config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 2 }
2024-11-20T13:22:21.6182381Z nsfs: config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 2 }
2024-11-20T13:22:21.6183023Z nsfs: merged config.json= { ALLOW_HTTP: true, ENDPOINT_FORKS: 2 }
```
2. No more printings of "Could not log bucket operation"
```bash
➜  ~ grep -i 'Could not log bucket operation' /Users/shiradymnik/Downloads/logs_31118484677/0_nsfs-ceph-s3-tests.txt
➜  ~
```

**Review by romayalon — APPROVED** [review]

File: src/endpoint/s3/s3_rest.js [hunk 14]
```diff
@@ -165,7 +165,9 @@ async function handle_request(req, res) {
     try {
         await s3_logging.send_bucket_op_logs(req, res); // logging again with result
     } catch (err) {
-        dbg.error("Could not log bucket operation:", err);
+        // GAP - (NC) since we don't have the bucket in bucket_namespace_cache we cannot get the bucket info
```
[the remark this answers is not in the document]
Comment (shirady) [reply src/endpoint/s3/s3_rest.js]: You're right, thanks.

File: src/endpoint/s3/s3_bucket_logging.js [hunk 15]
```diff
@@ -19,15 +20,20 @@ async function send_bucket_op_logs(req, res) {
...
         const writes_aggregate = [];
 
-        const bucket_info = await req.object_sdk.read_bucket_sdk_config_info(req.params.bucket);
-        dbg.log2("read_bucket_sdk_config_info =  ", bucket_info);
+        let bucket_info; // please notice bucket_info might be undefined
+        try {
+            bucket_info = await req.object_sdk.read_bucket_sdk_config_info(req.params.bucket);
+            dbg.log2("read_bucket_sdk_config_info =  ", bucket_info);
+        } catch (err) {
+            dbg.warn(`send_bucket_op_logs of bucket ${req.params.bucket} got an error:`, err);
```
[the remark this answers is not in the document]
Comment (shirady) [reply src/endpoint/s3/s3_bucket_logging.js:28]: I will change it, thanks.
