### PR TITLE
NSFS | GPFS | fix put object over null version in suspended mode

### LINKED ISSUE #8379: NSFS | S3 | Versioning: InternalError upon PutObject over existing key in version-suspended bucket
### Environment info
- NooBaa Version: **5.17.0-20240904**
- Platform: **CentOS8, deployed using [https://github.com/IBM/StorageScaleVagrant](https://github.com/IBM/StorageScaleVagrant), Scale 5.2.2.0 240913.105913**

### Actual behavior

Second PutBucket causes InternalError.

See the following test code:

```
    def test_s3cever102():
        client = get_client()
        bucket_name = get_new_bucket(client=client)
    
        # The following operation uses another client instance -> following operations will fail
    #    check_configure_versioning_retry(bucket_name, "Enabled", "Enabled")
        _ces_safe_check_configure_versioning_retry(client, bucket_name, "Enabled", "Enabled")
    
        _ces_safe_check_configure_versioning_retry(client, bucket_name, "Suspended", "Suspended")
    
        key_name = 'obj'
        data = 'object-1'
        response = client.put_object(Bucket=bucket_name, Key=key_name, Body=data)
        version_id = None
        try:
            version_id = response['VersionId']
        except KeyError:
            version_id = None
        assert version_id == None
    
        response = client.list_object_versions(Bucket=bucket_name)
        versions = response['Versions']
        assert versions[0]['VersionId'] == "null"
    
        data = 'object-2'
>       response = client.put_object(Bucket=bucket_name, Key=key_name, Body=data)
...
E           botocore.exceptions.ClientError: An error occurred (InternalError) when calling the PutObject operation (reached max retries: 4): We encountered an internal error. Please try again.
```

### Expected behavior

PutBucket works and overwrites the previous object with the new content.

### Steps to reproduce

Execute the above test code added to Ceph s3-tests.

### More information - Screenshots / Logs / Other output

After the error occurred, it is not possible to delete the object using a simple `aws s3 rm s3://bucket/key` operation, these attempts also return InternalError.

Noobaa log with "all" log level attached
[noobaa_20240917_4.log.gz](https://github.com/user-attachments/files/17032654/noobaa_20240917_4.log.gz)

### PR DESCRIPTION
**Pull request by nadavMiz**
### Explain the changes
1. on Suspeded mode we need to delete the latest null version if a new object is created (as there can be only one object with null version). this delete fails on GPFS since we use the wrong gps_options. however since in GPFS link overrides existing file anyway, we don't need to call unlink at all in such scenario. changed so unlink will not be called to delete latest null version on Suspended mode for GPFS
2. add missing use of gpfs_options.delete_version instead of gpfs_options for deleting old null version

### Testing Instructions:
Run `test_nsfs_versioning_gpfs.js` tests on gpfs cluster
- [ ] Doc added/updated
- [x] Tests added

### CODE REVIEW

File: src/sdk/namespace_fs.js [hunk 1]
```diff
@@ -1419,23 +1419,22 @@ class NamespaceFS {
...
 
-                gpfs_options = is_gpfs ?
-                    await this._open_files_gpfs(fs_context, new_ver_tmp_path, latest_ver_path, upload_file,
-                        latest_ver_info, open_mode, undefined, versioned_info) :
-                    undefined;
                 const bucket_tmp_dir_path = this.get_bucket_tmpdir_full_path();
-                dbg.log1('Namespace_fs._move_to_dest_version:', latest_ver_info, new_ver_info, gpfs_options);
-
-                if (this._is_versioning_suspended()) {
+                if (!is_gpfs && this._is_versioning_suspended()) {
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:1423]: can you just add a comment, something like - 
on GPFS & while versioing is suspended & latest version is a null version, we can skip unlinking the old version because linkatif overrides.

File: src/sdk/namespace_fs.js [hunk 2]
```diff
@@ -1419,23 +1419,22 @@ class NamespaceFS {
...
                         await this._delete_null_version_from_versions_directory(key, fs_context);
                     }
                 }
+                gpfs_options = is_gpfs ?
+                await this._open_files_gpfs(fs_context, new_ver_tmp_path, latest_ver_path, upload_file,
+                    latest_ver_info, open_mode, undefined, versioned_info) :
+                undefined;
+                dbg.log1('Namespace_fs._move_to_dest_version:', latest_ver_info, new_ver_info, gpfs_options);
+
                 if (latest_ver_info &&
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:1438]: Not related to this line, on the github issue there is a test called test_s3cever102, is it already running in our ceph tests run?

File: src/sdk/namespace_fs.js [hunk 3]
```diff
@@ -1419,23 +1419,22 @@ class NamespaceFS {
                 const versioned_path = latest_ver_info && this._get_version_path(key, latest_ver_info.version_id_str);
                 const versioned_info = latest_ver_info && await this._get_version_info(fs_context, versioned_path);
 
-                gpfs_options = is_gpfs ?
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:1422]: can you move it back here? I think we wanted to open it at the beginning of the function

File: src/sdk/namespace_fs.js (hunk 2 above)
Comment (nadavMiz) [reply src/sdk/namespace_fs.js:1438]: no this test was made by herald. I think there is already test for that on our test. I'll check and add one if its missing

File: src/sdk/namespace_fs.js [hunk 4]
```diff
@@ -1419,23 +1419,22 @@ class NamespaceFS {
...
-                    await this._open_files_gpfs(fs_context, new_ver_tmp_path, latest_ver_path, upload_file,
-                        latest_ver_info, open_mode, undefined, versioned_info) :
-                    undefined;
                 const bucket_tmp_dir_path = this.get_bucket_tmpdir_full_path();
-                dbg.log1('Namespace_fs._move_to_dest_version:', latest_ver_info, new_ver_info, gpfs_options);
```
[the remark this answers is not in the document]
Comment (nadavMiz) [reply src/sdk/namespace_fs.js:1427]: might as well keep the gpfs options here instead of having two comments

File: src/sdk/namespace_fs.js (hunk 2 above)
Comment (nadavMiz) [reply src/sdk/namespace_fs.js:1440]: there is already a test in test_bucketspace_versioning.js:
https://github.com/noobaa/noobaa-core/blob/3c8a29a2153fe51e46b859617c8a193758e8abe7/src/test/unit_tests/test_bucketspace_versioning.js#L453-L478

Comment (nadavMiz) [reply src/sdk/namespace_fs.js:1440]: there is already a test for this in test_bucketspace_versioning.js:
https://github.com/noobaa/noobaa-core/blob/3c8a29a2153fe51e46b859617c8a193758e8abe7/src/test/unit_tests/test_bucketspace_versioning.js#L366-L372

File: src/sdk/namespace_fs.js [hunk 5]
```diff
@@ -1427,15 +1427,16 @@ class NamespaceFS {
                 dbg.log1('Namespace_fs._move_to_dest_version:', latest_ver_info, new_ver_info, gpfs_options);
 
                 if (this._is_versioning_suspended()) {
-                    if (latest_ver_info?.version_id_str === NULL_VERSION_ID) {
+                    //on GPFS safe_move overrides the latest object so no need to unlink
+                    if (!is_gpfs && latest_ver_info?.version_id_str === NULL_VERSION_ID) {
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:1431]: I think that this condition is not good because if it's GPFS but it's also NULL_VERSION_ID, we will do the else, I think that on the GPFS machine you didn't have this issue

Comment (nadavMiz) [reply src/sdk/namespace_fs.js]: right I changed it to be a condition inside the is latest version null condition. this way if the version isn't null we will act the same, and if it is null we will no unlink only on GPFS machine

File: src/sdk/namespace_fs.js (hunk 3 above)
Comment (romayalon) [reply src/sdk/namespace_fs.js:1422]: Hey can you move it back here?

**Review by romayalon — APPROVED** [review]
