### PR TITLE
NSFS | Content-type / directory object fixes

### LINKED ISSUE #7421: NSFS update content-type from cyberduck fails
Openshift 4.10.46
ODF MCG 

cyberduck
```
running with ns-fs
choosing object /obcprestotpcds/sf1000/tpcds1kpqt/reason

get info /  metadata
content-type application/octet-stream	

Change content-type to application/x-directory
```

output from endpoint
```
. . .
Aug-1 19:48:40.613 [Endpoint/14]    [L0] core.sdk.namespace_fs:: check_bucket_boundaries: fs_account_config { gid: 0, uid: 0, nsfs_only: true, new_buckets_path: '/', backend: 'GPFS', warn_threshold_ms: 100 } file_path /nsfs/pvc-pv-prestotpcds/sf1000/tpcds1kpqt/reason/.folder
Aug-1 19:48:40.615 [Endpoint/14]    [L0] core.sdk.namespace_fs:: check_bucket_boundaries: fs_account_config { gid: 0, uid: 0, nsfs_only: true, new_buckets_path: '/', backend: 'GPFS', warn_threshold_ms: 100 } file_path /nsfs/pvc-pv-prestotpcds/sf1000/tpcds1kpqt/reason/.folder
Aug-1 19:48:40.615 [Endpoint/14]    [L0] core.sdk.namespace_fs:: check_bucket_boundaries: fs_account_config { gid: 0, uid: 0, nsfs_only: true, new_buckets_path: '/', backend: 'GPFS', warn_threshold_ms: 100 } file_path /nsfs/pvc-pv-prestotpcds/sf1000/tpcds1kpqt/reason/.folder
Aug-1 19:48:40.616 [Endpoint/14]    [L0] core.sdk.namespace_fs:: NamespaceFS: read_object_stream { file_path: '/nsfs/pvc-pv-prestotpcds/sf1000/tpcds1kpqt/reason/.folder', start: 0, end: Infinity }
Aug-1 19:48:40.620 [Endpoint/14]    [L0] core.sdk.namespace_fs:: NamespaceFS: read_object_stream completed file /nsfs/pvc-pv-prestotpcds/sf1000/tpcds1kpqt/reason/.folder { num_bytes: 0, num_buffers: 0, avg_buffer: NaN, log2_size_histogram: {} }
Aug-1 19:48:40.818 [Endpoint/14] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>/obcprestotpcds/sf1000/tpcds1kpqt/reason/?acl=</Resource><RequestId>lksppe36-8cg5me-194r</RequestId></Error> PUT /obcprestotpcds/sf1000/tpcds1kpqt/reason/?acl= {"date":"Tue, 01 Aug 2023 19:47:45 GMT","expect":"100-continue","content-type":"text/plain","x-amz-content-sha256":"c31f9a29fc0e229dd1fdefe653f76096b89f9bdfbb41697f3b2f0d599fcb045d","x-amz-date":"20230801T194745Z","authorization":"AWS4-HMAC-SHA256 Credential=iJYC8inFPJN380vefArw/20230801/us-east-1/s3/aws4_request,SignedHeaders=content-type;date;host;x-amz-content-sha256;x-amz-date,Signature=dc661bc6ec74069a4255e6c9d39838780f391ae42e09001910f3441390e63b77","content-length":"351","user-agent":"Cyberduck/8.6.0.39818 (Windows 10/10.0.22621.0) (amd64)","accept-encoding":"gzip,deflate","host":"s3-openshift-storage.apps.ocp-cluster1.fusion-arc.res.ibm.com","x-forwarded-host":"s3-openshift-storage.apps.ocp-cluster1.fusion-arc.res.ibm.com","x-forwarded-port":"80","x-forwarded-proto":"http","forwarded":"for=9.61.21.3;host=s3-openshift-storage.apps.ocp-cluster1.fusion-arc.res.ibm.com;proto=http","x-forwarded-for":"9.61.21.3"} Error: Access Denied
    at Object.put_object_acl [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/ops/s3_put_object_acl.js:11:15)
    at handle_request (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:149:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.s3_rest [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:68:9)

```

### LINKED ISSUE #7430: NSFS should return content-type application/x-directory for dirs
### Environment info
- NooBaa Version: **5.12**
- Platform: **OpenShift 4.12**

### Actual behavior
1. Currently dirs return applicaiton/octet-stream like any other file.
2. This fails with presto trying to validate it - https://github.com/prestodb/presto/blob/6306290fb92223c51185efdc694f7dcaeb9ff020/presto-hive/src/main/java/com/facebook/presto/hive/s3/PrestoS3FileSystem.java#L377
3. This related PR added the ability to set/get content-type using xattr - #7390 - but this will not work if the directories are created from the FS or replicated from somewhere else.

### Expected behavior
1. Directories should report content-type application/x-directory.

### Steps to reproduce
1. `npm run nsfs .`
2. `mkdir logs`
3. `aws --endpoint http://localhost:6001 s3 cp --content-type applicaiton/x-directory /dev/null s3://logs/dir/`
4. `aws --endpoint http://localhost:6001 s3api head-object --bucket logs --key dir/`

### PR DESCRIPTION
**Pull request by romayalon**
### Issues: Fixed #xxx / Gap #xxx
1. Fixed #7430 
2. Fixed issue raised on slack - https://noobaa.slack.com/archives/C0NSK9ZNE/p1694374090079059
3. Fixed #7421
4. Today on some flows like override/copy we clean the user. xattr but we shouldn't clean internal xattrs like MD5, we need to merge and have a complete fix for it in - https://github.com/noobaa/noobaa-core/pull/7463 which contains the initial implementation of user.noobaa. xattr prefix in order to differentiate between user xattr and noobaa internal xattr

### Testing Instructions:
1. 

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/test/unit_tests/test_namespace_fs.js [hunk 1]
```diff
@@ -1305,6 +1334,261 @@ mocha.describe('namespace_fs copy object', function() {
...
+            const file_path = ns_tmp_bucket_path + '/' + key;
+            let xattr = await get_xattr(file_path);
+            let read_md_res = await ns_tmp.read_object_md({
+                bucket: upload_bkt,
+                key: key
+            }, dummy_object_sdk);
+            assert.equal(stream_content_type, read_md_res.content_type);
+            assert.equal(res.etag, read_md_res.etag);
+            assert.deepStrictEqual(xattr, { ...add_user_prefix(read_md_res.xattr), [XATTR_DIR_CONTENT]: `${read_md_res.size}` });
+            assert.deepStrictEqual(md1, read_md_res.xattr);
```
Comment (tangledbytes) [inline src/test/unit_tests/test_namespace_fs.js:1356]: I think we should strip away the sort symbol before comparing here?

File: src/test/unit_tests/test_namespace_fs.js [hunk 2]
```diff
@@ -798,6 +807,10 @@ mocha.describe('namespace_fs folders tests', function() {
             }, dummy_object_sdk, read_res);
             assert.equal(read_res.buffers.length, 1);
             assert.equal(read_res.total_length, 100);
+            let get_md_res = await ns_tmp.read_object_md({
```
Comment (tangledbytes) [inline src/test/unit_tests/test_namespace_fs.js:810]: I think I am missing something, why are we issuing `read_object_md` call twice?

Comment (romayalon) [reply src/test/unit_tests/test_namespace_fs.js]: correct, removed

File: src/test/unit_tests/test_namespace_fs.js (hunk 1 above)
Comment (romayalon) [reply src/test/unit_tests/test_namespace_fs.js:1352]: thanks added it like we do on other tests

**Review by naveenpaul1 — APPROVED** [review]
