### PR TITLE
NSFS | GPFS | fix delete latest object twice on GPFS

### LINKED ISSUE #8346: NSFS | S3 | Versioning: Double delete of object in version-enabled bucket fails
### Environment info
- NooBaa Version: ** 5.15.4**
- Platform: **CentOS 8, deployed using [https://github.com/IBM/StorageScaleVagrant](https://github.com/IBM/StorageScaleVagrant)**

### Actual behavior

When performing double deletes (without versionId) on objects in version-enabled buckets, the second delete fails with
```
E           botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the DeleteObject operation: The specified key does not exist.
```

### Expected behavior

The delete should pass due to the AWS idempotency principle. An additional DeleteMarker should get added.

### Steps to reproduce

Execute the following addition to Ceph s3-tests:
```
        client = get_client()
        bucket_name = get_new_bucket(client=client)
    
        # The following operation uses another client instance -> following operations will fail
    #    check_configure_versioning_retry(bucket_name, "Enabled", "Enabled")
        _ces_safe_check_configure_versioning_retry(client, bucket_name, "Enabled", "Enabled")
    
        key_names = ['bar', 'baz', 'foo']
        i = 1
        for key in key_names:
            response = client.put_object(Bucket=bucket_name, Key=key, Body='content-{}'.format(i))
            version_id = response['VersionId']
            print('Key {} version_id {}'.format(key, version_id))
            i = i + 1
    
        # 1st pass delete
        for key in key_names:
            response = client.delete_object(Bucket=bucket_name, Key=key)
    
       # 2nd pass delete
        for key in key_names:
           response = client.delete_object(Bucket=bucket_name, Key=key)

       # 3rd pass delete
       for key in key_names:
            response = client.delete_object(Bucket=bucket_name, Key=key)

       response = client.list_object_versions(Bucket=bucket_name)
       objs_list = response['Versions']
       print(objs_list)
       assert len(response['DeleteMarkers']) == 9
```

### More information - Screenshots / Logs / Other output

Logs with "all" log level:
[noobaa_20240911_1.log.gz](https://github.com/user-attachments/files/16960819/noobaa_20240911_1.log.gz)

### PR DESCRIPTION
**Pull request by nadavMiz**
### Explain the changes
1. change to get gpfs_options only if latest version exists. if it doesn't this value isn't needed
2. need to test on GPFS

### Testing Instructions:
1. need to test on GPFS

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/sdk/namespace_fs.js [hunk 1]
```diff
@@ -2921,13 +2921,13 @@ class NamespaceFS {
                 const versioned_path = latest_ver_info && this._get_version_path(params.key, latest_ver_info.version_id_str);
                 const versioned_info = latest_ver_info && await this._get_version_info(fs_context, versioned_path);
 
-                gpfs_options = is_gpfs ?
+                dbg.log1('Namespace_fs._delete_latest_version:', latest_ver_info, versioned_path, versioned_info, gpfs_options);
```
Comment (shirady) [inline src/sdk/namespace_fs.js:2924]: I think you can remove the `gpfs_options` from this printing since it will stay with an `undefined` value.
```suggestion
                dbg.log1('Namespace_fs._delete_latest_version:', latest_ver_info, versioned_path, versioned_info);
```

**Comment by shirady** [comment]
## Validation on GPFS cluster:
Cluster node:
1. We created an account using noobaa-cli: `noobaa-cli account add --name s3user-5001 --uid 5001 --gid 5001 --new_buckets_path /ibm/fs1/teams/` (note `new_buckets_path` is running on GPFS, you can run `df -T /ibm/fs1/teams/`)

Client node:
2. Created the `alias s3-u1='AWS_ACCESS_KEY_ID=<access-key> AWS_SECRET_ACCESS_KEY=<secret-key> aws --no-verify-ssl --endpoint https://1<ip-address-of-node>:6443/ --no-verify-ssl'`

3. Create a bucket:  `s3-u1 s3 mb s3://user-5001-b04; echo $?`

```
make_bucket: user-5001-b04
0
```

4. versioning enabled: `s3-u1 s3api put-bucket-versioning --bucket user-5001-b04 --versioning-configuration Status=Enabled` and then `s3-u1 s3api get-bucket-versioning --bucket user-5001-b04`

```
{
    "Status": "Enabled"
}
```

5. put an object (3 times): `s3-u1 s3api put-object --bucket user-5001-b04 --key hello.txt`

```
{
    "ETag": "\"mtime-d49g9qnwrk74-ino-1pmo\"",
    "VersionId": "mtime-d49g9qnwrk74-ino-1pmo"
}

{
    "ETag": "\"mtime-d49g9ul4o2kg-ino-1pmp\"",
    "VersionId": "mtime-d49g9ul4o2kg-ino-1pmp"
}

{
    "ETag": "\"mtime-d49g9yhdv4e8-ino-1pmr\"",
    "VersionId": "mtime-d49g9yhdv4e8-ino-1pmr"
}
```

6. delete an object (twice): `s3-u1 s3api delete-object --bucket user-5001-b04  --key hello.txt`

```
{
    "DeleteMarker": true,
    "VersionId": "mtime-d49gac5ga328-ino-cn7"
}

{
    "DeleteMarker": true,
    "VersionId": "mtime-d49gaf2g785c-ino-cn4"
}
```

7. list object-versions (ou can 3 versions and 2 delete-markers,  `"IsLatest": true,` on the delete marker):

```
{
    "Versions": [
        {
            "ETag": "\"mtime-d49g9yhdv4e8-ino-1pmr\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "hello.txt",
            "VersionId": "mtime-d49g9yhdv4e8-ino-1pmr",
            "IsLatest": false,
            "LastModified": "2024-09-18T13:39:01+00:00",
            "Owner": {
                "DisplayName": "s3user-5001",
                "ID": "66ea982774ca1f62a8fb0005"
            }
        },
        {
            "ETag": "\"mtime-d49g9ul4o2kg-ino-1pmp\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "hello.txt",
            "VersionId": "mtime-d49g9ul4o2kg-ino-1pmp",
            "IsLatest": false,
            "LastModified": "2024-09-18T13:38:52+00:00",
            "Owner": {
                "DisplayName": "s3user-5001",
                "ID": "66ea982774ca1f62a8fb0005"
            }
        },
        {
            "ETag": "\"mtime-d49g9qnwrk74-ino-1pmo\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "hello.txt",
            "VersionId": "mtime-d49g9qnwrk74-ino-1pmo",
            "IsLatest": false,
            "LastModified": "2024-09-18T13:38:44+00:00",
            "Owner": {
                "DisplayName": "s3user-5001",
                "ID": "66ea982774ca1f62a8fb0005"
            }
        }
    ],
    "DeleteMarkers": [
        {
            "Owner": {
                "DisplayName": "s3user-5001",
                "ID": "66ea982774ca1f62a8fb0005"
            },
            "Key": "hello.txt",
            "VersionId": "mtime-d49gaf2g785c-ino-cn4",
            "IsLatest": true,
            "LastModified": "2024-09-18T13:39:37+00:00"
        },
        {
            "Owner": {
                "DisplayName": "s3user-5001",
                "ID": "66ea982774ca1f62a8fb0005"
            },
            "Key": "hello.txt",
            "VersionId": "mtime-d49gac5ga328-ino-cn7",
            "IsLatest": false,
            "LastModified": "2024-09-18T13:39:31+00:00"
        }
    ],
    "RequestCharged": null
}
```

Outputs are as expected, no errors.
@romayalon @nadavMiz

**Review by romayalon — APPROVED** [review]

**Review by romayalon — COMMENTED** [review]
LGTM, @nadavMiz please remove the relevant ceph tests from the pedning list (if it's not already running)
