### PR TITLE
NSFS | NC | Validate Options in Manage NSFS (CLI)

### LINKED ISSUE #7647: key names are not validated for the node commands invalid key is also considered as input
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20231207-master.el8.x86_64.rpm
- Platform: standalone

### Actual behavior
node src/cmd/manage_nsfs account delete --namek noobaa1 
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /ibm/fs1/ces/s3-config
nsfs: config_dir_path=/ibm/fs1/ces/s3-config config.json= {
  ENDPOINT_FORKS: 2,
  GPFS_DL_PATH: '/usr/lib64/libgpfs.so',
  UV_THREADPOOL_SIZE: 4,
  NOOBAA_LOG_LEVEL: 'warn'
}
2023-12-07 13:57:53.533771 [PID-380067/TID-380067] FS::GPFS GPFS_DL_PATH=/usr/lib64/libgpfs.so
2023-12-07 13:57:53.533872 [PID-380067/TID-380067] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lib64/libgpfs.so
ERROR : Account do not exists with access key : undefined

### Expected behavior
1.node src/cmd/manage_nsfs account delete --namek noobaa1 
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /ibm/fs1/ces/s3-config
nsfs: config_dir_path=/ibm/fs1/ces/s3-config config.json= {
  ENDPOINT_FORKS: 2,
  GPFS_DL_PATH: '/usr/lib64/libgpfs.so',
  UV_THREADPOOL_SIZE: 4,
  NOOBAA_LOG_LEVEL: 'warn'
}
2023-12-07 13:27:27.758762 [PID-333128/TID-333128] FS::GPFS GPFS_DL_PATH=/usr/lib64/libgpfs.so
2023-12-07 13:27:27.758841 [PID-333128/TID-333128] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lib64/libgpfs.so
Error: Access key or account name should not be empty
Help:

    "nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.
    Each sub directory of the root filesystem represents an S3 bucket.
    manage nsfs will provide a command line interface to create new accounts and map existing directories 
    to Noobaa as buckets. For more information refer to the noobaa docs.
Usage:

    node src/cmd/manage_nsfs <type> <action> [options...]
Arguments:

    <type>    Set the resource type such as accounts and buckets
    <action>  Action could be add, update, list, status and delete for accounts/buckets.
Account Options:

    # Read account details from the JSON file, there is no need to mention all the properties one by one in the CLI
    --from_file <dir>                       (default none)                  Set account schema full path.
                                                                            Get account details from JSON file                
    --config_root_backend <none | GPFS >    (default none)                  Set the config_root FS type to be GPFS

    # required for add, update 
    --name <name>               (default none)                              Set the name for the account.
    --email <email>             (default none)                              Set the email for the account.
    --new_name <name>           (default none)                              Set a new name for the account (update).
    --uid <uid>                 (default as process)                        Send requests to the Filesystem with uid.
    --gid <gid>                 (default as process)                        Send requests to the Filesystem with gid.
    --secret_key <key>          (default none)                              The secret key pair for the access key.
    --new_buckets_path <dir>    (default none)                              Set the filesystem's root where each subdir is a bucket.
    
    # required for add, update, and delete
    --access_key <key>          (default none)                              Authenticate incoming requests for this access key only (default is no auth).
    --new_access_key <key>      (default none)                              Set a new access key for the account.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)   Configuration files path for Noobaa standalon NSFS.

    # Used for list
    --wide                      (default none)                              Will print the list with details (same as status but for all accounts)

### Steps to reproduce
1.

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. Validate options in manage NSFS (CLI).
2. Rename `InvalidConfigType` to `InvalidType`.
3. Update the help menu to print the `root_config` global config for every action in bucket and account, and add a clarification that an account can be identified by `access_key` (in addition to `name`).
4. Update the tests that would not pass irrelevant options.

### Issues: Fixed #7647
1. Currently we don't check if the user passed options that we don't use (we ignored them), with this fix, we would return an error.

### Testing Instructions:
1. For manual tests add an invalid option, for example `--lala lala` for each command, examples:
- `sudo node src/cmd/manage_nsfs account add --name <account-name> --email <email> --new_buckets_path <path>  --uid <uid> --gid <gid> --lala lala`
- `sudo node src/cmd/manage_nsfs bucket add --name <bucket-name> --email <email> --path <path> --lala lala`
- `sudo node src/cmd/manage_nsfs bucket status --name <bucket-name> --lala lala`
- `sudo node src/cmd/manage_nsfs whitelist  --ips '["127.0.0.1"]' --lala lala`
2. For running the unit tests with the new test, please run:
- `sudo node ./node_modules/.bin/_mocha src/test/unit_tests/test_nc_nsfs_cli.js`.
- `sudo npx jest test_nc_nsfs_account_cli.test.js`.

- [ ] Doc added/updated
- [X] Tests added

### CODE REVIEW

File: src/manage_nsfs/manage_nsfs_constants.js [hunk 1]
```diff
@@ -15,6 +15,34 @@ const ACTIONS = {
...
+    'list': ['wide', GLOBAL_CONFIG_ROOT],
+    'status': ['name', GLOBAL_CONFIG_ROOT],
+};
+
+const VALID_OPTIONS_WHITELIST = ['ips', GLOBAL_CONFIG_ROOT];
+
+const VALID_OPTIONS = {
+    account_options: VALID_OPTIONS_ACCOUNT,
+    bucket_options: VALID_OPTIONS_BUCKET,
+    wihtelist_options: VALID_OPTIONS_WHITELIST,
```
Comment (romayalon) [inline src/manage_nsfs/manage_nsfs_constants.js:42]:
```suggestion
    whitelist_options: VALID_OPTIONS_WHITELIST,
```

File: src/cmd/manage_nsfs.js [hunk 2]
```diff
@@ -92,7 +99,8 @@ async function main(argv = minimist(process.argv.slice(2))) {
         } else if (type === TYPES.IP_WHITELIST) {
             await whitelist_ips_management(argv);
         } else {
-            throw_cli_error(ManageCLIError.InvalidConfigType);
+            // we won't get here (we check it before)
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:102]: please don't keep code that is irrelevant

File: src/cmd/manage_nsfs.js [hunk 3]
```diff
@@ -748,6 +758,42 @@ async function validate_account_args(data, action) {
...
+    } else if (type === TYPES.ACCOUNT) {
+        valid_options = VALID_OPTIONS.account_options[action];
+    } else {
+        valid_options = VALID_OPTIONS.wihtelist_options;
+    }
+
+    valid_options = new Set(valid_options); // for performance, we use Set as data structure
+    const invalid_input_options = input_options.filter(element => !valid_options.has(element));
+
+    // we return a promise because we want the call of this function to be async
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:790]: can you explain why we need it to be async?

File: src/cmd/manage_nsfs.js [hunk 4]
```diff
@@ -748,6 +758,42 @@ async function validate_account_args(data, action) {
...
+    let valid_options;
+    if (type === TYPES.BUCKET) {
+        valid_options = VALID_OPTIONS.bucket_options[action];
+    } else if (type === TYPES.ACCOUNT) {
+        valid_options = VALID_OPTIONS.account_options[action];
+    } else {
+        valid_options = VALID_OPTIONS.wihtelist_options;
+    }
+
+    valid_options = new Set(valid_options); // for performance, we use Set as data structure
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:787]: you can use Set() at the definition of the valid options in manafe_nsfs_constants
the additional iteration on the array for creating the Set() decreases the performance unwillingly

File: src/cmd/manage_nsfs.js (hunk 2 above)
Comment (shirady) [reply src/cmd/manage_nsfs.js:102]: But it is more readable when reading the function than removing this `else` and making the `else if` before the new `else`.
Also in case someone adds a new type it will get an error until he adds a new condition.

File: src/cmd/manage_nsfs.js (hunk 4 above)
Comment (shirady) [reply src/cmd/manage_nsfs.js:787]: Thank you, this what I wished, but missed it.

File: src/cmd/manage_nsfs.js (hunk 3 above)
Comment (shirady) [reply src/cmd/manage_nsfs.js:790]: Removed, my mistake (it was something that was left from testing and writing the code).

**Review by romayalon — APPROVED** [review]

File: src/cmd/manage_nsfs.js (hunk 2 above)
Comment (shirady) [reply src/cmd/manage_nsfs.js]: Discussed and I changed the comment so it will be clear ("should" instead of "would").
