### PR TITLE
Ohad k8s pools 

### LINKED ISSUE #1894: Alert when moving node between pool if node has noobaa data on it
### Environment info
- Version: 0.5.0-3582c94
- Deployment: NA
- Customer: NA
### Actual behaviour
1. Removing nodes from a pool which has data on them, leaving the pool in a state there is not enough space for rebuild gets the scrubber stuck.
### Expected behavior
1. End Goal - Prevent moving nodes if left space is not enough for rebuild
2. Temporary - Alert if node has data on it and is moved to another pool
### Steps to reproduce
1. Create a pool with 3 nodes, write some data to a bucket on that pool. Assign these 3 nodes to a different pool.

### LINKED ISSUE #1904: Need to be able to deactivate/activate nodes from the pools list.
### Environment info
- Version: 0.5.0-943e243
- Deployment:  **GCloud** 
- Customer: **QA**
### Actual behaviour

1.
Customer would most often than not deactivate groups of nodes at the same time.
Going one by one makes you want to kill yourself.

### LINKED ISSUE #2728: Nodes stuck in migrating after moving nodes between pools and retuning to the original pool
### Environment info
- Version: 1.1.0-35ea489
- Deployment: AZURE
- Customer: QA

### Actual behavior
1. Adding 4 nodes to the machine
2. falsely moving just 2 nodes to another pools - both pools are down - as they should
3. the nodes in the new pool go into migrating phase
4. decided to move the nodes back to the original pool to fix the problem
5. the nodes still stuck on migrating - default pool is down
 
### Expected behavior
1. the nodes should stop the migration in some phase - looks like it's a permanent situation 

### Steps to reproduce
1. written in actual behavior

### Screenshots or Logs or other output that would be helpful
noobaa_management_console

### LINKED ISSUE #3088: Deactivated nodes should not be under the issue tab in the node filter
### Environment info
- Version: **1.8.0-b618666**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. Deactivated nodes are under the issue tab in the node filter

### Expected behavior
1. Deactivated should not be under issue

### Steps to reproduce
1. deactivate a node and see that it goes to the issue section.

noobaa_management_console

### LINKED ISSUE #4164: After deleting hosts we can see that there are activities even thought the host were removed from the UI
### Environment info
- Version: **2.0.0-f7255e5**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. After deleting hosts we can see that there are activities even thought the host were removed from the UI

### Expected behavior
1. There should be no activities.

### Steps to reproduce
1. Delete host

### Screenshots or Logs or other output that would be helpful
noobaa_management_console

### LINKED ISSUE #4166: When delete host is finished we are not getting a popup message
### Environment info
- Version: **2.0.0-f7255e5**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. When delete host is finished we are not getting a popup message 

### Expected behavior
1. A popup message should be prompt

### Steps to reproduce
1. Delete Host
2. See that there is no pop up message

### LINKED ISSUE #4651: Node stays in migrating state- Node shows stored part although the data is not there anymore
### Environment info
- Version: **2.3.0-0d13ab6**
- Deployment: **AZURE**
- Customer: **demo2**

### Actual behavior
1. Noticed that the node is migrating. 
2. I checked the stored parts. Were on a bucket with EC 16+8 and the bucket was unhealthy. 
3. I changed the EC to 2+1. 
4. The bucket turned green, the files parts are on three nodes, but not the migrating one. The migrating node still show this part

At first, I thought it may relate to the fact we don't change the EC, but we do show only 3 blocks. 

*** Update ***
deleting the files from the bucket, solved the problem. So it's mainly supportability here

### Expected behavior
1. The node should abort its attempt to migrate. 

### Screenshots or Logs or other output that would be helpful

http://noobaademo20.westus2.cloudapp.azure.com:8080/fe/systems/demo/resources/pools/paris/nodes/a106-123Linux39d18e%252334/parts

image

http://noobaademo20.westus2.cloudapp.azure.com:8080/fe/systems/demo/buckets/ec-high/objects/GCP_open_firewall.png?page=0&row=0

image

### LINKED ISSUE #5192: When we are deleting deactivated node the status does not change to deleting node
### Environment info
- Version: **2.9.2-a09fff9**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. When we are deleting deactivated node the status does not change to deleting node

### Expected behavior
1. The status should change to deleting node

delete_nodes

### LINKED ISSUE #5211: Delete host crashes the UI in some cases.
### Environment info
- Version: **2.10.0-e688299**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. Delete host crashes the UI in some cases.

### Expected behavior
1. Delete host should not crash the UI.

### Screenshots or Logs or other output that would be helpful
[nbfedump.2018_11_11-17_45_40.json.gz](https://github.com/noobaa/noobaa-core/files/2569548/nbfedump.2018_11_11-17_45_40.json.gz)

### PR DESCRIPTION
**Pull request by nb-ohad**
### Explain the changes
1.  Move from using standalone node installation to installing nodes as part of pool creation
2. A pool can be managed or unmanaged
    -  Agents on managed pools are deployed by NooBaa as pods on a stateful set that provide the storage for the pool and are deleted when the pool is scaled to 0 or deleted.
    - Agents on unmanaged pools should be deployed manually using a YAML that can be acquired from the management console and the admin should delete the underlaying stateful set manually after he completed the deletion of the NooBaa pool.
3. Nodes cannot be migrated between pools anymore 
4. Nodes cannot be deleted manually (but they can still be decommissioned) or a pool can be scaled down which will trigger node deletions.
5. The agent pool controller (the part of NooBaa that manages the storage agents for the pool) is implemented separately from the pool server. This allows us to switch the implementation for diff scenarios (for example use an implementation that starts agents in process in the case of unit tests or  
use an implementation of a backing store CRD when the NooBaa operator will be ready)

### Issues: Fixed #xxx / Gap #xxx
The following issues become irrelevant with the changes in this PR
1. closes #5211 
2. closes #5192 
3. closes #4166 
4. closes #4164
5. closes #3088 
6. closes #1904 
7. closes #1894 
8. closes #2728 
9. closes #4651 

### Testing Instructions:
1.

### CODE REVIEW

File: src/server/node_services/nodes_monitor.js [hunk 1]
```diff
@@ -1019,6 +1019,19 @@ class NodesMonitor extends EventEmitter {
             .then(() => this._update_status(item))
             .then(() => this._handle_issues(item))
             .then(() => this._update_nodes_store())
+            .finally(() => {
```
Comment (nimrod-becker) [inline src/server/node_services/nodes_monitor.js]: What's the relation to _uninstall_deleting_node? Is that still relevant? (assuming no muli-PVs per pod)

File: src/test/framework/test_env_builder_kubernetes.js [hunk 2]
```diff
@@ -2,12 +2,12 @@
 'use strict';
 
 const os = require('os');
-const fs = require('fs');
+// const fs = require('fs');
```
Comment (nimrod-becker) [inline src/test/framework/test_env_builder_kubernetes.js]: Remove if not needed

File: src/test/framework/test_env_builder_kubernetes.js [hunk 3]
```diff
@@ -2,12 +2,12 @@
...
 const path = require('path');
-const { KubernetesFunctions, IS_IN_POD } = require('../../deploy/kubernetes_functions');
+const { KubernetesFunctions } = require('../../deploy/kubernetes_functions');
 const argv = require('minimist')(process.argv);
 const server_functions = require('../utils/server_functions');
-const agent_functions = require('../utils/agent_functions');
+// const agent_functions = require('../utils/agent_functions');
```
Comment (nimrod-becker) [inline src/test/framework/test_env_builder_kubernetes.js]: same

File: src/test/system_tests/test_utils.js [hunk 4]
```diff
@@ -73,4 +73,62 @@ function blocks_exist_on_cloud(need_to_exist, pool_id, bucket_name, blocks, s3)
         });
 }
 
+async function create_hosts_pool(
```
Comment (nimrod-becker) [inline src/test/system_tests/test_utils.js]: Change filename to test_utils_agents or something similar to indicate handling of pools/agents?

File: src/test/system_tests/test_bucket_access.js [hunk 5]
```diff
@@ -107,6 +107,8 @@ function setup() {
 
     let account;
     return P.resolve()
+        // Create a default pool for the users.
+        .then(() => test_utils.create_hosts_pool(client, POOL_NAME))
```
Comment (nimrod-becker) [inline src/test/system_tests/test_bucket_access.js]:
```suggestion
        .then(() => test_utils.create_hosts_pool(client, POOL_NAME, 3))
```

File: src/test/system_tests/test_bucket_placement.js [hunk 6]
```diff
@@ -81,23 +77,10 @@ async function upload_random_file() {
...
-    await client.pool.create_hosts_pool({
-        name: "pool1",
-        hosts: sys_hosts.hosts.map(host => host.name).slice(0, 3)
-    });
-    await client.pool.create_hosts_pool({
-        name: "pool2",
-        hosts: sys_hosts.hosts.map(host => host.name).slice(3, 6)
-    });
+    await create_auth();
+    await test_utils.create_hosts_pool(client, 'pool1');
```
Comment (nimrod-becker) [inline src/test/system_tests/test_bucket_placement.js]:
```suggestion
    await test_utils.create_hosts_pool(client, 'pool1', 3);
```

File: src/test/system_tests/test_bucket_placement.js [hunk 7]
```diff
@@ -81,23 +77,10 @@ async function upload_random_file() {
...
+    await test_utils.create_hosts_pool(client, 'pool2');
```
Comment (nimrod-becker) [inline src/test/system_tests/test_bucket_placement.js]:
```suggestion
    await test_utils.create_hosts_pool(client, 'pool2', 3);
```

File: src/test/system_tests/test_build_chunks.js [hunk 8]
```diff
@@ -12,25 +12,24 @@ const _ = require('lodash');
 const fs = require('fs');
 const AWS = require('aws-sdk');
 const util = require('util');
-const crypto = require('crypto');
+// const crypto = require('crypto');
```
Comment (nimrod-becker) [inline src/test/system_tests/test_build_chunks.js]: remove

File: src/test/system_tests/test_build_chunks.js [hunk 9]
```diff
@@ -12,25 +12,24 @@ const _ = require('lodash');
...
 const P = require('../../util/promise');
 const api = require('../../api');
 const ops = require('../utils/basic_server_ops');
-const config = require('../../../config.js');
 const dotenv = require('../../util/dotenv');
 const ObjectIO = require('../../sdk/object_io');
 const test_utils = require('./test_utils');
 const promise_utils = require('../../util/promise_utils');
-const { RPC_BUFFERS } = require('../../rpc');
+// const { RPC_BUFFERS } = require('../../rpc');
```
Comment (nimrod-becker) [inline src/test/system_tests/test_build_chunks.js]: remove

File: src/test/system_tests/test_build_chunks.js [hunk 10]
```diff
@@ -222,425 +215,392 @@ function print_verification_warning(diff, num_blocks_per_part, expected_num_bloc
...
-function main() {
-    return run_test()
-        .then(function() {
-            process.exit(0);
-        })
-        .catch(function(err) {
-            console.warn('error while running test. ', err);
-            process.exit(1);
-        });
+// function scale_pool(pool_name, host_count) {
```
Comment (nimrod-becker) [inline src/test/system_tests/test_build_chunks.js]: Remove

File: src/test/system_tests/test_build_chunks.js [hunk 11]
```diff
@@ -222,425 +215,392 @@ function print_verification_warning(diff, num_blocks_per_part, expected_num_bloc
...
-            throw err;
-        })
-        .finally(() => test_tear_down());
+    } finally {
+        await test_tear_down();
+    }
 }
 
-function test_setup(bucket_name, pool_names, mirrored, cloud_pool, num_of_nodes_per_pool) {
+// async function test_rebuild_unavailable_from_cloud_pool() {
```
Comment (nimrod-becker) [inline src/test/system_tests/test_build_chunks.js]: remove?

File: src/util/promise_utils.js [hunk 12]
```diff
@@ -266,13 +266,13 @@ function fork(command, input_args, opts, ignore_rc) {
 function exec(command, options) {
     const ignore_rc = (options && options.ignore_rc) || false;
     const return_stdout = (options && options.return_stdout) || false;
-    const timeout = (options && options.timeout) || 0;
+    const timeout_ms = (options && options.timeout) || 0;
```
Comment (nimrod-becker) [inline src/util/promise_utils.js]: Did I miss calling sites changes? 
server_diagnostics & os_utils

File: src/api/pool_api.js [hunk 13]
```diff
@@ -12,34 +12,39 @@ module.exports = {
...
+                    },
+                    host_count: {
+                        type: 'integer',
+                        minimum: 3
+                    },
+                    host_config: {
+                        type: 'object',
+                        properties: {
+                            volume_size: {
+                                $ref: 'common_api#/definitions/bigint'
```
[the remark this answers is not in the document]
Comment (nb-ohad) [reply src/api/pool_api.js]: @nimrod-becker I want it in bIgInt format in case the volume size is more then 1 peta

File: src/deploy/NVA_build/noobaa_deploy_k8s.sh [hunk 14]
```diff
@@ -253,9 +253,9 @@ function delete_noobaa {
     ${KUBECTL} delete pvc datadir-${NOOBAA_POD_NAME}
     ${KUBECTL} delete pvc logdir-${NOOBAA_POD_NAME}
     ${KUBECTL} delete statefulset noobaa-agent
-    ${KUBECTL} delete pvc noobaastorage-noobaa-agent-0
-    ${KUBECTL} delete pvc noobaastorage-noobaa-agent-1
-    ${KUBECTL} delete pvc noobaastorage-noobaa-agent-2
+    # ${KUBECTL} delete pvc noobaastorage-noobaa-agent-0
```
[the remark this answers is not in the document]
Comment (nb-ohad) [reply src/deploy/NVA_build/noobaa_deploy_k8s.sh]: This feature was added to allow the deployment of storage together with noobaa what we really want is to replace this noobaastorage pods with pool creation deletion. For now, I just commented out the code to remind me to fix this later.

File: src/server/node_services/nodes_client.js [hunk 15]
```diff
@@ -312,6 +311,54 @@ class NodesClient {
         }
     }
 
+    async list_hosts_by_pool(pool_name, system_id, auth_token) {
```
[the remark this answers is not in the document]
Comment (nb-ohad) [reply src/server/node_services/nodes_client.js]: The hosts API is the one I (and most the code before the change) is relying on, I don't know who is using the list_nodes on the node_api so I didn't touched it

File: src/server/node_services/nodes_client.js [hunk 16]
```diff
@@ -312,6 +311,54 @@ class NodesClient {
...
+                pools: [pool_name]
+            }
+        }, {
+            auth_token
+        });
+        mongo_utils.fix_id_type(res.hosts);
+        return res;
+    }
+
+    async delete_hosts_by_pool(pool_name, system_id, count = Infinity) {
```
[the remark this answers is not in the document]
Comment (nb-ohad) [reply src/server/node_services/nodes_client.js]: delete_resource_pool was used for cloud_pools and mongo_pools. 
Hosts pool used delete_host_pool, which I reimplemented in the pool server

File: src/server/node_services/nodes_monitor.js (hunk 1 above)
Comment (nb-ohad) [reply src/server/node_services/nodes_monitor.js]: We do not wait for uninstall, it is not necessary

File: src/test/system_tests/test_utils.js (hunk 4 above)
Comment (nb-ohad) [reply src/test/system_tests/test_utils.js]: It is a general file for utils to be used in tests, you can see that blocks_exist_on_cloud was already there before the change. I don't see any need to separate at the current moment (only 3 utils are implemented)

File: src/test/system_tests/test_bucket_access.js (hunk 5 above)
Comment (nb-ohad) [reply src/test/system_tests/test_bucket_access.js]: @nimrod-becker Why not use the default?

File: src/test/system_tests/test_bucket_placement.js (hunk 6 above)
Comment (nb-ohad) [reply src/test/system_tests/test_bucket_placement.js]: same as above

File: src/test/system_tests/test_build_chunks.js (hunk 8 above)
Comment (nb-ohad) [reply src/test/system_tests/test_build_chunks.js]: Should not be removed. it is used in the commented out tests the ew should re-enable (maybe not as part of the current task).
I can check if my rewrite of the test fixed the bug already.

File: src/test/system_tests/test_build_chunks.js (hunk 9 above)
Comment (nb-ohad) [reply src/test/system_tests/test_build_chunks.js]: same as above

File: src/test/system_tests/test_build_chunks.js (hunk 10 above)
Comment (nb-ohad) [reply src/test/system_tests/test_build_chunks.js]: same as above

File: src/test/system_tests/test_build_chunks.js (hunk 11 above)
Comment (nb-ohad) [reply src/test/system_tests/test_build_chunks.js]: same as above

File: src/util/promise_utils.js (hunk 12 above)
Comment (nb-ohad) [reply src/util/promise_utils.js]: The issue is that I added a util called timeout and the linter does not like it. The interface stayed the same it just a local variable

File: src/deploy/NVA_build/noobaa_deploy_k8s.sh (hunk 14 above)
[the remark this answers is not in the document]
Comment (nimrod-becker) [reply src/deploy/NVA_build/noobaa_deploy_k8s.sh]: ?
After your merge if I call the script with clean, will the stateful sets be cleaned?

File: src/server/node_services/nodes_client.js (hunk 15 above)
[the remark this answers is not in the document]
Comment (nimrod-becker) [reply src/server/node_services/nodes_client.js]: Let's not create multiple paths which are basically the same. Either use the old one or move the uses (if exist) of the old one to the new func?

File: src/server/node_services/nodes_monitor.js (hunk 1 above)
Comment (nimrod-becker) [reply src/server/node_services/nodes_monitor.js]: then remove it

File: src/test/system_tests/test_utils.js (hunk 4 above)
Comment (nimrod-becker) [reply src/test/system_tests/test_utils.js]: General utils for tests should be under /test/utils and should be separated according to areas of concern

File: src/test/system_tests/test_bucket_access.js (hunk 5 above)
Comment (nimrod-becker) [reply src/test/system_tests/test_bucket_access.js]: Easier to understand the test flow when it's explicit

File: src/test/system_tests/test_build_chunks.js (hunk 8 above)
Comment (nimrod-becker) [reply src/test/system_tests/test_build_chunks.js]: Check it, if it's not working, remove it. We have the history in git, we don't need comments as history

Comment (nb-ohad) [reply src/test/system_tests/test_build_chunks.js]: We don't have the history it is a rewrite of the tests, If you want we can merge then add a new PR to remove

Comment (nimrod-becker) [reply src/test/system_tests/test_build_chunks.js]: We have the old functions, so we have the idea of the logic of the test. If the new code isn't working, it means someone will have to re-write it which means the current code only value is to understand what was under test, which can also be deduced from the previous code version.

File: package.json [hunk 17]
```diff
@@ -127,6 +127,7 @@
     "ws": "7.0.1",
     "xml2js": "0.4.19",
     "yaml": "1.6.0",
+    "yamljs": "0.3.0",
```
Comment (dannyzaken) [inline package.json]: what's the difference between `yaml` and `yamljs`? do we need both or can we get rid of one of them?

Comment (nb-ohad) [reply package.json]: "yaml" is a lib that allows you to convert YAML files to some kind of YAML AST. 
The only place we use it is in yaml_tools to split documents.

"yamljs" is a lib that allows us to convert a YAML file to a similar formatted javascript object tree (natural conversion), it is used in yaml_utils. I use it to parse and stringify YAML files so I could work with them in javascript.

File: src/deploy/NVA_build/noobaa_deploy_k8s.sh (hunk 14 above)
[the remark this answers is not in the document]
Comment (dannyzaken) [reply src/deploy/NVA_build/noobaa_deploy_k8s.sh]: why not change `install_storage_agents` to create a kubernetes pool? will the current implementation even work now? 
in any case, we should also clean whatever we create in `install_storage_agent`

**Review by dannyzaken — APPROVED** [review]

**Review by dannyzaken — APPROVED** [review]
