### PR TITLE
NC | CLI | Restrict Access Keys chars + performance improvement

### LINKED ISSUE #7931: SignatureDoesNotMatch for presigned URL when access key contains special character (`+`)
### Environment info
- NooBaa Version: **noobaa-core-5.16.0-20240310.el8.x86_64**
- Platform: **rhel-8**

### Actual behavior
1. Created an account, set the access key manually to `abc+abc`.
2. **NOTICE** - this happens when manually setting the access key, because [when we generate access keys we only pick alphanumeric chars](https://github.com/guymguym/noobaa-core/blob/dfd93ea1bcae0893700291d48e9fc489a4935c4a/src/util/cloud_utils.js#L191).
3. Used aws cli and cyberduck with that access key and secret without any issues (uses sigv4 in authentication header).
4. Tried to create a presigned URL with `aws s3 presign s3://bucket/key` but getting the URL failed with SignatureDoesNotMatch error.
5. Changed the access key to contain no `+`, and presign works too.
6. Tried also to get signed URL with cyberduck - the duck did not encode the + sign in the url and it messed up even before getting to the server.

### Expected behavior
1. Either block using access keys with invalid chars, or make it work ok also for presigned URL.

### Steps to reproduce
1. See above.

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. Change the access keys constraints per the following rules - 
- access_key -
   a. Length = 20.
   b. Contains only alphanumeric chars.
- secret_key -
  a. Length = 40.
  b. Contains only alphanumeric chars, "+", "/".

2. Performance improvements -
 Before the change, we tested 4 different regexp on the same access_key/secret_key, now we do it once.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #7931

### Testing Instructions:
1. `sudo jest --testRegex=jest_tests/test_nc_nsfs_account_cli`

- [ ] Doc added/updated
- [x] Tests added

### CODE REVIEW

File: src/manage_nsfs/manage_nsfs_validations.js [hunk 1]
```diff
@@ -16,6 +15,9 @@ const { throw_cli_error, get_config_file_path, get_bucket_owner_account,
 const { TYPES, ACTIONS, VALID_OPTIONS, OPTION_TYPE, FROM_FILE, BOOLEAN_STRING_VALUES,
     GLACIER_ACTIONS, LIST_UNSETABLE_OPTIONS } = require('../manage_nsfs/manage_nsfs_constants');
 
+const valid_access_key_regex = /^[a-zA-Z0-9]+$/;
+const valid_secret_key_regex = /^[a-zA-Z0-9+/]+$/;
```
Comment (guymguym) [inline src/manage_nsfs/manage_nsfs_validations.js:19]: I would move these regex to be in a common module like string_utils where we have the other common regex defined.
Also it is possible to set the exact length in the regex so it doesn't require more checks.
```suggestion
const valid_access_key_regex = /^[a-zA-Z0-9]{20}$/;
const valid_secret_key_regex = /^[a-zA-Z0-9+/]{40}$/;
```

**Review by guymguym — CHANGES_REQUESTED** [review]

File: src/manage_nsfs/manage_nsfs_validations.js (hunk 1 above)
Comment (romayalon) [reply src/manage_nsfs/manage_nsfs_validations.js:19]: nice! will do

**Review by guymguym — APPROVED** [review]
