### PR TITLE
NSFS | Adding metric type to the prefix + Removing the errors in the nsfs io count

### LINKED ISSUE #7188: From delete buckets operation's metrics, remove `error_write_count` and `error_read_count` for I/O metrics.
### Environment info
- NooBaa Version: **VERSION**
- Platform: **OpenShift Data Foundation 4.12.0**
```
ODF Operator: 4.12.0
ODF Operator Image: quay.io/rhceph-dev/odf4-odf-rhel8-operator@sha256:64ad5456e46e04551488c0e0a3c10f02d6d1bef9a4e0273347b82acab9e8c101
Noobaa Core Image: quay.io/rhceph-dev/odf4-mcg-core-rhel8@sha256:d4c5835811499197cc171ac81b0f2ed3d7d732773c8bdeba49598513d75a93b6
Noobaa Operator Image: quay.io/rhceph-dev/odf4-mcg-rhel8-operator@sha256:16ef22df996c4f77e63761a96b843a74da35023af2c33ec1e0b72f16d7c81fd8
```

### Steps to reproduce
1. Create multiple buckets with `s3 mb` command
2. Delete bucket using `s3 rb` command
3. Check metrics, for delete buckets operation (after 60sec)

#### Metrics after deleting buckets
```
noobaa_nsfs_read_count: 0
noobaa_nsfs_write_count: 0
noobaa_nsfs_read_bytes: 0
noobaa_nsfs_write_bytes: 0
noobaa_nsfs_error_write_bytes: 0
noobaa_nsfs_error_write_count: 0
noobaa_nsfs_error_read_bytes: 0
noobaa_nsfs_error_read_count: 0

noobaa_nsfs_delete_bucket_min_time_milisec: 288
noobaa_nsfs_delete_bucket_max_time_milisec: 3883
noobaa_nsfs_delete_bucket_avg_time_milisec: 1509
noobaa_nsfs_delete_bucket_count: 3
noobaa_nsfs_delete_bucket_error_count: 0

noobaa_nsfs_stat_min_time_microsec: 10
noobaa_nsfs_stat_max_time_microsec: 16062
noobaa_nsfs_stat_avg_time_microsec: 6875
noobaa_nsfs_stat_count: 6
noobaa_nsfs_stat_error_count: 0

noobaa_nsfs_realpath_min_time_microsec: 19
noobaa_nsfs_realpath_max_time_microsec: 122
noobaa_nsfs_realpath_avg_time_microsec: 70
noobaa_nsfs_realpath_count: 3
noobaa_nsfs_realpath_error_count: 0

noobaa_nsfs_checkaccess_min_time_microsec: 33
noobaa_nsfs_checkaccess_max_time_microsec: 79
noobaa_nsfs_checkaccess_avg_time_microsec: 61
noobaa_nsfs_checkaccess_count: 3
noobaa_nsfs_checkaccess_error_count: 0

noobaa_nsfs_readdir_min_time_microsec: 25
noobaa_nsfs_readdir_max_time_microsec: 24596
noobaa_nsfs_readdir_avg_time_microsec: 4153
noobaa_nsfs_readdir_count: 6
noobaa_nsfs_readdir_error_count: 0

noobaa_nsfs_rmdir_min_time_microsec: 5145
noobaa_nsfs_rmdir_max_time_microsec: 22344
noobaa_nsfs_rmdir_avg_time_microsec: 15840
noobaa_nsfs_rmdir_count: 3
noobaa_nsfs_rmdir_error_count: 0
```

### LINKED ISSUE #7190: metrics params name should be identical, for I/O Ops, S3Ops, and FS Ops
### Environment info
- NooBaa Version: **VERSION**
- Platform: **OpenShift Data Foundation 4.12.0**
```
ODF Operator: 4.12.0
ODF Operator Image: quay.io/rhceph-dev/odf4-odf-rhel8-operator@sha256:64ad5456e46e04551488c0e0a3c10f02d6d1bef9a4e0273347b82acab9e8c101
Noobaa Core Image: quay.io/rhceph-dev/odf4-mcg-core-rhel8@sha256:d4c5835811499197cc171ac81b0f2ed3d7d732773c8bdeba49598513d75a93b6
Noobaa Operator Image: quay.io/rhceph-dev/odf4-mcg-rhel8-operator@sha256:16ef22df996c4f77e63761a96b843a74da35023af2c33ec1e0b72f16d7c81fd8
```

### Actual behavior
1.  Currently we are getting metrics with same format name, for I/O Ops, S3Ops and FS Ops
2. It is difficult to identify metrics from I/O Ops or S3 Ops or FS Ops.

### Expected behavior
1. Please changed to categorized names for all metrics, so we can identify metrics from which category it is.

### Steps to reproduce
1. Perform s3 operations
2. Check metrics

### More information - Screenshots / Logs / Other output
```

noobaa_nsfs_read_count: 0
noobaa_nsfs_write_count: 1
noobaa_nsfs_read_bytes: 8388608
noobaa_nsfs_write_bytes: 50
noobaa_nsfs_error_write_bytes: 0
noobaa_nsfs_error_write_count: 0
noobaa_nsfs_error_read_bytes: 0
noobaa_nsfs_error_read_count: 0

noobaa_nsfs_create_bucket_min_time_milisec: 4022
noobaa_nsfs_create_bucket_max_time_milisec: 4022
noobaa_nsfs_create_bucket_avg_time_milisec: 4022
noobaa_nsfs_create_bucket_count: 1
noobaa_nsfs_create_bucket_error_count: 0

noobaa_nsfs_read_object_min_time_milisec: 4
noobaa_nsfs_read_object_max_time_milisec: 11
noobaa_nsfs_read_object_avg_time_milisec: 7
noobaa_nsfs_read_object_count: 2
noobaa_nsfs_read_object_error_count: 0

noobaa_nsfs_list_buckets_min_time_milisec: 0
noobaa_nsfs_list_buckets_max_time_milisec: 0
noobaa_nsfs_list_buckets_avg_time_milisec: 0
noobaa_nsfs_list_buckets_count: 1
noobaa_nsfs_list_buckets_error_count: 0

noobaa_nsfs_list_objects_min_time_milisec: 2
noobaa_nsfs_list_objects_max_time_milisec: 18
noobaa_nsfs_list_objects_avg_time_milisec: 7
noobaa_nsfs_list_objects_count: 3
noobaa_nsfs_list_objects_error_count: 0

noobaa_nsfs_head_object_min_time_milisec: 2
noobaa_nsfs_head_object_max_time_milisec: 9
noobaa_nsfs_head_object_avg_time_milisec: 5
noobaa_nsfs_head_object_count: 2
noobaa_nsfs_head_object_error_count: 0

noobaa_nsfs_delete_object_min_time_milisec: 26
noobaa_nsfs_delete_object_max_time_milisec: 26
noobaa_nsfs_delete_object_avg_time_milisec: 26
noobaa_nsfs_delete_object_count: 1
noobaa_nsfs_delete_object_error_count: 0

noobaa_nsfs_stat_min_time_microsec: 5
noobaa_nsfs_stat_max_time_microsec: 9112
noobaa_nsfs_stat_avg_time_microsec: 722
noobaa_nsfs_stat_count: 13
noobaa_nsfs_stat_error_count: 0

noobaa_nsfs_realpath_min_time_microsec: 25
noobaa_nsfs_realpath_max_time_microsec: 5650
noobaa_nsfs_realpath_avg_time_microsec: 1166
noobaa_nsfs_realpath_count: 9
noobaa_nsfs_realpath_error_count: 0

noobaa_nsfs_fileopen_min_time_microsec: 37
noobaa_nsfs_fileopen_max_time_microsec: 892
noobaa_nsfs_fileopen_avg_time_microsec: 394
noobaa_nsfs_fileopen_count: 4
noobaa_nsfs_fileopen_error_count: 0

noobaa_nsfs_fileread_min_time_microsec: 10
noobaa_nsfs_fileread_max_time_microsec: 57
noobaa_nsfs_fileread_avg_time_microsec: 30
noobaa_nsfs_fileread_count: 4
noobaa_nsfs_fileread_error_count: 0

noobaa_nsfs_fileclose_min_time_microsec: 15
noobaa_nsfs_fileclose_max_time_microsec: 37
noobaa_nsfs_fileclose_avg_time_microsec: 23
noobaa_nsfs_fileclose_count: 4
noobaa_nsfs_fileclose_error_count: 0

noobaa_nsfs_mkdir_min_time_microsec: 88511
noobaa_nsfs_mkdir_max_time_microsec: 88511
noobaa_nsfs_mkdir_avg_time_microsec: 88511
noobaa_nsfs_mkdir_count: 1
noobaa_nsfs_mkdir_error_count: 0

noobaa_nsfs_checkaccess_min_time_microsec: 54
noobaa_nsfs_checkaccess_max_time_microsec: 75
noobaa_nsfs_checkaccess_avg_time_microsec: 61
noobaa_nsfs_checkaccess_count: 3
noobaa_nsfs_checkaccess_error_count: 0

noobaa_nsfs_readdir_min_time_microsec: 95
noobaa_nsfs_readdir_max_time_microsec: 1461
noobaa_nsfs_readdir_avg_time_microsec: 552
noobaa_nsfs_readdir_count: 3
noobaa_nsfs_readdir_error_count: 0

noobaa_nsfs_filestat_min_time_microsec: 7
noobaa_nsfs_filestat_max_time_microsec: 21
noobaa_nsfs_filestat_avg_time_microsec: 14
noobaa_nsfs_filestat_count: 2
noobaa_nsfs_filestat_error_count: 0

noobaa_nsfs_filegetxattr_min_time_microsec: 70
noobaa_nsfs_filegetxattr_max_time_microsec: 84
noobaa_nsfs_filegetxattr_avg_time_microsec: 77
noobaa_nsfs_filegetxattr_count: 2
noobaa_nsfs_filegetxattr_error_count: 0

noobaa_nsfs_unlink_min_time_microsec: 24299
noobaa_nsfs_unlink_max_time_microsec: 24299
noobaa_nsfs_unlink_avg_time_microsec: 24299
noobaa_nsfs_unlink_count: 1
noobaa_nsfs_unlink_error_count: 0
```

### PR DESCRIPTION
**Pull request by liranmauda**
### Explain the changes
- Removing read and write error count for NSFS  I/O metrics
- If the namespace count does have some error prompting a warning. just that we will be aware and consider re-adding it
- Adding to the NSFS metrics report the metric type (fs/op/io)

Signed-off-by: liranmauda <liran.mauda@gmail.com>

### Issues: Fixed #xxx / Gap #xxx
1. Fixes: https://github.com/noobaa/noobaa-core/issues/7188
2. Fixes: https://github.com/noobaa/noobaa-core/issues/7190

### Testing Instructions:
1. Create an NSFS bucket
3. Upload files
4.  Check the metrics in `/metrics/nsfs_stats`

https___192_168_64_205_30009_metrics_nsfs_stats

### CODE REVIEW

**Comment by liranmauda** [comment]
There are 2 commits intentionally.

**Review by nimrod-becker — APPROVED** [review]

File: src/sdk/endpoint_stats_collector.js [hunk 1]
```diff
@@ -218,8 +227,9 @@ class EndpointStatsCollector {
 
     update_nsfs_read_counters({ size = 0, count = 0, is_err }) {
         if (is_err) {
-            this.nsfs_io_counters.error_read_count += count;
-            this.nsfs_io_counters.error_read_bytes += size;
+            dbg.warn(`unexpectedly reached here upon error, we need to figure out why and maybe re-add the error counters`);
+            // this.nsfs_io_counters.error_read_count += count;
```
Comment (shirady) [inline src/sdk/endpoint_stats_collector.js:231]: I think that we should not leave code in comments in general.
If we would get here and need to debug it - we have version control.

If you insist on leaving them, at least I would suggest also leaving a comment here about why we added the code in a comment explicitly. For example:
```
Uncomment these lines in case we see the warning above in the logs.
I left them to help us debug it easily.
We can delete them if we will see that we don't have the warning above for a while.
```

Comment (liranmauda) [reply src/sdk/endpoint_stats_collector.js:231]: The warning itself is the explanation.
here we will probably never reach the error path as it is in under layer, and the error will fail much earlier.
with that said, this code is relaying on an older code, and for the chance that we are missing a flow, we added the warning to explain and to see that we actually moved throw this flow.

once we get confidante we can remove  the condition completely (the whole if, else will not be relevant).
