### PR TITLE
NSFS | NC | Improve Help Printings

### LINKED ISSUE #7726: node command --help is not returing user friendly response
### Environment info

* NooBaa Version: noobaa-core-5.15.0-20240109.el8.x86_64.rpm

### Actual behavior
1. node command --help message are not user friendly

### Expected behavior
1. node command --help message should return proper and specific to subcommands. Like which all parameters need(required or optional). Also it should have proper description

### Steps to reproduce
1. run any node command --help

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. Improve help printings, continuing PR #7741 - add more changes according to new requirements and not just split the actions.

### Issues: Fixed #7726 
1. Please read the comments in the issue (and not just the original issue).

### Testing Instructions:
1. Use the `help` option in `manage_nsfs, examples:
- `sudo node src/cmd/manage_nsfs bucket --help 2>/dev/null`
- `sudo node src/cmd/manage_nsfs bucket <action> --help 2>/dev/null` (replace `<action>` with add, update, delete, status, or list)
- `sudo node src/cmd/manage_nsfs account --help 2>/dev/null`
- `sudo node src/cmd/manage_nsfs account <action> --help 2>/dev/null` (replace `<action>` with add, update, delete, status, or list)
- `sudo node src/cmd/manage_nsfs account <action> --help 2>/dev/null` (replace `<action>` with add, update, delete, status, or list)
- `sudo node src/cmd/manage_nsfs whitelist --help 2>/dev/null`

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

**Comment by shirady** [comment]
Will be in state "Ready for review" after:
(1) I'll get response in issue #7726.
(2) I'll merge PR that contains the data types #7756

File: src/manage_nsfs/manage_nsfs_help_utils.js [hunk 1]
```diff
@@ -17,200 +17,181 @@ Usage:
...
-    --gid                                                                                       Filters the list based on the provided GID.
-    --user                                                                                      Filters the list based on the provided FS user distinguished name.
-    --name                                                                                      Filters the list based on the provided account name.
-    --access_key                                                                                Filters the list based on the provided account access_key.
+const ACCOUNT_FLAGS_LIST = `
+Usage:
+account list [flags]
+
+Flags:
+--wide                                                    (optional)                        Print the additional details for each account
```
Comment (naveenpaul1) [inline src/manage_nsfs/manage_nsfs_help_utils.js:130]: @shirady it will be good if can mention the default value for wide and show_secrets flags.

**Review by naveenpaul1 — APPROVED** [review]

File: src/manage_nsfs/manage_nsfs_help_utils.js (hunk 1 above)
Comment (shirady) [reply src/manage_nsfs/manage_nsfs_help_utils.js:130]: @naveenpaul1 Would you please add the suggestion?
If I would change it to:
```suggestion
--wide                                                    (optional)                        Print the additional details for each account (default is false)
```
I'm afraid that someone would understand that he needs to add `--wide true`.
I think that how it is written the default value is implicit but understandable.

Comment (shirady) [reply src/manage_nsfs/manage_nsfs_help_utils.js:130]: @naveenpaul1 Would you please add your suggestion or you meant what I added?
