### PR TITLE
NC | CLI | trimmed output fix

### LINKED ISSUE #8111: Noobaa command to list bucket/account giving trimmed output in pipe
### Environment info
- NooBaa Version: **5.15.0/1/2/3**
- Platform: **other: RHEL9**

### Actual behavior
1. Bucket/account details output getting trimmed when using with pipe

### Expected behavior
1. it should give full output in pipe

### Steps to reproduce
1.

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. A follow up to https://github.com/noobaa/noobaa-core/pull/7898, doing the same changes but for noobaa_cli.
2. Had to move the stdout write on error to the catch scope of main() in manage_nsfs due to https://github.com/noobaa/noobaa-core/issues/7894.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #8111 
2. We should consider making the same changes of bullet 2 for success flow (write_stdout_output).

### Testing Instructions:
1. `env LC_ALL=C /usr/local/bin/noobaa-cli bucket 2>/dev/null list --wide`

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/cmd/manage_nsfs.js [hunk 1]
```diff
@@ -102,10 +102,13 @@ async function main(argv = minimist(process.argv.slice(2))) {
...
         const manage_err = ((err instanceof ManageCLIError) && err) ||
-            new ManageCLIError(ManageCLIError.FS_ERRORS_TO_MANAGE[err.code] ||
+            new ManageCLIError({
+                ...(ManageCLIError.FS_ERRORS_TO_MANAGE[err.code] ||
                 ManageCLIError.RPC_ERROR_TO_MANAGE[err.rpc_code] ||
-                ManageCLIError.InternalError);
-        throw_cli_error(manage_err, err.stack || err);
+                ManageCLIError.InternalError), detail: err.stack || err });
+        process.stdout.write(manage_err.to_string() + '\n', () => {
+            process.exit(0);
```
Comment (guymguym) [inline src/cmd/manage_nsfs.js:110]: exit 1

File: src/cmd/manage_nsfs.js [hunk 2]
```diff
@@ -102,10 +102,13 @@ async function main(argv = minimist(process.argv.slice(2))) {
     } catch (err) {
         dbg.log1('NSFS Manage command: exit on error', err.stack || err);
         const manage_err = ((err instanceof ManageCLIError) && err) ||
-            new ManageCLIError(ManageCLIError.FS_ERRORS_TO_MANAGE[err.code] ||
+            new ManageCLIError({
+                ...(ManageCLIError.FS_ERRORS_TO_MANAGE[err.code] ||
                 ManageCLIError.RPC_ERROR_TO_MANAGE[err.rpc_code] ||
-                ManageCLIError.InternalError);
-        throw_cli_error(manage_err, err.stack || err);
+                ManageCLIError.InternalError), detail: err.stack || err });
```
Comment (guymguym) [inline src/cmd/manage_nsfs.js:108]: i think the detail here is not needed because it repeats the message

**Review by guymguym — CHANGES_REQUESTED** [review]

File: src/cmd/manage_nsfs.js (hunk 2 above)
Comment (guymguym) [reply src/cmd/manage_nsfs.js:108]: oh you want it for the stacktrace? in that case, perhaps just add the stack trace to the to_string() function itself - it can get the stack from this.stack and then it can go into a stack field and not details...

File: src/cmd/manage_nsfs.js (hunk 1 above)
Comment (romayalon) [reply src/cmd/manage_nsfs.js]: oops thanks

File: src/cmd/manage_nsfs.js (hunk 2 above)
Comment (romayalon) [reply src/cmd/manage_nsfs.js]: yes 👍🏻 I added it to the to_string()

File: src/manage_nsfs/manage_nsfs_cli_errors.js [hunk 3]
```diff
@@ -16,18 +18,21 @@ class ManageCLIError extends Error {
     /**
      * @param {ManageCLIErrorSpec} error_spec 
      */
-    constructor({ code, message, http_code }) {
+    constructor({ code, message, http_code, detail, stack }) {
         super(message); // sets this.message
         this.code = code;
         this.http_code = http_code;
+        this.detail = detail;
+        this.stack = stack;
```
Comment (guymguym) [inline src/manage_nsfs/manage_nsfs_cli_errors.js:26]: oh now I understand that you needed the original error stack and not this error stack.
so in js Errors have a `cause` attribute that can be set with new Error(message, { cause: another_error }).
we can pass that optional cause to `super(message, { cause })` in beginning of ctor,
and then to_string() can return `cause: this.cause.stack || this.cause.message`

Comment (romayalon) [reply src/manage_nsfs/manage_nsfs_cli_errors.js]: sure, stack vs cause - 
```
cause -

{
  "error": {
    "code": "InternalError",
    "message": "The server encountered an internal error. Please retry the request",
    "cause": "ReferenceError: validate_account_args1 is not defined\n    at get_account_status (noobaa-core/src/cmd/manage_nsfs.js:539:5)\n    at manage_account_operations (noobaa-core/src/cmd/manage_nsfs.js:561:15)\n    at account_management (noobaa-core/src/cmd/manage_nsfs.js:308:11)\n    at async main (noobaa-core/src/cmd/manage_nsfs.js:95:13)"
  }
}

stack -

{
  "error": {
    "code": "InternalError",
    "message": "The server encountered an internal error. Please retry the request",
    "stack": "ReferenceError: validate_account_args1 is not defined\n    at get_account_status (noobaa-core/src/cmd/manage_nsfs.js:539:5)\n    at manage_account_operations (noobaa-core/src/cmd/manage_nsfs.js:561:15)\n    at account_management (noobaa-core/src/cmd/manage_nsfs.js:308:11)\n    at async main (noobaa-core/src/cmd/manage_nsfs.js:95:13)"
  }
}
```

File: src/manage_nsfs/manage_nsfs_cli_errors.js [hunk 4]
```diff
@@ -16,18 +18,21 @@ class ManageCLIError extends Error {
...
      * @param {ManageCLIErrorSpec} error_spec 
      */
-    constructor({ code, message, http_code }) {
-        super(message); // sets this.message
+    constructor({ code, message, http_code, detail, cause }) {
+        super(message, { cause });
         this.code = code;
         this.http_code = http_code;
+        this.detail = detail;
+        this.cause = cause;
```
Comment (guymguym) [inline src/manage_nsfs/manage_nsfs_cli_errors.js:26]: No need to set this.cause because the standard Error ctor which is called in super() will do that.

**Review by guymguym — APPROVED** [review]
one small comment, otherwise looks good
