### PR TITLE
Bug Fix #7166 | Change message of error in PG client

### LINKED ISSUE #7166: Account creation give error while noobaa-db pod running node is power down
### Environment info
- ODF 4.9 and 4.10
- Platform: OCP 4.9.31

### Actual behavior
1. account create fails with in-appropriate message when noobaa-db pod is in Init state
```
error: "this.begin() must be called before sending queries on this transaction' 
```
### Expected behavior
1.  account create fails should give Appropriate message when noobaa-db pod is in Init state. like:
```
Cannot connect to noobaa-db pod
```

### PR DESCRIPTION
**Pull request by shirady**
Signed-off-by: shirady <57721533+shirady@users.noreply.github.com>

### Explain the changes
1. Change the error message in case the query failed (command `query`).
2. Wrap the action `client.pool.connect` with an exception (i.e. - try... catch clause).
3.  Add a flag `should_rollback` to prevent rollback call in case the DB was not connected.

### Issues:
1. Although the issue was opened with a request to change the message to "Cannot connect to noobaa-db pod", this is still a fix to this issue ([link to the issue](https://github.com/noobaa/noobaa-core/issues/7166)).
_Note: this link was not added to the title of issues because we didn't want it to automatically close the issue - we changed the label of it._

### Testing Instructions:
1. Based on the instructions [here](https://gist.github.com/dannyzaken/c85f0006e5d6582c8d8666cafce6ab76) - the steps of ‘Build images’ and ‘Deploy noobaa’.
3. use the watch to see all 5 pods running (and observe the changes that we will do).
`watch kubectl get pods`
4. kill `noobaa-db-pg` pod and create a new account
```
kubectl delete pod noobaa-db-pg-0 && nb api account_api create_account '{
  "email": "jenia5@noobaa.io",
  "name": "jenia5",
  "has_login": false,
  "s3_access": true,
  "default_resource": "noobaa-default-backing-store"
}'
```

### Attached Screenshots:
Previous message:
Screenshot 2023-01-17 at 13 26 49

New message:
Screenshot 2023-01-23 at 14 31 13

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/util/postgres_client.js [hunk 1]
```diff
@@ -91,7 +92,7 @@ function encode_json(schema, val) {
     if (!val || !schema) {
         return val;
     }
-    // eslint-disable-next-line no-use-before-define
```
Comment (dannyzaken) [inline src/util/postgres_client.js:94]: removing this line is causing eslint errors, at least in my env. I'm not sure why it is not failing eslint in the tests

Comment (shirady) [reply src/util/postgres_client.js:94]: Hi Danny,
I run `eslint` on the file and I don't get an error.
Just to be sure `eslint` works I changed the header (2016 -> zzz) and saved and got an error.
Change it back - and nothing...
Screenshot 2023-01-19 at 8 23 18

Comment (shirady) [reply src/util/postgres_client.js:94]: 1. `eslint` is running in the required checks and it passed (runs `npm run lint`), as mentioned above and in the CI/CD meeting.
2. After fetching the most updated code, including #7158  this was not an error on Danny's machine as well.

**Comment by shirady** [comment]
Moved to draft PR because we think about adding major changes and the above screenshot with the future printing is not a better solution.

Suggested changes related to PG client DB (not in the current code changes):
1.  The origin of the printings is after a failure to publish to cluster of an RPC call.
2. Today we mock MongoDb behavior and we use `bulk_per_collection` @dannyzaken  suggested that we would want to change it since we can in PG use bulk for all collections.
3. In case it helps, here is the stack from the logs (noobaa-core pod after deleting the DB pod + creating a new account as mentioned in the description of the PR):
Screenshot 2023-01-19 at 16 21 23

File: src/server/system_services/system_store.js [hunk 2]
```diff
@@ -742,7 +742,7 @@ class SystemStore extends EventEmitter {
         for (const res of bulk_results) {
             if (res && !res.ok) {
                 dbg.error('got error on bulk execute', res.err);
-                // should we throw here? retry?
+                throw new Error(res.err);
```
Comment (shirady) [inline src/server/system_services/system_store.js:745]: @dannyzaken @guymguym What do you think? (please also comment in the PR)

File: src/util/postgres_client.js [hunk 3]
```diff
@@ -396,9 +402,11 @@ class BulkOp {
         let nMatched = 0;
         let nModified = 0;
         let nRemoved = 0;
+        let should_rollback = false;
         try {
             await this.transaction.begin();
             const batch_query = this.queries.join('; ');
+            should_rollback = true;
```
Comment (romayalon) [inline src/util/postgres_client.js:409]: Wondering about this change,
this.transaction.begin() includes -
1. initialization of this.pg_client 
2. running the first query of the transaction - BEGIN TRANSACTION

if something failed for example in this.queries.join, shouldn't we call rollback?
I know nothing happened but indeed a transaction started in the db, do we need it as a cleanup?

File: src/server/system_services/system_store.js (hunk 2 above)
Comment (dannyzaken) [reply src/server/system_services/system_store.js:745]: for now, I think we should throw here. 
later on, we should change the behavior to perform all bulk changes in the system_store in a single transaction (and not per collection)

**Comment by romayalon** [comment]
@rkomandu Is the new error message suggested by these changes informative enough?

File: src/util/postgres_client.js (hunk 3 above)
Comment (shirady) [reply src/util/postgres_client.js:409]: @Danny with this change we still have the `BEGIN TRANSACTION` in our DB and we will not rollback it - from what I understand that @romayalon wrote.

Comment (romayalon) [reply src/util/postgres_client.js:408]: @shirady yes but after reading a bit I think that rollback won't clean the started transaction and actually we can keep committing updates to the transaction after rollbacking, so I guess this is okay.

**Review by romayalon — APPROVED** [review]

**Review by dannyzaken — APPROVED** [review]

**Comment by shirady** [comment]
The flow was: RPC request -> create account (account server) -> make changes (system store) -> ... -> make changes internal (system store) -> execute (transaction error - this was failing since the db pod was down) -> rollback + query (which we don't need because we didn't execute and failed in the begin function since the db pod was down).
