### PR TITLE
Re-writing Authorization flow 

### LINKED ISSUE #5838: read_bucket_sdk_info is set the request as anonymous
### Environment info
- NooBaa Version: **5.3.0**

### Actual behavior
read_bucket_sdk_info is set the request as anonymous and then we are failing in has_s3_bucket_permission

### PR DESCRIPTION
**Pull request by jeniawhite**
### Explain the changes
1. Added several comments explaining the flow
2. Changed the markdown of anonymous on the request in order not to taint the whole request and always check method by method
3. Started checking for anonymous permissions only when the bucket is configured to serve them, if not we are rolling back to the regular permissions flow

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #5838 
2. Gap #5889 

### Testing Instructions:
1.

### CODE REVIEW

File: src/server/common_services/auth_server.js [hunk 1]
```diff
@@ -543,7 +542,8 @@ function _prepare_auth_request(req) {
         }
 
         // check that auth contains valid system role or the account is support
-        if (!ignore_missing_system) {
+        // We should not check for roles and accounts in anonymous access
+        if (!ignore_missing_system && !allow_anonymous_access) {
```
Comment (guymguym) [inline src/server/common_services/auth_server.js]: There's a nuance here that we want to be strict about which is when the method allows anonymous, but the request is authenticated, in this case I think it is best to check the request as authenticated and verify the roles are valid, so the condition should just check for preconditions to the request having the account and system info -
```suggestion
        if (req.auth && req.system && req.account) {
```

File: src/server/common_services/auth_server.js [hunk 2]
```diff
@@ -590,18 +590,22 @@ function _prepare_auth_request(req) {
 
     req.has_s3_bucket_permission = function(bucket) {
         const options = this.method_api.auth || {};
-        if (req.anonymous) {
-            return true;
+        // Since this method can be called both authorized and unauthorized
+        // We need to check the anonymous permission only when the bucket is configured to server anonymous requests
+        // In case of anonymous function but with authentication flow we roll back to previous code and not return here
+        if (options.anonymous) {
```
Comment (guymguym) [inline src/server/common_services/auth_server.js]: Lets try again to use this logic and discuss which methods are failing -
```
if (req.auth_token && typeof req.auth_token === 'object') {
    return req.has_bucket_permission(bucket);
}
if (options.anonymous === true) {	
    return req.has_bucket_anonymous_permission(bucket);	
}	
return false;
```

File: src/server/common_services/auth_server.js [hunk 3]
```diff
@@ -519,13 +511,20 @@ function _prepare_auth_request(req) {
...
+            req.account = system_store.data.get_by_id(req.auth.account_id);
+            req.system = system_store.data.get_by_id(req.auth.system_id);
+            req.role = req.auth.role;
+        }
+
         if (allow_anonymous_access) {
-            req.anonymous = true;
             // Currently authorize anonymous with the system that we have
-            if (!ignore_missing_system) {
+            if (!ignore_missing_system && !req.system) {
```
Comment (guymguym) [inline src/server/common_services/auth_server.js]: Move below all other checks for account and system, and merge conditions to one - and explain in a single commet "Initialize default system for anynomous requests..."

File: src/server/common_services/auth_server.js [hunk 4]
```diff
@@ -590,18 +590,22 @@ function _prepare_auth_request(req) {
...
             return req.has_bucket_permission(bucket);
-        } else if (options.anonymous === true) {
-            return req.has_bucket_anonymous_permission(bucket);
-        } else {
-            return true;
         }
+        // Notice that we passthrough requests that potentially can be without any authentication
+        // This is becuase we rely on a higher level authorization check in load_auth
+        // This is crucial in order for unauthenticated methods to work 
+        return true;
```
Comment (guymguym) [inline src/server/common_services/auth_server.js]: We want to fix this.

**Comment by guymguym** [comment]
@jeniawhite I asked for review from @nb-ohad in order to verify the changes to endpoints tokens.

File: src/api/cluster_server_api.js [hunk 5]
```diff
@@ -162,6 +162,7 @@ module.exports = {
             auth: {
                 account: false,
                 system: false,
+                anonymous: true,
```
Comment (guymguym) [inline src/api/cluster_server_api.js]: Gap: in `read_server_config()` remove the call to `_get_aws_owner()` if possible or fix otherwise to avoid anonymous calls with unwanted side effects

File: src/api/system_api.js [hunk 6]
```diff
@@ -58,6 +58,7 @@ module.exports = {
             auth: {
                 account: false,
                 system: false,
+                anonymous: true,
```
Comment (guymguym) [inline src/api/system_api.js]: Add check to create_system that fails if there is one system and `config.test_mode !== true`

File: src/api/system_api.js [hunk 7]
```diff
@@ -274,6 +275,7 @@ module.exports = {
...
```
Comment (guymguym) [inline src/api/system_api.js]: Currently this method is unused, so remove the anonymous. Will update auth when needed.

**Review by guymguym — APPROVED** [review]

File: src/api/cluster_server_api.js (hunk 5 above)
Comment (jeniawhite) [reply src/api/cluster_server_api.js]: FE uses it, so I will not remove it yet.
