### PR TITLE
NSFS | NC | Handle Concurrency When Reading Entries and They Deleted by Another Process

### LINKED ISSUE #7920: unable to delete all the accounts in a loop, got internal error while deleting few of them
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

Standalone Noobaa with ODF 4.15.0 (d/s build ) 0313 --> noobaa-core-5.15.0-20240313.el9.x86_64

### Actual behavior
1. Created accounts and deleting them in a loop 
2
for i in `seq 8100 9000`; do mms3 account delete s3user-$i; done

Account s3user-8369 deleted successfully
Account s3user-8370 deleted successfully
Account s3user-8371 deleted successfully
Account s3user-8372 deleted successfully
Account s3user-8373 deleted successfully
Account s3user-8374 deleted successfully
Account s3user-8375 deleted successfully
Account s3user-8376 deleted successfully
Failed to execute command for Account s3user-8377: The server encountered an internal error. Please retry the request  --> here
Account s3user-8378 deleted successfully
Account s3user-8379 deleted successfully
Account s3user-8380 deleted successfully
Account s3user-8381 deleted successfully
Account s3user-8382 deleted successfully

[root@rkomandu-ip-cls-x-worker2 ~]# mms3 account list | grep 8377
s3user-8377             /mnt/fs1/s3user-8377-dir        8377    8377

[root@rkomandu-ip-cls-x-worker2 ~]# mms3 account list | grep 8377
s3user-8377             /mnt/fs1/s3user-8377-dir        8377    8377
[root@rkomandu-ip-cls-x-worker2 ~]# mms3 account list | grep 8376
[root@rkomandu-ip-cls-x-worker2 ~]# mms3 account list | grep 8378

[root@rkomandu-ip-cls-x-worker2 ~]# ls -ld /mnt/fs1/s3user-8377-dir
drwxrwx--- 2 8377 8377 4096 Mar 14 10:27 /mnt/fs1/s3user-8377-dir

[root@rkomandu-ip-cls-x-worker2 ~]# ls -ltr /mnt/fs1/s3user-8377-dir
total 0

Account s3user-8522 deleted successfully
Account s3user-8523 deleted successfully
Account s3user-8524 deleted successfully
Account s3user-8525 deleted successfully
Account s3user-8526 deleted successfully
Account s3user-8527 deleted successfully
Account s3user-8528 deleted successfully
Failed to execute command for Account s3user-8529: The server encountered an internal error. Please retry the request --> here
Account s3user-8530 deleted successfully
Account s3user-8531 deleted successfully
Account s3user-8532 deleted successfully
..
Account s3user-8966 deleted successfully
Account s3user-8967 deleted successfully
Account s3user-8968 deleted successfully
Account s3user-8969 deleted successfully
Account s3user-8970 deleted successfully
Account s3user-8971 deleted successfully
Failed to execute command for Account s3user-8972: The server encountered an internal error. Please retry the request  --> here
Account s3user-8973 deleted successfully
Account s3user-8974 deleted successfully
Account s3user-8975 deleted successfully
Account s3user-8976 deleted successfully
Failed to execute command for Account s3user-8977: The server encountered an internal error. Please retry the request --> here
Account s3user-8978 deleted successfully

[root@rkomandu-ip-cls-x-worker2 ~]# mms3 account list | grep 8972
s3user-8972             /mnt/fs1/s3user-8972-dir        8972    8972

[root@rkomandu-ip-cls-x-worker2 ~]# mms3 account list | grep 8977
s3user-8977             /mnt/fs1/s3user-8977-dir        8977    8977

we opened defect internally (RTC 327700) , and Ramya figured out that it is due to Noobaa problem. 

```
noobaa_events.log
-------------------------
{"timestamp":"2024-03-19T03:35:46.501712-07:00","message":"{\"code\":\"noobaa_account_deleted\",\"message\":\"Account deleted\",\"description\":\"Noobaa Acc
ount deleted\",\"entity_type\":\"NODE\",\"event_type\":\"INFO\",\"scope\":\"NODE\",\"severity\":\"INFO\",\"state\":\"HEALTHY\",\"arguments\":{\"account\":\"
s3user-8970\"},\"pid\":515114}","host":"rkomandu-ip-cls-x-worker1","severity":"notice","facility":"local2","syslog-tag":"node[515114]:","source":"node"}
{"timestamp":"2024-03-19T03:35:50.833533-07:00","message":"{\"code\":\"noobaa_account_deleted\",\"message\":\"Account deleted\",\"description\":\"Noobaa Account deleted\",\"entity_type\":\"NODE\",\"event_type\":\"INFO\",\"scope\":\"NODE\",\"severity\":\"INFO\",\"state\":\"HEALTHY\",\"arguments\":{\"account\":\"s3user-8971\"},\"pid\":515690}","host":"rkomandu-ip-cls-x-worker1","severity":"notice","facility":"local2","syslog-tag":"node[515690]:","source":"node"}
{"timestamp":"2024-03-19T03:35:58.484860-07:00","message":"{\"code\":\"noobaa_account_deleted\",\"message\":\"Account deleted\",\"description\":\"Noobaa Account deleted\",\"entity_type\":\"NODE\",\"event_type\":\"INFO\",\"scope\":\"NODE\",\"severity\":\"INFO\",\"state\":\"HEALTHY\",\"arguments\":{\"account\":\"s3user-8973\"},\"pid\":516371}","host":"rkomandu-ip-cls-x-worker1","severity":"notice","facility":"local2","syslog-tag":"node[516371]:","source":"node"}
{"timestamp":"2024-03-19T03:36:02.950806-07:00","message":"{\"code\":\"noobaa_account_deleted\",\"message\":\"Account deleted\",\"description\":\"Noobaa Account deleted\",\"entity_type\":\"NODE\",\"event_type\":\"INFO\",\"scope\":\"NODE\",\"severity\":\"INFO\",\"state\":\"HEALTHY\",\"arguments\":{\"account\":\"s3user-8974\"},\"pid\":516690}","host":"rkomandu-ip-cls-x-worker1","severity":"notice","facility":"local2","syslog-tag":"node[516690]:","source":"node"}
{"timestamp":"2024-03-19T03:36:07.077782-07:00","message":"{\"code\":\"noobaa_account_deleted\",\"message\":\"Account deleted\",\"description\":\"Noobaa Account deleted\",\"entity_type\":\"NODE\",\"event_type\":\"INFO\",\"scope\":\"NODE\",\"severity\":\"INFO\",\"state\":\"HEALTHY\",\"arguments\":{\"account\":\"s3user-8975\"},\"pid\":517290}","host":"rkomandu-ip-cls-x-worker1","severity":"notice","facility":"local2","syslog-tag":"node[517290]:","source":"node"}

```
as you could observe no entry for the s3user-8972  delete request 

### Expected behavior
1.

It shouldn't show 
### Steps to reproduce
1.

Create accounts in a loop say 2K and then try to delete, may be along with buckets as well. Try deleting them from the CES nodes

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. Fix the concurrency issue on the CLI delete account (when a bucket was deleted during account deletion)
2. Fix the concurrency issue on the CLI list:
   - CLI list buckets (when a bucket was deleted during the list)
   - CLI list accounts (when an account was deleted during the list)
4. Fix the concurrency issue on S3 API list buckets (when a bucket was deleted during the list)
5. Add TODO in `accountspace_fs`.
6. Add test (not related to the issue, was added during debug) 

### Issues: Fixed #7920 
1. GAP - `accountspace_fs` list (IAM ListUsers API) should also be fixed.

#### Manual Tests:
1. To see the failure and the changes with a manual test we will simulate 2 processes: the first process executes the operation that reads the directory content and we add sleep after it in the code (for more information see [comment below](https://github.com/noobaa/noobaa-core/pull/8183#issuecomment-2209149169)), and the second process deletes one of the entries.
2. First, create the `FS_ROOT` and a directory for a bucket: `mkdir -p /tmp/nsfs_root1/my-bucket` and give permissions `chmod 777 /tmp/nsfs_root1/` `chmod 777 /tmp/nsfs_root1/my-bucket`.
This will be the argument for:
  - `new_buckets_path` flag  `/tmp/nsfs_root1` (that we will use in the account commands)
  - `path` in the buckets commands `/tmp/nsfs_root1/my-bucket` (that we will use in bucket commands).
3. Create an account: `sudo node src/cmd/manage_nsfs account add --name <account-name> --uid <uid> --gid <gid> --new_buckets_path <new_buckets_path>`
4. Create 3 buckets: `sudo node src/cmd/manage_nsfs bucket add --name <bucket-name> --owner <account-name> --path <path>` (use the `--owner` from the previous account add command, for example: bucket-1, bucket-2, bucket-3).

For example - when deleting an account we check if the account has buckets (hence we list them):
5. (process 1 - open a tab in the terminal) Delete account: `sudo node src/cmd/manage_nsfs account delete --name <account-name> --debug 5` (we use the debug flag to see printing related to the filesystem, we expect to see on the deleted config file an error message "No such file or directory")
6. (process 2 - open a tab in the terminal) Delete bucket (bucket-2 for example): `sudo node src/cmd/manage_nsfs bucket delete --name <bucket-name> `

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/sdk/bucketspace_fs.js [hunk 1]
```diff
@@ -231,7 +231,14 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
                 return;
             }
             const bucket_name = this.get_bucket_name(entry.name);
-            const bucket = await object_sdk.read_bucket_sdk_config_info(bucket_name);
+            let bucket;
+            // in case the config file was deleted during the list - we will continue (silent)
+            try {
+                bucket = await object_sdk.read_bucket_sdk_config_info(bucket_name);
+            } catch (err) {
+                if (err.code !== 'ENOENT') throw err;
```
Comment (romayalon) [inline src/sdk/bucketspace_fs.js:239]: @shirady I think that on this case we need to not fail on anything, WDYT?

File: src/manage_nsfs/manage_nsfs_cli_utils.js [hunk 2]
```diff
@@ -55,6 +55,22 @@ async function get_config_data(config_root_backend, config_file_path, show_secre
...
+ * if the config file was deleted (encounter ENOENT) - continue
+ * @param {string} config_file_path
+ * @param {boolean} [show_secrets]
+ */
+async function silent_get_config_data(config_root_backend, config_file_path, show_secrets = false) {
+    try {
+        const config_data = await get_config_data(config_root_backend, config_file_path, show_secrets);
+        return config_data;
+    } catch (err) {
+        if (err.code !== 'ENOENT') throw err;
```
Comment (romayalon) [inline src/manage_nsfs/manage_nsfs_cli_utils.js:70]: @shirady Can you add dbg.warn() error message?

File: src/sdk/bucketspace_fs.js (hunk 1 above)
Comment (romayalon) [reply src/sdk/bucketspace_fs.js:239]: Can you add dbg.warn() error message?

Comment (shirady) [reply src/sdk/bucketspace_fs.js:239]: Do you mean that you do not want to fail any error when you try to list the buckets using the API?
I can add, but it will be very verbose in case many buckets were deleted concurrently.

File: src/manage_nsfs/manage_nsfs_cli_utils.js (hunk 2 above)
Comment (romayalon) [reply src/manage_nsfs/manage_nsfs_cli_utils.js:70]: @shirady Not on this PR, we need to rethink about the list error handling...
Also, we wanted to not fail on master keys manager failures as well, See - https://github.com/noobaa/noobaa-core/issues/8104
We should put the try & catch on the loop content, and return the entry name of the listed entity with the error...

File: src/sdk/bucketspace_fs.js (hunk 1 above)
Comment (romayalon) [reply src/sdk/bucketspace_fs.js:239]: Right, but it'll help debug
I meant to remove this ENOENT and always skip,
we need to think about what's worse, failing the whole list op on (for example) non accessible bucket.json or not showing the bucket on the list, it's a dilemma because not showing the bucket is also not good
NOT NOW - on NooBaa CLI we can add an error section to the bucket on the list, but on S3 it's a defined protocol, so I suppose that omitting the bucket and add a warning on the logs is the correct thing to do.
@guymguym

Comment (shirady) [reply src/sdk/bucketspace_fs.js]: The decision for this PR is to add `dbg.warn` and continue if the bucket does not exist.
The check will be on the `rpc_code` of `NO_SUCH_BUCKET` because that is the translated error from `read_bucket_sdk_config_info`, and we want to be precise on the specific case.

File: src/manage_nsfs/manage_nsfs_cli_utils.js (hunk 2 above)
Comment (shirady) [reply src/manage_nsfs/manage_nsfs_cli_utils.js:71]: @romayalon I suggest opening an issue or managing it with a task, so we will not forget.

Comment (romayalon) [reply src/manage_nsfs/manage_nsfs_cli_utils.js:71]: @shirady we already have a bug - https://github.com/noobaa/noobaa-core/issues/8104

Comment (shirady) [reply src/manage_nsfs/manage_nsfs_cli_utils.js:71]: The original issue is about accounts, your comment here expands it to buckets (in noobaa CLI and S3 API).

Comment (romayalon) [reply src/manage_nsfs/manage_nsfs_cli_utils.js:71]: Ok, so we can expand the original issue, why don't need a different bug for buckets

Comment (shirady) [reply src/manage_nsfs/manage_nsfs_cli_utils.js:71]: Sure

**Review by romayalon — APPROVED** [review]
