### PR TITLE
NSFS | NC | Add Validate Flags Combination

### LINKED ISSUE #7918: NSFS | NC | Manage NSFS | Invalid Flags Combination Is Ignored (Could Throw an Error)
### Environment info
- NooBaa Version: master
- Platform: NC

### Actual behavior
1. Invalid flags combination is ignored, for example:
   - `--show_secrets` without `wide` in the account list (`--show_secrets` is ignored).
   - `--user` with `--gid` and `--uid` (`gid` and `uid` are ignored).

### Expected behavior
1. Invalid flags combination could be checked and returned an error.

### Steps to reproduce
1. `sudo node src/cmd/manage_nsfs account list --show_secrets` (without `--wide`)
2. `sudo node src/cmd/manage_nsfs account add --name <account-name> --uid <uid> --gid <gid> --user root` (with `user` and `uid` + `gid`) 

### More information - Screenshots / Logs / Other output
none

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. Add validate flags combination.

### Issues: Fixed #7918 
1. Currently, an Invalid flags combination is ignored, examples:
   - `--show_secrets` without `wide` in the account list (`--show_secrets` is ignored).
   - `--user` with `--gid` and `--uid` (`gid` and `uid` are ignored).

#### Unit Tests
1. Please run: `sudo npx jest test_nc_nsfs_account_cli.test.js`.

#### Manual Tests
1. First, create the `FS_ROOT` and a directory for a bucket: `mkdir -p /tmp/nsfs_root1/my-bucket` and give permissions `chmod 777 /tmp/nsfs_root1/` `chmod 777 /tmp/nsfs_root1/my-bucket`.
This will be the argument for:
  - `new_buckets_path` flag  `/tmp/nsfs_root1` (that we will use in the account commands)
  - `path` in the buckets commands `/tmp/nsfs_root1/my-bucket` (that we will use in bucket commands).
2. Create an account with `user` and also `uid` and `gid`: `sudo node src/cmd/manage_nsfs account add --name <account-name> --user root --uid <uid> --gid <gid> --new_buckets_path <new_buckets_path>` (should throw an error).
3. Create an account with `uid` and `gid` (we will try to update it): `sudo node src/cmd/manage_nsfs account add --name <account-name> --uid <uid> --gid <gid> --new_buckets_path <new_buckets_path>` (should throw an error).
4. Update the account using the `user`, `uid` and `gid` flags: `sudo node src/cmd/manage_nsfs account update --name <account-name> --user root --uid <uid> --gid <gid>` (should throw an error).
5. List accounts with `--show_secrets` without `wide`: `sudo node src/cmd/manage_nsfs account list --show_secrets`
6. From-file option: `sudo node src/cmd/manage_nsfs account add --from_file <path-to-json-file>`  (should throw an error), a file for example (includes `uid` and `user`):
```json
{
    "name": "shira-account-1024",
    "uid": 1024,
    "user": "root",
    "new_buckets_path": "/tmp/nsfs_root1/my-bucket"
}
```

- [ ] Doc added/updated
- [X] Tests added

### CODE REVIEW

File: src/manage_nsfs/manage_nsfs_validations.js [hunk 1]
```diff
@@ -183,6 +185,34 @@ function validate_min_flags_for_update(type, input_options_with_data) {
         }
 }
 
+
+/**
+ * validate_flags_combination checks invalid flags combination, for example:
+ * 1, account add or update - user without gid and uid flags
+ * 2. account list - show_secrets only with wide
```
Comment (romayalon) [inline src/manage_nsfs/manage_nsfs_validations.js:192]:
```suggestion
 * 1. account add or update - user and gid or uid is an invalid flags combination
 * 2. account list - show_secrets without wide is an invalid flags combination
```

**Review by romayalon — COMMENTED** [review]
@shirady Awesome!
Regarding the Gap you wrote - why is this a gap?

**Comment by shirady** [comment]
> @shirady Awesome! Regarding the Gap you wrote - why is this a gap?

I removed it, I just wanted to verify works (we can update only `gid` or `uid` in account update).

**Review by romayalon — APPROVED** [review]
