### PR TITLE
NSFS | NC | Account Has Distinguished Name and Update UID, GID (And Vice Versa)

### LINKED ISSUE #8023: account update for --user option is throwing some invalid error
### Environment info
- NooBaa Version: 5.15.3
- Platform: standalone

### Actual behavior
1.# noobaa-cli account update --name 2* --user root 2>/dev/null
{
  "error": {
    "code": "InvalidSchema",
    "message": "Schema invalid, please use required properties",
    "detail": "Error: must NOT have additional properties | {\"additionalProperty\":\"distinguished_name\"} | \"/nsfs_account_config\"\n    at Object.validate_account_schema (/usr/local/noobaa-core/src/manage_nsfs/nsfs_schema_utils.js:50:15)\n    at update_account (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:482:27)\n    at async manage_account_operations (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:585:9)\n    at async account_management (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:337:5)\n    at async main (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:112:13)"
  }
}

### Expected behavior
1. valid error message should be thrown

### Steps to reproduce
1.

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. Add the case of update in function `fetch_existing_account_data` to avoid merging the data that would contain `uid`, `gid` and `distinguished_name`.
2. Add 2 test cases for the fix above, add 2 `describe`s under `account update`.
3. Change the paths in tests to avoid concurrency issues in Jest.

### Issues: Fixed #8023 #8072
1. Currently, if an account was added with `gid` and `uid` flags, when attempting to update the flag `user` we will get an error (instead of updating the account).
2. Currently, if an account was added with `user`, when attempting to update the `uid` and `gid` flags we will get an error (instead of updating the account).

#### Unit Tests:
Please run: `sudo npx jest test_nc_nsfs_account_cli.test.js`.

#### Manual Tests:
1. First, create the `FS_ROOT` and a directory for a bucket: `mkdir -p /tmp/nsfs_root1/my-bucket` and give permissions `chmod 777 /tmp/nsfs_root1/` `chmod 777 /tmp/nsfs_root1/my-bucket`.
This will be the argument for:
  - `new_buckets_path` flag  `/tmp/nsfs_root1` (that we will use in the account commands)
  - `path` in the buckets commands `/tmp/nsfs_root1/my-bucket` (that we will use in bucket commands).
2. Create an account with `uid` and `gid`: `sudo node src/cmd/manage_nsfs account add --name <account-name> --uid <uid> --gid <gid> --new_buckets_path <new_buckets_path>`
3. Update the account using the `user` flag: `sudo node src/cmd/manage_nsfs account update --name <account-name> --user root`
4. Delete the account: `sudo node src/cmd/manage_nsfs account delete --name <account-name>`
5. Create an account with `user`: `sudo node src/cmd/manage_nsfs account add --name <account-name> --user root --new_buckets_path <new_buckets_path>`
6. Update the account using the `uid` and `gid` flags: `sudo node src/cmd/manage_nsfs account update --name <account-name> --uid 1001 --gid 1001` (uid and gid that are different from those of the user).
7. Delete the account: `sudo node src/cmd/manage_nsfs account delete --name <account-name>`

- [ ] Doc added/updated
- [X] Tests added

### CODE REVIEW

File: src/cmd/manage_nsfs.js [hunk 1]
```diff
@@ -385,6 +386,23 @@ async function fetch_existing_account_data(target) {
         throw err;
     }
     const data = _.merge({}, source, target);
+    if (action === ACTIONS.UPDATE) {
+        // update with user flag (=distinguished_name) on account that had uid and gid
+        const update_distinguished_name = check_if_only_distinguished_name_set(target.nsfs_account_config);
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:391]: why these checks are needed? shouldn't we care only about the values of the target?
Also, I suggest to avoid this code if no uid/gid/dn changed.
IIUC all you need to do is something like the suggested code
```suggestion
    const uid_update = !_.isUndefined(target.nsfs_account_config.uid);
    const gid_update = !_.isUndefined(target.nsfs_account_config.gid);
    const dn_update = !_.isUndefined(target.nsfs_account_config.distinguished_name);
    const user_fs_permissions_change = uid_update || gid_update || dn_update;
    if (action === ACTIONS.UPDATE && user_fs_permissions_change) {
        if (dn_update) {
            delete data.nsfs_account_config.uid;
            delete data.nsfs_account_config.gid;
        } else {
            delete data.nsfs_account_config.distinguished_name;
        }
    }
```

Comment (shirady) [reply src/cmd/manage_nsfs.js]: I changed it.
I did those checks because the validation currently happens after the fetch, I wished to separate the checks between the source and the target (for example the case where someone sends `--gid` and `--user` in the update).

**Comment by shirady** [comment]
This PR moved to draft since there is a prior fix before this one we want to merge.

**Review by romayalon — APPROVED** [review]
