### PR TITLE
Stats return for all services which where configured

### LINKED ISSUE #5121: get_cloud_services_stats - does not return empty stats for configured services which where not used yet
### Environment info
- Version: **VERSION**
- Deployment: **AZURE | AWS | GCLOUD | ESX | VBOX | DEV**
- Customer: **NAME**

### Actual behavior
1. Stats returned only for services which where accessed

### Expected behavior
1. Stats should be returned for all services which where configured

### Steps to reproduce
1.

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. added default values for all services.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #5121 

### Testing Instructions:
1.

### CODE REVIEW

File: src/server/system_services/pool_server.js [hunk 1]
```diff
@@ -834,6 +834,16 @@ async function get_cloud_services_stats(req) {
     ]);
 
     const all_services = {};
+    let services_types_arr = ['AWS', 'AZURE', 'S3_COMPATIBLE', 'GOOGLE', 'FLASHBLADE', 'NET_STORAGE'];
```
Comment (jeniawhite) [inline src/server/system_services/pool_server.js]: We have lots of places where we declare this array (APIs, schemas, code paths).
Not all are using exactly this array as is, some are using a subarray. 
I think that most of the APIs and schemas should have the same definition in common_api.
Regarding the code paths, we can also aggregate that to a single point in config.js for example.
Obviously, the paths that need subarray will need to declare it locally.

Comment (jeniawhite) [reply src/server/system_services/pool_server.js]: Better to declare as const instead of let in this case (this is a constant array that won't be changed).
Even if you will decide to not change it.

Comment (jeniawhite) [reply src/server/system_services/pool_server.js]: Since now you are sending all of the services we need to make sure what to show and not show in the UI. 
I think there should be filtering in the UI side.

Comment (guymguym) [reply src/server/system_services/pool_server.js]: Regardless of the location of it (config.js sounds good to me) keep in mind that `const` only affects the ability to change the reference to the array, but in order to make the array itself immutable you should also freeze the dude:
```
const services_types_arr = Object.freeze(['AWS', 'AZURE', 'S3_COMPATIBLE', 'GOOGLE', 'FLASHBLADE', 'NET_STORAGE']);
```

File: src/server/system_services/pool_server.js [hunk 2]
```diff
@@ -834,6 +834,15 @@ async function get_cloud_services_stats(req) {
     ]);
 
     const all_services = {};
+    for (const service of config.SERVICES_TYPES) {
+        all_services[service] = {
+            service: service,
```
Comment (guymguym) [inline src/server/system_services/pool_server.js]: It's really optional, just making sure you know about this short syntax to set an object property from a variable that has the same name:
```suggestion
            service,
```

**Review by guymguym — APPROVED** [review]

**Review by jeniawhite — APPROVED** [review]
