### PR TITLE
NC | Online Upgrade CLI | Validate `expected_version` on `upgrade start`

### LINKED ISSUE #8851: Error message cause should not throw internal error message
### Environment info
- NooBaa Version: noobaa-core-5.18.0-20250222.el9.x86_66
- Platform: Standalone

### Actual behavior
1. # noobaa-cli upgrade start --expected_version 5.13.3 2>/dev/null
{
 "error": {
  "code": "UpgradeFailed",
  "message": "Upgrade request failed",
  "cause": "Error: system does not exist\n  at NCUpgradeManager.upgrade_config_dir (/usr/local/noobaa-core/src/upgrade/nc_upgrade_manager.js:102:33)\n  at async start_config_dir_upgrade (/usr/local/noobaa-core/src/manage_nsfs/upgrade.js:55:29)\n  at async Object.manage_upgrade_operations (/usr/local/noobaa-core/src/manage_nsfs/upgrade.js:23:13)\n  at async main (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:74:13)"
 }
}

### Expected behavior
# noobaa-cli upgrade start --expected_version 5.13.3 2>/dev/null
{
 "error": {
  "code": "UpgradeFailed",
  "message": "Upgrade request failed",
  "cause": "The version provided is lower than the installed version"
 }
}
### Steps to reproduce
1.

### LINKED ISSUE #8852: If the version is not supported proper error should be thrown
### Environment info

NooBaa Version: noobaa-core-5.18.0-20250222.el9.x86_66
Platform: Standalone

### Actual behavior
# noobaa-cli upgrade start --expected_version 5.19.0 2>/dev/null
{
  "response": {
    "code": "UpgradeSuccessful",
    "reply": {
      "message": "config_dir_version on system.json and config_fs.config_dir_version match, nothing to upgrade"
    }
  }
}

### Expected behavior
1. It should be error instead of success

### Steps to reproduce
1.

### PR DESCRIPTION
**Pull request by shirady**
### Describe the Problem
Currently, we do not validate the value of the argument of `expected_version` in noobaa-cli when using `upgrade start` command.

### Explain the Changes
1. Add the function of `validate_expected_version` that would check that we have the flag of `expected_version` and it is from the supported versions we allow. Also, add specific errors to the CLI (`MissingExpectedVersionFlag` and `InvalidArgumentType`) so that eventually we would not report it as `UpgradeFailed`.
2. Move functions that are related to versions to `versions_utils`, and added a helper function `is_valid_sematic_version` to check the structure of the string.
3. Throw an error instead of the message "config_dir_version on system.json and config_fs.config_dir_version match, nothing to upgrade" and change the tests accordingly.
4. Add the `skip_verification` to `BOOLEAN_STRING_OPTIONS` and use it to in `validate_expected_version`. 

### Issues: Fixed #8852, Fixed #8851
1. In the described issues, the example is of using `upgrade start --expected_version <expected_version>` when `expected_version` is not supported: either lower than expected, or at the same version.

#### Automatic Testing
Please run:
- `sudo rm -rf /etc/noobaa.conf.d/; sudo npx jest test_cli_upgrade.test` (only in a test environment).
- `sudo npx jest test_nc_upgrade_manager.test.js`

#### Manual Testing
You can recreate the failing flag options, for example:
-  `sudo node src/cmd/manage_nsfs upgrade start #invalid, missing --expected_version`
- `sudo node src/cmd/manage_nsfs upgrade start --expected_version  9  #invalid (number and not string)`
-  `sudo node src/cmd/manage_nsfs upgrade start --expected_version  bla #invalid not semver structure`
- `sudo node src/cmd/manage_nsfs upgrade start --expected_version '6.18.0' #invalid version (higher)`
- `sudo node src/cmd/manage_nsfs upgrade start --expected_version '4.18.0' #invalid version (lower)`
- `sudo node src/cmd/manage_nsfs upgrade start --expected_version '5.19.0' #nothing to upgrade`, for the following case, we need to have `system.json` created, therefore before running it please create an account and start the NSFS server: (1) Create an account with the CLI: `sudo node src/cmd/manage_nsfs account add --name <account-name> --new_buckets_path /Users/buckets/ --access_key <access-key> --secret_key <secret-key> --uid <uid> --gid <gid>` - before creating the account need to give permission to the `new_buckets_path`: `chmod 777 /Users/buckets/`
(2) Start the NSFS server with: `sudo node src/cmd/nsfs --debug 5`

- [ ] Doc added/updated
- [X] Tests added

### CODE REVIEW

File: src/manage_nsfs/manage_nsfs_validations.js [hunk 1]
```diff
@@ -738,6 +740,39 @@ function validate_connection_args(user_input, action) {
...
+ * @param {string} expected_version
+ */
+function validate_expected_version(expected_version) {
+    if (!expected_version) {
+        throw new Error('expected_version flag is required');
+    }
+    if (!version_utils.is_valid_sematic_version(expected_version)) {
+        throw new Error('expected_version must have sematic version structure (major.minor.patch)');
+    }
+    if (check_if_expected_version_newer_that_package_version(expected_version)) {
```
Comment (naveenpaul1) [inline src/manage_nsfs/manage_nsfs_validations.js:759]: method name is confusing, It gives a feeling that an error is thrown when the expected version is latest.
And I am not sure if a long method name like this is really helpful or not.

File: src/manage_nsfs/manage_nsfs_validations.js [hunk 2]
```diff
@@ -751,3 +786,5 @@ exports.validate_whitelist_ips = validate_whitelist_ips;
 exports.validate_flags_combination = validate_flags_combination;
 exports.validate_connection_args = validate_connection_args;
 exports.validate_no_extra_args = validate_no_extra_args;
+exports.validate_expected_version = validate_expected_version;
+exports.check_if_expected_version_newer_that_package_version = check_if_expected_version_newer_that_package_version;
```
Comment (naveenpaul1) [inline src/manage_nsfs/manage_nsfs_validations.js:790]: no need to export.

File: src/util/versions_utils.js [hunk 3]
```diff
@@ -0,0 +1,47 @@
+/* Copyright (C) 2016 NooBaa */
```
Comment (naveenpaul1) [inline src/util/versions_utils.js:1]: 2025

File: src/manage_nsfs/manage_nsfs_validations.js [hunk 4]
```diff
@@ -738,6 +740,39 @@ function validate_connection_args(user_input, action) {
...
+////////////////////////////
+//// UPGRADE VALIDATION ////
+///////////////////////////
+
+/**
+ * validate_expected_version checks that expected_version is valid
+ * if it's not valid it throws an error
+ * @param {string} expected_version
+ */
+function validate_expected_version(expected_version) {
```
Comment (naveenpaul1) [inline src/manage_nsfs/manage_nsfs_validations.js:752]: can we move this method also to new util file?

File: src/manage_nsfs/manage_nsfs_validations.js [hunk 5]
```diff
@@ -738,6 +740,39 @@ function validate_connection_args(user_input, action) {
...
+    }
+}
+
+/**
+ * compare_version_to_current_version checks that the version
+ * is not later that the one that was defined in the pkg
+ * @param {string} expected_version
+ * @returns {boolean}
+ */
+function check_if_expected_version_newer_that_package_version(expected_version) {
```
Comment (naveenpaul1) [inline src/manage_nsfs/manage_nsfs_validations.js:770]: can we move this method also to new util file?

**Comment by romayalon** [comment]
@shirady 
That's a nice change but I don't see how this answers the bug, the reporter got confused by the error code "SuccessfulUpgrade" although there was no upgrade because 5.19.0 is the current version, this is the error message they got - `"message": "config_dir_version on system.json and config_fs.config_dir_version match, nothing to upgrade"` - this is an error of the user but not NooBaa's, we need to decide if we want to report it as an error or as a response saying nothing to upgrade.

File: src/manage_nsfs/manage_nsfs_validations.js [hunk 6]
```diff
@@ -738,6 +740,39 @@ function validate_connection_args(user_input, action) {
...
+ */
+function validate_expected_version(expected_version) {
+    if (!expected_version) {
+        throw new Error('expected_version flag is required');
+    }
+    if (!version_utils.is_valid_sematic_version(expected_version)) {
+        throw new Error('expected_version must have sematic version structure (major.minor.patch)');
+    }
+    if (check_if_expected_version_newer_that_package_version(expected_version)) {
+        throw new Error(`expected_version cannot be later that the package version ${pkg.version}`);
```
Comment (romayalon) [inline src/manage_nsfs/manage_nsfs_validations.js:760]: what happens if the expected version equals to pkg.version?

File: src/manage_nsfs/manage_nsfs_validations.js [hunk 7]
```diff
@@ -738,6 +740,39 @@ function validate_connection_args(user_input, action) {
...
+
+/**
+ * compare_version_to_current_version checks that the version
+ * is not later that the one that was defined in the pkg
+ * @param {string} expected_version
+ * @returns {boolean}
+ */
+function check_if_expected_version_newer_that_package_version(expected_version) {
+    const package_version = pkg.version;
+    const diff_from_package_version = version_utils.version_compare(expected_version, package_version);
```
Comment (romayalon) [inline src/manage_nsfs/manage_nsfs_validations.js:772]: in the bug, the error is about config_dir_version and not source code version
so that's a nice change but we probably should check how we behave on source code valid upgrade while in the config dir version there is nothing to upgrade because they match

File: src/manage_nsfs/manage_nsfs_validations.js (hunk 1 above)
Comment (shirady) [reply src/manage_nsfs/manage_nsfs_validations.js]: I tried to change it, if you think you have a better suggestion please suggest.

File: src/manage_nsfs/manage_nsfs_validations.js (hunk 2 above)
Comment (shirady) [reply src/manage_nsfs/manage_nsfs_validations.js]: Removed, thanks.

File: src/util/versions_utils.js (hunk 3 above)
Comment (shirady) [reply src/util/versions_utils.js]: Updated, thanks.

File: src/manage_nsfs/manage_nsfs_validations.js (hunk 4 above)
Comment (shirady) [reply src/manage_nsfs/manage_nsfs_validations.js:752]: It's about an argument, the `versions_utils.js` is more general (like a library that we can use).

File: src/manage_nsfs/manage_nsfs_validations.js (hunk 5 above)
Comment (shirady) [reply src/manage_nsfs/manage_nsfs_validations.js]: It's about an argument, the `versions_utils.js` is more general (like a library that we can use).

**Comment by shirady** [comment]
> @shirady That's a nice change but I don't see how this answers the bug, the reporter got confused by the error code "SuccessfulUpgrade" although there was no upgrade because 5.19.0 is the current version, this is the message they got - `"message": "config_dir_version on system.json and config_fs.config_dir_version match, nothing to upgrade"` - this is an error of the user but not NooBaa's, we need to decide if we want to report it as an error or as a response saying nothing to upgrade.

@romayalon I added a case for throwing an error on the message "config_dir_version on system.json and config_fs.config_dir_version match, nothing to upgrade".

In their case in the issue they used RPM `noobaa-core-5.18.0-20250222.el9.x86_66` in it the pkg.version is `5.18.0` and in the suggested code change they would get `UpgradeFailed` when trying to upgrade using the CLI.

File: src/manage_nsfs/manage_nsfs_validations.js (hunk 6 above)
Comment (shirady) [reply src/manage_nsfs/manage_nsfs_validations.js:760]: I do not fail it from the CLI perspective (I saw in the tests that adding it fails parts of the tests).
I had an assumption that there are cases where the upgrade did not finish, and we wanted to rerun it, and didn't want the CLI to block it on the argument.

File: src/manage_nsfs/manage_nsfs_validations.js (hunk 7 above)
Comment (shirady) [reply src/manage_nsfs/manage_nsfs_validations.js:772]: I added the error thrown in a separate commit.

Comment (romayalon) [reply src/manage_nsfs/manage_nsfs_validations.js:772]: I think there is a misunderstanding here, 
when upgrading the config dir, the package.version must be equal to the expected_version 
we already throw on this issue in the first check of _verify_config_dir_upgrade(), and this verification can be disabled, this is something we should consider

**Review by romayalon — APPROVED** [review]

File: src/upgrade/nc_upgrade_manager.js [hunk 8]
```diff
@@ -108,7 +109,11 @@ class NCUpgradeManager {
         const package_to_version = this.package_version;
         const this_upgrade_versions = { config_dir_from_version, config_dir_to_version, package_from_version, package_to_version };
 
-        if (!should_upgrade(config_dir_from_version, config_dir_to_version)) return { message: 'config_dir_version on system.json and config_fs.config_dir_version match, nothing to upgrade' };
```
Comment (romayalon) [inline src/upgrade/nc_upgrade_manager.js:111]: @jackyalbo - https://issues.redhat.com/browse/DFBUGS-2801
original change
