### PR TITLE
NC | Create a new github action for running Hadoop S3A test

### LINKED ISSUE #9282: Hadoop S3A tests should be added to CI
### Environment info
- NooBaa Version: **5.18.8**
- Platform: **RHEL 9.4**

### Actual behavior
1. No S3A tests run in the CI

### Expected behavior
1. https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/testing.html
2. https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/third_party_stores.html

### Steps to reproduce

```sh
# install
dnf install -y maven
git clone https://github.com/apache/hadoop
cd hadoop
git checkout rel/release-3.4.2
cd hadoop-tools/hadoop-aws

# configure
cat >src/test/resources/auth-keys.xml <<EOF
<configuration>
  <property>
    <name>test.fs.s3a.name</name>
    <value>s3a://hadoop/</value>
  </property>
  <property>
    <name>fs.contract.test.fs.s3a</name>
    <value>${test.fs.s3a.name}</value>
  </property>

  <property>
    <name>fs.s3a.endpoint</name>
    <value>http://10.1.0.1:6001</value>
  </property>
  <property>
    <name>fs.s3a.endpoint.region</name>
    <value>us-east-1</value>
  </property>

  <property>
    <name>fs.s3a.connection.ssl.enabled</name>
    <value>false</value>
  </property>
  <property>
    <name>fs.s3a.path.style.access</name>
    <value>true</value>
  </property>
  <property>
    <name>test.fs.s3a.encryption.enabled</name>
    <value>false</value>
  </property>
  <property>
    <name>test.fs.s3a.create.storage.class.enabled</name>
    <value>false</value>
  </property>
  <property>
    <name>test.fs.s3a.sts.enabled</name>
    <value>false</value>
  </property>
  <property>
    <name>test.fs.s3a.create.create.acl.enabled</name>
    <value>false</value>
  </property>

  <property>
    <name>fs.s3.awsAccessKeyId</name>
    <value>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</value>
  </property>
  <property>
    <name>fs.s3.awsSecretAccessKey</name>
    <value>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</value>
  </property>
  <property>
    <name>fs.s3n.awsAccessKeyId</name>
    <value>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</value>
  </property>
  <property>
    <name>fs.s3n.awsSecretAccessKey</name>
    <value>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</value>
  </property>
  <property>
    <name>fs.s3a.access.key</name>
    <description>AWS access key ID. Omit for Role-based authentication.</description>
    <value>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</value>
  </property>
  <property>
    <name>fs.s3a.secret.key</name>
    <description>AWS secret key. Omit for Role-based authentication.</description>
    <value>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</value>
  </property>

</configuration>
EOF

# run
mvn clean verify -Dtest=TestS3A* -Dit.test=ITestS3A* | tee s3a-tests.log

# summary line e.g. "[ERROR] Tests run: 1152, Failures: 1, Errors: 2, Skipped: 3"
grep "Tests run" s3a-tests.log | tail -1
# failures
grep FAILURE s3a-tests.log
```

### PR DESCRIPTION
**Pull request by jackyalbo**
### Describe the Problem
We want to add S3A test to our CI

### Explain the Changes
1. Adding an action that will build latest noobaa -> start NC on one container -> start tests on a second container

### Issues: Fixed #xxx / Gap #xxx
1.  Fixed #9282 

### Testing Instructions:
1.  run the workflow for github actions

- [ ] Doc added/updated
- [x] Tests added

## Summary by CodeRabbit

* **Chores**
  * Added a CI workflow and a local Make target to run Hadoop S3A integration tests with concurrency and timeout controls.
  * Provisioned containerized test infrastructure with automated endpoint setup, readiness checks, test orchestration, and cleanup.

* **Tests**
  * Added scripted, reproducible Hadoop S3A integration tests runnable locally or in CI.

* **Documentation**
  * Added user-facing docs describing how to run and configure the Hadoop S3A tests.

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -548,6 +567,54 @@ define stop_noobaa
 	@echo "\033[1;32mRemoving test container done.\033[0m"
 endef
 
+define run_nc_endpoint
```
Comment (nadavMiz) [inline Makefile]: if its not a generic nc container should probably change the name to something like run_nc_sa3_endpoint

File: Makefile [hunk 2]
```diff
@@ -548,6 +567,54 @@ define stop_noobaa
...
+	@echo "\033[1;34mStarting NC endpoint container\033[0m"
+	$(CONTAINER_ENGINE) rm -f noobaa_$(GIT_COMMIT)_$(NAME_POSTFIX) >/dev/null 2>&1 || true
+	$(CONTAINER_ENGINE) run -d --name noobaa_$(GIT_COMMIT)_$(NAME_POSTFIX) --network noobaa-net \
+		--network-alias noobaa-s3a \
+		--privileged --user root $(TESTER_TAG) \
+		bash -c "./src/test/external_tests/hadoop_s3a_tests/run_s3a_on_test_container.sh; tail -f /dev/null"
+	@echo "\033[1;32mNC endpoint container started.\033[0m"
+endef
+
+define stop_nc_endpoint
```
Comment (nadavMiz) [inline Makefile]: same name problem if you are waiting or stopping the s3a specific endpoint

File: Makefile (hunk 1 above)
Comment (nadavMiz) [reply Makefile]: if its a generic nc endpoint, should change script name to run_standalone_nsfs_on_test_container,sh

File: src/test/external_tests/hadoop_s3a_tests/configure_s3a.js [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+        console.error(`S3A Setup Failed: ${err}`);
+        process.exit(1);
+    }
+    process.exit(0);
+}
+
+async function s3a_test_setup() {
+    console.info('S3A TEST CONFIGURATION:', JSON.stringify(S3A_TEST));
+    await create_account(S3A_TEST.nc_s3a_account_params);
+    await create_bucket(S3A_TEST.nc_s3a_bucket_params);
```
[the remark this answers is not in the document]
Comment (jackyalbo) [reply src/test/external_tests/hadoop_s3a_tests/configure_s3a.js:20]: it's internal access_key and secret - nothing is exposed here

File: docs/CI & Tests/HadoopS3A.md [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+
+
+## Introduction
+
+Hadoop S3A tests validate NooBaa's S3 compatibility against the Hadoop S3A connector used by Apache Hadoop for S3 access. These tests exercise the `hadoop-aws` module's integration and contract suites against a live NooBaa endpoint, focusing on request correctness, path-style access, and credential handling.
+
+The CI flow runs the tests against the NC (ConfigFS) endpoint and uses a pinned Hadoop branch (`rel/release-3.3.6`) so test behavior remains consistent over time.
+
+Upstream test sources live in the Hadoop repository:
+- https://github.com/apache/hadoop/tree/rel/release-3.3.6/hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a
```
[the remark this answers is not in the document]
Comment (jackyalbo) [reply docs/CI & Tests/HadoopS3A.md:16]: you are correct - will be fixed

**Review by nadavMiz — APPROVED** [review]
LGTM
