### PR TITLE
S3 Website and Policy fixes

### LINKED ISSUE #6134: Question: Is there any way to create public access noobaa bucket?
I wanna create a public read access bucket that i can use my object urls in my web applications. But it does not work.
if i request(get) to "http://localhost:6001/first.bucket/index.html" it gives me access denied.
what i want is get original file that i uploaded to my noobaa bucket. 

i researched [Bucket Website Support](https://github.com/noobaa/noobaa-core/wiki/Bucket-Website-Support) documentation. I think it is out dated. 

Env: 
Noobaa core: 5.4.0 (it is not minikube)

in database bucket model looks like this.
```
{
    "_id": {
        "$oid": "5f3e2cd83a5bfdb352693f2d"
    },
    "name": "first.bucket",
    "tag": "",
    "system": {
        "$oid": "5f3e2cd83a5bfdb352693f26"
    },
    "owner_account": {
        "$oid": "5f3e2cd83a5bfdb352693f25"
    },
    "tiering": {
        "$oid": "5f3e2cd83a5bfdb352693f2c"
    },
    "storage_stats": {
        "chunks_capacity": 363,
        "objects_size": 644,
        "objects_count": 3,
        "stats_by_content_type": [
            {
                "content_type": "application/json",
                "count": 1,
                "size": 484
            },
            {
                "content_type": "text/html",
                "count": 2,
                "size": 160
            }
        ],
        "blocks_size": 363,
        "pools": {
            "5f3e2cd83a5bfdb352693f27": {
                "blocks_size": 363
            }
        },
        "objects_hist": [
            {
                "label": "0 - 1 B",
                "aggregated_sum": 0,
                "count": 0
            },
            {
                "label": "1 B - 2 B",
                "aggregated_sum": 0,
                "count": 0
            },
            {
                "label": "2 B - 4 B",
                "aggregated_sum": 0,
                "count": 0
            },
            {
                "label": "4 B - 8 B",
                "aggregated_sum": 0,
                "count": 0
            },
            {
                "label": "8 B - 16 B",
                "aggregated_sum": 0,
                "count": 0
            },
            {
                "label": "16 B - 32 B",
                "aggregated_sum": 0,
                "count": 0
            },
            {
                "label": "32 B - 64 B",
                "aggregated_sum": 0,
                "count": 0
            },
            {
                "label": "64 B - 128 B",
                "aggregated_sum": 160,
                "count": 2
            },
            {
                "label": "128 B - 256 B",
                "aggregated_sum": 0,
                "count": 0
            },
            {
                "label": "256 B - 512 B",
                "aggregated_sum": 484,
                "count": 1
            }
        ],
        "last_update": 1597915816286
    },
    "lambda_triggers": [],
    "versioning": "DISABLED",
    "last_update": 1597915712565,
    "s3_policy": {
        "version": "2012-10-17",
        "statement": [
            {
                "sid": "publicreadforgetbucketobjects",
                "effect": "allow",
                "principal": [
                    "*"
                ],
                "action": [
                    "s3:getobject"
                ],
                "resource": [
                    "arn:aws:s3:::first.bucket/*"
                ]
            }
        ]
    },
    "website": {
        "website_configuration": {
            "index_document": {
                "suffix": "index.html"
            },
            "error_document": {
                "key": "error.html"
            }
        }
    }
}
```
Any help would be appreciate.

### PR DESCRIPTION
**Pull request by jeniawhite**
### Explain the changes
1. Website feature did not work and there were S3 Policy gaps

### Issues: Fixed #xxx / Gap #xxx
1. Fixed https://github.com/noobaa/noobaa-core/issues/6134

### Testing Instructions:
1.

### CODE REVIEW

**Review by nimrod-becker — APPROVED** [review]

File: src/server/common_services/auth_server.js [hunk 1]
```diff
@@ -681,13 +681,18 @@ function has_bucket_anonymous_permission(bucket) {
...
+        Resource: [`arn:aws:s3:::${bucket.name.unwrap()}/*`],
     };
-    const bucket_policy = bucket.policy;
+    const bucket_policy = bucket.s3_policy;
     if (!bucket_policy) return false;
-    const statements = bucket_policy.Statement;
+    const statements = bucket_policy.statement;
     if (!statements) return false;
-    return _.some(statements, record => _.isEqual(required_configuration, record));
+    return _.some(statements, record => {
```
Comment (jackyalbo) [inline src/server/common_services/auth_server.js:690]: can you please add a comment that explains what we are checking here: one of the priniciples is * and the rest looks like required_configuration, have to say it can be done much simpler without going to JSON and return back. maybe I'm missing something... what about if action has more than just s3:getObject, or have other resources (which is unneeded I agree - but maybe was added anyway)?

**Review by jackyalbo — CHANGES_REQUESTED** [review]

File: src/server/common_services/auth_server.js (hunk 1 above)
Comment (jeniawhite) [reply src/server/common_services/auth_server.js]: Refactored the code.

**Review by jackyalbo — APPROVED** [review]
