### PR TITLE
postgres client | upsert duplications fix

### LINKED ISSUE #7076: Warp IO workload errors out with "The specified key does not exist" on Bare Metal
### Environment info
- NooBaa Version: 
```
[root@hpo-app11 ~]# noobaa version
INFO[0000] CLI version: 5.10.1
INFO[0000] noobaa-image: noobaa/noobaa-core:5.10.1
INFO[0000] operator-image: noobaa/noobaa-operator:5.10.1
[root@hpo-app11 ~]#
```

- Platform: 

```
[root@hpo-app11 ~]# oc version
Client Version: 4.11.0
Kustomize Version: v4.5.4
Server Version: 4.11.0
Kubernetes Version: v1.24.0+9546431
[root@hpo-app11 ~]#
```

ODF Version

```
[root@hpo-app11 ~]# oc get csv
NAME                                   DISPLAY                       VERSION               REPLACES                          PHASE
mcg-operator.v4.11.1                   NooBaa Operator               4.11.1                mcg-operator.v4.11.0              Succeeded
metallb-operator.4.11.0-202208300306   MetalLB Operator              4.11.0-202208300306                                     Succeeded
ocs-operator.v4.11.1                   OpenShift Container Storage   4.11.1                ocs-operator.v4.11.0              Succeeded
odf-csi-addons-operator.v4.11.1        CSI Addons                    4.11.1                odf-csi-addons-operator.v4.11.0   Succeeded
odf-operator.v4.11.1                   OpenShift Data Foundation     4.11.1                odf-operator.v4.11.0              Succeeded
[root@hpo-app11 ~]#

```

Warp version:

```
[root@hpo-app11 ~]# warp --version
warp version 0.5.5 - 1baadbc
[root@hpo-app11 ~]#
```

### Actual behavior
warp run on Bare Metal fails on all three metallb Endpoints

### Expected behavior
warp should execute successfully

### Steps to reproduce
1. Setup BM with CNSA/CSI RC4, ODF 4.11.1, latest DAS operator. 
2. Run warp on all three metallb IPs with 3 different users:

warp mixed --host=10.49.0.109 --access-key=uIBpl5fBWanFrXxLY6JW --secret-key=Z658YPATWG491XEbnn9ZwCPUGUS8KS36m91zWhUO --obj.size=1K --duration=120m --bucket=bucket11 --debug --insecure --tls 1> capture1.txt 2> error1.txt

warp mixed --host=10.49.0.110 --access-key=lDW9JSyitHuYa0EGx6vM --secret-key=BAu2KPpbAct28rvYwCdjILkO1vNWphsO57H5htlD --obj.size=1K --duration=120m --bucket=bucket22 --debug --insecure --tls 1> capture2.txt 2> error2.txt

warp mixed --host=10.49.0.111 --access-key=8FnXjkMLesfOOOr4TKw6 --secret-key=OjcPkdOyTE6FDujcmBj3JeUVl11TpZznyj4GyVhe --obj.size=1M --duration=120m --bucket=bucket33 --debug --insecure --tls 1> capture3.txt 2> error3.txt

Attachments:
[capture2.txt](https://github.com/noobaa/noobaa-core/files/9599718/capture2.txt)
[capture3.txt](https://github.com/noobaa/noobaa-core/files/9599725/capture3.txt)
[capture1.txt](https://github.com/noobaa/noobaa-core/files/9599713/capture1.txt)
[error1.txt](https://github.com/noobaa/noobaa-core/files/9599747/error1.txt)
[error2.txt](https://github.com/noobaa/noobaa-core/files/9599748/error2.txt)
[error3.txt](https://github.com/noobaa/noobaa-core/files/9599749/error3.txt)

Logs: https://ibmandredhatguests.slack.com/archives/G015Z7SDWQ0/p1663598668494769?thread_ts=1663597420.548999&cid=G015Z7SDWQ0

### PR DESCRIPTION
**Pull request by romayalon**
Signed-off-by: Romy <romy2232@gmail.com>

### Explain the changes
1. _Upsert() - added a call to _updateOneWithClient() after locking the table in order to avoid race conditions that cause duplications as we saw in io_stats & bucket_stats in some warp runs and in the past in a BZ.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed a symptom in #7076 

### Testing Instructions:
1. 

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/util/postgres_client.js [hunk 1]
```diff
@@ -1207,27 +1207,29 @@ class PostgresTable {
...
-                let update_res = await this._updateOneWithClient(pg_client, query, update, options);
-                if (update_res.rowCount === 0) {
-                    // try to lock the advisory_lock_key for this table and insert the first doc
-                    let locked = await this.try_lock_table(pg_client);
-                    if (locked) {
+                locked = await this.try_lock_table(pg_client);
+                if (locked) {
+                    let update_res = await this._updateOneWithClient(pg_client, query, update, options);
+                    if (update_res.rowCount === 0) {
+                        // try to lock the advisory_lock_key for this table and insert the first doc
```
Comment (liranmauda) [inline src/util/postgres_client.js:1217]: I think that this comment should be above the lock operation.

File: src/util/postgres_client.js [hunk 2]
```diff
@@ -1207,27 +1207,29 @@ class PostgresTable {
...
+            let locked;
             try {
                 pg_client = await this.client.pool.connect();
-                let update_res = await this._updateOneWithClient(pg_client, query, update, options);
-                if (update_res.rowCount === 0) {
-                    // try to lock the advisory_lock_key for this table and insert the first doc
-                    let locked = await this.try_lock_table(pg_client);
-                    if (locked) {
+                locked = await this.try_lock_table(pg_client);
+                if (locked) {
```
Comment (dannyzaken) [inline src/util/postgres_client.js:1214]: the purpose of the update before the lock is to avoid serialization of all upserts. I think that the bug here is that we need to try and update again after the lock is acquired and before inserting

**Review by dannyzaken — APPROVED** [review]
