### PR TITLE
NSFS | NC | CLI | Account add/update when uid = 0 and gid != 0 bug fix

### LINKED ISSUE #7787: NSFS | NC | CLI | Account add/update is failing when uid = 0 and gid != 0 and vice versa
### Environment info
- NooBaa Version: Master
- Platform: NC

### Actual behavior
1. Account add/update is failing when uid = 0 but and gid != 0 and vice versa

### Expected behavior
1. An account can get created/updated  when uid = 0 but and gid != 0 and vice versa

### Steps to reproduce
```
> manage_nsfs.js account add --name foo --email foo@example.com --uid 0 --gid 10 2>/dev/null
{
  "error": {
    "code": "MissingAccountNSFSConfigUID",
    "message": "Account config should include UID",
    "detail": {
      "uid": 0,
      "gid": 10,
      "new_buckets_path": "/gpfs/bucket-root"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. is_undefined() checks using if (!value), which return true when uid/gid is 0, causing the account add/update to fail.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed https://github.com/noobaa/noobaa-core/issues/7787

### Testing Instructions:
1. `manage_nsfs.js account add --name foo --email foo@example.com --uid 0 --gid 10 2>/dev/null`

- [ ] Doc added/updated
- [x] Tests added

### CODE REVIEW

File: src/cmd/manage_nsfs.js [hunk 1]
```diff
@@ -774,10 +774,10 @@ async function validate_account_args(data, action) {
 
         if (is_undefined(data.access_keys[0].secret_key)) throw_cli_error(ManageCLIError.MissingAccountSecretKeyFlag);
         if (is_undefined(data.access_keys[0].access_key)) throw_cli_error(ManageCLIError.MissingAccountAccessKeyFlag);
-        if (data.nsfs_account_config.gid && (is_undefined(data.nsfs_account_config.uid))) {
```
Comment (shirady) [inline src/cmd/manage_nsfs.js:777]: In addition to your change, I think either the function name `is_undefined` or the implementation of the function should be changed. 
- Function name change - The current implementation doesn't check if the value is undefined but if the value is Falsy (here is a [link](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)), and 0 is Falsy.
- Change function implementation - to check if the value is_undefined explicitly (includes the SensitiveString case).
I would go on the second option.

File: src/test/unit_tests/test_nc_nsfs_cli.js [hunk 2]
```diff
@@ -530,6 +531,33 @@ mocha.describe('manage_nsfs cli', function() {
             }
         });
 
+        mocha.it('cli account add - uid=0, gid!=0', async function() {
+            const action = ACTIONS.ADD;
+            const account_name = 'uid_is_0';
+            const options = { name: account_name, email: account_name, uid: 0, gid: 1001 };
```
Comment (shirady) [inline src/test/unit_tests/test_nc_nsfs_cli.js:537]: So it won't confuse I would add a variable for the account email, for example:
```suggestion
            const account_name = 'uid_is_0';
            const account_email = `${account_name}@noobaa.com`
            const options = { name: account_name, email: account_email, uid: 0, gid: 1001 };
```

File: src/test/unit_tests/test_nc_nsfs_cli.js [hunk 3]
```diff
@@ -530,6 +531,33 @@ mocha.describe('manage_nsfs cli', function() {
             }
         });
 
+        mocha.it('cli account add - uid=0, gid!=0', async function() {
```
Comment (shirady) [inline src/test/unit_tests/test_nc_nsfs_cli.js:534]: I would change the description so it will be clear for others... (other tests as well).
```suggestion
        mocha.it('cli account add - uid is 0, gid is not 0', async function() {
```

**Comment by shirady** [comment]
@romayalon please notice there is a similar issue that is not covered by this fix:
`sudo node src/cmd/manage_nsfs account add --name foo --email foo@example.com --user 0` (user name is 0).

```json
{
  "error": {
    "code": "InvalidAccountNSFSConfig",
    "message": "Account config should not be empty, should contain UID, GID or user",
    "detail": {
      "distinguished_name": 0
    }
  }
}
```

File: src/test/unit_tests/test_nc_nsfs_cli.js (hunk 3 above)
Comment (naveenpaul1) [inline src/test/unit_tests/test_nc_nsfs_cli.js:534]: I think it would be better if you add this in jest test `test_nc_nsfs_account_cli.test.js`

**Comment by romayalon** [comment]
@shirady As discussed on Slack - this is a different type of issue that will addressed by replacing the STRING_OR_NUMBER type with string only.

> @romayalon please notice there is a similar issue that is not covered by this fix: `sudo node src/cmd/manage_nsfs account add --name foo --email foo@example.com --user 0` (user name is 0).
> 
> ```json
> {
>   "error": {
>     "code": "InvalidAccountNSFSConfig",
>     "message": "Account config should not be empty, should contain UID, GID or user",
>     "detail": {
>       "distinguished_name": 0
>     }
>   }
> }
> ```

**Review by shirady — APPROVED** [review]
You can leave the comment unhandled and mentioned it as a GAP (the fix is more important)
