### PR TITLE
NC | NSFS | Add stat to `account_cache`

### LINKED ISSUE #8071: After account update with new access keys, old access keys are valid for next 5min ~
### Environment info
- NooBaa Version: **noobaa-core-5.15.3-20240514.el9.x86_64**
- Platform: **Standalone Noobaa**

### Actual behaviour
After account update with new access keys, old access keys are valid for next 5min ~

### Expected behaviour
After successful account update, the old access keys should become invalid immediately.

### Steps to reproduce
1. Create an account and a bucket. Upload an object in to bucket.
```
[root@3node-x-worker1 ~]# noobaa-cli account add --name account-first --uid 1002 --gid 1002 --fs_backend GPFS --new_buckets_path /mnt/fs1/account-first 2>/dev/null
{
  "response": {
    "code": "AccountCreated",
    "reply": {
      "_id": "664f1b4ce22980ca61b1d181",
      "name": "account-first",
      "email": "account-first",
      "creation_date": "2024-05-23T10:32:44.775Z",
      "access_keys": [
        {
          "access_key": "YIxrhiDGAjJjyqwnxp9I",
          "secret_key": "Md+P1NYohQfK26kKD9guYTKFE1+OJ1DZ3mzQClaF"
        }
      ],
      "nsfs_account_config": {
        "uid": 1002,
        "gid": 1002,
        "new_buckets_path": "/mnt/fs1/account-first",
        "fs_backend": "GPFS"
      },
      "allow_bucket_creation": true,
      "master_key_id": "664e107282dba0d07d51b455"
    }
  }
}
```

```
[root@3node-x-worker1 ~]# mms3 bucket create bucket-first --accountName account-first --filesystemPath /mnt/fs1/account-first/bucket-first
Bucket bucket-first created successfully
```

Step2: Update the account's access key. Only last one character is updated.

```
[root@3node-x-worker1 ~]# noobaa-cli account update --name account-first --fs_backend GPFS --access_key YIxrhiDGAjJjyqwnxp9L --secret_key Md+P1NYohQfK26kKD9guYTKFE1+OJ1DZ3mzQClaF 2>/dev/null
{
  "response": {
    "code": "AccountUpdated",
    "reply": {
      "_id": "664f1b4ce22980ca61b1d181",
      "name": "account-first",
      "email": "account-first",
      "creation_date": "2024-05-23T10:32:44.775Z",
      "access_keys": [
        {
          "access_key": "YIxrhiDGAjJjyqwnxp9L",
          "secret_key": "Md+P1NYohQfK26kKD9guYTKFE1+OJ1DZ3mzQClaF"
        }
      ],
      "nsfs_account_config": {
        "uid": 1002,
        "gid": 1002,
        "new_buckets_path": "/mnt/fs1/account-first",
        "fs_backend": "GPFS"
      },
      "allow_bucket_creation": true,
      "master_key_id": "664e107282dba0d07d51b455"
    }
  }
}
```

**Step3 : Now do the object upload using old access Key : Success. --> This is the issue**
```
[root@anan-rhel921 ~]# AWS_ACCESS_KEY_ID=YIxrhiDGAjJjyqwnxp9I AWS_SECRET_ACCESS_KEY=Md+P1NYohQfK26kKD9guYTKFE1+OJ1DZ3mzQClaF aws --endpoint https://10.11.71.87:6443 --no-verify-ssl s3 cp awscliv2.zip s3://bucket-first
upload: ./awscliv2.zip to s3://bucket-first/awscliv2.zip
```

Step4 : Now verify that new access key is also working 

```
[root@anan-rhel921 ~]# AWS_ACCESS_KEY_ID=YIxrhiDGAjJjyqwnxp9L AWS_SECRET_ACCESS_KEY=Md+P1NYohQfK26kKD9guYTKFE1+OJ1DZ3mzQClaF aws --endpoint https://10.11.71.87:6443 --no-verify-ssl s3 cp awscliv2.zip s3://bucket-first
upload: ./awscliv2.zip to s3://bucket-first/awscliv2.zip
```

Step5 : After few mins, it started erroring out about the invalid key, if I use the old key. This is expected

```
[root@anan-rhel921 ~]# AWS_ACCESS_KEY_ID=YIxrhiDGAjJjyqwnxp9I AWS_SECRET_ACCESS_KEY=Md+P1NYohQfK26kKD9guYTKFE1+OJ1DZ3mzQClaF aws --endpoint https://10.11.71.87:6443 --no-verify-ssl s3 cp awscliv2.zip s3://bucket-first
upload failed: ./awscliv2.zip to s3://bucket-first/awscliv2.zip An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS access key Id you provided does not exist in our records.
```

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. In `account_cache` move the value that we had in `expiry_ms` to the `config.js` (with its comment of "TODO"), and add `_validate_account` function (like in `bucket_namespace_cache` we have the method `_validate_bucket_namespace`).
2. In `read_account_by_access_key` add the property `stat` so we can save the stat of the account config.
3. Rename `check_same_stat` to `check_same_stat_bucket` so we can have 2 methods for buckets and accounts. Also rename `ns_allow_stat_bucket` to `bs_allow_stat_bucket` (as it is implemented in the bucketspace and not in the namespace).
4. Add `stat_account_config_file` in `config_fs`.

### Issues: Fixed #8071
1. Currently, when updating access keys of an account using the noobaa-cli they are validate until the item is expired (in the current config 10 mminutes). With the suggested code change, updating the access keys results in changing the config file, and therefore the stat is changing and the item is no longer valid in the `account_cache`.

GAPS:
1. There are many functions that should move to accountspace and not bucketspace (and also the `account_cache` itself should be in `account_sdk`). Please see [comment1](https://github.com/noobaa/noobaa-core/pull/8585#discussion_r1890212811) [comment2](https://github.com/noobaa/noobaa-core/pull/8585#discussion_r1888280651).
2. We would probably want to do the same on `account_id_cache`.

Note: the idea for the solution was planned as part of issue #8391 

#### Automatic Test:
Please run: `sudo NC_CORETEST=true node ./node_modules/mocha/bin/mocha ./src/test/unit_tests/test_nc_with_a_couple_of_forks.js`

#### Manual Test:
1. Add the line: `dbg.log('SDSD same_stat', same_stat);` after declaring the variable `same_stat`, and restart the server.
##### Regular account (not anonymous)
2. Create an account with the CLI: `sudo node src/cmd/manage_nsfs account add --name <account-name> --new_buckets_path /Users/buckets/ --access_key <access-key> --secret_key <secret-key> --uid <uid> --gid <gid>`
Note: before creating the account need to give permission to the `new_buckets_path`: `chmod 777 /Users/buckets/`
4. Start the NSFS server with: `sudo node src/cmd/nsfs --debug 5`
5. Create the alias for S3 service:`alias nc-user-1-s3=‘AWS_ACCESS_KEY_ID=<access-key> AWS_SECRET_ACCESS_KEY=<secret-key> aws --no-verify-ssl --endpoint-url https://localhost:6443’`
6. Check the connection to the endpoint and try to list the buckets (should be empty): `nc-user-1-s3 s3 ls; echo $?`
6. Change the account configuration, for example: `sudo node src/cmd/manage_nsfs account update --name <account-name> --fs_backend GPFS`
7. List the buckets again (should be empty): `nc-user-1-s3 s3 ls; echo $?` (search in the logs for the added printing with `SDSD same_stat false`

##### Anonymous account
8. Create an anonymous account with the CLI: `sudo node src/cmd/manage_nsfs account add --anonymous --uid <uid> --gid <gid>`
9. Create the alias for S3 service:`alias nc-user-anon-s3='aws --no-verify-ssl --endpoint-url https://localhost:6443 --no-sign-request' #anonymous`
10. Check the connection to the endpoint and try to list the buckets (should be empty): `nc-user-anon-s3 s3 ls; echo $?`
11. Change the account configuration, for example: `sudo node src/cmd/manage_nsfs account update --anonymous --uid 3333`
12. List the buckets again (should be empty): `nc-user-anon-s3 s3 ls; echo $?` (search in the logs for the added printing with `SDSD same_stat false`

- [ ] Doc added/updated
- [X] Tests added

### CODE REVIEW

File: src/sdk/object_sdk.js [hunk 1]
```diff
@@ -47,17 +47,20 @@ const bucket_namespace_cache = new LRUCache({
 
 const account_cache = new LRUCache({
     name: 'AccountCache',
-    // TODO: Decide on a time that we want to invalidate
-    expiry_ms: Number(process.env.ACCOUNTS_CACHE_EXPIRY) || 10 * 60 * 1000,
+    // This is intentional. Cache entry expiration is handled by _validate_account().
+    // The expiration time is controlled by config.OBJECT_SDK_ACCOUNT_CACHE_EXPIRY_MS.
+    expiry_ms: 0,
```
[the remark this answers is not in the document]
Comment (shirady) [reply src/sdk/object_sdk.js:52]: I imitated the way it was implemented in `bucket_namespace_cache`.
https://github.com/noobaa/noobaa-core/blob/cf0daca364e3da98a549011e13915d9adb2eeb39/src/sdk/object_sdk.js#L30-L34
Anyway, in the class if we don't pass this value it is initiated to 0.
https://github.com/noobaa/noobaa-core/blob/cf0daca364e3da98a549011e13915d9adb2eeb39/src/util/lru_cache.js#L48

File: src/sdk/object_sdk.js [hunk 2]
```diff
@@ -319,6 +323,20 @@ class ObjectSDK {
         }
     }
 
+    async _validate_account(data, params) {
```
[the remark this answers is not in the document]
Comment (shirady) [reply src/sdk/object_sdk.js:326]: We have the call of `account_cache.get_with_cache` from account_sdk, object_sdk and sts_sdk.
Those are separated classes, so I had to move a callback that was implemented the same in each one of them.

File: src/sdk/sts_sdk.js [hunk 3]
```diff
@@ -34,13 +35,29 @@ class StsSDK {
         return this.bucketspace;
     }
 
+    async _validate_account(data, params) {
```
[the remark this answers is not in the document]
Comment (shirady) [reply src/sdk/sts_sdk.js:38]: You're right, as I mentioned in the previous comment.
I'm resolving this, so we have one place for discussion.

File: src/sdk/bucketspace_fs.js [hunk 4]
```diff
@@ -186,18 +194,37 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+     */
+    async check_same_stat_account(account_id, account_stat) {
+        try {
+            const path_for_account_or_user_config_file = this.config_fs.get_identity_path_by_id(account_id);
+            const current_stat = await this.config_fs.stat_account_config_file(path_for_account_or_user_config_file);
+            if (current_stat) {
+                return current_stat.ino === account_stat.ino && current_stat.mtimeNsBigint === account_stat.mtimeNsBigint;
+            }
+        } catch (err) {
+            dbg.warn('check_same_stat_account: current_stat got an error', err, 'ignoring...');
```
[the remark this answers is not in the document]
Comment (shirady) [reply src/sdk/bucketspace_fs.js:227]: I didn't want to confuse with the case where it is not the same stat.

[the remark this answers is not in the document]
Comment (shirady) [reply src/sdk/bucketspace_fs.js:228]: I edited the JSDoc according to your comment.

File: src/sdk/object_sdk.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (shirady) [reply src/sdk/object_sdk.js]: I changed the code according to your suggestion, now every module will export the method from file `object_sdk` (which is located outside of the the class `ObjectSDK`).

File: config.js [hunk 5]
```diff
@@ -637,9 +637,15 @@ config.INLINE_MAX_SIZE = 4096;
 
 // Object SDK bucket cache expiration time
 config.OBJECT_SDK_BUCKET_CACHE_EXPIRY_MS = 60000;
+// Object SDK bucket cache expiration time
```
Comment (romayalon) [inline config.js:640]:
```suggestion
// Object SDK account cache expiration time
```

File: src/sdk/bucketspace_fs.js [hunk 6]
```diff
@@ -85,6 +85,14 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
             if (account.nsfs_account_config.distinguished_name) {
                 account.nsfs_account_config.distinguished_name = new SensitiveString(account.nsfs_account_config.distinguished_name);
             }
+            try {
+                const path_for_account_or_user_config_file = access_key === anonymous_access_key ?
+                this.config_fs.get_account_path_by_name(config.ANONYMOUS_ACCOUNT_NAME) :
```
Comment (romayalon) [inline src/sdk/bucketspace_fs.js:90]: this logic should be inside stat_account_config_file()

File: src/sdk/bucketspace_fs.js [hunk 7]
```diff
@@ -186,18 +194,38 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+    }
+
+    /**
+     * check_same_stat_bucket will return true the config file was not changed
+     * in case we had any issue (for example error during stat) the returned value will be undefined
+     * @param {string} account_id
+     * @param {nb.NativeFSStats} account_stat
+     * @returns Promise<{boolean|undefined>}
+     */
+    async check_same_stat_account(account_id, account_stat) {
```
Comment (romayalon) [inline src/sdk/bucketspace_fs.js:220]: why check_same_stat_account is in bucketspace_fs and not in accountspace_fs?

File: src/sdk/object_sdk.js [hunk 8]
```diff
@@ -79,6 +82,25 @@ const MULTIPART_NAMESPACES = [
...
+    // stat check (only in bucketspace FS)
+    const bs = params.bucketspace;
+    const bs_allow_stat_account = Boolean(bs.check_same_stat_account);
+    if (bs_allow_stat_account && config.NC_ENABLE_ACCOUNT_CACHE_STAT_VALIDATION) {
+        const same_stat = await bs.check_same_stat_account(data._id, data.stat);
+        if (!same_stat) { // config file of bucket was changed
+            return false;
+        }
+    }
+    if (time <= data.valid_until) return true;
```
Comment (romayalon) [inline src/sdk/object_sdk.js:101]: else?

Comment (romayalon) [inline src/sdk/object_sdk.js:101]: Are you using here the valid_until of the bucketspace?

File: src/sdk/object_sdk.js [hunk 9]
```diff
@@ -227,6 +249,7 @@ class ObjectSDK {
             this.requesting_account = await account_cache.get_with_cache({
                 bucketspace: this._get_bucketspace(),
                 access_key: token ? token.access_key : anonymous_access_key,
+                validation_callback: _validate_account,
```
Comment (romayalon) [inline src/sdk/object_sdk.js:252]: how this works on containerized?

File: src/sdk/bucketspace_fs.js [hunk 10]
```diff
@@ -85,6 +85,14 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
             if (account.nsfs_account_config.distinguished_name) {
                 account.nsfs_account_config.distinguished_name = new SensitiveString(account.nsfs_account_config.distinguished_name);
             }
+            try {
```
Comment (romayalon) [inline src/sdk/bucketspace_fs.js:88]: @guymguym I think we need to reconsider having read_account_by_access_key and other new account related functions in bucketspace_fs, it worked before when we didn't have accountspaceFS but now I think it just weird

**Review by romayalon — CHANGES_REQUESTED** [review]

File: config.js (hunk 5 above)
Comment (shirady) [reply config.js]: I changed it, thanks.

File: src/sdk/bucketspace_fs.js (hunk 6 above)
Comment (shirady) [reply src/sdk/bucketspace_fs.js]: I tried to avoid passing the Symbol type that might be in access_key.
Anyway, now I changed it according to this comment, thanks.

File: src/sdk/bucketspace_fs.js (hunk 7 above)
Comment (shirady) [reply src/sdk/bucketspace_fs.js]: I think it is related to another comment you raised ([here](https://github.com/noobaa/noobaa-core/pull/8585#discussion_r1888280651)).
 Because I know I have bucketspace in all the services, the function of `read_account_by_access_key` in NC is implemented inside bucketspace_fs.

File: src/sdk/object_sdk.js (hunk 8 above)
Comment (shirady) [reply src/sdk/object_sdk.js]: Thanks, I added it.

Comment (shirady) [reply src/sdk/object_sdk.js]: You're were right, I missed to set it and it was always `undefined`, now it is set it in the phase where we call the `account_cache.get_with_cache`, since it is configured to 10 minutes so I'm fine with it called prior to the actual load.

File: src/sdk/object_sdk.js (hunk 9 above)
Comment (shirady) [reply src/sdk/object_sdk.js:255]: The function is implemented in `object_sdk` and in all the cases when it is called it should not have stat the files, as it is not relevant, and only check the validation by time.

File: src/sdk/object_sdk.js [hunk 11]
```diff
@@ -79,6 +82,25 @@ const MULTIPART_NAMESPACES = [
...
+ * S3 (object_sdk), IAM (account_sdk), STS (sts_sdk)
+ * @param {object} data
+ * @param {object} params
+ */
+async function _validate_account(data, params) {
+    const time = Date.now();
+    // stat check (only in bucketspace FS)
+    const bs = params.bucketspace;
+    const bs_allow_stat_account = Boolean(bs.check_same_stat_account);
+    if (bs_allow_stat_account && config.NC_ENABLE_ACCOUNT_CACHE_STAT_VALIDATION) {
```
[the remark this answers is not in the document]
Comment (shirady) [reply src/sdk/object_sdk.js:97]: Now where we call the `account_cache.get_with_cache`, thanks.

File: src/sdk/bucketspace_fs.js (hunk 7 above)
Comment (romayalon) [reply src/sdk/bucketspace_fs.js]: having `read_account_by_access_key` in the bucketspaces was the desired behavior as long as we didn't have accountspaceFS.
Now that we do, it doesn't make sense anymore to have additional account-related functionalities in the bucketspaces.
Same for the account cache, why it's in objectSDK and not in accountSDK? 
Account cache move is not something that we can easily change, especially not in containerized env where we currently don't have accountSDK. @guymguym WDYT?
@shirady these changes are not in the right place, validate_account should call accountspaces functionalities.

File: src/sdk/object_sdk.js [hunk 12]
```diff
@@ -227,6 +252,8 @@ class ObjectSDK {
             this.requesting_account = await account_cache.get_with_cache({
                 bucketspace: this._get_bucketspace(),
                 access_key: token ? token.access_key : anonymous_access_key,
+                validation_callback: _validate_account,
+                valid_until: Date.now() + config.OBJECT_SDK_ACCOUNT_CACHE_EXPIRY_MS,
```
Comment (romayalon) [inline src/sdk/object_sdk.js:256]: if we always pass 10 minutes from now to validate_account and validate_account check `  if (time <= params.valid_until) return true;` wouldn't it always be valid?

File: src/sdk/config_fs.js [hunk 13]
```diff
@@ -438,6 +438,25 @@ class ConfigFS {
...
+    /**
+     * stat_account_config_file will return the stat output on account config file
+     * please notice that stat might throw an error - you should wrap it with try-catch and handle the error
+     * Note: access_key type of anonymous_access_key is a symbol, otherwise it is a string (not SensitiveString)
+     * @param {Symbol|string} access_key
+     * @returns {Promise<nb.NativeFSStats>}
+     */
+    stat_account_config_file(access_key) {
+        let path_for_account_or_user_config_file;
+        if (typeof access_key === 'symbol') { // anonymous account case
```
Comment (romayalon) [inline src/sdk/config_fs.js:450]: add a check that it's the anonymous symbol

File: src/sdk/bucketspace_fs.js [hunk 14]
```diff
@@ -186,18 +192,37 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
             if (current_stat) {
                 return current_stat.ino === bucket_stat.ino && current_stat.mtimeNsBigint === bucket_stat.mtimeNsBigint;
             }
         } catch (err) {
-            dbg.warn('check_same_stat: current_stat got an error', err, 'ignoring...');
+            dbg.warn('check_same_stat_bucket: current_stat got an error', err, 'ignoring...');
+        }
+    }
+
+    /**
```
Comment (romayalon) [inline src/sdk/bucketspace_fs.js:211]: add TODO move to accountspaceFS

Comment (shirady) [reply src/sdk/bucketspace_fs.js:212]: I added, thanks.

File: src/sdk/bucketspace_fs.js (hunk 7 above)
Comment (shirady) [reply src/sdk/bucketspace_fs.js]: I think you're right, and while trying to assess the change of moving all the related function to account_sdk and accountspace seems not trivial, I mentioned this as a gap.

File: src/sdk/bucketspace_fs.js (hunk 10 above)
Comment (shirady) [reply src/sdk/bucketspace_fs.js:89]: I think that Guy would agree with you from what I understand while I worked on IAM).
I will mention this as a GAP in the PR description.

File: src/sdk/object_sdk.js (hunk 12 above)
Comment (shirady) [reply src/sdk/object_sdk.js]: Thank you, I changed the implementation, I hope it is fine now.

File: src/sdk/config_fs.js (hunk 13 above)
Comment (shirady) [reply src/sdk/config_fs.js]: I added it, thanks.

**Comment by shirady** [comment]
I'm waiting for the CI to pass (it is stuck on Ceph tests) - See PR #8621 and PR #8567

**Review by romayalon — APPROVED** [review]
