### PR TITLE
NSFS | NC | Add Condition in `authorize_request_policy`

### LINKED ISSUE #8080: Account update with account name is not updating bucket_name.json file automatically
###Environment info

NooBaa Version: noobaa-core-5.15.3-20240514.el9.x86_64
Platform: Standalone Noobaa

### Actual behavior
1.Account update with account name is not updating bucket_name.json file automatically. 
I/O is failing due to this issue.

### Expected behavior
If the account name is updated with a new name, the corresponding buckets should get auto updated with the new account name.
Otherwise it is a tedious task to manually update all the buckets with owner details

### Steps to reproduce
1. Create an account with noobaa-cli
```
[root@3node-x-worker1 ~]# noobaa-cli account add --name account_test_old --uid 7000 --gid 7000 --new_buckets_path /mnt/fs1/account_test_old 2>/dev/null
{
  "response": {
    "code": "AccountCreated",
    "reply": {
      "_id": "66544e9f738d7528d7f9e70b",
      "name": "account_test_old",
      "email": "account_test_old",
      "creation_date": "2024-05-27T09:13:03.211Z",
      "access_keys": [
        {
          "access_key": "BjLLk92yXAEFxOKaOFyA",
          "secret_key": "xYPDVxbTaH6g8b42T2ecOk/j3I53spnA/JkDtEi2"
        }
      ],
      "nsfs_account_config": {
        "uid": 7000,
        "gid": 7000,
        "new_buckets_path": "/mnt/fs1/account_test_old",
        "fs_backend": "GPFS"
      },
      "allow_bucket_creation": true,
      "master_key_id": "664e107282dba0d07d51b455"
    }
  }
}
```

2. Create a bucket with noobaa-cli.

```
[root@3node-x-worker1 ~]# noobaa-cli bucket add --name bucket-old --owner account_test_old --path /mnt/fs1/account_test_old/bucket_old 2>/dev/null
{
  "response": {
    "code": "BucketCreated",
    "reply": {
      "_id": "66544f33b1260396610d32cc",
      "name": "bucket-old",
      "owner_account": "66544e9f738d7528d7f9e70b",
      "system_owner": "account_test_old",
      "bucket_owner": "account_test_old",
      "versioning": "DISABLED",
      "creation_date": "2024-05-27T09:15:31.368Z",
      "path": "/mnt/fs1/account_test_old/bucket_old",
      "should_create_underlying_storage": false,
      "fs_backend": "GPFS"
    }
  }
}
```

3. Update the account name to a new name : PASS

```
[root@3node-x-worker1 ~]# noobaa-cli account update --name account_test_old --new_name account_test_new
load_nsfs_nc_config.setting config.NSFS_NC_CONF_DIR /gpfs/fs-ces-shared/ces/s3-config
nsfs: config_dir_path=/gpfs/fs-ces-shared/ces/s3-config config.json= {
  ENDPOINT_FORKS: 2,
  ENDPOINT_PORT: 6001,
  ENDPOINT_SSL_PORT: 6443,
  ALLOW_HTTP: true,
  UV_THREADPOOL_SIZE: 16,
  GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so',
  NOOBAA_LOG_LEVEL: 'default',
  NSFS_NC_STORAGE_BACKEND: 'GPFS',
  NSFS_NC_CONFIG_DIR_BACKEND: 'GPFS',
  NSFS_DIR_CACHE_MAX_DIR_SIZE: 536870912,
  NSFS_DIR_CACHE_MAX_TOTAL_SIZE: 1073741824,
  NC_MASTER_KEYS_GET_EXECUTABLE: '/usr/lpp/mmfs/bin/cess3_key_get',
  NC_MASTER_KEYS_PUT_EXECUTABLE: '/usr/lpp/mmfs/bin/cess3_key_put',
  NC_MASTER_KEYS_STORE_TYPE: 'executable'
}
2024-05-27 02:16:52.852822 [PID-1489615/TID-1489615] FS::GPFS GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
2024-05-27 02:16:52.853560 [PID-1489615/TID-1489615] FS::GPFS found GPFS lib file GPFS_DL_PATH=/usr/lpp/mmfs/lib/libgpfs.so
May-27 2:16:53.876 [/1489615]   [LOG] CONSOLE:: detect_fips_mode: found /proc/sys/crypto/fips_enabled with value 0
(node:1489615) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
May-27 2:16:53.976 [/1489615]   [LOG] CONSOLE:: read_rand_seed: reading 32 bytes from /dev/urandom ...
May-27 2:16:53.993 [/1489615]   [LOG] CONSOLE:: read_rand_seed: got 32 bytes from /dev/urandom, total 32 ...
May-27 2:16:53.994 [/1489615]   [LOG] CONSOLE:: read_rand_seed: closing fd ...
May-27 2:16:53.995 [/1489615]   [LOG] CONSOLE:: init_rand_seed: seeding with 32 bytes
May-27 2:16:53.996 [/1489615]   [LOG] CONSOLE:: generate_entropy: entropy_avail 256
May-27 2:16:54.041 [/1489615]   [LOG] CONSOLE:: generate_entropy: adding entropy: dd if=/dev/vda bs=1048576 count=32 skip=215443 | md5sum
May-27 2:16:54.199 [/1489615]   [LOG] CONSOLE:: init_rand_seed: done
May-27 2:16:54.217 [/1489615]    [L0] core.manage_nsfs.nc_master_key_manager:: init_from_exec: get master keys response status=OK, version=1
{
  "response": {
    "code": "AccountUpdated",
    "reply": {
      "_id": "66544e9f738d7528d7f9e70b",
      "name": "account_test_new",
      "email": "account_test_new",
      "creation_date": "2024-05-27T09:13:03.211Z",
      "access_keys": [
        {
          "access_key": "BjLLk92yXAEFxOKaOFyA",
          "secret_key": "xYPDVxbTaH6g8b42T2ecOk/j3I53spnA/JkDtEi2"
        }
      ],
      "nsfs_account_config": {
        "uid": 7000,
        "gid": 7000,
        "new_buckets_path": "/mnt/fs1/account_test_old",
        "fs_backend": "GPFS"
      },
      "allow_bucket_creation": true,
      "master_key_id": "664e107282dba0d07d51b455"
    }
  }
}
```

4. Now verify the ownership of the bucket. It is still showing old account name

```
[root@3node-x-worker1 ~]# jq "." /gpfs/fs-ces-shared/ces/s3-config/buckets/bucket-old.json
{
  "_id": "66544f33b1260396610d32cc",
  "name": "bucket-old",
  "owner_account": "66544e9f738d7528d7f9e70b",
  "system_owner": "**account_test_old**",
  "bucket_owner": "**account_test_old**",
  "versioning": "DISABLED",
  "creation_date": "2024-05-27T09:15:31.368Z",
  "path": "/mnt/fs1/account_test_old/bucket_old",
  "should_create_underlying_storage": false,
  "fs_backend": "GPFS"
}
```

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. Add Condition in `authorize_request_policy` in `s3_rest`.
2. To have the details of the account owner also return the `owner_account` in the function  `read_bucket_sdk_policy_info`.
3. In nsfs add the `owner_account` with mock value just to return a value like in the function `read_bucket_sdk_policy_info`.

### Issues: Fixed (partial) #8080 
1. Currently, after an account name is updated it results in failure in S3 request that the account tries to perform on the bucket (`AccessDenied`). It happens because the `bucket_owner` is with the previous name and the `account_identifier` is with the new name.

after this fix, the S3 request should not return an error, although there are still GAPS:
- The buckets that the account owns still have the properties `system_owner` and `bucket_owner` with the previous name (in the bucket config).
- Currently, the `s3_policy` is set in the bucket config files with the name of the account, and this will also not be updated, for example: `Principal: { AWS: 'user10' }`.

#### Manual Test:
Before you start: Change the `config.NSFS_CHECK_BUCKET_BOUNDARIES = false;`
1. First, create the `FS_ROOT` and a directory for a bucket: `mkdir -p /tmp/nsfs_root1/my-bucket` and give permissions `chmod 777 /tmp/nsfs_root1/` `chmod 777 /tmp/nsfs_root1/my-bucket`.
This will be the argument for:
  - `new_buckets_path` flag  `/tmp/nsfs_root1` (that we will use in the account commands)
  - `path` in the buckets commands `/tmp/nsfs_root1/my-bucket` (that we will use in bucket commands).
2. Run the nsfs server: `sudo node src/cmd/nsfs --debug 5`
3. Create an account with an access key and secret key:
`sudo node src/cmd/manage_nsfs account add --name shira-1003 --new_buckets_path /tmp/nsfs_root1 --access_key <access-key> --secret_key <secret-key> --uid 1003 --gid 1003`
4. Create a bucket for the account
`sudo node src/cmd/manage_nsfs bucket add --name shira-1003-bucket-1 --owner shira-1003 --path /tmp/nsfs_root1/my-bucket`
5. Create the alias for sending the requests using AWS CLI (access key and secret key were omitted):
`alias s3-nc-user-1='AWS_ACCESS_KEY_ID=<access-key>  AWS_SECRET_ACCESS_KEY=<secret-key> aws --no-verify-ssl --endpoint-url https://localhost:6443'`
6. Send S3 requests, for example: `s3-nc-user-1 s3api put-object --bucket shira-1003-bucket-1 --key hello.txt` (should work).
7. Rename the account (account update):
`sudo node src/cmd/manage_nsfs account update --name shira-1003 --new_name shira-1003-new`
8. See that the owner of the bucket was not changed (still with the previous name shira-1003)
`sudo node src/cmd/manage_nsfs bucket status --name shira-1003-bucket-1`
9. Send S3 request, for example: `s3-nc-user-1 s3api put-object --bucket shira-1003-bucket-1 --key hello.txt` (should work after the fix, before that it throws an error). Please make sure that you send the request after the `bucket_namespace_cache` is clear, else you would not be able to reproduce the initial issue).

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/cmd/nsfs.js [hunk 1]
```diff
@@ -206,6 +206,7 @@ class NsfsObjectSDK extends ObjectSDK {
             },
             system_owner: new SensitiveString('nsfs'),
             bucket_owner: new SensitiveString('nsfs'),
+            owner_account: new SensitiveString('nsfs-id'), // temp
```
Comment (naveenpaul1) [inline src/cmd/nsfs.js:209]: `owner_account` is failing to convey the actual value stored in this property. Can We have something like `bucket_owner_id`. WDYT?

Comment (shirady) [reply src/cmd/nsfs.js:209]: The change of `owner_account` was added after the change of the function `read_bucket_sdk_policy_info` in which I added the `owner_account` as a property of the returned object. The property `owner_account` is part of the NSFS bucket schema:
https://github.com/noobaa/noobaa-core/blob/426e7c79f33245c765a39a9ee0aaebc84e16f7cc/src/server/system_services/schemas/nsfs_bucket_schema.js#L22-L25

If you want to change the property name from `owner_account ` to `bucket_owner_id` it is something that we can do, but it is a schema change and should be in a separate PR, not related to this fix.

**Comment by naveenpaul1** [comment]
LGTM

**Review by naveenpaul1 — APPROVED** [review]

**Comment by romayalon** [comment]
@shirady why did you do `Before you start: Change the config.NSFS_CHECK_BUCKET_BOUNDARIES = false;` ? 
will this fix work without this change?

**Comment by shirady** [comment]
@romayalon I always change the config for running the s3 operation in NC NSFS, it should work the same.

**Comment by romayalon** [comment]
@shirady Why are you doing that?

**Comment by romayalon** [comment]
Thanks @shirady! please try to reproduce and open a bug if needed, we don't want to mask a bug by setting this config 👍🏻

**Comment by shirady** [comment]
> Thanks @shirady! please try to reproduce and open a bug if needed, we don't want to mask a bug by setting this config 👍🏻

@romayalon I opened the issue #8177.
