### PR TITLE
Handle BucketAlreadyOwnedByYou s3 error

### LINKED ISSUE #5980: Incorrect error returned if a user tries to recreate a bucket
### Environment info
- NooBaa Version: master
- Platform: minikube 1.1.1 

### Actual behavior
1. If a user tries to recreate a bucket which it already owns, Noobaa server throws "BucketAlreadyExists" error

### Expected behavior
1. But as per https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html, Noobaa server should return "BucketAlreadyOwnedByYou" error.

### Steps to reproduce
1. Create a bucket on Noobaa endpoint from a user
2. Now via the same user, try to recreate the bucket with same name
3. The operation fails with 'BucketAlreadyExists' error

### PR DESCRIPTION
**Pull request by soumyakoduri**
As per https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html,
in case a user tries to create a bucket which already exists
and owned by it, 'BucketAlreadyOwnedByYou' error should be returned
instead of 'BucketAlreadyExists'.

This patch is to address the same.

Signed-off-by: Soumya Koduri <skoduri@redhat.com>

### Explain the changes
While validating bucket during creation, match the owner too 

### Issues: Fixed #xxx / Gap #xxx
Fixed #5980 

### Testing Instructions:
1.  Create a user with RW permissions to the noobaa end point or user admin user itself
2. Create a bucket via that user
3. Now try to create the bucket with same name.
- if its the same user, "BucketAlreadyOwnedByYou" error should be returned and 
- if it is different user, "BucketAlreadyExists" error should be returned.

### CODE REVIEW

**Review by nimrod-becker — APPROVED** [review]

File: src/server/system_services/bucket_server.js [hunk 1]
```diff
@@ -1284,9 +1284,16 @@ function validate_bucket_creation(req) {
         !VALID_BUCKET_NAME_REGEXP.test(req.rpc_params.name.unwrap())) {
         throw new RpcError('INVALID_BUCKET_NAME');
     }
-    if (req.system.buckets_by_name && req.system.buckets_by_name[req.rpc_params.name.unwrap()]) {
-        throw new RpcError('BUCKET_ALREADY_EXISTS');
+    var bucket = req.system.buckets_by_name && req.system.buckets_by_name[req.rpc_params.name.unwrap()];
```
Comment (guymguym) [inline src/server/system_services/bucket_server.js:1287]: use `const bucket = ...`

File: src/server/system_services/bucket_server.js [hunk 2]
```diff
@@ -1284,9 +1284,16 @@ function validate_bucket_creation(req) {
...
+
+    if (bucket) {
+        if (bucket.owner_account._id === req.account._id) {
```
Comment (guymguym) [inline src/server/system_services/bucket_server.js:1290]: This comparison does not work for ObjectId type.
Need to compare the string value of it or use the `system_store.has_same_id()` function.

File: src/server/system_services/bucket_server.js [hunk 3]
```diff
@@ -1284,9 +1284,16 @@ function validate_bucket_creation(req) {
...
+            throw new RpcError('BUCKET_ALREADY_OWNED_BYYOU');
```
Comment (guymguym) [inline src/server/system_services/bucket_server.js:1291]:
```suggestion
            throw new RpcError('BUCKET_ALREADY_OWNED_BY_YOU');
```

File: src/endpoint/s3/s3_rest.js [hunk 4]
```diff
@@ -65,6 +65,7 @@ const RPC_ERRORS_TO_S3 = Object.freeze({
     INVALID_BUCKET_NAME: S3Error.InvalidBucketName,
     NOT_EMPTY: S3Error.BucketNotEmpty,
     BUCKET_ALREADY_EXISTS: S3Error.BucketAlreadyExists,
+    BUCKET_ALREADY_OWNED_BYYOU: S3Error.BucketAlreadyOwnedByYou,
```
Comment (guymguym) [inline src/endpoint/s3/s3_rest.js:68]:
```suggestion
    BUCKET_ALREADY_OWNED_BY_YOU: S3Error.BucketAlreadyOwnedByYou,
```

**Review by guymguym — CHANGES_REQUESTED** [review]
Thanks @soumyakoduri. 
See small comments, and also rebase from master is required.

**Comment by guymguym** [comment]
@soumyakoduri we better also add a small regression test for this case in here -
https://github.com/noobaa/noobaa-core/blob/c6e33a8aef9f547151ed8dae8e9008451be2216f/src/test/unit_tests/test_s3_ops.js#L47

If you need assistance to add it feel free to let us know.
@nimrod-becker can assign someone to suggest that test code.

File: src/server/system_services/bucket_server.js (hunk 1 above)
Comment (soumyakoduri) [reply src/server/system_services/bucket_server.js:1287]: done

File: src/server/system_services/bucket_server.js (hunk 2 above)
Comment (soumyakoduri) [reply src/server/system_services/bucket_server.js:1290]: have used system_store.has_same_id()

File: src/server/system_services/bucket_server.js (hunk 3 above)
Comment (soumyakoduri) [reply src/server/system_services/bucket_server.js:1291]: done.

File: src/endpoint/s3/s3_rest.js (hunk 4 above)
Comment (soumyakoduri) [reply src/endpoint/s3/s3_rest.js:68]: done

**Comment by soumyakoduri** [comment]
> @soumyakoduri we better also add a small regression test for this case in here -
> 
> https://github.com/noobaa/noobaa-core/blob/c6e33a8aef9f547151ed8dae8e9008451be2216f/src/test/unit_tests/test_s3_ops.js#L47
> 
> If you need assistance to add it feel free to let us know.
> @nimrod-becker can assign someone to suggest that test code.

Okay.. I will take a look and let you know in case need help. Thanks!

**Comment by soumyakoduri** [comment]
> @soumyakoduri we better also add a small regression test for this case in here -
> 
> https://github.com/noobaa/noobaa-core/blob/c6e33a8aef9f547151ed8dae8e9008451be2216f/src/test/unit_tests/test_s3_ops.js#L47
> 
> If you need assistance to add it feel free to let us know.
> @nimrod-becker can assign someone to suggest that test code.
@nimrod-becker @guymguym 
        mocha.it('should not recreate bucket', async function() {                    
           const res = await s3.createBucket({ Bucket: BKT1 }).promise();            
          assert(res.... == BucketAlreadyOwnedByYou);
        });

Please let me know if above simple case is good enough and how to retrieve the error code from result 'res'?

**Comment by guymguym** [comment]
> mocha.it('should not recreate bucket', async function() {
> const res = await s3.createBucket({ Bucket: BKT1 }).promise();
> assert(res.... == BucketAlreadyOwnedByYou);
> });
> 
> Please let me know if above simple case is good enough and how to retrieve the error code from result 'res'?

@soumyakoduri BTW this test uses the standard AWS JS SDK so online docs can help too.
In this case, after awaiting the promise, the error should be thrown as exception.
One way to assert for it is using https://nodejs.org/docs/latest-v12.x/api/assert.html#assert_assert_rejects_asyncfn_error_message.

So you can write something like this:

```javascript
mocha.it('should not recreate bucket', async function() {
    const func = async () => s3.createBucket({ Bucket: BKT1 }).promise();
    const expected_err_props = {
        name: 'BucketAlreadyOwnedByYou',
        code: 'BucketAlreadyOwnedByYou',
        statusCode: 409,
    };
    await assert.rejects(func, expected_err_props);
});
```

**Comment by guymguym** [comment]
@soumyakoduri You can run it manually with:
```
mocha src/test/unit_tests/test_s3_ops.js -g "should not recreate bucket"
```

But not sure if you have the repo setup for development.
In any case I'll approve once the test is pushed and passes the CI runs.
Thanks

**Comment by guymguym** [comment]
@soumyakoduri In addition, can you remove that test case from the ceph/s3-tests blacklist to make the CI run the `test_bucket_create_exists` case too:

https://github.com/noobaa/noobaa-core/blob/c6e33a8aef9f547151ed8dae8e9008451be2216f/src/test/system_tests/test_ceph_s3.js#L242

**Comment by soumyakoduri** [comment]
> 
> @soumyakoduri BTW this test uses the standard AWS JS SDK so online docs can help too.
> In this case, after awaiting the promise, the error should be thrown as exception.
> One way to assert for it is using https://nodejs.org/docs/latest-v12.x/api/assert.html#assert_assert_rejects_asyncfn_error_message.
> 
> So you can write something like this:
> 
> ```js
> mocha.it('should not recreate bucket', async function() {
>     const func = async () => s3.createBucket({ Bucket: BKT1 }).promise();
>     const expected_err_props = {
>         name: 'BucketAlreadyOwnedByYou',
>         code: 'BucketAlreadyOwnedByYou',
>         statusCode: 409,
>     };
>     await assert.rejects(func, expected_err_props);
> });
> ```

Thanks.. Added this case.

**Comment by soumyakoduri** [comment]
> @soumyakoduri In addition, can you remove that test case from the ceph/s3-tests blacklist to make the CI run the `test_bucket_create_exists` case too:
> 
> https://github.com/noobaa/noobaa-core/blob/c6e33a8aef9f547151ed8dae8e9008451be2216f/src/test/system_tests/test_ceph_s3.js#L242

Done.

> @soumyakoduri You can run it manually with:
> 
> ```
> mocha src/test/unit_tests/test_s3_ops.js -g "should not recreate bucket"
> ```
> 
> But not sure if you have the repo setup for development.
> In any case I'll approve once the test is pushed and passes the CI runs.
> Thanks

I do not have development environment installed as am still facing issues with 'npm install' errors. Right now I have been testing changes by building docker image and deploying it. I have uploaded the changes to check for CI runs

**Comment by guymguym** [comment]
@soumyakoduri You can also run tests locally in docker simply with `make test` which will build a tested image with all the needed environment and run it.

**Comment by guymguym** [comment]
@nimrod-becker @liranmauda Seems like CI completed in 19 minutes - is that about right?

**Review by guymguym — APPROVED** [review]
Looks good. 
Just ceph/s3-tests were not run as part of CI...
@nimrod-becker - merge when you're ready...

**Comment by soumyakoduri** [comment]
> @soumyakoduri You can also run tests locally in docker simply with `make test` which will build a tested image with all the needed environment and run it.

okay thanks.. I will try this out.

**Comment by nimrod-becker** [comment]
@guymguym yes we have issues running them on travis, merging
