### PR TITLE
Fix lifecycle deleting in minutes instead of days

### LINKED ISSUE #6818: Files are deleted from the bucket regardless of the expiration rule defined on the lifecycle configuration
### Environment info
- NooBaa Version: 5.7.0
- Platform: OpenShift 4

### Actual behavior
1. I'm trying to set a lifecycle configuration on my bucket so objects older than 4 days will be expired (deleted).
Thing is that, for some reason, ~30 minutes after setting that cleanup rule all the files in the bucket are deleted, regardless of their creation date.

### Expected behavior
1. Only files that are older than 4 days should be deleted

### Steps to reproduce
1. Existing S3 bucket with existing files. some of the files were uploaded to the bucket more that 4 days ago, some of the files were uploaded to the bucket less than 4 days ago.
2. Call PutBucketLifecycleConfiguration REST API to set a cleanup rule that expires the files after 4 days.
3. Actual - ~30 minutes after that REST call, ALL the files are deleted from the bucket.

### More information - Screenshots / Logs / Other output
The payload used to setup the lifecycle configuration:

`<LifecycleConfiguration>
    <Rule>
        <ID>ExpirationRule</ID>
        <Prefix></Prefix>
        <Status>Enabled</Status>
        <Expiration>
            <Days>4</Days>
        </Expiration>
    </Rule>
</LifecycleConfiguration>`

### PR DESCRIPTION
**Pull request by liranmauda**
### Explain the changes
- Fix lifecycle deleting in minutes instead of days
- Async/await lifecycle

Signed-off-by: liranmauda <liran.mauda@gmail.com>

### Issues: Fixed #xxx / Gap #xxx
1. Fixes: #6818

### CODE REVIEW

File: src/server/bg_services/lifecycle.js [hunk 1]
```diff
@@ -16,80 +16,67 @@ var LIFECYCLE = {
...
-                                'status:', lifecycle_rule.status, 'last_sync',
-                                Math.floor((now - lifecycle_rule.last_sync) / 1000 / 60), 'min ago.');
+    if (!system) return;
+    try {
+        dbg.log0('LIFECYCLE READ BUCKETS configuration: BEGIN');
+        await system_store.refresh();
+        for (const bucket of system_store.data.buckets) {
+            if (!bucket.lifecycle_configuration_rules || bucket.deleting) return;
+
+            P.all(_.map(bucket.lifecycle_configuration_rules, async function(lifecycle_rule, j) {
```
Comment (dannyzaken) [inline src/server/bg_services/lifecycle.js:28]: check if this has to be in the background or we should wait for it.

also maybe change to arrow function 
```suggestion
            P.all(_.map(bucket.lifecycle_configuration_rules, async (lifecycle_rule, j) => {
```

**Review by dannyzaken — APPROVED** [review]
