### PR TITLE
Fix s3_get_bucket_policy_status

### LINKED ISSUE #7924: NSFS | NC | get-bucket-policy-status fails with internal error (TypeError: policy.statement is not iterable)
### Environment info
- NooBaa Version: **5.15.0**
- Platform: **RHEL8**

### Actual behavior
1. get-bucket-policy works, but get-bucket-policy-status fails with internal error:

```sh
$ aws s3api --endpoint http://localhost:80 get-bucket-policy --bucket bucket1                                                                              
{
    "Policy": "{\"Statement\":[{\"Sid\":\"AllowEveryoneReadOnlyAccess\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":[\"s3:GetObject\",\"s3:ListBucket\"],\"Resource\":[\"arn:aws:s3:::bucket1\",\"arn:aws:s3:::bucket1/*\"]}]}"
}

$ aws s3api --endpoint http://localhost:80 get-bucket-policy-status --bucket bucket1                                                                       

An error occurred (InternalError) when calling the GetBucketPolicyStatus operation (reached max retries: 4): We encountered an internal error. Please try again.  
```

From the log:
```js
2024-03-07T15:50:13.684579+09:00 server node[1833210]: [nsfs/1833210]    [L0] core.sdk.bucketspace_fs:: BucketSpaceFS.read_bucket_sdk_info: bucket_config_path /gpfs/nsfs/buckets/bucket1.json
2024-03-07T15:50:13.685137+09:00 server node[1833210]: [nsfs/1833210]    [L0] core.sdk.bucketspace_fs:: BucketSpaceFS.read_bucket_sdk_info: bucket_config_path /gpfs/nsfs/buckets/bucket1.json
2024-03-07T15:50:13.687272+09:00 server node[1833210]: [nsfs/1833210]    [L1] core.sdk.object_sdk:: validate_non_nsfs_bucket:  
  { 
    name: SENSITIVE-5cfd9f24ccdd38e2, 
    email: SENSITIVE-5cfd9f24ccdd38e2, 
    creation_date: '2024-03-06T03:38:40.902Z', 
    access_keys: [ { access_key: SENSITIVE-2ca9fc5184acac2a, secret_key: SENSITIVE-1c41343d78549359 } ], 
    nsfs_account_config: { uid: 0, gid: 10, new_buckets_path: '/gpfs/bucket-root', fs_backend: 'GPFS' }, 
    allow_bucket_creation: true, 
    _id: '65e7e540e397b951176d4055' 
  } { fs_root_path: '', fs_backend: 'GPFS' }
2024-03-07T15:50:13.687881+09:00 server node[1833210]: [nsfs/1833210]    [L1] core.endpoint.s3.s3_rest:: S3 REQUEST GET /bucket1?policyStatus op get_bucket_policy_status request_id ltgvbupc-dgo0b9-iz1 
  { 
    host: 'localhost', 
    'accept-encoding': 'identity', 
    'user-agent': 'aws-cli/1.23.2 Python/3.6.8 Linux/4.18.0-477.27.1.el8_8.x86_64 botocore/1.23.46', 
    'x-amz-date': '20240307T065013Z', 
    'x-amz-content-sha256': '...', 
    authorization: 'AWS4-HMAC-SHA256 ...' 
  }
2024-03-07T15:50:13.688515+09:00 server node[1833210]: [nsfs/1833210]    [L0] core.sdk.bucketspace_fs:: BucketSpaceFS.get_bucket_policy: Bucket name bucket1
2024-03-07T15:50:13.689263+09:00 server node[1833210]: [nsfs/1833210]    [L0] core.sdk.bucketspace_fs:: BucketSpaceFS.get_bucket_policy: policy 
  {  
    Statement: [ { 
      Sid: 'AllowEveryoneReadOnlyAccess', 
      Effect: 'Allow', 
      Principal: '*', 
      Action: [ 's3:GetObject', 's3:ListBucket' ], 
      Resource: [ 'arn:aws:s3:::bucket1', 'arn:aws:s3:::bucket1/*' ] 
    } ]
  }
2024-03-07T15:50:13.689969+09:00 server node[1833210]: [nsfs/1833210] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR 
  <?xml version="1.0" encoding="UTF-8"?>
  <Error>
    <Code>InternalError</Code>
    <Message>We encountered an internal error. Please try again.</Message>
    <Resource>/bucket1?policyStatus</Resource>
    <RequestId>ltgvbupc-dgo0b9-iz1</RequestId>
  </Error> 
  GET /bucket1?policyStatus {
    "host":"localhost",
    "accept-encoding":"identity",
    "user-agent":"aws-cli/1.23.2 Python/3.6.8 Linux/4.18.0-477.27.1.el8_8.x86_64 botocore/1.23.46",
    "x-amz-date":"20240307T065013Z",
    "x-amz-content-sha256":"...",
    "authorization":"...
  } 
  TypeError: policy.statement is not iterable
    at _is_policy_public (/usr/local/noobaa-core/src/endpoint/s3/ops/s3_get_bucket_policy_status.js:19:36)
    at Object.get_bucket_policy_status [as handler] (/usr/local/noobaa-core/src/endpoint/s3/ops/s3_get_bucket_policy_status.js:12:23)
    at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:150:19)
    at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:65:9)

```

### Expected behavior
1. The output should be like below.

{
    "PolicyStatus": {
        "IsPublic": false
    }
}

### Steps to reproduce
1. See above

### PR DESCRIPTION
**Pull request by nadavMiz**
### Explain the changes
1. change s3_get_bucket_policy_status to work with the new bucket policy schema
2. change the function to comply more closely with [public policy definition](https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html#access-control-block-public-access-policy-status) by:
- removing resource check since it's not validated for public policy
- always return true for Principal: '*'
3. added unit tests

### Issues: Fixed #xxx / Gap #xxx
1. Fixes: https://github.com/noobaa/noobaa-core/issues/7924

### Testing Instructions:
1. run `make run-single-test-postgres testname=test_s3_bucket_policy.js`

- [ ] Doc added/updated
- [x] Tests added

### CODE REVIEW

File: src/endpoint/s3/ops/s3_get_bucket_policy_status.js [hunk 1]
```diff
@@ -16,27 +17,17 @@ async function get_bucket_policy_status(req) {
...
-                principal_wildcard = true;
-            }
-        }
-        for (const resource of statement.resource) {
-            if ((/[?*]/).test(resource)) {
-                resource_wildcard = true;
+    for (const statement of policy.Statement) {
+        if (statement.Effect === 'Allow' && statement.Principal) {
+            const statement_principal = statement.Principal.AWS ? statement.Principal.AWS : statement.Principal;
+            for (const principal of _.flatten([statement_principal])) {
```
Comment (jackyalbo) [inline src/endpoint/s3/ops/s3_get_bucket_policy_status.js:23]: is this something possible? that we will have more than one principle, and one of them be '*' (seems redundant no?)

File: src/endpoint/s3/ops/s3_get_bucket_policy_status.js [hunk 2]
```diff
@@ -16,27 +17,17 @@ async function get_bucket_policy_status(req) {
...
-        let resource_wildcard = false;
-        if (statement.effect === 'deny') {
-            return false;
-        }
-        for (const principal of statement.principal) {
-            if (principal.unwrap() === '*') {
-                principal_wildcard = true;
-            }
-        }
-        for (const resource of statement.resource) {
```
Comment (jackyalbo) [inline src/endpoint/s3/ops/s3_get_bucket_policy_status.js:30]: is this something you checked with AWS? because in all the examples they have the resource is *

File: src/endpoint/s3/ops/s3_get_bucket_policy_status.js (hunk 1 above)
Comment (nadavMiz) [reply src/endpoint/s3/ops/s3_get_bucket_policy_status.js:23]: it is redundant but possible both in our code and AWS. In AWS if at least one of the principles is * it counts as public policy. so we might as well do the same

File: src/endpoint/s3/ops/s3_get_bucket_policy_status.js (hunk 2 above)
Comment (nadavMiz) [reply src/endpoint/s3/ops/s3_get_bucket_policy_status.js:30]: yes, I checked it. when adding a policy with specific principles and resources with a wildcard it returns 'false' for this function. it did return true for specific resource and wildcard principals. Also looking at the definition of public it doesn't seem to list resources as one of the things evaluated for public policy. I am not sure why in their examples the resource is always *

**Review by jackyalbo — APPROVED** [review]
