### PR TITLE
NC | NSFS | Fix Bug | Head Object on a Tagged Object Does Not Return `x-amz-tagging-count` Header

### LINKED ISSUE #8353: NSFS | S3 | Versioning: HeadObject on tagged object in version-enabled bucket does not return x-amz-tagging-count
### Environment info
- NooBaa Version: **5.15.4**
- Platform: **CentOS 8, deployed using [https://github.com/IBM/StorageScaleVagrant](https://github.com/IBM/StorageScaleVagrant)**

### Actual behavior

When performing a HeadObject operation on an object with multiple versions that got tagged (without versionId), there is no `x-amz-tagging-count` entry in the HTTP response headers:

```
        response = client.head_object(Bucket=bucket_name, Key=key)
        assert response['ResponseMetadata']['HTTPStatusCode'] == 200
>       assert response['ResponseMetadata']['HTTPHeaders']['x-amz-tagging-count'] == str(count)
E       KeyError: 'x-amz-tagging-count'
```

### Expected behavior

The HeadObject HTTP response header returns `x-amz-tagging-count` with a value of 1.

### Steps to reproduce

Execute the following extension code for Ceph s3-tests:

```
    @pytest.mark.versioning
    def test_s3cever12():
        client = get_client()
        bucket_name = get_new_bucket(client=client)
    
        # The following operation uses another client instance -> following operations will fail
    #    check_configure_versioning_retry(bucket_name, "Enabled", "Enabled")
        _ces_safe_check_configure_versioning_retry(client, bucket_name, "Enabled", "Enabled")
    
        key = "test"
        version_ids = []
        contents = []
        num_versions = 3
        (version_ids, contents) = create_multiple_versions(client, bucket_name, key, num_versions)
    
        response = client.list_object_versions(Bucket=bucket_name)
        assert len(response['Versions']) == 3
    
        count = 1
        tagset = _create_simple_tagset(count)
        client.put_object_tagging(Bucket=bucket_name, Key=key, Tagging=tagset)
    
        response = client.head_object(Bucket=bucket_name, Key=key)
        print(response)
        assert response['ResponseMetadata']['HTTPStatusCode'] == 200
        assert response['ResponseMetadata']['HTTPHeaders']['x-amz-tagging-count'] == str(count)
```

### More information - Screenshots / Logs / Other output

Complete response metadata:

```
{'ResponseMetadata': {'RequestId': 'm0xz10l6-42drw2-7nf', 'HostId': 'm0xz10l6-42drw2-7nf', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-request-id': 'm0xz10l6-42drw2-7nf', 'x-amz-id-2': 'm0xz10l6-42drw2-7nf', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'true', 'access-control-allow-methods': 'GET,POST,PUT,DELETE,OPTIONS', 'access-control-allow-headers': 'Content-Type,Content-MD5,Authorization,X-Amz-User-Agent,X-Amz-Date,ETag,X-Amz-Content-Sha256,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'ETag,X-Amz-Version-Id', 'etag': '"mtime-d43j9qlyz9j4-ino-f0j"', 'last-modified': 'Wed, 11 Sep 2024 14:43:47 GMT', 'content-type': 'application/octet-stream', 'content-length': '9', 'accept-ranges': 'bytes', 'x-amz-version-id': 'mtime-d43j9qlyz9j4-ino-f0j', 'date': 'Wed, 11 Sep 2024 14:43:47 GMT', 'connection': 'keep-alive', 'keep-alive': 'timeout=5'}, 'RetryAttempts': 0}, 'AcceptRanges': 'bytes', 'LastModified': datetime.datetime(2024, 9, 11, 14, 43, 47, tzinfo=tzutc()), 'ContentLength': 9, 'ETag': '"mtime-d43j9qlyz9j4-ino-f0j"', 'VersionId': 'mtime-d43j9qlyz9j4-ino-f0j', 'ContentType': 'application/octet-stream', 'Metadata': {}}
```

Logs with "all" log level:
[noobaa_20240911_3.log.gz](https://github.com/user-attachments/files/16965417/noobaa_20240911_3.log.gz)

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. In `namespace_fs` return  `tag_count` which is the sum of all the extended attribute that has the prefix `user.noobaa.tag.`.
2. Rename `XATTR_NOOBAA_CUSTOM_PREFIX` to `XATTR_TAG` and move the variable declaration to a lower place in the variable declaration list.

### Issues: Fixed #8353
1. Currently, in `namespace_fs` we always return `tag_count: 0`, therefore the client would not receive the `x-amz-tagging-count` header.

#### Automatic Test
Please run: `s3tests_boto3/functional/test_s3.py::test_get_obj_head_tagging` in NC deployment.

#### Manual Test
1. Create an account with the CLI: `sudo node src/cmd/manage_nsfs account add --name <account-name> --new_buckets_path /tmp/nsfs_root1 --access_key <access-key> --secret_key <secret-key> --uid <uid> --gid <gid>`
Note: before creating the account need to give permission to the `new_buckets_path`: `chmod 777 /tmp/nsfs_root1`, `chmod 777 /tmp/nsfs_root1`.
3. Start the NSFS server with: `sudo node src/cmd/nsfs --debug 5`
Notes: 
- I Change the `config.NSFS_CHECK_BUCKET_BOUNDARIES = false; //SDSD` because I’m using the `/tmp/` and not `/private/tmp/`.
4. Create the alias for S3 service:`alias nc-user-1-s3=‘AWS_ACCESS_KEY_ID=<access-key> AWS_SECRET_ACCESS_KEY=<secret-key> aws --no-verify-ssl --endpoint-url https://localhost:6443’`.
5. Check the connection to the endpoint and try to list the buckets (should be empty): `nc-user-1-s3 s3 ls; echo $?`
6. Add bucket to the account using AWS CLI: `nc-user-1-s3 s3 mb s3://bucket-1` (`bucket-1` is the bucket name in this example)
7. Put an object: `nc-user-1-s3 s3api put-object --bucket bucket-1 --key hello.txt`
8. Put object-tagging: `nc-user-1-s3 s3api put-object-tagging --tagging '{"TagSet": [{ "Key": "designation", "Value": "confidential" }, { "Key": "department", "Value": "finance" }, { "Key": "team", "Value": "payroll" } ]}' --bucket bucket-1 --key hello.txt` (in this example there are 3 added tags).
9. Head the object: `nc-user-1-s3 s3api get-object --bucket bucket-1 --key hello.txt --debug` (use the `debug` flag to validate the header of `x-amz-tagging-count, expected to see 3).

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/sdk/namespace_fs.js [hunk 1]
```diff
@@ -2315,6 +2315,10 @@ class NamespaceFS {
         return xattr[XATTR_MD5_KEY];
     }
 
+    _number_of_tags_fs_xttr(xattr) {
+        return Object.keys(xattr).filter(xattr_key => xattr_key.includes(XATTR_NOOBAA_CUSTOM_PREFIX)).length;
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:2319]: Can you rename XATTR_NOOBAA_CUSTOM_PREFIX to a name that includes TAG? I find it a very confusing name

**Review by romayalon — APPROVED** [review]

File: src/sdk/namespace_fs.js (hunk 1 above)
Comment (shirady) [reply src/sdk/namespace_fs.js:2319]: Do you mean rename `XATTR_NOOBAA_CUSTOM_PREFIX` to `XATTR_NOOBAA_CUSTOM_PREFIX_TAG`?

Comment (romayalon) [reply src/sdk/namespace_fs.js]: maybe XATTR_TAG, similar to the other xattrs
