### PR TITLE
Fixing dir streaming and issue 6558

### LINKED ISSUE #6558: Endpoint crashed on listing max objects - 100K, "JavaScript heap out of memory"
### Environment info
- NooBaa Version: master-20210607
- Platform: OCP 4.6.16

### Actual behavior
1. Listing of 100K objects from app-server causes pod restart. Error in the endpoint log

### Expected behavior
1. Listing of 100K objects should work well. Endpoint crash should not come

### Steps to reproduce
1. Uploaded 100K objects on bucket-11
2. Listing them causes endpoint crash

```
An error occurred (503) when calling the ListObjectsV2 operation (reached max retries: 2): Service Unavailable
99000
[root@hpo-node1 ~]# s3u1 ls s3://bucket-11 --recursive |wc -l
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

An error occurred (503) when calling the ListObjectsV2 operation (reached max retries: 2): Service Unavailable
5000
```

From endpoint log:
```

Jun-8 5:43:38.931 [Endpoint/9]   [LOG] CONSOLE:: NamespaceFS: buffers_pool BuffersPool {
  buf_size: 8388608,
  buffers: [],
  sem: Semaphore { _initial: 536870912, _value: 536870912, _waiting_value: 0, _wq: WaitQueue { _name: '_wq_', _q: <ref *1> LinkedList { next: '_lln_', prev: '_llp_', head: '_llh_', length: 0, _lln_: [Circular *1], _llp_: [Circular *1], _llh_: [Circular *1] } } }
}
Jun-8 5:44:25.394 [Endpoint/9]    [L0] core.server.system_services.system_store:: SystemStore.load: Got load request with a timestamp older then my last update time

<--- Last few GCs --->

[9:0x4cc5f40]  1009804 ms: Scavenge (reduce) 1010.1 (1023.2) -> 1010.2 (1026.4) MB, 74.1 / 0.0 ms  (average mu = 0.176, current mu = 0.161) allocation failure 
[9:0x4cc5f40]  1009829 ms: Scavenge (reduce) 1011.1 (1030.9) -> 1011.1 (1032.2) MB, 9.8 / 0.0 ms  (average mu = 0.176, current mu = 0.161) allocation failure 
[9:0x4cc5f40]  1009857 ms: Scavenge (reduce) 1012.3 (1025.4) -> 1012.3 (1028.4) MB, 9.9 / 0.0 ms  (average mu = 0.176, current mu = 0.161) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa04200 node::Abort() [node]
 2: 0x94e4e9 node::FatalError(char const*, char const*) [node]
 3: 0xb7978e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb79b07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd34395  [node]
 6: 0xd34f1f  [node]
 7: 0xd42fab v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xd46b6c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xd162c2 v8::internal::Factory::AllocateRawWithAllocationSite(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationType, v8::internal::Handle<v8::internal::AllocationSite>) [node]
10: 0xd16378 v8::internal::Factory::NewJSObjectFromMap(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationType, v8::internal::Handle<v8::internal::AllocationSite>) [node]
11: 0xb912b8 v8::Object::New(v8::Isolate*) [node]
12: 0x9bc4d0 napi_create_object [node]
13: 0x7f964153806d noobaa::Readdir::OnOK() [/root/node_modules/noobaa-core/build/Release/nb_native.node]
14: 0x7f964151cc6e Napi::AsyncWorker::OnAsyncWorkComplete(napi_env__*, napi_status, void*) [/root/node_modules/noobaa-core/build/Release/nb_native.node]
15: 0x9d83e9 node::ThreadPoolWork::ScheduleWork()::{lambda(uv_work_s*, int)#2}::_FUN(uv_work_s*, int) [node]
16: 0x137750d  [node]
17: 0x137bb06  [node]
18: 0x138e5e5  [node]
19: 0x137c438 uv_run [node]
20: 0xa44974 node::NodeMainInstance::Run() [node]
21: 0x9d1e15 node::Start(int, char**) [node]
22: 0x7f96441cd7b3 __libc_start_main [/lib64/libc.so.6]
23: 0x9694cc  [node]
/noobaa_init_files/noobaa_init.sh: line 74:     9 Aborted                 $*




######################################################################
Tue Jun  8 05:44:37 UTC 2021 NooBaa: Process exited RIP (RC=134)
######################################################################


```
### More information - Screenshots / Logs / Other output
Uploading noobaa diagnose

### PR DESCRIPTION
**Pull request by jackyalbo**
Signed-off-by: jackyalbo <jacky.albo@gmail.com>

### Explain the changes
1. Fixing issue 6558 - The cache wasn't working so we keep on adding more and more dir list to the cache until we ran out of memory - it was because we used the whole object as the key - which doesn't work. Changed to fs_dir + uid + gid - I hope it's good enough please let me know if we need other variables as well.
2. A quick fix for a huge directories. When I tried with 100K objects I got to 3 MB cache - So to get to 64 MB I guess we will need 2M. Tried with 100K with NSFS_DIR_CACHE_MAX_DIR_SIZE set to 1MB - very slow but does work (~4.5 minutes for 100K. with caching ~31 seconds). Scanning 1M objects 100K times(for each default 1K objects) will probably take ages.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #6558

### Testing Instructions:
1.

### CODE REVIEW

**Comment by jackyalbo** [comment]
Please read the explanation before reviewing - I do need your feedback on the decisions I made. Thanks

File: src/sdk/namespace_fs.js [hunk 1]
```diff
@@ -82,6 +82,7 @@ function make_named_dirent(name) {
  */
 const dir_cache = new LRUCache({
     name: 'nsfs-dir-cache',
+    make_key: ({ dir_path, fs_account_config }) => dir_path + fs_account_config.uid + fs_account_config.gid,
```
Comment (guymguym) [inline src/sdk/namespace_fs.js:85]: I think we don't want the uid and gid in the cache key.
Just the path.

Comment (jackyalbo) [reply src/sdk/namespace_fs.js:85]: @guymguym throwing this to the mix:
https://issues.redhat.com/browse/MCGI-48
Not sure how bad was the validation issue @romayalon was seeing. I guess that with uid gid -  validation won't fail as much -  But It can create a lot of cache keys for the same directory.

Comment (jackyalbo) [reply src/sdk/namespace_fs.js]: ok after a call with @romayalon and follwing the discussion you had about MCGI-48 removing the uid and gid

**Comment by guymguym** [comment]
You can make very long file names - that will increase the size of the dir in cache with lower number of entries.

File: src/native/fs/fs_napi.cpp [hunk 2]
```diff
@@ -919,8 +918,8 @@ struct DirReadEntry : public FSWrapWorker<DirWrap>
                 } else {
                     _eof = true;
                 }
-                break;
             }
+            break;
```
Comment (guymguym) [inline src/native/fs/fs_napi.cpp:922]: since this loop is only needed for the . and .. cases, how about we try to change it a bit like this:

```cpp
        struct dirent* e = 0;

        // loop to skip parent and current directories
        do {
            // need to set errno before the call to readdir() to detect between EOF and error
            errno = 0;
            e = readdir(dir);
        } while (e && (strcmp(e->d_name, ".") == 0 || strcmp(e->d_name, "..") == 0));

        if (e) {
            _entry.name = std::string(e->d_name);
            _entry.ino = e->d_ino;
            _entry.type = e->d_type;
        } else {
            if (errno) {
                SetSyscallError();
            } else {
                _eof = true;
            }
        }
```

File: src/sdk/namespace_fs.js [hunk 3]
```diff
@@ -82,6 +82,7 @@ function make_named_dirent(name) {
  */
 const dir_cache = new LRUCache({
     name: 'nsfs-dir-cache',
+    make_key: ({ dir_path, fs_account_config }) => dir_path,
```
Comment (guymguym) [inline src/sdk/namespace_fs.js:85]:
```suggestion
    make_key: ({ dir_path }) => dir_path,
```

**Review by guymguym — APPROVED** [review]
looks good. made two small suggestions.

File: src/native/fs/fs_napi.cpp (hunk 2 above)
Comment (jackyalbo) [reply src/native/fs/fs_napi.cpp:922]: was thinking about do while :) sure will use that

Comment (guymguym) [reply src/native/fs/fs_napi.cpp]: there are so little cases where do-while really helps that if you find one you have to use it :)
