### PR TITLE
Change loopback address to support IPv6

### LINKED ISSUE #5352: Support IPv6-only addresses
### Environment info
- Version: **3.0**
- Deployment: **NA**
- Customer: **NA**

### Actual behavior
1. Currently our code uses loopback address `127.0.0.1`.
2. This will not work on IPv6-only hosts.

### Expected behavior
1. Change to use `::1` or `localhost` instead.

### Steps to reproduce
1. NA

### PR DESCRIPTION
**Pull request by liranmauda**
### Explain the changes
Change loopback address to support IPv6:
- Change loopback address from 127.0.0.1 to localhost
- Add `net_utils.is_localhost(address)`

Fixes: #5352

Signed-off-by: liranmauda <liran.mauda@gmail.com>

### CODE REVIEW

**Comment by nimrod-becker** [comment]
are all the places we handle IPs (mostly nodes I guess, maybe endpoints as well) are handling both v4 and v6 ?

**Comment by liranmauda** [comment]
> are all the places we handle IPs (mostly nodes I guess, maybe endpoints as well) are handling both v4 and v6 ?

We changed all the 127.0.0.1 to localhost which is agnostic to ipv4 or ipv6:
```
[root@97436135fcf8 /]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
[root@97436135fcf8 /]# cat /etc/host
cat: /etc/host: No such file or directory
[root@97436135fcf8 /]# cat /etc/host
host.conf  hostname   hosts

[root@97436135fcf8 /]# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	97436135fcf8
```

File: src/server/node_services/nodes_monitor.js [hunk 1]
```diff
@@ -3625,7 +3625,7 @@ function progress_by_time(time, now) {
 
 function is_localhost(address) {
     let addr_url = url.parse(address);
-    return addr_url.hostname === '127.0.0.1' || addr_url.hostname.toLowerCase() === 'localhost';
+    return addr_url.hostname === 'localhost' || addr_url.hostname.toLowerCase() === 'localhost';
```
Comment (guymguym) [inline src/server/node_services/nodes_monitor.js:3628]: I tthink you want to keep this as before

File: src/server/system_services/cluster_server.js [hunk 2]
```diff
@@ -135,7 +135,7 @@ function pre_add_member_to_cluster(req) {
                 dbg.log0('updating adding server ip in db');
                 let shard_idx = cutil.find_shard_index(req.rpc_params.shard);
                 let server_idx = _.findIndex(topology.shards[shard_idx].servers,
-                    server => server.address === '127.0.0.1');
+                    server => server.address === 'localhost');
```
Comment (guymguym) [inline src/server/system_services/cluster_server.js:138]: I think we need a `net_utils.is_localhost(address)` to check both 127.0.0.1 or localhost or ::1
because in these cases where we check we probably want to accept all options.

File: src/server/node_services/nodes_monitor.js (hunk 1 above)
Comment (guymguym) [reply src/server/node_services/nodes_monitor.js:3628]: or switch to `net_utils.is_localhost(addr_url.hostname)` as suggested below

File: src/tools/http_speed.go [hunk 3]
```diff
@@ -171,7 +171,7 @@ func GenerateCert() tls.Certificate {
 		BasicConstraintsValid: true,
 		KeyUsage:              x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
 		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
-		IPAddresses:           []net.IP{net.ParseIP("127.0.0.1")},
+		IPAddresses:           []net.IP{net.ParseIP("localhost")},
```
Comment (guymguym) [inline src/tools/http_speed.go:174]: I don't think this will work

File: src/tools/tcp_speed.go [hunk 4]
```diff
@@ -173,7 +173,7 @@ func GenerateCert() tls.Certificate {
 		BasicConstraintsValid: true,
 		KeyUsage:              x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
 		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
-		IPAddresses:           []net.IP{net.ParseIP("127.0.0.1")},
+		IPAddresses:           []net.IP{net.ParseIP("localhost")},
```
Comment (guymguym) [inline src/tools/tcp_speed.go:176]: I don't think this will work

**Review by guymguym — CHANGES_REQUESTED** [review]
I think you need to separate between checks for localhost which should accept several options as I commented above, and setting a default localhost address, and be careful not to send it to configs that expect a real IP.

**Review by dannyzaken — APPROVED** [review]

File: src/server/utils/clustering_utils.js [hunk 5]
```diff
@@ -181,7 +181,7 @@ function get_cluster_info() {
             version: version,
             hostname: hostname,
             secret: cinfo.owner_secret,
-            addresses: cinfo.owner_address === '127.0.0.1' ? os_utils.get_local_ipv4_ips() : [cinfo.owner_address].concat(os_utils.get_local_ipv4_ips()),
+            addresses: cinfo.owner_address === 'localhost' ? os_utils.get_local_ipv4_ips() : [cinfo.owner_address].concat(os_utils.get_local_ipv4_ips()),
```
Comment (guymguym) [inline src/server/utils/clustering_utils.js:184]: Why not net_utils.is_localhost here?

File: src/util/net_utils.js [hunk 6]
```diff
@@ -77,6 +77,16 @@ function is_fqdn(target) {
     return false;
 }
 
+function is_localhost(address) {
```
Comment (guymguym) [inline src/util/net_utils.js:80]:
```suggestion
/**
 * @param {string} address
 * @returns {boolean}
 */
function is_localhost(address) {
```

File: src/util/net_utils.js [hunk 7]
```diff
@@ -77,6 +77,16 @@ function is_fqdn(target) {
...
+    if (address === '127.0.0.1' || address === 'localhost' || address === '::1') {
+        return true;
+    } else if (address.toLowerCase() === 'localhost') { //same as there were in node_monitor
+        return true;
+    }
+
+    return false;
```
Comment (guymguym) [inline src/util/net_utils.js:87]:
```suggestion
    return (
        address === '127.0.0.1' ||
        address === '::1' ||
        address.toLowerCase() === 'localhost'
    );
```

**Review by guymguym — APPROVED** [review]
Minor suggestions
