### PR TITLE
[NC | NSFS | Glacier] handle `ENOENT` in `_finalize_restore` and fix glacier tests not running

### LINKED ISSUE #8251: NSFS | NC | GLACIER restore flow needs to handle `ENOENT`
### Environment info
- NooBaa Version: **master**
- Platform: **DBS3**

### Actual behavior
If `finalize_restore` fails because of `ENOENT` due to any reason including an object getting deleted after a restore request is submitted. This will force NooBaa to retry the restore over and over again.

### Expected behavior
NooBaa must handle `ENOENT` cases in it's restore flow.

### PR DESCRIPTION
**Pull request by tangledbytes**
### Explain the changes
This PR simply adds the handler in `_finalize_restore` to make sure that it doesn't errors out if encounters `ENOENT`.

Fixes #8251

### Testing Instructions:
1. `./node_modules/.bin/mocha src/test/unit_tests/test_nsfs_glacier_backend.js`

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/sdk/nsfs_glacier_backend/tapecloud.js [hunk 1]
```diff
@@ -396,6 +396,13 @@ class TapeCloudGlacierBackend extends GlacierBackend {
 
             await fh.replacexattr(fs_context, undefined, GlacierBackend.XATTR_RESTORE_REQUEST);
         } catch (error) {
+            // restore does check if a file exist or not before triggering eeadm call but the file could get deleted
+            // after `restore` performs that check so check it here once again
+            if (error.code === 'ENOENT') {
+                dbg.warn(`TapeCloudGlacierBackend._finalize_restore: log entry unexpectedly not found: ${entry.path}`);
+                return;
+            }
```
Comment (guymguym) [inline src/sdk/nsfs_glacier_backend/tapecloud.js:404]: it would be better if this was in a separate try-catch which is only on the open() call, to make sure we don't add any other fs calls in the flow that would be interpreted as missing file accidentally

**Review by guymguym — CHANGES_REQUESTED** [review]

File: src/sdk/nsfs_glacier_backend/tapecloud.js (hunk 1 above)
Comment (tangledbytes) [reply src/sdk/nsfs_glacier_backend/tapecloud.js]: Updated the PR

**Comment by tangledbytes** [comment]
@guymguym, I have added 2 commits in this PR. One PR is the actual fix while the other one fixes the glacier tests not running (my guess since about 3 weeks now). I have split the commits for the ease of backport at least as one would be picked up by DBS3.

**Review by guymguym — APPROVED** [review]
