### PR TITLE
NC | supplemental groups - getpwuid concurrency issue

### LINKED ISSUE #8985: Supplemental groups thread safety issue + dynamic supplemental groups PANIC in a container
### Environment info
- NooBaa Version: 4.19
- Platform: NC in oowy container

### Actual behavior
1. We use `getpwuid(uid)` in our os_linux.cpp and os_darwin.cpp code while it's an unsafe for multi threaded usage per the [getpwuid man page](https://man7.org/linux/man-pages/man3/getpwuid.3p.html), while the thread safe function we should use is `getpwuid_r()`.
```

The getpwuid() function need not be thread-safe.
...
The getpwuid_r() function is thread-safe and returns values in a
user-supplied buffer instead of possibly using a static data area
that may be overwritten by each call.
```
image
One more issue that might be related (or not) is the following - 

4.19 - 
```
Apr 22 13:28:37 node[1234]: PANIC: MUST SYSCALL FAILED: syscall(SYS_setgroups, groups.size(), &groups[0]) = -1 Operation not permitted (1) set_supplemental_groups() at ../src/native/util/os_linux.cpp:75
```
4.18.2 - 
```
Apr 24 11:10:23 d93e136f730c node[442]: PANIC: MUST SYSCALL FAILED: syscall(SYS_setgroups, orig_groups.size(), &orig_groups[0]) = -1 Op
eration not permitted (1) restore_user() at ../src/native/util/os_linux.cpp:63
Apr 24 11:10:23 d93e136f730c node[442]: qemu: uncaught target signal 6 (Aborted) - core dumped
```

### Expected behavior
1. All napi functions in use should be thread safe and we should not fail on PANIC. 

### Steps to reproduce
1. Run RHEL 9 container - `docker run --privileged --user root -d --platform=linux/amd64 oowy/redhat:ubi9`
2. login to the container - docker exec -it <container_id> bash
3. install NooBaa RPM per the instructions mentioned in https://github.com/noobaa/noobaa-core/blob/master/docs/NooBaaNonContainerized/GettingStarted.md#install
4. Check NooBaa restarts in the logs - `journalctl -u noobaa`

### PR DESCRIPTION
**Pull request by nadavMiz**
### Describe the Problem
as noted in #8982 : getpwuid function is not thread safe. so need to replace with thread safe getpwuid_r

### Explain the Changes
1. create a static variable for password buffer size in ThreadScope scope. initialize it from buffer length we got in fs_napi CTOR
2. replace getpwuid in both dynamic supplemental group usage for both linux and darwin.

### Testing Instructions:
1. for general supplemental groups tests run:
`sudo NC_CORETEST=true node ./node_modules/mocha/bin/mocha src/test/unit_tests/test_nsfs_access.js`

- [ ] Doc added/updated
- [x] Tests added

### CODE REVIEW

File: src/native/fs/fs_napi.cpp [hunk 1]
```diff
@@ -2420,6 +2420,7 @@ fs_napi(Napi::Env env, Napi::Object exports)
         passwd_bufsize = 16384;
     }
     PASSWD_BUF_SIZE = passwd_bufsize;
+    ThreadScope::set_passwd_buf_size(PASSWD_BUF_SIZE);
```
Comment (guymguym) [inline src/native/fs/fs_napi.cpp:2423]: Maintaining the same in two places is messy for no good reason. Let choose one place. It can be the ThreadScope for ease of sharing it. Just add a getter and use it also from fs_napi.

File: src/native/util/os.h [hunk 2]
```diff
@@ -41,11 +41,17 @@ class ThreadScope
...
+    {
+        passwd_buf_size = buf_size;
+    }
+
     int add_thread_capabilities();
 
     const static uid_t orig_uid;
     const static gid_t orig_gid;
     const static std::vector<gid_t> orig_groups;
+    static int passwd_buf_size;
```
Comment (guymguym) [inline src/native/util/os.h:54]: use type long to match the sysconf output.

File: src/native/util/os_darwin.cpp [hunk 3]
```diff
@@ -43,15 +43,18 @@ get_current_uid()
...
 get_supplemental_groups_by_uid(uid_t uid, std::vector<gid_t>& groups)
 {
-    // getpwuid will only indicate if an error happened by setting errno. set it to 0, so will know if there is a change
-    errno = 0;
-    struct passwd* pw = getpwuid(uid);
-    if (pw == NULL) {
-        if (errno == 0) {
+    std::unique_ptr<char[]> buf(new char[ThreadScope::passwd_buf_size]);
+    struct passwd pwd;
+    struct passwd *getpwnam_res;
```
Comment (guymguym) [inline src/native/util/os_darwin.cpp:53]: initialize pointer to null.
also there is no real need to change the name to be long and anoying, it can stay pw.

File: src/native/util/os_darwin.cpp [hunk 4]
```diff
@@ -61,7 +64,7 @@ get_supplemental_groups_by_uid(uid_t uid, std::vector<gid_t>& groups)
     int ngroups = NGROUPS_MAX;
     //for some reason on mac getgrouplist accepts an array of int instead of gid_t. so need to create a vector of int and then insert it into groups
     std::vector<int> tmp_groups(ngroups);
-    if (getgrouplist(pw->pw_name, pw->pw_gid, &tmp_groups[0], &ngroups) < 0) {
+    if (getgrouplist(pwd.pw_name, pwd.pw_gid, &tmp_groups[0], &ngroups) < 0) {
```
Comment (guymguym) [inline src/native/util/os_darwin.cpp:67]: I think it's better to keep using the pointer pw->pw_name to access the info. the pwd struct is only a "storage" variable, and the pointer is the actual response.

File: src/native/fs/fs_napi.cpp [hunk 5]
```diff
@@ -2419,7 +2419,7 @@ fs_napi(Napi::Env env, Napi::Object exports)
     if (passwd_bufsize == -1) {
         passwd_bufsize = 16384;
     }
-    PASSWD_BUF_SIZE = passwd_bufsize;
+    ThreadScope::set_passwd_buf_size(passwd_bufsize);
```
[the remark this answers is not in the document]
Comment (guymguym) [reply src/native/fs/fs_napi.cpp:2422]: it's not per thread. it's completely static in the process. we just needed somewhere to manage this that would be available to both fs_napi and the thread_scope code. I wouldn't be too worried about this integer  appearing too much like a per-thread constant because it's just a number we keep.

[the remark this answers is not in the document]
Comment (romayalon) [reply src/native/fs/fs_napi.cpp]: exactly it's not really per thread because it's a static constant, it's not worrying :) it's just a bit weird it's there
let's move on with this solution

File: src/native/util/os_darwin.cpp [hunk 6]
```diff
@@ -43,15 +43,19 @@ get_current_uid()
 const uid_t ThreadScope::orig_uid = getuid();
 const gid_t ThreadScope::orig_gid = getgid();
 const std::vector<gid_t> ThreadScope::orig_groups = get_process_groups();
+long ThreadScope::passwd_buf_size = -1;
```
Comment (romayalon) [inline src/native/util/os_darwin.cpp:46]: do we still need this line?

**Review by romayalon — APPROVED** [review]
