### PR TITLE
NSFS | NC | fix bucket policy issue

### LINKED ISSUE #7527: principal.unwrap is not a function
### Environment info
- NooBaa Version: nsfs / noobaa-core-5.15.0-1.el8.x86_64 (head commit 08c1d008ab482830bf9b381cf073a469e409effb)
- Platform: RHEL 8.6, GPFS 5.1.7.1, NSFS

### Actual behavior
Bucket policy doesn't work. Getting `TypeError: principal.unwrap is not a function` when trying to access.

### Steps to reproduce
Create policy file with content:

```
{
"Version":"2012-10-17",
"Statement":[
        {
          "Sid":"this-is-the-sid",
          "Effect":"Allow",
          "Principal": [
              "actor2@noobaa.io"
           ],
          "Action":["s3:*"],
          "Resource":["arn:aws:s3:::*"]
        }
   ]
}
```

(have tried various ways of pointing at the principal.. name, email, "*".. always same error)

Assign to bucket:

`aws --profile actor3 --endpoint http://localhost:6001  s3api put-bucket-policy --bucket ns9012k --policy  file:///root/allow-actor2-ns9012k.policy`

Access bucket as actor2:

```
# aws --profile actor2 --endpoint http://localhost:6001 s3 ls s3://ns9012k`

An error occurred (InternalError) when calling the ListObjectsV2 operation (reached max retries: 2): We encountered an internal error. Please try again.`
```

### More information - Screenshots / Logs / Other output

Strange it's saying validate_non_nsfs_bucket in the log, as this is supposed to be NSFS.

```
Oct 06 14:42:41 scale-test-os-1.oslo.forum.ibm.com node[3449126]: Oct-6 14:42:41.511 [nsfs/3449126]    [L1] core.sdk.object_sdk:: validate_non_nsfs_bucket:  { name: SENSITIVE-f4532c518b6d03dc, email: SENSITIVE-f4532c518b6d03dc, has_login: 'false', has_s3_access: 'true', allow_bucket_creation: 'true', access_keys: [ { access_key: SENSITIVE-92c409ac6a89ab37, secret_key: SENSITIVE-0683bcd1285ff91f } ], nsfs_account_config: { uid: 5678, gid: 5678, new_buckets_path: '/ibm/fs1/buckets1', nsfs_only: 'true' } } { fs_root_path: '' }
Oct 06 14:42:41 scale-test-os-1.oslo.forum.ibm.com node[3449126]: Oct-6 14:42:41.513 [nsfs/3449126] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/ns9012k?list-type=2&amp;prefix=&amp;delimiter=%2F&amp;encoding-type=url</Resource><RequestId>lneljsgz-elrq7f-19z5</RequestId></Error> GET /ns9012k?list-type=2&prefix=&delimiter=%2F&encoding-type=url {"host":"localhost:6001","accept-encoding":"identity","user-agent":"aws-cli/2.4.6 Python/3.8.8 Linux/4.18.0-348.2.1.el8_5.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.ls","x-amz-date":"20231006T124241Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=kWmbUkx99didgIw27HqG/20231006/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=a05a4fb8584191d9690028cb4380ab923d4b8a4ba35e7456121373bfc16f9f98"} TypeError: principal.unwrap is not a function
Oct 06 14:42:41 scale-test-os-1.oslo.forum.ibm.com node[3449126]:     at _is_principal_fit (/usr/local/noobaa-core/src/endpoint/s3/s3_bucket_policy_utils.js:168:24)
Oct 06 14:42:41 scale-test-os-1.oslo.forum.ibm.com node[3449126]:     at _is_statements_fit (/usr/local/noobaa-core/src/endpoint/s3/s3_bucket_policy_utils.js:192:31)
Oct 06 14:42:41 scale-test-os-1.oslo.forum.ibm.com node[3449126]:     at Object.has_bucket_policy_permission (/usr/local/noobaa-core/src/endpoint/s3/s3_bucket_policy_utils.js:143:15)
Oct 06 14:42:41 scale-test-os-1.oslo.forum.ibm.com node[3449126]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Oct 06 14:42:41 scale-test-os-1.oslo.forum.ibm.com node[3449126]:     at async authorize_request_policy (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:237:24)
Oct 06 14:42:41 scale-test-os-1.oslo.forum.ibm.com node[3449126]:     at async Promise.all (index 1)
Oct 06 14:42:41 scale-test-os-1.oslo.forum.ibm.com node[3449126]:     at async authorize_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:197:5)
Oct 06 14:42:41 scale-test-os-1.oslo.forum.ibm.com node[3449126]:     at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:113:5)
Oct 06 14:42:41 scale-test-os-1.oslo.forum.ibm.com node[3449126]:     at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:64:9)
```

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. bucketspace_fs.read_bucket_sdk_info() added iteration on existing bucket policies in order to convert plain principals  (email/"*") string to sensitive strings.
2.  bucketspace_fs.put_bucket_policy() - added validate_s3_policy() call.
3. moved validate_s3_policy() func from bucket_server to bucket_policy_utils so it can be re-used by bucketspace_fs.
since we don't have a system store in NC env, we currently won't check existence of accounts mentioned in bucket policies (see Gaps).
4. Added unit tests

### Issues: Fixed #xxx / Gap #xxx
1. Currently we won't check for existence of the accounts provided in the bucket policy as it requires a new account_by_email cache or a different solution.
2. Fixed #7527 

### Testing Instructions:
1. 

- [ ] Doc added/updated
- [x] Tests added

### CODE REVIEW

File: src/endpoint/s3/s3_bucket_policy_utils.js [hunk 1]
```diff
@@ -233,7 +236,52 @@ function _parse_condition_keys(condition_statement) {
...
+                }
+            }
+        }
+        // TODO: Need to validate that the resource comply with the action
+    }
+}
 
 exports.OP_NAME_TO_ACTION = OP_NAME_TO_ACTION;
-exports.SUPPORTED_BUCKET_POLICY_CONDITIONS = Object.keys(supported_actions);
+exports.SUPPORTED_BUCKET_POLICY_CONDITIONS = SUPPORTED_BUCKET_POLICY_CONDITIONS;
```
Comment (naveenpaul1) [inline src/endpoint/s3/s3_bucket_policy_utils.js:285]: do we need to export this now?

**Review by naveenpaul1 — APPROVED** [review]
a small comment, LGTM
