### PR TITLE
NSFS | Versioning | Delete of partial directory of nested key results in AccessDeniedError

### LINKED ISSUE #8454: NC | NSFS | Versioning | Delete of partial directory of nested key results in `AccessDeniedError`
### Environment info
- NooBaa Version: 5.18.0 (current master)
- Platform: NC

### Actual behavior
1. When a bucket with versioning enabled and there is a nested key inside and the client tries to delete the parent directory of the file without the last slash '/' (let's say it was by accident) will result in an error `AccessDenied` and in FS layer it is `Error: Operation not permitted, code: 'EPERM'`

### Expected behavior
1. Create a delete marker without an error.

### Steps to reproduce

1. Create an account with the CLI: `sudo node src/cmd/manage_nsfs account add --name <account-name> --new_buckets_path /tmp/nsfs_root1 --access_key <access-key> --secret_key <secret-key> --uid <uid> --gid <gid>`
Note: before creating the account need to give permission to the `new_buckets_path`: `chmod 777 /tmp/nsfs_root1`, `chmod 777 /tmp/nsfs_root2`.
2. Start the NSFS server with: `sudo node src/cmd/nsfs --debug 5`
Notes: 
- I Change the `config.NSFS_CHECK_BUCKET_BOUNDARIES = false; //SDSD` because I’m using the `/tmp/` and not `/private/tmp/`.
3. Create the alias for S3 service:`alias nc-user-1-s3=‘AWS_ACCESS_KEY_ID=<access-key> AWS_SECRET_ACCESS_KEY=<secret-key> aws --no-verify-ssl --endpoint-url https://localhost:6443’`.
4. Check the connection to the endpoint and try to list the buckets (should be empty): `nc-user-1-s3 s3 ls; echo $?`
5. Add bucket to the account using AWS CLI: `nc-user-1-s3 s3 mb s3://bucket-v` (`bucket-v` is the bucket name in this example)
6. Enable versioning: `nc-user-1-s3 s3api put-bucket-versioning --bucket bucket-v --versioning-configuration Status=Enabled`
7. Put a nested  object: `nc-user-1-s3 s3api put-object --bucket bucket-v --key /a/b/c/lala.txt`
8. Delete the key /a/b/c (without the last slash): `nc-user-1-s3 s3api delete-object --bucket bucket-v --key  /a/b/c`
Note: deleting the directory creates the delete marker as expected (`nc-user-1-s3 s3api delete-object --bucket bucket-v --key /a/b/c/`).

### More information - Screenshots / Logs / Other output
Might be that this issue is with the same root cause of the issue - #8320

```
Oct-10 16:13:38.960 [nsfs/79233]  [WARN] core.sdk.namespace_fs:: NamespaceFS._delete_latest_version error: retries=10 latest_ver_path=/tmp/nsfs_root1/bucket-v/a/b/c [Error: Operation not permitted] { code: 'EPERM', context: 'SafeLink _link_from.c_str()=/tmp/nsfs_root1/bucket-v/a/b/c _link_to.c_str()=/tmp/nsfs_root1/bucket-v/a/b/.versions/c_null _link_expected_mtime=1728566008914826496 _link_expected_inode=152582414 ' }
Oct-10 16:13:38.961 [nsfs/79233] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>/bucket-v//a/b/c</Resource><RequestId>m23bksck-csss5c-135r</RequestId></Error> DELETE /bucket-v//a/b/c {"host":"localhost:6443","accept-encoding":"identity","user-agent":"aws-cli/2.17.11 md/awscrt#0.20.11 ua/2.0 os/macos#24.0.0 md/arch#arm64 lang/python#3.11.9 md/pyimpl#CPython cfg/retry-mode#standard md/installer#source md/prompt#off md/command#s3api.delete-object","x-amz-date":"20241010T131338Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=<>/20241010/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=4dc8ae840909447ab17ef08ce5c6d25c62a422ed1ba7fa79900a210ac1cfa3b5","content-length":"0"} Error: Operation not permitted - context: SafeLink _link_from.c_str()=/tmp/nsfs_root1/bucket-v/a/b/c _link_to.c_str()=/tmp/nsfs_root1/bucket-v/a/b/.versions/c_null _link_expected_mtime=1728566008914826496 _link_expected_inode=152582414
```

### PR DESCRIPTION
**Pull request by naveenpaul1**
### Explain the changes
1. Version bucket does not support dir versioning, Deleting dir key(`a/b/c/`) just deletes the .folder file and does not create delete_marker.
2.  If the bucket has key `a/b/c/test.txt` and then tries to delete key `a/b/c` code will throw `AccessDenied` error.

### Issues: Fixed #xxx / Gap #xxx
1. https://github.com/noobaa/noobaa-core/issues/8454

### Testing Instructions:
1. Please check the issue

- [ ] Doc added/updated
- [X] Tests added

### CODE REVIEW

File: src/test/unit_tests/test_namespace_fs.js [hunk 1]
```diff
@@ -472,6 +474,22 @@ mocha.describe('namespace_fs', function() {
 
         });
 
+        mocha.it('delete dir object without last slash - a/b/c', async function() {
```
Comment (shirady) [inline src/test/unit_tests/test_namespace_fs.js:477]: minor (missing the first slash in the title)
```suggestion
        mocha.it('delete dir object without last slash - /a/b/c', async function() {
```

File: src/sdk/namespace_fs.js [hunk 2]
```diff
@@ -2778,6 +2779,24 @@ class NamespaceFS {
...
     }
+    /** 
+    * method append slash at the end of dir key when key misses last slash.
+    * @param {import('./nb').NativeFSContext} fs_context
+    * @param {string} key
+    */
+    async _get_correct_key_path(fs_context, key) {
+        try {
+            const key_path = path.normalize(path.join(this.bucket_path, key));
+            const key_state = await nb_native().fs.stat(fs_context, key_path, { skip_user_xattr: true });
```
Comment (shirady) [inline src/sdk/namespace_fs.js:2790]: Is it `key_state` or `key_stat`? (we are running a stat on the key)

**Review by shirady — COMMENTED** [review]
I added minor comments

**Comment by shirady** [comment]
@naveenpaul1 could you add the test in file `src/test/unit_tests/test_bucketspace_versioning.js`?
I found this issue while I worked on PR #8453

File: src/test/unit_tests/test_namespace_fs.js [hunk 3]
```diff
@@ -472,6 +474,22 @@ mocha.describe('namespace_fs', function() {
...
+            await upload_object(ns_tmp, upload_bkt, upload_key_4, dummy_object_sdk, source);
+            await delete_object(ns_tmp, upload_bkt, '/x/y/z', dummy_object_sdk);
+
+            let entries;
+            try {
+                entries = await nb_native().fs.readdir(DEFAULT_FS_CONFIG, ns_tmp_bucket_path + dir_2);
+            } catch (e) {
+                assert.ifError(e);
+            }
+            console.log('stop when not empty - entries', entries);
```
Comment (shirady) [inline src/test/unit_tests/test_namespace_fs.js:488]: Do we need this printing in the CI?
I'm not sure I understand it, could you please a comment with an explnantion?

File: src/test/unit_tests/test_namespace_fs.js [hunk 4]
```diff
@@ -472,6 +474,22 @@ mocha.describe('namespace_fs', function() {
 
         });
 
+        mocha.it('delete dir object without last slash - /x/y/z/', async function() {
+            const source = buffer_utils.buffer_to_read_stream(data);
+            await upload_object(ns_tmp, upload_bkt, upload_key_4, dummy_object_sdk, source);
+            await delete_object(ns_tmp, upload_bkt, '/x/y/z', dummy_object_sdk);
```
Comment (shirady) [inline src/test/unit_tests/test_namespace_fs.js:480]: I think it would be easier to read with additional variable:
```suggestion
           const partial_dir_3 = dir_3.slice(0, -1); // the path without the last slash
            await delete_object(ns_tmp, upload_bkt, partial_dir_3, dummy_object_sdk);
```

**Review by shirady — APPROVED** [review]
LGTM
added 2 minor comments

**Review by romayalon — CHANGES_REQUESTED** [review]
I want to request changes because the original issue seems incorrect to me, can you please check that throwing AccessDenied is also not thrown by AWS in the specified reproduction steps?

**Comment by naveenpaul1** [comment]
@romayalon added the AWS same behaviour finding in [issue](https://github.com/noobaa/noobaa-core/issues/8454#issuecomment-2454316675) , For AWS aslo partial dir key is creating delete_marker for object.
cc: @shirady

**Comment by romayalon** [comment]
@naveenpaul1 thanks for checking it, 
can you run get_object before deleting the object?
my assumption is that you would receive ENOENT, because there is no such object called a/b/c.. later please check on NooBaa if this is still the behavior with the code of this PR
When deleting an object when versioning is enabled, AWS don't care if the object exists or not, they just create a delete marker.

**Comment by naveenpaul1** [comment]
@romayalon updated the get-object behavior in [issue](https://github.com/noobaa/noobaa-core/issues/8454#issuecomment-2454595083) please check

File: src/sdk/namespace_fs.js [hunk 5]
```diff
@@ -2772,6 +2772,7 @@ class NamespaceFS {
      * @returns {Promise<string>}
      */
     async _find_version_path(fs_context, { key, version_id }, return_md_path) {
+        key = await this._get_correct_key_path(fs_context, key);
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:2775]: can you explain this change please?

Comment (naveenpaul1) [reply src/sdk/namespace_fs.js:2775]: @romayalon if the key is a partial dir path such as `a/b/c` this method will check whether the key is dir or not if its dir, then a backslash is added to the key to avoid the `AccessDeniedError` error. file path will leave key as it is

Comment (romayalon) [reply src/sdk/namespace_fs.js:2775]: But notice that we expect to fail with ENOENT when key doesn't end with a slash, and the folder is not a content dir - 
```
if (!stat.xattr?.[XATTR_DIR_CONTENT] || !params.key.endsWith('/')) {
throw error_utils.new_error_code('ENOENT', 'NoSuchKey');
```
if you change the key to have a / at the end, will we fail on this situation as we should per AWS?

File: src/sdk/namespace_fs.js [hunk 6]
```diff
@@ -3017,8 +3033,12 @@ class NamespaceFS {
         const is_gpfs = native_fs_utils._is_gpfs(fs_context);
         let retries = config.NSFS_RENAME_RETRIES;
         let latest_ver_info;
+        const is_key_dir_path = await this._is_key_dir_path(fs_context, params.key);
         for (;;) {
             try {
+                if (is_key_dir_path && !this._is_directory_content(latest_ver_path, params.key)) {
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:3039]: @naveenpaul1 @shirady Have you checked also what happens when trying to delete a/b/c/?

Comment (romayalon) [reply src/sdk/namespace_fs.js:3039]: we probably want to avoid versioning flow on this case as well, right?

File: src/sdk/namespace_fs.js [hunk 7]
```diff
@@ -2784,6 +2784,22 @@ class NamespaceFS {
...
+    * @param {string} key
+    */
+    async _is_key_dir_path(fs_context, key) {
+        try {
+            const key_path = path.normalize(path.join(this.bucket_path, key));
+            const key_stat = await nb_native().fs.stat(fs_context, key_path, { skip_user_xattr: true });
+            const is_dir = native_fs_utils.isDirectory(key_stat);
+            return is_dir;
+        } catch (err) {
+            dbg.warn('NamespaceFS._correct_key_path : error while getting state for key ', key, err);
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:2799]:
```suggestion
            dbg.warn('NamespaceFS. _is_key_dir_path : error while getting state for key ', key, err);
```

File: src/sdk/namespace_fs.js (hunk 6 above)
Comment (shirady) [reply src/sdk/namespace_fs.js:3039]: I don't remember that I checked this case - delete a/b/c without the beginning slash instead of /ab/c/ (I thought only about deleting/a/b/c without the ending slash instead of /a/b/c/ as mentioned in the issue).

Comment (naveenpaul1) [reply src/sdk/namespace_fs.js:3039]: @romayalon @shirady for`a/b/c/`, with this code we are just deleting the `.folder` file not creating any delet_marker,

[the remark this answers is not in the document]
Comment (naveenpaul1) [reply src/sdk/namespace_fs.js:3039]: @romayalon we are returning empty response for deleted scenario also, if we do the same for error case also it will create confusion.

Comment (romayalon) [reply src/sdk/namespace_fs.js:3039]: @naveenpaul1 can you point me to the code that does that?

[the remark this answers is not in the document]
Comment (romayalon) [reply src/sdk/namespace_fs.js:3039]: maybe it'll create a confusion, but in any case access denied is not an appropriate error code

Comment (naveenpaul1) [reply src/sdk/namespace_fs.js:3039]: @romayalon here : [link](https://github.com/noobaa/noobaa-core/pull/8480/files#diff-74a1674f40effb24da2459330c005cd5ab9fda4e1bca500a4387607926a2af1fR3058) we are skipping copy file to new version when customer try to delete the dir. and else block get executed which do simple deletion and e are also skipping delete_marker creation if is_key_dir_path true.

[the remark this answers is not in the document]
Comment (naveenpaul1) [reply src/sdk/namespace_fs.js:3039]: @romayalon even if we dont throw error here try catch block will throw a `EPERM` error and clent will convert the error to `AccessDenied` error,
response after removing the code that throws S3Error.AccessDenied error 
```
naveenpaul:noobaa-core$ s3 s3api delete-object --bucket bucket1 --key /a/b/c
An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied
```

Comment (naveenpaul1) [reply src/sdk/namespace_fs.js:3039]: @romayalon we are deleting the `.folder` file when user pass key `a/b/c/` we are not creating the version and delete_marker

File: src/sdk/namespace_fs.js [hunk 8]
```diff
@@ -1926,7 +1926,9 @@ class NamespaceFS {
             await this._check_path_in_bucket_boundaries(fs_context, file_path);
             dbg.log0('NamespaceFS: delete_object', file_path);
             let res;
-            if (this._is_versioning_disabled()) {
+            const is_key_dir_path = await this._is_key_dir_path(fs_context, params.key);
+            if (this._is_versioning_disabled() || is_key_dir_path) {
+                // TODO : Dir versioning not implemented, This should be fixed as part of #8320
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:1931]:
```suggestion
            // TODO- Directory object (key/) is currently can't co-exist while key (without slash) exists. see -https://github.com/noobaa/noobaa-core/issues/8320
            // Also, Directory object (key/) is currently not supported combined with versioning - see - <add link>
            if (this._is_versioning_disabled() || is_key_dir_path) {
```

please mention the 2 issues here - https://github.com/noobaa/noobaa-core/issues/8531

File: src/sdk/namespace_fs.js [hunk 9]
```diff
@@ -3035,7 +3054,7 @@ class NamespaceFS {
                     const suspended_and_latest_is_not_null = this._is_versioning_suspended() &&
                         latest_ver_info.version_id_str !== NULL_VERSION_ID;
                     const bucket_tmp_dir_path = this.get_bucket_tmpdir_full_path();
-                    if (this._is_versioning_enabled() || suspended_and_latest_is_not_null) {
+                    if ((this._is_versioning_enabled() || suspended_and_latest_is_not_null)) {
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:3057]: left overs from old code

**Review by romayalon — APPROVED** [review]
