### PR TITLE
NSFS | NC | list buckets missing policy check & performance improvement

### LINKED ISSUE #7809: NSFS | Bucket policy authorization is skipped on List Buckets operation
### Environment info
- NooBaa Version: master
- Platform: ALL

### Actual behavior
1. Currently, we do not authorize bucket policy on list buckets - 
```
async function authorize_request_policy(req) {
    console.log('req.params: ', req.params); // on s3 ls -> noobaa printed - { bucket: '', key: '' }
    if (!req.params.bucket) return; // we return here
```
This gap causes an issue when having multiple accounts, account1 running s3 ls can see the buckets of account2 and vice versa.
On other bucketspaces we check again on the list buckets operation for every bucket if it is allowed to be listed.

for example in bucket server - 
```
    const buckets_by_name = _.filter(
        req.system.buckets_by_name,
        async bucket => await req.has_s3_bucket_permission(bucket, "s3:ListBucket", req) && !bucket.deleting
    );
```

### Expected behavior
1. account1 running s3 ls can not see the buckets of account2 and vice versa.

### Steps to reproduce
1. create account1
2. create account2
3. create bucket1 using account1
4. create bucket2 using bucket1
5. account1 s3 ls // expect only bucket1
6. account2 s3 ls // expect only bucket2

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. bucketspaceFS - list_buckets - Added bucket policy check so we won't let account1 to list buckets of account2 if it's not allowed by a bucket policy even if it's allowed by fs (matching uid gid).
2. bucketspaceFS - list_buckets - refactored this function, we iterated the buckets array 4 times, now we will iterate it 2 times -
a. First iteration - map_with_concurrency with concurrency rate of 10 entries at the same time.
If entry is dir file/entry is non json / bucket is unaccessible by bucket policy / underlying storage of the bucket is unaccessible by fs we will return undefined, else - the bucket config info.
b. Second iteration - filter entries - filter will remove undefined values produced by the map_with_concurrency(). 

### Issues: Fixed #xxx / Gap #xxx
1. Fixed - https://github.com/noobaa/noobaa-core/issues/7809
2. Gap - Move the following 3 functions - has_bucket_action_permission(), validate_fs_bucket_access(), _has_access_to_nsfs_dir() so they can be re-used - follow up PR.

### Testing Instructions:
1. 

- [ ] Doc added/updated
- [x] Tests added

### CODE REVIEW

File: src/sdk/bucketspace_fs.js [hunk 1]
```diff
@@ -650,6 +623,72 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+        dbg.log1('has_bucket_action_permission:', bucket.name.unwrap(), account_identifier, bucket.system_owner, bucket.owner_account);
+
+        const is_system_owner = account_identifier === bucket.system_owner.unwrap();
+
+        // If the system owner account wants to access the bucket, allow it
+        if (is_system_owner) return true;
+        const is_owner = (bucket.bucket_owner.unwrap() === account_identifier);
+        const bucket_policy = bucket.s3_policy;
+
+        if (!bucket_policy) return false;
```
Comment (naveenpaul1) [inline src/sdk/bucketspace_fs.js:644]: @romayalon should we return true when `is_owner` true and there is no policy for buckey?

Comment (romayalon) [reply src/sdk/bucketspace_fs.js:644]: see lines 657-658, if bucket policy result is DENY we will return false

File: src/sdk/bucketspace_fs.js [hunk 2]
```diff
@@ -202,55 +202,28 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
             }
             throw this._translate_bucket_error_codes(err);
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:203]: Would you please move lines 195 to 203 to a function?
The whole logic is just for getting the entries, not the "core" of the list buckets operation.

File: src/sdk/bucketspace_fs.js [hunk 3]
```diff
@@ -202,55 +202,28 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
-            if (err.code === 'ENOENT' || err.code === 'EACCES' || (err.code === 'EPERM' && err.message === 'Operation not permitted')) return false;
-            throw err;
-        }
+        const buckets = await P.map_with_concurrency(10, entries, async entry => {
+            if (native_fs_utils.isDirectory(entry) || !entry.name.endsWith('.json')) {
+                return;
+            }
+            const bucket_name = this.get_bucket_name(entry.name);
+            const bucket = await object_sdk.read_bucket_sdk_config_info(bucket_name);
+            const bucket_policy_accessible = await this.has_bucket_action_permission(bucket, account, "s3:ListBucket");
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:213]: regarding: "s3:ListBucket":
Is there a special reason for double quotes?
I think it would be better to save it as a constant variable and reuse it whenever needed.

File: src/sdk/bucketspace_fs.js [hunk 4]
```diff
@@ -202,55 +202,28 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+            if (!bucket_policy_accessible) return;
+            const fs_accessible = await this.validate_fs_bucket_access(bucket, object_sdk);
+            return fs_accessible && bucket;
+        });
+        const filteres_buckets = buckets.filter(bucket => bucket);
+        return { buckets: filteres_buckets };
     }
 
+
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:222]: I think this new line redundant.

File: src/sdk/bucketspace_fs.js (hunk 1 above)
Comment (shirady) [reply src/sdk/bucketspace_fs.js:644]: @romayalon I didn't understand why it is different from:
https://github.com/noobaa/noobaa-core/blob/8ef4d07243d91c030a9501e8903413dca760d4df/src/server/common_services/auth_server.js#L683
Worth adding a comment with an explanation about this.

File: src/sdk/bucketspace_fs.js [hunk 5]
```diff
@@ -650,6 +623,72 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+        const ns = bucket.namespace;
+        const is_nsfs_bucket = object_sdk.is_nsfs_bucket(ns);
+        const accessible = is_nsfs_bucket ? await this._has_access_to_nsfs_dir(ns, object_sdk) : false;
+        dbg.log1('bucketspace_fs.validate_fs_bucket_access:', bucket.name.unwrap(), is_nsfs_bucket, accessible);
+        return accessible;
+    }
+
+    async _has_access_to_nsfs_dir(ns, object_sdk) {
+        const account = object_sdk.requesting_account;
+        dbg.log0('_has_access_to_nsfs_dir: nsr: ', ns, 'account.nsfs_account_config: ', account && account.nsfs_account_config);
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:672]: `log0` on purpose? (the rest of the added logs were `log1` in utils function)

File: src/sdk/bucketspace_fs.js [hunk 6]
```diff
@@ -650,6 +623,72 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+        // nsfs bucket
+        if (!account || !account.nsfs_account_config || _.isUndefined(account.nsfs_account_config.uid) ||
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:674]: Account name can be also a number, for example, number 0, so I would suggest changing it to `_.isUndefined(account)`.
At this point, just want to make sure - Did we already converted the distinguished_name to uid and gid? (if you can refer where).

File: src/sdk/bucketspace_fs.js [hunk 7]
```diff
@@ -650,6 +623,72 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+            _.isUndefined(account.nsfs_account_config.gid)) return false;
+        try {
+            dbg.log0('_has_access_to_nsfs_dir: checking access:', ns.write_resource, account.nsfs_account_config.uid, account.nsfs_account_config.gid);
+            await nb_native().fs.checkAccess({
+                uid: account.nsfs_account_config.uid,
+                gid: account.nsfs_account_config.gid,
+                backend: ns.write_resource.resource.fs_backend,
+                warn_threshold_ms: config.NSFS_WARN_THRESHOLD_MS,
+            }, path.join(ns.write_resource.resource.fs_root_path, ns.write_resource.path || ''));
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:683]: I think it will be more readable to separate it into the variables `fs_context` and `path`.

File: src/test/unit_tests/test_bucketspace.js [hunk 8]
```diff
@@ -41,6 +41,169 @@ const DEFAULT_FS_CONFIG = {
...
+        },
+        // 'account4': {
+        //     bucket: 'bucket4',
+        //     create_bucket_via: 'CLI',
+        //     account_info: {
+        //         uid: 1234,
+        //         gid: 1234,
+        //         new_buckets_path
+        //     }
+        // },
```
Comment (shirady) [inline src/test/unit_tests/test_bucketspace.js:83]: Why is it in comment? better to explain it or delete it.

File: src/test/unit_tests/test_bucketspace.js [hunk 9]
```diff
@@ -41,6 +41,169 @@ const DEFAULT_FS_CONFIG = {
...
+            }
+        }
+    });
+
+    mocha.after(async function() {
+        this.timeout(60000); // eslint-disable-line no-invalid-this
+        for (const account_name of Object.keys(accounts)) {
+            const { bucket } = accounts[account_name];
+            await rpc_client.bucket.delete_bucket({ name: bucket });
+            await rpc_client.account.delete_account({ email: `${account_name}@noobaa.com` });
```
Comment (shirady) [inline src/test/unit_tests/test_bucketspace.js:135]: Where do we add the `@noobaa.com` to the email account?

File: src/test/unit_tests/test_bucketspace.js [hunk 10]
```diff
@@ -41,6 +41,169 @@ const DEFAULT_FS_CONFIG = {
...
+        }
+        await fs_utils.folder_delete(tmp_fs_root);
+    });
+
+    mocha.it('list buckets - each account can list only its own bucket - no bucket policies applied ', async function() {
+        for (const account of Object.values(accounts)) {
+            const { s3_client } = account;
+            const res = await s3_client.listBuckets({});
+            const buckets = res.Buckets.filter(bucket => bucket.Name !== 'first.bucket');
```
Comment (shirady) [inline src/test/unit_tests/test_bucketspace.js:144]: Please add a comment about the filtering of 'first.bucket'

File: src/test/unit_tests/test_bucketspace.js [hunk 11]
```diff
@@ -41,6 +41,169 @@ const DEFAULT_FS_CONFIG = {
...
+            .map(generated =>
+                rpc_client.bucket.put_bucket_policy({
+                    name: generated.params.bucket,
+                    policy: generated.policy,
+                })
+            )
+        );
+        let s3_client = accounts.account1.s3_client;
+        let res = await s3_client.listBuckets({});
+        let buckets = res.Buckets.filter(bucket => bucket.Name !== 'first.bucket' && bucket.Name !== accounts.account1.bucket);
```
Comment (shirady) [inline src/test/unit_tests/test_bucketspace.js:195]: Why did you add the second condition `bucket.Name !== accounts.account1.bucket`?
Please add an explanation in a comment

File: src/test/unit_tests/test_bucketspace.js [hunk 12]
```diff
@@ -41,6 +41,169 @@ const DEFAULT_FS_CONFIG = {
...
+        }
+
+        // delete bucket policy
+        await rpc_client.bucket.put_bucket_policy({
+            name: public_bucket,
+            policy: '',
+        });
+    });
+
+    mocha.it('account2 - set allow all only account1, account1 should list bucket2 but account3 shouldnt', async function() {
```
Comment (shirady) [inline src/test/unit_tests/test_bucketspace.js:177]: This test seems complicated to understand, so try to simplify it (remember that it might fail to someone who touches a small part of the code and needs to understand how to debug it...).

File: src/test/unit_tests/test_bucketspace.js [hunk 13]
```diff
@@ -478,12 +641,22 @@ mocha.describe('bucket operations - namespace_fs', async function() {
...
     mocha.it('list buckets with dn', async function() {
-        // Give s3_correct_uid access to the required buckets
         const res = await s3_correct_dn_default_nsr.listBuckets({});
         console.log(inspect(res));
-        const list_ok = bucket_in_list([bucket_name + "-s3-2"], [], res.Buckets);
+        const list_ok = bucket_in_list([bucket_name + '-s3-2'], [], res.Buckets);
         assert.ok(list_ok);
     });
+
+    mocha.it('delete bucket with dn', async function() {
```
Comment (shirady) [inline src/test/unit_tests/test_bucketspace.js:650]: Why did you add this test?

File: src/sdk/bucketspace_fs.js (hunk 2 above)
Comment (romayalon) [reply src/sdk/bucketspace_fs.js:203]: this needs to be done as part of a refactoring PR, I see we can have this function used by health.js and manage_nsfs.js

File: src/test/unit_tests/test_bucketspace.js (hunk 13 above)
Comment (romayalon) [reply src/test/unit_tests/test_bucketspace.js:650]: why not?
this bucket was not cleaned on the teardown, so instead of removing it on teardown I added a test that checks also that we can delete this bucket using dn

Comment (shirady) [reply src/test/unit_tests/test_bucketspace.js:650]: I asked because I didn't understand how this test is related to the list buckets.
As I understand it now it is not related to the change, but you added a test to improve our coverage with bucket deletion using a distinguished name.

File: src/sdk/bucketspace_fs.js (hunk 6 above)
Comment (romayalon) [reply src/sdk/bucketspace_fs.js:674]: account is an object here

File: src/test/unit_tests/test_bucketspace.js (hunk 11 above)
Comment (romayalon) [reply src/test/unit_tests/test_bucketspace.js]: I removed it

File: src/test/unit_tests/test_bucketspace.js (hunk 12 above)
Comment (romayalon) [reply src/test/unit_tests/test_bucketspace.js]: I added comments

File: src/sdk/bucketspace_fs.js [hunk 14]
```diff
@@ -202,55 +202,28 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+            }
+            const bucket_name = this.get_bucket_name(entry.name);
+            const bucket = await object_sdk.read_bucket_sdk_config_info(bucket_name);
+            const bucket_policy_accessible = await this.has_bucket_action_permission(bucket, account, 's3:ListBucket');
+            if (!bucket_policy_accessible) return;
+            const fs_accessible = await this.validate_fs_bucket_access(bucket, object_sdk);
+            if (!fs_accessible) return;
+            return bucket;
+        });
+        const filteres_buckets = buckets.filter(bucket => bucket);
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:219]: I think a more meaningful variable name can be nice here (`accessible_buckets `maybe?).

File: src/sdk/bucketspace_fs.js [hunk 15]
```diff
@@ -650,6 +623,73 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+
+    /////////////////
+    ///// UTILS /////
+    /////////////////
+
+    // TODO: move the following 3 functions - has_bucket_action_permission(), validate_fs_bucket_access(), _has_access_to_nsfs_dir()
+    // so they can be re-used
+    async has_bucket_action_permission(bucket, account, action, bucket_path = "") {
+        const account_identifier = account.name.unwrap();
+        dbg.log1('has_bucket_action_permission:', bucket.name.unwrap(), account_identifier, bucket.system_owner, bucket.owner_account);
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:635]: Don't you need to unwrap `bucket.system_owner` and `bucket.owner_account`?

File: src/sdk/bucketspace_fs.js [hunk 16]
```diff
@@ -650,6 +623,73 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
         // TODO
     }
+
+    /////////////////
+    ///// UTILS /////
+    /////////////////
+
+    // TODO: move the following 3 functions - has_bucket_action_permission(), validate_fs_bucket_access(), _has_access_to_nsfs_dir()
+    // so they can be re-used
+    async has_bucket_action_permission(bucket, account, action, bucket_path = "") {
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:633]: Why changing the name of the parameter from `method` to `action`?

File: src/sdk/bucketspace_fs.js [hunk 17]
```diff
@@ -650,6 +623,73 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+        if (!bucket_policy) return is_owner;
+        if (!action) {
+            throw new Error('has_bucket_action_permission: action is required');
+        }
+
+        const result = await bucket_policy_utils.has_bucket_policy_permission(
+            bucket_policy,
+            account_identifier,
+            action,
+            `arn:aws:s3:::${bucket.name.unwrap()}${bucket_path}`,
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:653]: It is name and path without any separator between them?

File: src/sdk/bucketspace_fs.js [hunk 18]
```diff
@@ -650,6 +623,73 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+            undefined
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:654]: What does it mean that we always pass undefined?
I see that in the internal function it will be `condition_fit` true, but I don't understand the whole context.

File: src/sdk/bucketspace_fs.js [hunk 19]
```diff
@@ -650,6 +623,73 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+    }
+
+    async _has_access_to_nsfs_dir(ns, object_sdk) {
+        const account = object_sdk.requesting_account;
+        dbg.log1('_has_access_to_nsfs_dir: nsr: ', ns, 'account.nsfs_account_config: ', account && account.nsfs_account_config);
+        // nsfs bucket
+        if (!account || !account.nsfs_account_config || _.isUndefined(account.nsfs_account_config.uid) ||
+            _.isUndefined(account.nsfs_account_config.gid)) return false;
+        try {
+            dbg.log0('_has_access_to_nsfs_dir: checking access:', ns.write_resource, account.nsfs_account_config.uid, account.nsfs_account_config.gid);
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:677]: `dbg.log0` on purpose?

File: src/sdk/bucketspace_fs.js [hunk 20]
```diff
@@ -650,6 +623,73 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+        return accessible;
+    }
+
+    async _has_access_to_nsfs_dir(ns, object_sdk) {
+        const account = object_sdk.requesting_account;
+        dbg.log1('_has_access_to_nsfs_dir: nsr: ', ns, 'account.nsfs_account_config: ', account && account.nsfs_account_config);
+        // nsfs bucket
+        if (!account || !account.nsfs_account_config || _.isUndefined(account.nsfs_account_config.uid) ||
+            _.isUndefined(account.nsfs_account_config.gid)) return false;
+        try {
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:676]: At this point we know that `account.nsfs_account_config.uid` and `account.nsfs_account_config.gid` are defined, we can define variables for easier readability:
const uid = account.nsfs_account_config.uid;
const gid = account.nsfs_account_config.gid;

File: src/test/unit_tests/test_bucketspace.js [hunk 21]
```diff
@@ -478,11 +478,21 @@ mocha.describe('bucket operations - namespace_fs', async function() {
...
+        const bucket = bucket_name + '-s3-2';
+        await s3_correct_dn_default_nsr.deleteBucket({ Bucket: bucket });
+        await fs_utils.file_must_not_exist(path.join(s3_new_buckets_path, bucket));
+        const res = await s3_correct_dn_default_nsr.listBuckets({});
+        console.log(inspect(res));
+        const list_ok = bucket_in_list([], [bucket_name + '-s3-2'], res.Buckets);
         assert.ok(list_ok);
+
```
Comment (shirady) [inline src/test/unit_tests/test_bucketspace.js:495]: redundant newline

File: src/test/unit_tests/test_bucketspace.js [hunk 22]
```diff
@@ -1532,7 +1433,294 @@ mocha.describe('nsfs account configurations', function() {
...
+        assert.equal(buckets.length, 2);
+        assert.deepStrictEqual(buckets, [accounts.account3.bucket, 'first.bucket']);
+    });
+});
+
 function get_tmp_path_by_os(_path) {
     return process.platform === MAC_PLATFORM ? '/private/' + _path : _path;
 }
 
+
```
Comment (shirady) [inline src/test/unit_tests/test_bucketspace.js:1608]: redundant newline

File: src/test/unit_tests/test_bucketspace.js [hunk 23]
```diff
@@ -1532,7 +1433,294 @@ mocha.describe('nsfs account configurations', function() {
...
+        nsfs_account_config,
+        default_resource
+    });
+    return {
+        access_key: account.access_keys[0].access_key.unwrap(),
+        secret_key: account.access_keys[0].secret_key.unwrap(),
+        email: `${random_name}@noobaa.com`
+    };
+}
+
```
Comment (shirady) [inline src/test/unit_tests/test_bucketspace.js:1658]: redundant newline

File: src/test/unit_tests/test_bucketspace.js [hunk 24]
```diff
@@ -1532,7 +1433,294 @@ mocha.describe('nsfs account configurations', function() {
...
+        }
+        assert.fail(`put_object failed ${err}, ${err.stack}`);
+    }
+
+    await s3_account.deleteObject({
+        Bucket: bucket,
+        Key: key,
+    });
+}
+
```
Comment (shirady) [inline src/test/unit_tests/test_bucketspace.js:1683]: redundant newline

**Comment by shirady** [comment]
@romayalon, general questions that this PR raised:
1. Would you please attach an explanation (or refer to a link) about the scope of the bucket policy that we support in NC NSFS? From the PR I understand that we check and validate 's3:ListBucket'.
2. In manage nsfs CLI the list buckets operation is done by the admin who is always the system owner, therefore we don't check bucket policy before the bucket list, is that correct?

File: src/sdk/bucketspace_fs.js (hunk 14 above)
Comment (romayalon) [reply src/sdk/bucketspace_fs.js:219]: I removed this variable, it was there for debugging

File: src/sdk/bucketspace_fs.js (hunk 16 above)
Comment (romayalon) [reply src/sdk/bucketspace_fs.js:633]: https://github.com/noobaa/noobaa-core/blob/master/src/server/common_services/auth_server.js#L673
it wasn't changed

File: src/sdk/bucketspace_fs.js (hunk 17 above)
Comment (romayalon) [reply src/sdk/bucketspace_fs.js:653]: it's the same as in https://github.com/noobaa/noobaa-core/blob/master/src/server/common_services/auth_server.js#L673

File: src/sdk/bucketspace_fs.js (hunk 20 above)
Comment (romayalon) [reply src/sdk/bucketspace_fs.js:676]: Please notice that declaring variables might be sometimes needed for readability like in path_to_check , but we should keep in mind that declaring variables can be very wasteful in space and memory.

Eventually, it was not needed because I decided to avoid redundant code and just call a function instead-
```
 const path_to_check = path.join(ns.write_resource.resource.fs_root_path, ns.write_resource.path || '');
 const fs_context = prepare_fs_context(object_sdk, ns.write_resource.resource.fs_backend);
```

File: src/sdk/bucketspace_fs.js (hunk 18 above)
Comment (romayalon) [reply src/sdk/bucketspace_fs.js:655]: req is needed when conditions are passed in order to run the condition's function.
see here - https://github.com/noobaa/noobaa-core/pull/7273

File: src/sdk/bucketspace_fs.js [hunk 25]
```diff
@@ -203,55 +205,27 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
-                warn_threshold_ms: config.NSFS_WARN_THRESHOLD_MS,
-            }, path.join(ns.write_resource.resource.fs_root_path, ns.write_resource.path || ''));
-
-            return true;
-        } catch (err) {
-            dbg.log0('_has_access_to_nsfs_dir: failed', err);
-            if (err.code === 'ENOENT' || err.code === 'EACCES' || (err.code === 'EPERM' && err.message === 'Operation not permitted')) return false;
-            throw err;
-        }
+        const buckets = await P.map_with_concurrency(10, entries, async entry => {
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:210]: Please add a comment before `map_with_concurrency` or in the JSDOC of the function with an explanation of the procedure (you can reuse the PR description).

File: src/sdk/bucketspace_fs.js [hunk 26]
```diff
@@ -203,55 +205,27 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+            if (native_fs_utils.isDirectory(entry) || !entry.name.endsWith('.json')) {
+                return;
+            }
+            const bucket_name = this.get_bucket_name(entry.name);
+            const bucket = await object_sdk.read_bucket_sdk_config_info(bucket_name);
+            const bucket_policy_accessible = await this.has_bucket_action_permission(bucket, account, 's3:ListBucket');
+            if (!bucket_policy_accessible) return;
+            const fs_accessible = await this.validate_fs_bucket_access(bucket, object_sdk);
+            if (!fs_accessible) return;
+            return bucket;
```
Comment (shirady) [inline src/sdk/bucketspace_fs.js:220]: Do you know why in the previous implementation `creation_date` was used? (It is not used in your new implementation).

File: src/test/unit_tests/nc_coretest.js [hunk 27]
```diff
@@ -375,7 +375,7 @@ function create_namespace_resource_mock(options) {
 async function create_bucket_manage(options) {
     const { resource, path } = options.namespace.write_resource;
     const bucket_storage_path = p.join(nsrs_to_root_paths[resource], path);
-    const cli_options = { name: options.name, owner: NC_CORETEST, path: bucket_storage_path};
+    const cli_options = { name: options.name, owner: options.owner || NC_CORETEST, path: bucket_storage_path};
```
Comment (shirady) [inline src/test/unit_tests/nc_coretest.js:378]: Why did you add this: `options.owner || NC_CORETEST`?

File: src/test/unit_tests/test_bucketspace.js [hunk 28]
```diff
@@ -1532,7 +1432,291 @@ mocha.describe('nsfs account configurations', function() {
...
+            const buckets = res.Buckets.map(bucket => bucket.Name).sort();
+            assert.equal(buckets.length, 2);
+            assert.deepStrictEqual(buckets, [account.bucket, 'first.bucket']);
+        }
+    });
+
+    mocha.it('account1 - all accounts are allowed to list bucket1', async function() {
+        // allow all accounts to list bucket1
+        const public_bucket = accounts.account1.bucket;
+        const bucket_policy = test_utils.generate_s3_policy('*', public_bucket, ['s3:*']);
```
Comment (shirady) [inline src/test/unit_tests/test_bucketspace.js:1546]: Why do you add all actions and not just the `'s3:ListBucket'`?

File: src/test/unit_tests/nc_coretest.js (hunk 27 above)
Comment (romayalon) [reply src/test/unit_tests/nc_coretest.js:378]: because we want to let to create buckets that their owner is not NC_CORETEST...

File: src/sdk/bucketspace_fs.js (hunk 26 above)
Comment (romayalon) [reply src/sdk/bucketspace_fs.js:220]: yes, it was a part of this fix - https://github.com/noobaa/noobaa-core/pull/7799
bucket contains creation date

**Review by shirady — APPROVED** [review]
LGTM

**Review by naveenpaul1 — APPROVED** [review]
LGTM

File: src/sdk/bucketspace_fs.js [hunk 29]
```diff
@@ -651,6 +637,68 @@ class BucketSpaceFS extends BucketSpaceSimpleFS {
...
+        const account = object_sdk.requesting_account;
+        dbg.log1('_has_access_to_nsfs_dir: nsr: ', ns, 'account.nsfs_account_config: ', account && account.nsfs_account_config);
+        // nsfs bucket
+        if (!account || !account.nsfs_account_config || _.isUndefined(account.nsfs_account_config.uid) ||
+            _.isUndefined(account.nsfs_account_config.gid)) return false;
+        try {
+            dbg.log1('_has_access_to_nsfs_dir: checking access:', ns.write_resource, account.nsfs_account_config.uid, account.nsfs_account_config.gid);
+            const path_to_check = path.join(ns.write_resource.resource.fs_root_path, ns.write_resource.path || '');
+            const fs_context = prepare_fs_context(object_sdk, ns.write_resource.resource.fs_backend);
+            await nb_native().fs.checkAccess(fs_context, path_to_check);
```
[the remark this answers is not in the document]
Comment (romayalon) [reply src/sdk/bucketspace_fs.js:694]: Hey @naveenpaul1 great question,
for listing buckets we need to check only read permissions so checkAccess() is the correct function to use,
But as part of https://github.com/noobaa/noobaa-core/pull/7775 we will merge the 2 functionalities so stay tuned :)
