### PR TITLE
Delete account should throw FORBIDDEN and not UNAUTHORIZED when it's owner of existing buckets

### LINKED ISSUE #7129: From HPO defect #923:  unexpected return code for error message `Cannot delete account that is owner of buckets`
From HPO defect: https://github.ibm.com/IBMSpectrumScale/hpo-core/issues/923

### Environment info
- OCP 4.11, ODF 4.11.4 and DAS is latest from the 516 branch

### Actual behavior
1. Trying to delete an account that has the buckets for the user, 
```
time="2022-12-10T15:00:16Z" level=info msg="Delete account Request is{token: XXX"api":"account_api","method":"delete_account","params":{"email":"[s3user5001@fvt.com](mailto:s3user5001@fvt.com)"}}"
time="2022-12-10T15:00:16Z" level=info msg="Noobaa uri is [https://noobaa-mgmt.openshift-storage.svc:443/rpc](https://noobaa-mgmt.openshift-storage.svc/rpc)"
time="2022-12-10T15:00:16Z" level=debug msg="Noobaa Response function"
time="2022-12-10T15:00:16Z" level=debug msg="Noobaa response is&{200 OK 200 HTTP/1.1 1 1 map[Access-Control-Allow-Credentials:[true] Access-Control-Allow-Headers:[Content-Type,Content-MD5,Authorization] Access-Control-Allow-Methods:[GET,POST,PUT,DELETE,OPTIONS] Access-Control-Allow-Origin:[*] Connection:[keep-alive] Date:[Sat, 10 Dec 2022 15:00:16 GMT] Keep-Alive:[timeout=5] X-Noobaa-Rpc-Body-Len:[192] X-Noobaa-Rpc-Version:[3120562176]] 0xc000324040 -1 [chunked] false false map[] 0xc00011a700 0xc0000f0420}"
time="2022-12-10T15:00:16Z" level=debug msg="Noobaa return response"
time="2022-12-10T15:00:16Z" level=debug msg="Noobaa account delete response body is{"op":"res","reqid":"1@https://::ffff:10.254.12.249:59082(20iono49jp)","took":0.7715280055999756,"error":{"message":"Cannot delete account that is owner of buckets","rpc_code":"UNAUTHORIZED"}}"
time="2022-12-10T15:00:16Z" level=debug msg="Error message appear in the response"
time="2022-12-10T15:00:16Z" level=debug msg="Response is Cannot delete account that is owner of buckets"
time="2022-12-10T15:00:16Z" level=error msg="Unauthorized Error "
```
The DAS log is shown `Unauthorized` error with return code 401.

### Expected behavior
For this case, DAS is expected return code other than 401, like 403.

### Steps to reproduce
1) create account
2) create buckets belong to this account
3) delete the account

### PR DESCRIPTION
**Pull request by romayalon**
Signed-off-by: Romy <romy2232@gmail.com>

### Explain the changes
1. changed the RPC error code
2. patched an old fix for delete_account() that needs to be also on delete_account_by_property() 
3. added a unit test

### Issues: Fixed #xxx / Gap #xxx
1. Fixed https://github.com/noobaa/noobaa-core/issues/7129

### Testing Instructions:
1. 

- [ ] Doc added/updated
- [x] Tests added

### CODE REVIEW

File: src/test/unit_tests/test_bucketspace.js [hunk 1]
```diff
@@ -578,7 +600,10 @@ async function update_account_nsfs_config(email, default_resource, new_nsfs_acco
 mocha.describe('list objects - namespace_fs', function() {
     const nsr = 'nsr1-list';
     const bucket_name = 'bucket-to-list1';
-    const tmp_fs_root = '/tmp/test_bucket_namespace_fs1';
+    let tmp_fs_root = '/tmp/test_bucket_namespace_fs1';
```
Comment (jackyalbo) [inline src/test/unit_tests/test_bucketspace.js:603]: maybe move to a function called get_tmp_fs_root or something and handle both for MAC and linux, WDYT?

File: src/server/system_services/account_server.js [hunk 2]
```diff
@@ -654,10 +654,13 @@ function delete_account_by_property(req) {
             if (!is_support_or_admin_or_me(req.system, req.account, account_to_delete)) {
                 throw new RpcError('UNAUTHORIZED', 'Cannot delete account');
             }
-            if (system_store.data.buckets.find(b => String(b.owner_account) === String(account_to_delete._id))) {
-                throw new RpcError('UNAUTHORIZED', 'Cannot delete account that is owner of buckets');
-            }
 
+            for (const bucket of system_store.data.buckets) {
```
Comment (jackyalbo) [inline src/server/system_services/account_server.js:658]: there is any change here except of the UNAUTHORIZED -> FORBIDDEN?
why can't we use the same logic? I also think this can maybe be a function called check_buckets_owner or something...

File: src/test/unit_tests/test_bucketspace.js (hunk 1 above)
Comment (romayalon) [reply src/test/unit_tests/test_bucketspace.js]: thanks!

File: src/server/system_services/account_server.js (hunk 2 above)
Comment (romayalon) [reply src/server/system_services/account_server.js]: yes I patched an old fix for delete_account() that needs to be also on delete_account_by_property()
moved the entire verification for both functions to a united function

File: src/test/unit_tests/test_bucketspace.js [hunk 3]
```diff
@@ -578,7 +597,7 @@ async function update_account_nsfs_config(email, default_resource, new_nsfs_acco
 mocha.describe('list objects - namespace_fs', function() {
     const nsr = 'nsr1-list';
     const bucket_name = 'bucket-to-list1';
-    const tmp_fs_root = '/tmp/test_bucket_namespace_fs1';
+    let tmp_fs_root = get_tmp_path_by_os('/tmp/test_bucket_namespace_fs1');
```
Comment (jackyalbo) [inline src/test/unit_tests/test_bucketspace.js:600]: it can still be const no? in all cases...
```suggestion
    const tmp_fs_root = get_tmp_path_by_os('/tmp/test_bucket_namespace_fs1');
```

File: src/test/unit_tests/test_bucketspace.js [hunk 4]
```diff
@@ -29,7 +30,7 @@ let new_account_params = {
 mocha.describe('bucket operations - namespace_fs', function() {
     const nsr = 'nsr';
     const bucket_name = 'src-bucket';
-    const tmp_fs_root = '/tmp/test_bucket_namespace_fs';
+    let tmp_fs_root = get_tmp_path_by_os('/tmp/test_bucket_namespace_fs');
```
Comment (jackyalbo) [inline src/test/unit_tests/test_bucketspace.js:33]:
```suggestion
    const tmp_fs_root = get_tmp_path_by_os('/tmp/test_bucket_namespace_fs');
```

File: src/test/unit_tests/test_bucketspace.js [hunk 5]
```diff
@@ -808,7 +826,7 @@ mocha.describe('nsfs account configurations', function() {
     const non_nsfs_bucket1 = 'first.bucket';
     const non_nsfs_bucket2 = 'second.bucket';
     const nsr2_connection = 'nsr2_connection';
-    const tmp_fs_root1 = '/tmp/test_bucket_namespace_fs2';
+    let tmp_fs_root1 = get_tmp_path_by_os('/tmp/test_bucket_namespace_fs2');
```
Comment (jackyalbo) [inline src/test/unit_tests/test_bucketspace.js:829]:
```suggestion
    const tmp_fs_root1 = get_tmp_path_by_os('/tmp/test_bucket_namespace_fs2');
```

**Review by jackyalbo — COMMENTED** [review]
Looks great!

**Review by jackyalbo — APPROVED** [review]

**Comment by romayalon** [comment]
@nimrod-becker @dannyzaken 
There is a request to backport it to 5.11.5/5.12, any news about it?

**Comment by nimrod-becker** [comment]
I think we can safely backport to 5.12.1, regarding 5.11 we need to discuss

**Comment by rkomandu** [comment]
How do we map with 5.12 and 5.11 ? we talk in terms of ODF 4.11 / 4.12

**Comment by nimrod-becker** [comment]
5.12 maps to ODF 4.12 and 5.11 to ODF 4.11

**Comment by rkomandu** [comment]
@nimrod-becker , we saw this broke in ODF as part of our DAS 516 release. There was a new code added to address Customer issue and it is required to have this fixed in ODF 4.11.x stream as mentioned earlier. Please check the feasibility

**Comment by rkomandu** [comment]
@nimrod-becker , the test was performed on ODF 4.12 GA code and it still shows the same error. Is the fix got into the ODF 4.12 or in Queue for 4.12.1?

**Comment by nimrod-becker** [comment]
4.12.1

**Comment by rkomandu** [comment]
@nimrod-becker , can we use the d/s builds(from Quay.io) and try it out or else need to wait ?

**Comment by rkomandu** [comment]
@nimrod-becker as of today 4.12.1-13 still doesn't have the fix yet looks like 

```
in our env ----> account delete  s3user6001@fvt.com
Got `Unauthorised` response from IBM Spectrum Scale GUI
For user ‘das-gui-user’, the password may be expired or invalid

[root@api.rkomandu-ocp412-hpo.cp.fyre.ibm.com cnsa-517-builds]# oc get csv -n openshift-storage -o yaml |grep full
      full_version: 4.12.1-13
      full_version: 4.12.1-13
      full_version: 4.12.1-13

```

**Comment by cxhong** [comment]
still has same error message on ODF 4.12.1
```
time="2023-02-15T13:52:07Z" level=info msg="Delete account Request is{token: XXX\"api\":\"account_api\",\"method\":\"delete_account\",\"params\":{\"email\":\"s3user6001@fvt.com\"}}"
time="2023-02-15T13:52:07Z" level=info msg="Noobaa uri is https://noobaa-mgmt.openshift-storage.svc:443/rpc"
time="2023-02-15T13:52:07Z" level=debug msg="Noobaa Response function"
time="2023-02-15T13:52:07Z" level=debug msg="Noobaa response is&{200 OK 200 HTTP/1.1 1 1 map[Access-Control-Allow-Credentials:[true] Access-Control-Allow-Headers:[Content-Type,Content-MD5,Authorization] Access-Control-Allow-Methods:[GET,POST,PUT,DELETE,OPTIONS] Access-Control-Allow-Origin:[*] Connection:[keep-alive] Date:[Wed, 15 Feb 2023 13:52:07 GMT] Keep-Alive:[timeout=5] X-Noobaa-Rpc-Body-Len:[190] X-Noobaa-Rpc-Version:[3120562176]] 0xc0003a2200 -1 [chunked] false false map[] 0xc000224000 0xc000788000}"
time="2023-02-15T13:52:07Z" level=debug msg="Noobaa return response"
time="2023-02-15T13:52:07Z" level=debug msg="Noobaa account delete response body is{\"op\":\"res\",\"reqid\":\"1@https://::ffff:10.254.17.193:39558(6vh7sws28)\",\"took\":1.727427002042532,\"error\":{\"message\":\"Cannot delete account that is owner of buckets\",\"rpc_code\":\"UNAUTHORIZED\"}}"
time="2023-02-15T13:52:07Z" level=debug msg="Error message appear in the response"
time="2023-02-15T13:52:07Z" level=debug msg="Response is Cannot delete account that is owner of buckets"
time="2023-02-15T13:52:07Z" level=error msg="Unauthorized Error "
```

**Comment by rkomandu** [comment]
Nimrod and Romy any update on this. Fix isn't available in the ODF 4.12.1 d/s as well
