### PR TITLE
NSFS | MPU | optimization

### LINKED ISSUE #7348: NSFS Presto uploads large file as multiparts, calls complete with short timeout, causing retries and race on the mpu dir
### Environment info
- NooBaa Version: **5.10**
- Platform: **OpenShift 4.10**

### Actual behavior
1. NSFS complete_multipart_upload copies the parts one by one to a final file, and once it's done it moves the final file to target dir and deletes the parts files.
2. For 8 GB files, the default timeout of presto for the complete call is too short (few seconds), and then it aborts and sends second and third retries.
3. Presto will give up anyway, but we also see the retries print errors in the log of "No such file or directory", because the first complete request will eventually finish copying the data and then goes and deletes the part files, failing the other requests.

### Expected behavior
1. We should prefer to upload parts directly to the final file by offset if possible.
2. If not possible, we somehow need to "lock" the multipart directory to prevent more than one requests modifying it.

### Steps to reproduce
1. Presto write large files to S3 endpoints.

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. 

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #7348 

### Testing Instructions:
1. 

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

**Review by liranmauda — APPROVED** [review]
Some comments but LGTM

File: src/sdk/namespace_fs.js [hunk 1]
```diff
@@ -1465,76 +1529,133 @@ class NamespaceFS {
...
+
+    async _copy_bytes(fs_context, src_file, dst_file, size, write_offset, read_offset) {
+        dbg.log0(`NamespaceFS._copy_bytes size=${size} read_offset=${read_offset} write_offset=${write_offset}`);
+        let buffer_pool_cleanup = null;
+        try {
+            let read_pos = Number(read_offset || 0);
+            let bytes_written = 0;
+            const total_bytes_to_write = Number(size);
+            let write_pos = Number(write_offset || 0);
+            for (;;) {
```
[the remark this answers is not in the document]
Comment (romayalon) [reply src/sdk/namespace_fs.js:1608]: I passed this one because while(true) throws eslint error on constant condition

File: src/sdk/namespace_fs.js [hunk 2]
```diff
@@ -1390,35 +1398,89 @@ class NamespaceFS {
...
+
+            const md_upload_path = this._get_part_md_path(params);
+            part_md_file = await this._open_file(fs_context, md_upload_path, md_open_mode);
+            let md_upload_params = {
+                fs_context, params, object_sdk, upload_path: md_upload_path, open_mode: md_open_mode,
+                target_file: part_md_file, file_path: md_upload_path
+            };
+
+            let upload_res;
+            const pre_known_size = params.size;
```
Comment (guymguym) [inline src/sdk/namespace_fs.js:1437]: change to boolean to allow size 0 parts (theoretic)
```suggestion
             pre_known_size = (size >= 0);
```

File: src/sdk/namespace_fs.js [hunk 3]
```diff
@@ -1390,35 +1398,89 @@ class NamespaceFS {
...
+            if (!pre_known_size) {
+                // 2.1
+                upload_res = await buffers_pool_sem.surround_count(config.NSFS_BUF_SIZE, async () => this._upload_stream(md_upload_params));
+                params.size = upload_res.total_bytes;
+            }
+            const offset = params.size * (params.num - 1);
+            const upload_path = this._get_part_data_path(params);
+            try {
+                await nb_native().fs.stat(fs_context, upload_path);
```
Comment (guymguym) [inline src/sdk/namespace_fs.js:1446]: add comment - why we stat here?

File: src/sdk/namespace_fs.js [hunk 4]
```diff
@@ -1390,35 +1398,89 @@ class NamespaceFS {
...
+    //    2.1. upload data to part_md_file
+    //    2.2. calc offset
+    //    2.3. copy the bytes to by_size file
+    //    2.4. set on the part_md_file size, offset and etag xattr
     async upload_multipart(params, object_sdk) {
-        // We can use 'wt' for open mode like we do for upload_object() when
-        // we figure out how to create multipart upload using temp files.
-        const open_mode = 'w';
+        let open_mode = 'r+';
+        const md_open_mode = 'w+';
```
Comment (guymguym) [inline src/sdk/namespace_fs.js:1421]: we can add a single open mode if that can help here -
```
    { "w*", O_CREAT | O_RDWR },
```

File: src/sdk/namespace_fs.js [hunk 5]
```diff
@@ -1464,77 +1534,137 @@ class NamespaceFS {
...
         } catch (err) {
             dbg.error(err);
             throw this._translate_object_error_codes(err);
         } finally {
-            await this.complete_object_upload_finally(buffer_pool_cleanup, read_file, target_file, fs_context);
+            await this.complete_object_upload_finally(undefined, [...part_size_to_fd_map.values()], target_file, fs_context);
+        }
+    }
+
+    async _copy_bytes(fs_context, src_file, dst_file, size, write_offset, read_offset) {
```
Comment (guymguym) [inline src/sdk/namespace_fs.js:1609]: extract to util

File: src/sdk/namespace_fs.js [hunk 6]
```diff
@@ -39,6 +39,9 @@ const XATTR_USER_PREFIX = 'user.';
 // TODO: In order to verify validity add content_md5_mtime as well
 const XATTR_CONTENT_TYPE = XATTR_USER_PREFIX + 'content_type';
 const XATTR_MD5_KEY = XATTR_USER_PREFIX + 'content_md5';
+const XATTR_PART_OFFSET = XATTR_USER_PREFIX + 'part_offset';
+const XATTR_PART_SIZE = XATTR_USER_PREFIX + 'part_size';
+const XATTR_PART_ETAG = XATTR_USER_PREFIX + 'part_etag';
```
Comment (guymguym) [inline src/sdk/namespace_fs.js:44]: add noobaa prefix - user.noobaa.xattrname
we want for the internal xattrs, i.e ones that we do not want others to rely on, we want to add the noobaa prefix.

**Review by guymguym — CHANGES_REQUESTED** [review]

File: src/native/fs/fs_napi.cpp [hunk 7]
```diff
@@ -1397,22 +1397,31 @@ struct FileWrite : public FSWrapWorker<FileWrap>
...
     }
     virtual void Work()
     {
         int fd = _wrap->_fd;
         CHECK_WRAP_FD(fd);
-        // TODO: Switch to pwrite when needed
-        ssize_t bw = write(fd, _buf, _len);
+        ssize_t bw = -1;
+        if (_offset == 0) {
+            bw = write(fd, _buf, _len);
```
[the remark this answers is not in the document]
Comment (romayalon) [reply src/native/fs/fs_napi.cpp]: done

File: src/sdk/namespace_fs.js (hunk 3 above)
Comment (romayalon) [reply src/sdk/namespace_fs.js]: with the new open mode - w*, the stat is redundant, I removed it

File: src/sdk/namespace_fs.js (hunk 4 above)
Comment (romayalon) [reply src/sdk/namespace_fs.js]: instead, what I did it to use * as truncate remover, let me know what you think

Comment (guymguym) [reply src/sdk/namespace_fs.js]: I'd summon @eshelmarc to comment on that. WDYT on this mode. We don't want to truncate, but keep writing to the file in offsets that are multiplies of the part size. Romy said that O_APPEND is also not suitable so we wanted to open with just O_CREAT - Does this make sense?

File: src/util/chunk_fs.js [hunk 8]
```diff
@@ -57,6 +61,7 @@ class ChunkFS extends stream.Transform {
                 if (this.q_buffers.length === this.iov_max || this.q_size >= config.NSFS_BUF_SIZE) await this._flush_buffers();
                 chunk = (available_size < chunk.length) ? chunk.slice(available_size) : null;
             }
+            this.total_bytes += this.q_size;
```
Comment (guymguym) [inline src/util/chunk_fs.js:64]: I would prefer to count it inside flush right next to where we handle _total_num_buffers and offset.
I understand that we are counting the input bytes and the output bytes are the same, only that the timing and error cases is different, so I would count bytes that we already output, and that's only known inside flush.

File: src/util/native_fs_utils.js [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+
+
+async function copy_bytes(buffers_pool, fs_context, src_file, dst_file, size, write_offset, read_offset) {
+    dbg.log1(`NamespaceFS._copy_bytes size=${size} read_offset=${read_offset} write_offset=${write_offset}`);
+    let buffer_pool_cleanup = null;
+    try {
+        let read_pos = Number(read_offset || 0);
+        let bytes_written = 0;
+        const total_bytes_to_write = Number(size);
+        let write_pos = Number(write_offset || 0);
```
Comment (guymguym) [inline src/util/native_fs_utils.js:14]:
```suggestion
        let write_pos = write_offset >= 0 ? write_offset : 0;
```

File: src/util/native_fs_utils.js [hunk 10]
```diff
@@ -0,0 +1,50 @@
+/* Copyright (C) 2016 NooBaa */
+'use strict';
+
+const dbg = require('../util/debug_module')(__filename);
+
+
+async function copy_bytes(buffers_pool, fs_context, src_file, dst_file, size, write_offset, read_offset) {
```
Comment (guymguym) [inline src/util/native_fs_utils.js:7]: add jsdoc with types

File: src/sdk/namespace_fs.js [hunk 11]
```diff
@@ -1390,35 +1393,82 @@ class NamespaceFS {
...
+            const upload_info = await this._finish_upload(md_upload_params);
             return upload_info;
         } catch (err) {
             this.run_update_issues_report(object_sdk, err);
             throw this._translate_object_error_codes(err);
         } finally {
             try {
-                if (target_file) await target_file.close(fs_context);
+                if (target_file) target_file.close(fs_context);
+                if (part_md_file) part_md_file.close(fs_context);
```
Comment (guymguym) [inline src/sdk/namespace_fs.js:1464]: need to await each one individually. I think its time we have a small util function `native_fs_utils.finally_close_files(list_of_files)` that takes a list of files and calls close() on all (maybe with P.map with some small concurrency like 4) and catches the errors on each one individually to print to the log, but it should not throw so that we can call it in finally.
