### PR TITLE
NSFS | NC | Split The Error "Account config should not be empty"

### LINKED ISSUE #7651: Missing any parameter is causing the invalid error proper error message should be displayed
### Environment info
- NooBaa Version: noobaa-core-5.15.0-20231207-master.el8.x86_64.rpm
- Platform: standalone

### Actual behavior
node src/cmd/manage_nsfs account add --name noobaa1 --email noobaa@gmail.com --new_buckets_path /ibm/fs1/tes  --gid 1 --access_key 22w3 --secret_key 2w34 2>/dev/null 
Error: Account config should not be empty
Help:

    "nsfs" is a noobaa-core command runs a local S3 endpoint on top of a filesystem.
    Each sub directory of the root filesystem represents an S3 bucket.
    manage nsfs will provide a command line interface to create new accounts and map existing directories 
    to Noobaa as buckets. For more information refer to the noobaa docs.
Usage:

    node src/cmd/manage_nsfs <type> <action> [options...]
Arguments:

    <type>    Set the resource type such as accounts and buckets
    <action>  Action could be add, update, list, status and delete for accounts/buckets.
Account Options:

    # Read account details from the JSON file, there is no need to mention all the properties one by one in the CLI
    --from_file <dir>                       (default none)                  Set account schema full path.
                                                                            Get account details from JSON file                
    --config_root_backend <none | GPFS >    (default none)                  Set the config_root FS type to be GPFS

    # required for add, update 
    --name <name>               (default none)                              Set the name for the account.
    --email <email>             (default none)                              Set the email for the account.
    --new_name <name>           (default none)                              Set a new name for the account (update).
    --uid <uid>                 (default as process)                        Send requests to the Filesystem with uid.
    --gid <gid>                 (default as process)                        Send requests to the Filesystem with gid.
    --secret_key <key>          (default none)                              The secret key pair for the access key.
    --new_buckets_path <dir>    (default none)                              Set the filesystem's root where each subdir is a bucket.
    
    # required for add, update, and delete
    --access_key <key>          (default none)                              Authenticate incoming requests for this access key only (default is no auth).
    --new_access_key <key>      (default none)                              Set a new access key for the account.
    --config_root <dir>         (default config.NSFS_NC_DEFAULT_CONF_DIR)   Configuration files path for Noobaa standalon NSFS.

    # Used for list
    --wide                      (default none)                              Will print the list with details (same as status but for all accounts)

### Expected behavior
1. if more than one parameter missing just display help

### Steps to reproduce
1.

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. Split the error `Account config should not be empty`.

### Issues: Fixed #7651
1. Currently the error `Account config should not be empty` is not indicative enough.

### Testing Instructions:
1. Manual tests: create account without gid, uid, user, examples:
- `sudo node src/cmd/manage_nsfs account add --name <account-name> --email <email> --new_buckets_path <path>` (without any configurations)
- `sudo node src/cmd/manage_nsfs account add --name <account-name> --email <email> --new_buckets_path <path> --uid <uid>` (without gid)
- `sudo node src/cmd/manage_nsfs account add --name <account-name> --email <email> --new_buckets_path <path> --gid <gid>` (without uid)
2. For running the unit test with the new test, please run: `sudo node ./node_modules/.bin/_mocha src/test/unit_tests/test_nc_nsfs_cli.js`.

- [ ] Doc added/updated
- [X] Tests added

### CODE REVIEW

File: src/cmd/manage_nsfs.js [hunk 1]
```diff
@@ -795,6 +795,12 @@ async function validate_account_args(data, action) {
 
         if (is_undefined(data.access_keys[0].secret_key)) throw_cli_error(ManageCLIError.MissingAccountSecretKeyFlag);
         if (is_undefined(data.access_keys[0].access_key)) throw_cli_error(ManageCLIError.MissingAccountAccessKeyFlag);
+        if (data.nsfs_account_config.gid && (is_undefined(data.nsfs_account_config.uid))) {
+            throw_cli_error(ManageCLIError.InvalidAccountNSFSConfigUID, data.nsfs_account_config);
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:799]:
```suggestion
            throw_cli_error(ManageCLIError.MissingAccountNSFSConfigUID, data.nsfs_account_config);
```
we already have ManageCLIError.InvalidAccountUID and it's not the appropriate message, I think that missing is the correct term for this issue, please change here and for gid also

**Review by romayalon — APPROVED** [review]
one comment regarding the error name

File: src/cmd/manage_nsfs.js (hunk 1 above)
Comment (shirady) [reply src/cmd/manage_nsfs.js]: I will change it, thanks.
