### PR TITLE
NC | CLI | CLI errors handling when master key is invalid

### LINKED ISSUE #8083: Account delete is not allowing when master keys gets updated/changed
### Environment info
- NooBaa Version: 5.15.3
- Platform: standalone

### Actual behavior
noobaa-cli account delete --name test 2>/dev/null
{
  "error": {
    "code": "InternalError",
    "message": "The server encountered an internal error. Please retry the request",
    "detail": "Error: master key id is missing in master_keys_by_id\n    at NCMasterKeysManager.decryptSync (/usr/local/noobaa-core/src/manage_nsfs/nc_master_key_manager.js:305:59)\n    at NCMasterKeysManager.decrypt (/usr/local/noobaa-core/src/manage_nsfs/nc_master_key_manager.js:294:21)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /usr/local/noobaa-core/src/manage_nsfs/nc_master_key_manager.js:335:29\n    at async Promise.all (index 0)\n    at async NCMasterKeysManager.decrypt_access_keys (/usr/local/noobaa-core/src/manage_nsfs/nc_master_key_manager.js:333:39)\n    at async fetch_existing_account_data (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:416:30)\n    at async fetch_account_data (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:385:16)\n    at async account_management (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:336:18)\n    at async main (/usr/local/noobaa-core/src/cmd/manage_nsfs.js:112:13)"
  }
}

### Expected behavior
1.

### Steps to reproduce
1.

### LINKED ISSUE #8084: Account status with show_secrets is not working when master_keys gets updated/changed
### Environment info
- NooBaa Version: 5.15.3
- Platform: standalone

### Actual behavior

noobaa-cli account status --name test 2>/dev/null
{
  "response": {
    "code": "AccountStatus",
    "reply": {
      "_id": "665035e800ed1d249be19986",
      "name": "test",
      "email": "test",
      "creation_date": "2024-05-24T06:38:32.179Z",
      "nsfs_account_config": {
        "uid": 10,
        "gid": 10,
        "new_buckets_path": "/mnt/gpfs0/test",
        "fs_backend": "GPFS"
      },
      "allow_bucket_creation": true,
      "master_key_id": "6650357884f47e736e1db1ee"
    }
  }
}
noobaa-cli account status --name test --show_secrets 2>/dev/null
{
  "error": {
    "code": "NoSuchAccountName",
    "message": "Account does not exist - name",
    "detail": "test"
  }
}

### Expected behavior
1.

### Steps to reproduce
1.

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. **manage_nsfs.js -** 
- Account Delete - skipped the decryption in this case as we might want to delete accounts even if master key has issues.
- Account status --show_secrets / Account update - 

2. **manage_nsfs_cli_errors.js -** Created a new CLI error InvalidMasterKey and added a mapping between RPC INVALID_MASTER_KEY to InvalidMasterKey.

3. **nc_master_key_manager.js -** threw INVALID_MASTER_KEY and changed the error messages to be more accurate.

4. **test_nc_account_invalid_mkm_intergration.test.js -** added integration tests for scenarios of CLI account functions and missing/corrupted master key file.

5. **test_nc_master_keys.test.js** - updated errors on tests and added a new empty file case.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #8083
2. Fixed #8084 

### Testing Instructions:
1. Automatic -
```
sudo jest --testRegex=jest_tests/test_nc_master_keys.test.js
sudo jest --testRegex=jest_tests/test_nc_account_invalid_mkm
```
Manual - 
There are many scenarios for testing it - 
1. `sudo node src/cmd/manage_nsfs account add --name=account1 --allow_bucket_creation=true --uid=0 --gid=0  --new_buckets_path=/tmp/new_buckets_path1/`
2. delete or corrupt /etc/noobaa.conf.d/master_keys.json
3. Run `sudo node src/cmd/manage_nsfs account update --name account1 --uid=1111` and expect the following error instead of an internal error - 
```
{
  "error": {
    "code": "InvalidMasterKey",
    "message": "Master key manager had issues loading master key, can not decrypt/encrypt secrets.",
    "detail": "Error: master key id is missing in master_keys_by_id\n    at NCMasterKeysManager._validate_master_key_manager (noobaa-core/src/manage_nsfs/nc_master_key_manager.js:347:59)\n    at NCMasterKeysManager.decryptSync (noobaa-core/src/manage_nsfs/nc_master_key_manager.js:305:14)\n    at NCMasterKeysManager.decrypt (noobaa-core/src/manage_nsfs/nc_master_key_manager.js:295:21)\n    at asyncnoobaa-core/src/manage_nsfs/nc_master_key_manager.js:335:29\n    at async Promise.all (index 0)\n    at async NCMasterKeysManager.decrypt_access_keys (noobaa-core/src/manage_nsfs/nc_master_key_manager.js:333:39)\n    at async fetch_existing_account_data (noobaa-core/src/cmd/manage_nsfs.js:376:54)\n    at async fetch_account_data (noobaa-core/src/cmd/manage_nsfs.js:341:16)\n    at async account_management (noobaa-core/src/cmd/manage_nsfs.js:291:18)\n    at async main (noobaa-core/src/cmd/manage_nsfs.js:91:13)"
  }
}
```
4. `sudo node src/cmd/manage_nsfs account status --name account1 --show_secrets` and expect the same error as in the previous bullet.
5. `sudo node src/cmd/manage_nsfs account delete --name account1` - should expect a successful response and account be deleted from `/etc/noobaa.conf.d/accounts/` and from `/etc/noobaa.conf.d/access_keys`-
```
{
  "response": {
    "code": "AccountDeleted"
  }
}
```
- [ ] Doc added/updated
- [x] Tests added

### CODE REVIEW

**Review by guymguym — APPROVED** [review]

**Comment by romayalon** [comment]
@guymguym I added more rpc errors in the new commit, please re-review

File: src/manage_nsfs/manage_nsfs_cli_errors.js [hunk 1]
```diff
@@ -141,6 +141,30 @@ ManageCLIError.WhiteListIPUpdateFailed = Object.freeze({
...
 });
 
+ManageCLIError.InvalidMasterKey = Object.freeze({
+    code: 'InvalidMasterKey',
+    message: 'Master key manager had issues loading master key, can not decrypt/encrypt secrets.',
+    http_code: 500,
+});
+
+ManageCLIError.InvalidMasterKeyStoreType = Object.freeze({
+    code: 'InvalidMasterKeyStoreType',
```
Comment (guymguym) [inline src/manage_nsfs/manage_nsfs_cli_errors.js:151]: the question if more specific codes are needed here because any client is interested to differentiate between these cases? if these are just for information then using the same code with a different message is better because it will allow clients to identify this error with a single error code...

Comment (romayalon) [reply src/manage_nsfs/manage_nsfs_cli_errors.js:151]: I wanted to make sure the client won't receive InternalError code and have a clear understanding of the failure.
A single error code and different error messages should be enough, thanks!

**Review by guymguym — APPROVED** [review]
