### PR TITLE
NSFS | Healthcheck is not reporting error for buckets with out access

### LINKED ISSUE #8428: Healthcheck is not reporting error for buckets with out access
### Environment info
- NooBaa Version: **noobaa-core-5.17.0-20240926.el9.x86_64**
- Platform: **Standalone Noobaa**

### Actual behavior
This test includes parameter "NC_DISABLE_ACCESS_CHECK=true"
1. If the account does not have access(r) to buckets directory path, health check should report this as an error.

### Expected behavior
1. Buckets are displayed as healthy even though account does not have access (r) bucket's directory path

### Steps to reproduce
1. set "NC_DISABLE_ACCESS_CHECK=true"
2. Create an account with proper access to its newbuckets path. (account-3)
3. Create a new directory with owner as root and mod bits 770
[root@522new-41 ~]# ls -ld /mnt/gpfs0/buck3/
drwxrwx---. 2 root root 4096 Oct  3 11:20 /mnt/gpfs0/buck3/

4. Create a bucket with account-3. This succeeds as the RW access check is turned off.
5. Change "NC_DISABLE_ACCESS_CHECK=false"
6. All other accounts with no access to --newbuckets path are shown as error. However buck3 is not showing any error as part of health check.

```
[root@522new-41 ~]# noobaa-cli diagnose health --all_bucket_details 2>/dev/null
{
  "response": {
    "code": "HealthStatus",
    "reply": {
      "service_name": "noobaa",
      "status": "OK",
      "memory": "316.7M",
      "checks": {
        "services": [
          {
            "name": "noobaa",
            "service_status": "active",
            "pid": "1367807"
          }
        ],
        "endpoint": {
          "endpoint_state": {
            "response": {
              "response_code": "RUNNING",
              "response_message": "Endpoint running successfuly."
            },
            "total_fork_count": 2,
            "running_workers": [
              2,
              1
            ]
          },
          "error_type": "TEMPORARY"
        },
        "buckets_status": {
          "invalid_buckets": [],
          "valid_buckets": [
            {
              "name": "buck3",
              "storage_path": "/mnt/gpfs0/buck3/"
            },
            {
              "name": "buck1",
              "storage_path": "/mnt/gpfs0/test/account-75000/buck1"
            },
            {
              "name": "buck2",
              "storage_path": "/mnt/gpfs0/test/account-75000/buck2"
            }
          ],
          "error_type": "PERSISTENT"
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by naveenpaul1**
### Explain the changes
1. user account specific context for checking bucket storage, not the root context
2. add test to validate bucket owner and modify invalid storage check to identify storage condition

### Issues: Fixed #xxx / Gap #xxx
1. https://github.com/noobaa/noobaa-core/issues/8428

### Testing Instructions:
1. Please check the same issue 

- [X] Doc added/updated
- [X] Tests added

### CODE REVIEW

File: src/manage_nsfs/health.js [hunk 1]
```diff
@@ -498,16 +525,21 @@ async function is_new_buckets_path_valid(config_file_path, config_data, new_buck
...
  * @returns {Promise<object>}
  */
-async function is_bucket_storage_path_exists(fs_context, config_data, storage_path) {
+async function is_bucket_storage_and_owner_exists(fs_context, config_data, storage_path) {
     let res_obj;
     try {
         if (!_should_skip_health_access_check()) {
+            if (!fs_context) {
+                const new_err = new Error('ACCESS DENIED');
+                new_err.code = 'OWNERMISSING';
```
Comment (romayalon) [inline src/manage_nsfs/health.js:540]:
```suggestion
                new_err.code = 'INVALID_ACCOUNT_OWNER';
```

File: src/manage_nsfs/health.js [hunk 2]
```diff
@@ -498,16 +525,21 @@ async function is_new_buckets_path_valid(config_file_path, config_data, new_buck
...
  * @param {object} config_data
  * @param {string} storage_path
  * @returns {Promise<object>}
  */
-async function is_bucket_storage_path_exists(fs_context, config_data, storage_path) {
+async function is_bucket_storage_and_owner_exists(fs_context, config_data, storage_path) {
     let res_obj;
     try {
         if (!_should_skip_health_access_check()) {
+            if (!fs_context) {
```
Comment (romayalon) [inline src/manage_nsfs/health.js:538]: fs_context missing doesn't mean OWNER_MISSING, maybe invalid

File: src/manage_nsfs/health.js [hunk 3]
```diff
@@ -364,7 +369,8 @@ class NSFSHealth {
                 const config_file_path = this.config_fs.get_account_path_by_name(config_file_name);
                 res = await is_new_buckets_path_valid(config_file_path, config_data, storage_path);
             } else if (type === TYPES.BUCKET) {
-                res = await is_bucket_storage_path_exists(this.config_fs.fs_context, config_data, storage_path);
+                const account_fs_context = await this.get_account_owner_context(config_data.name, config_data.owner_account);
```
Comment (romayalon) [inline src/manage_nsfs/health.js:372]: can you move account_fs_context to be inside is_bucket_storage_and_owner_exists(), I don't see anymore usage of it outside, do I miss something?

File: src/manage_nsfs/health.js [hunk 4]
```diff
@@ -378,6 +384,27 @@ class NSFSHealth {
...
+ * @returns {Promise<object>}
+ */
+    async get_account_owner_context(name, owner_account) {
+        let account_fs_context;
+        try {
+            if (owner_account) {
+                const owner_account_data = await get_bucket_owner_account_by_id(this.config_fs, owner_account);
+                account_fs_context = await native_fs_utils.get_fs_context(owner_account_data.nsfs_account_config,
+                                        owner_account_data.nsfs_account_config.fs_backend);
+            }
```
Comment (romayalon) [inline src/manage_nsfs/health.js:400]: why not throw an error from here? instead of checking if it's undefined outside and then throw an error

File: docs/NooBaaNonContainerized/Health.md [hunk 5]
```diff
@@ -351,3 +351,10 @@ The following error codes will be associated with a specific Bucket or Account s
   - Resolutions:
     - Check for FS user on the host running the Health CLI.
 
+#### 6. Bucket missing valid account owner
+  - Error code: `INVALID_ACCOUNT_OWNER`
+  - Error message: Bucket account owner was not found.
```
Comment (romayalon) [inline docs/NooBaaNonContainerized/Health.md:356]: this needs to be updated as well

File: src/manage_nsfs/health.js [hunk 6]
```diff
@@ -52,6 +52,10 @@ const health_errors = {
         error_code: 'INVALID_DISTINGUISHED_NAME',
         error_message: 'Account distinguished name was not found',
     },
+    INVALID_ACCOUNT_OWNER: {
+        error_code: 'INVALID_ACCOUNT_OWNER',
+        error_message: 'Bucket account owner was not found',
```
Comment (romayalon) [inline src/manage_nsfs/health.js:57]: here update as well please

File: src/manage_nsfs/health.js [hunk 7]
```diff
@@ -519,13 +525,34 @@ async function is_bucket_storage_path_exists(fs_context, config_data, storage_pa
...
+            err_code = health_errors.INVALID_ACCOUNT_OWNER.error_code;
         }
         res_obj = get_invalid_object(config_data.name, undefined, storage_path, err_code);
     }
     return res_obj;
 }
 
-
+/**
+ * get_config_file_data_or_error_object return an object containing config_data or err_obj if error occurred
```
Comment (romayalon) [inline src/manage_nsfs/health.js:538]: update comment

File: src/manage_nsfs/health.js [hunk 8]
```diff
@@ -519,13 +525,34 @@ async function is_bucket_storage_path_exists(fs_context, config_data, storage_pa
         } else if (err.code === 'EACCES' || (err.code === 'EPERM' && err.message === 'Operation not permitted')) {
             dbg.log1('Error:  Storage path should be accessible to account: ', storage_path);
             err_code = health_errors.ACCESS_DENIED.error_code;
+        } else if (err.code === 'BucketSetForbiddenBucketOwnerNotExists') {
```
Comment (romayalon) [inline src/manage_nsfs/health.js:528]: something is not clear here, BucketSetForbiddenBucketOwnerNotExists should be mapped MISSING_OWNER I meant to have INVALID_OWNER when the get_fs_context() threw an error.

File: src/manage_nsfs/health.js [hunk 9]
```diff
@@ -519,13 +525,34 @@ async function is_bucket_storage_path_exists(fs_context, config_data, storage_pa
...
+ * @returns {Promise<object>}
+ */
+async function get_account_owner_context(config_fs, owner_account) {
+    if (!owner_account) {
+        const detail_msg = `bucket owner account is empty`;
+        throw_cli_error(ManageCLIError.BucketSetForbiddenBucketOwnerNotExists, detail_msg);
+    }
+    // when account owner is invalid method will throw error
+    const owner_account_data = await get_bucket_owner_account_by_id(config_fs, owner_account);
+    if (owner_account_data) {
```
Comment (romayalon) [inline src/manage_nsfs/health.js:550]: please throw a MISSING_ACCOUNT_OWNER error if owner_account_data is undefined, we don't want to return undefined

File: src/manage_nsfs/health.js [hunk 10]
```diff
@@ -85,6 +89,7 @@ process.env.AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE = '1';
  */
 class NSFSHealth {
     constructor(options) {
+        this.config_root = options.config_root;
```
Comment (romayalon) [inline src/manage_nsfs/health.js:92]: why this is needed?
you can get it from config_fs.config_root

File: src/manage_nsfs/health.js (hunk 8 above)
Comment (naveenpaul1) [reply src/manage_nsfs/health.js:528]: `BucketSetForbiddenBucketOwnerNotExists` thrown from method `get_bucket_owner_account_by_id()` we are catching it here

File: src/manage_nsfs/health.js (hunk 9 above)
Comment (naveenpaul1) [reply src/manage_nsfs/health.js:550]: get_bucket_owner_account_by_id() will throw error if owner account is missing

Comment (romayalon) [reply src/manage_nsfs/health.js]: so why you check if (owner_account_data) ? is there a possibility it's undefined? if it undefined, what should we do with it?

Comment (naveenpaul1) [reply src/manage_nsfs/health.js]: @romayalon this is lo code and that check is removed, get_bucket_owner_account_by_id() is throwing error when owner_account is invalid, we are already doing empty check.

File: src/manage_nsfs/health.js [hunk 11]
```diff
@@ -519,13 +528,40 @@ async function is_bucket_storage_path_exists(fs_context, config_data, storage_pa
         } else if (err.code === 'EACCES' || (err.code === 'EPERM' && err.message === 'Operation not permitted')) {
             dbg.log1('Error:  Storage path should be accessible to account: ', storage_path);
             err_code = health_errors.ACCESS_DENIED.error_code;
+        } else if (err.code === health_errors.INVALID_ACCOUNT_OWNER.error_code ||
+                err.code === health_errors.MISSING_ACCOUNT_OWNER.error_code) {
+            dbg.log1('Error: Bucket account owner should be valid account id ', config_data.owner_account);
```
Comment (romayalon) [inline src/manage_nsfs/health.js:533]: I suggest seperate it to 2 different cases or say `... existing and valid account`

File: src/manage_nsfs/health.js [hunk 12]
```diff
@@ -519,13 +528,40 @@ async function is_bucket_storage_path_exists(fs_context, config_data, storage_pa
...
+            err_code = err.code;
         }
         res_obj = get_invalid_object(config_data.name, undefined, storage_path, err_code);
     }
     return res_obj;
 }
 
-
+/**
+ * get_account_owner_context return bucket account owner specific context
```
Comment (romayalon) [inline src/manage_nsfs/health.js:542]:
```suggestion
 * get_account_owner_context returns bucket account owner specific FS context
```

**Review by romayalon — APPROVED** [review]
Looks good, 2 minor suggestions

File: src/sdk/accountspace_fs.js [hunk 13]
```diff
@@ -31,11 +31,14 @@ const account_id_cache = new LRUCache({
...
-     * @param {{ _id: string, config_fs: import('./config_fs').ConfigFS }} params
+     * @param {{ _id: string, 
+     * show_secrets: boolean,
+     * decrypt_secret_key: boolean, 
+     * config_fs: import('./config_fs').ConfigFS }} params
      */
     make_key: ({ _id }) => _id,
-    load: async ({ _id, config_fs }) => config_fs.get_identity_by_id(_id, CONFIG_TYPES.ACCOUNT,
-        { show_secrets: true, decrypt_secret_key: true }),
+    load: async ({ _id, show_secrets, decrypt_secret_key, config_fs}) => config_fs.get_identity_by_id(_id, CONFIG_TYPES.ACCOUNT,
```
Comment (romayalon) [inline src/sdk/accountspace_fs.js:40]: this looks dangerous IMO, we don't want to have an account cache that has in it missing/encryped secret key, this could lead to runtime bugs
this cache code is being used by manage_nsfs and the endpoint, I believe people won't use it carefully
