### PR TITLE
NSFS | content dir, ignore failure to delete xattr from latest, if already deleted

### LINKED ISSUE #8846: CI test fail - content dir multiple puts of the same key - enabled
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1.

### Expected behavior
1.

### Steps to reproduce
1.

### More information - Screenshots / Logs / Other output
ERROR logs:
```
2025-03-03T12:20:56.0694858Z [32mMar-3 12:20:56.062[35m [/8184] [36m   [L0][39m core.sdk.endpoint_stats_collector:: nsfs stats - FS op=fileclose : { count: [33m33[39m, error_count: [33m0[39m, min_time: [33m2[39m, max_time: [33m5[39m, sum_time: [33m104[39m }
2025-03-03T12:20:56.0697653Z [32mMar-3 12:20:56.062[35m [/8184] [36m   [L0][39m core.sdk.endpoint_stats_collector:: nsfs stats - FS op=fileread : { count: [33m10[39m, error_count: [33m0[39m, min_time: [33m1[39m, max_time: [33m8[39m, sum_time: [33m18[39m }
2025-03-03T12:20:56.2633148Z [32mMar-3 12:20:56.262[35m [/8184] [36m   [L0][39m core.sdk.namespace_fs:: check_access: dir_path /tmp/test_versioning_concurrency fs_context { uid: [33m0[39m, gid: [33m0[39m, backend: [32m''[39m, warn_threshold_ms: [33m100[39m, report_fs_stats: [36m[Function (anonymous)][39m }
2025-03-03T12:20:56.2716155Z [32mMar-3 12:20:56.271[35m [/8184] [33m [WARN][39m core.util.native_fs_utils:: native_fs_utils.unlink_ignore_enoent unlink error: file path /tmp/test_versioning_concurrency/key-s/.folder error [Error: No such file or directory] { code: [32m'ENOENT'[39m, context: [32m'Unlink _path=/tmp/test_versioning_concurrency/key-s/.folder '[39m } ENOENT [33mtrue[39m
2025-03-03T12:20:56.2718303Z [32mMar-3 12:20:56.271[35m [/8184] [33m [WARN][39m core.util.native_fs_utils:: native_fs_utils.unlink_ignore_enoent unlink: file /tmp/test_versioning_concurrency/key-s/.folder already deleted or key is pointing to dir, ignoring..
2025-03-03T12:20:56.3040812Z [32mMar-3 12:20:56.303[35m [/8184] [31m[ERROR][39m core.sdk.namespace_fs:: NamespaceFS.handle_fs_xattr_op: failed with error:  [Error: No data available] { code: [32m'ENODATA'[39m, context: [32m'FileReplacexattr _wrap->_path=/tmp/test_versioning_concurrency/key-s '[39m } /tmp/test_versioning_concurrency/key-s
2025-03-03T12:20:56.3074383Z [32mMar-3 12:20:56.306[35m [/8184] [33m [WARN][39m core.sdk.namespace_fs:: NamespaceFS._move_to_dest_version error: retries=9 should_retry=false new_ver_tmp_path=/tmp/test_versioning_concurrency/.noobaa-nsfs_1/uploads/38c0a48d-42ff-4a7f-b54f-33642a5daa36 latest_ver_path=/tmp/test_versioning_concurrency/key-s/.folder [Error: No data available] { code: [32m'ENODATA'[39m, context: [32m'FileReplacexattr _wrap->_path=/tmp/test_versioning_concurrency/key-s '[39m, rpc_code: [32m'INTERNAL_ERROR'[39m }
2025-03-03T12:20:56.3092945Z [32mMar-3 12:20:56.306[35m [/8184] [33m [WARN][39m core.sdk.namespace_fs:: NamespaceFS: upload_object buffer pool cleanup error [Error: No data available] { code: [32m'ENODATA'[39m, context: [32m'FileReplacexattr _wrap->_path=/tmp/test_versioning_concurrency/key-s '[39m, rpc_code: [32m'INTERNAL_ERROR'[39m }
2025-03-03T12:20:56.3140170Z [32mMar-3 12:20:56.308[35m [/8184] [33m [WARN][39m core.sdk.namespace_fs:: NamespaceFS._move_to_dest_version error: retries=9 should_retry=true new_ver_tmp_path=/tmp/test_versioning_concurrency/.noobaa-nsfs_1/uploads/2cc2255a-d7a9-4f69-b1cd-1d920e8fabae latest_ver_path=/tmp/test_versioning_concurrency/key-s/.folder [Error: File exists] { code: [32m'EEXIST'[39m, context: [32m'SafeLink _link_from.c_str()=/tmp/test_versioning_concurrency/.noobaa-nsfs_1/uploads/2cc2255a-d7a9-4f69-b1cd-1d920e8fabae _link_to.c_str()=/tmp/test_versioning_concurrency/key-s/.folder _link_expected_mtime=1741004456281239296 _link_expected_inode=842684 '[39m }
2025-03-03T12:20:56.3152072Z [32mMar-3 12:20:56.309[35m [/8184] [33m [WARN][39m core.sdk.namespace_fs:: NamespaceFS._move_to_dest_version error: retries=9 should_retry=true new_ver_tmp_path=/tmp/test_versioning_concurrency/.noobaa-nsfs_1/uploads/794622e0-2cd1-49a7-ba45-d0ab5eb95c68 latest_ver_path=/tmp/test_versioning_concurrency/key-s/.folder [Error: File exists] { code: [32m'EEXIST'[39m, context: [32m'SafeLink _link_from.c_str()=/tmp/test_versioning_concurrency/.noobaa-nsfs_1/uploads/794622e0-2cd1-49a7-ba45-d0ab5eb95c68 _link_to.c_str()=/tmp/test_versioning_concurrency/key-s/.folder _link_expected_mtime=1741004456281239296 _link_expected_inode=842685 '[39m }
```

### PR DESCRIPTION
**Pull request by nadavMiz**
### Describe the Problem
when adding to content dir at the same time after enabling versioning. both of them might try to remove the xattr from the directory. one of them will fail with ENODATA (The named attribute does not exist). ignore this error because attribute already deleted. see [removexattr](https://man7.org/linux/man-pages/man2/removexattr.2.html)

### Explain the Changes
1. ignore xattr clear error for data already deleted

### Issues: Fixed #8846 
NOTE - issue doesn't replicate on my environment. ran jest tests on CI 15 times without test failing but since it is a concurrency test, there may be other problems that didn't happen by chance

### Testing Instructions:
1. run `sudo npx jest test_versioning_concurrency -t "content dir multiple puts of the same key"`

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

File: src/sdk/namespace_fs.js [hunk 1]
```diff
@@ -1610,7 +1610,13 @@ class NamespaceFS {
                     await this.set_fs_xattr_op(fs_context, versioned_path, filter_fs_xattr(directory_stat.xattr), undefined, "w");
                 }
             }
-            await this._clear_user_xattr(fs_context, latest_version_dir_path, XATTR_USER_PREFIX);
+            try {
+                await this._clear_user_xattr(fs_context, latest_version_dir_path, XATTR_USER_PREFIX);
+            } catch (err) {
+                if (err.code === 'ENODATA') {
```
Comment (shirady) [inline src/sdk/namespace_fs.js:1616]: Do you want to throw the error on the other case, right? (so missing an else throw or something like that...).

**Comment by nadavMiz** [comment]
@shirady regarding your comment. in _clear_user_xattr we clear the user xattr from the directory. we check that the xattr exists before clearing them. the issue is that two threads can get to this function together and then one thread deletes the xattr while the second fails with this error because the first already deleted the xattr. and so the `The named attribute does not exist`

**Comment by shirady** [comment]
@nadavMiz thank you for the explanation.
I was trying to understand which system cal exactly fails it - `fremovexattr` or `removexattr`, if you can show a reference from the code.

**Comment by nadavMiz** [comment]
log of the error:
```
2025-03-03T12:20:56.3040812Z �[32mMar-3 12:20:56.303�[35m [/8184] �[31m[ERROR]�[39m core.sdk.namespace_fs:: NamespaceFS.handle_fs_xattr_op: failed with error:  [Error: No data available] { code: �[32m'ENODATA'�[39m, context: �[32m'FileReplacexattr _wrap->_path=/tmp/test_versioning_concurrency/key-s '�[39m } /tmp/test_versioning_concurrency/key-s
```
since we have clear_prefix set in fs_napi FileReplacexattr we go to to clear_xattr (fs_napi.cpp:1198). so the function used is `fremovexattr` 
```
(buf.length()) {
        std::string key(buf.cdata());
        // remove xattr only if its key starts with prefix
        if (key.rfind(_prefix, 0) == 0) {
            ssize_t value_len = fremovexattr(fd, key.c_str());
            if (value_len == -1) return -1;
        }
        buf.slice(key.size() + 1, buf.length());
    }
```

also looks like the errors are the same for both `fremovexattr` and `removexattr`

File: src/sdk/namespace_fs.js [hunk 2]
```diff
@@ -1610,7 +1610,12 @@ class NamespaceFS {
                     await this.set_fs_xattr_op(fs_context, versioned_path, filter_fs_xattr(directory_stat.xattr), undefined, "w");
                 }
             }
-            await this._clear_user_xattr(fs_context, latest_version_dir_path, XATTR_USER_PREFIX);
+            try {
+                await this._clear_user_xattr(fs_context, latest_version_dir_path, XATTR_USER_PREFIX);
```
Comment (romayalon) [inline src/sdk/namespace_fs.js:1614]: Hey @nadavMiz why not adding this catch to the clear function? or having it with a flag, I saw it'll be useful in https://github.com/noobaa/noobaa-core/pull/8975 as well

**Comment by nadavMiz** [comment]
@shirady we are using fremovexattr. see clear_xattr in fs_nappi. however both fremovexattr and removexattr have the same errors

**Review by romayalon — APPROVED** [review]
