### PR TITLE
NC | GPFS | Threaded Multiple Object Delete fix

### LINKED ISSUE #8377: NSFS | S3 | Versioning: Threaded delete of multiple objects does not delete
### Environment info
- NooBaa Version: **5.17.0-20240904**
- Platform: **CentOS8, deployed using [https://github.com/IBM/StorageScaleVagrant](https://github.com/IBM/StorageScaleVagrant), Scale 5.2.2.0 240913.105913**

### Actual behavior

With the following test code, all delete_objects commands return, but the objects are still present afterwards:

```
    def test_versioning_concurrent_multi_object_delete():
        num_objects = 5
        num_threads = 5
        bucket_name = get_new_bucket()
    
        check_configure_versioning_retry(bucket_name, "Enabled", "Enabled")
    
        key_names = ["key_{:d}".format(x) for x in range(num_objects)]
        bucket = _create_objects(bucket_name=bucket_name, keys=key_names)
    
        client = get_client()
        versions = client.list_object_versions(Bucket=bucket_name)['Versions']
        assert len(versions) == num_objects
        objs_dict = {'Objects': [dict((k, v[k]) for k in ["Key", "VersionId"]) for v in versions]}
        results = [None] * num_threads
    
        def do_request(n):
            results[n] = client.delete_objects(Bucket=bucket_name, Delete=objs_dict)
    
        t = []
        for i in range(num_threads):
            thr = threading.Thread(target = do_request, args=[i])
            thr.start()
            t.append(thr)
        _do_wait_completion(t)
    
        for response in results:
            assert len(response['Deleted']) == num_objects
            assert 'Errors' not in response
    
        response = client.list_objects(Bucket=bucket_name)
>       assert 'Contents' not in response
E       assert 'Contents' not in {'Contents': [{'ETag': '"mtime-d48pnbhmvi0w-ino-15hc"', 'Key': 'key_0', 'LastModified': datetime.datetime(2024, 9, 17,..., 'ID': '66e85c103a034ad6a392511e'}, ...}], 'Delimiter': 'undefined', 'EncodingType': 'url', 'IsTruncated': False, ...}
```

### Expected behavior

Test code passes and all objects get properly deleted.

### Steps to reproduce

Execute the above test code as part of Ceph s3-tests.

### More information - Screenshots / Logs / Other output

Noobaa log with "all" log level attached
[noobaa_20240917_2.log.gz](https://github.com/user-attachments/files/17032395/noobaa_20240917_2.log.gz)

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. When calling delete multiple objects on the same key & version concurrently, the version might move/delete, on GPFS we saw that _open_files_gpfs() failed on ENOENT in that case, therefore added a retry when got ENOENT, next iteration we will return if the version was deleted or get the new location of the version.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #8377 
2. Gap - Enable `s3tests_boto3/functional/test_s3.py::test_versioning_concurrent_multi_object_delete`, currently it's not working because they call put bucket twice and the test fails on BucketAlreadyExists, the test I added dooes the same as the ceph test but in general we want to remove it from the pending list. Opened a bug - https://github.com/ceph/s3-tests/issues/588.

### Testing Instructions:
1. Run `sudo jest -t 'concurrent multi object delete'` on GPFS cluster or run `s3tests_boto3/functional/test_s3.py::test_versioning_concurrent_multi_object_delete` while fixing manually the bug on s3-tests code - see the suggested fix in https://github.com/ceph/s3-tests/issues/588.

- [ ] Doc added/updated
- [x] Tests added

### CODE REVIEW

File: src/sdk/namespace_fs.js [hunk 1]
```diff
@@ -2766,9 +2766,11 @@ class NamespaceFS {
                 }
                 return version_info;
             } catch (err) {
-                retries -= 1;
-                if (retries <= 0 || !native_fs_utils.should_retry_link_unlink(is_gpfs, err)) throw err;
                 dbg.warn(`NamespaceFS._delete_single_object_versioned: retrying retries=${retries} file_path=${file_path}`, err);
+                retries -= 1;
+                // retry also on ENOENT if the version moved from .versions -> latest or the opposite/deleted concurrently
```
Comment (nadavMiz) [inline src/sdk/namespace_fs.js:2771]: can you maybe elaborate on what exactly is the issue that might cause this. its not clear from the comment

Comment (romayalon) [reply src/sdk/namespace_fs.js]: it's written in the description but I updated the comment as well, please take a look

**Review by nadavMiz — APPROVED** [review]
LGTM

File: src/sdk/namespace_fs.js [hunk 2]
```diff
@@ -2766,9 +2766,16 @@ class NamespaceFS {
...
                 dbg.warn(`NamespaceFS._delete_single_object_versioned: retrying retries=${retries} file_path=${file_path}`, err);
+                retries -= 1;
+                // there are a few concurrency scenarios that might happen we should retry for -
+                // 1. the version id is the latest, concurrent put will might move the version id from being the latest to .versions/ -
+                // will throw safe unlink failed on non matching fd (on GPFS) or inode/mtime (on POSIX).
+                // 2. the version id is the second latest and stays under .versions/ - on concurrent delete of the latest, 
+                // the version id might move to be the latest and we will get ENOENT
+                // 3. concurrent delete of this version - will get ENOENT, doing a retry will return successfully 
+                // after we will see that the version was already deleted
+                if (retries <= 0 || (!native_fs_utils.should_retry_link_unlink(is_gpfs, err) && err.code !== 'ENOENT')) throw err;
```
Comment (guymguym) [inline src/sdk/namespace_fs.js:2778]: should this ENOENT condition be added inside the utility function maybe?

**Comment by shirady** [comment]
@romayalon could you please add the issue you opened on the Ceph S3 tests `s3tests_boto3/functional/test_s3.py::test_versioning_concurrent_multi_object_delete` to the table in this doc [Ceph S3 Tests - Pending List Status](https://github.com/noobaa/noobaa-core/blob/master/docs/dev_guide/ceph_s3_tests/ceph_s3_tests_pending_list_status.md#ceph-s3-tests---pending-list-status) in the changes of this PR?
