### PR TITLE
moving pvpool responsibility to noobaa operator

### LINKED ISSUE #5942: Host pool stuck in not initialized mode while all hosts are OPTIMAL
### Environment info
- NooBaa Version: **5.2**
- Platform: **OpenShift 3.11**
- CC: @nb-ohad 

### Actual behavior
1. After restarting the services, perhaps while pool_server was handling the host pool scale, the _init function of pool_server bails because all hosts are already running and optimal, and it does not fix the initialized flag on the pool.

### Expected behavior
1. Should fix the initialized state when all hosts are OPTIMAL.

### Steps to reproduce
1. Restart the server soon after creating a host pool, while it waits for the hosts to start.

### LINKED ISSUE #5960: pv-pool backingstore does not propagate imagePullSecret to pool statefulset
### Environment info
- NooBaa Version: **5.2**
- Platform: **OpenShift 3.11**

### Actual behavior
1. Used imagePullSecret in NooBaa spec.
2. Created  pv-pool BackingStore.
3. The backingstore Statefulset did not get the imagePullSecret.
4. Whenever we added it manually it was overridden.

### Expected behavior
1. imagePullSecret should propagate from the NooBaa spec to the pv-pool Statefulset.
2. The pool_controller should not overwrite things that it didn't write.

### Steps to reproduce
1. See above.

### PR DESCRIPTION
**Pull request by jackyalbo**
### Explain the changes
1. creating pvpool using operator's pvpool backing store and not by  statefulset
2. returning agent_config to the operator on new pvpool creation
3. fixes to kube_utils and pool_controllers to support new method  

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #5960 
2. Fixed #5942 

### Testing Instructions:
1.

### CODE REVIEW

File: src/server/system_services/pool_controllers.js [hunk 1]
```diff
@@ -69,7 +64,7 @@ class ManagedStatefulSetPoolController extends PoolController {
             JSON.stringify(pool_k8s_conf, null, 2));
 
         await kube_utils.apply_conf(pool_k8s_conf);
-        return yaml_utils.stringify(pool_k8s_conf);
+        return yaml.stringify(pool_k8s_conf, 6, 2);
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:67]: This code should use the kube_store and not kube_utils. we do not want to continue to run kubectl as a process. Especially after we introduced the kube_store to handle communication with the kube API directly

File: src/server/system_services/pool_controllers.js [hunk 2]
```diff
@@ -78,78 +73,34 @@ class ManagedStatefulSetPoolController extends PoolController {
...
+            this.pool_name
         } from ${
             pod_count
         } replicas to ${
             host_count
         } replicas`);
 
         if (host_count > 0) {
-            await kube_utils.patch_resource('StatefulSet', _statefulset_name, { spec: { replicas: host_count } });
+            await kube_utils.patch_resource('BackingStore', this.pool_name, { spec: { pvPool: { numVolumes: host_count } } });
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:87]: Same as last comment (use kube_store)

File: src/server/system_services/pool_controllers.js [hunk 3]
```diff
@@ -78,78 +73,34 @@ class ManagedStatefulSetPoolController extends PoolController {
...
-                    dbg.log0(`ManagedStatefulSetPoolController::scale: waiting for pod ${pod_name} to be deleted`);
-                    await kube_utils.wait_for_delete('pod', pod_name, 15 * 60 * 1000);
-
-                    // Delete the pvc claimed by the pod.
-                    const pvc_name = `noobaastorage-${pod_name}`;
-                    dbg.log0(`ManagedStatefulSetPoolController::scale: deleting pvc ${pvc_name}`);
-                    return kube_utils.delete_resource('pvc', pvc_name);
-                })
-           );
+            await kube_utils.delete_resource('BackingStore', this.pool_name);
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:89]: Same as above (use kube_store)

File: src/server/system_services/pool_controllers.js [hunk 4]
```diff
@@ -78,78 +73,34 @@ class ManagedStatefulSetPoolController extends PoolController {
...
     async delete() {
         this.scale(0);
     }
 
     async _list_pods() {
-        const escaped_statefulset_name = string_utils.escape_reg_exp(this._statefulset_name);
-        const pod_name_regexp = new RegExp(`^${escaped_statefulset_name}-\\d+$`);
-        const { items: pods } = await kube_utils.list_resources('pod', 'noobaa-module=noobaa-agent');
-        return pods.filter(pod => pod_name_regexp.test(pod.metadata.name));
+        const { items: pods } = await kube_utils.list_resources('pod', `pool=${this.pool_name}`);
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:102]: same as above (use kube_store)

**Review by nb-ohad — CHANGES_REQUESTED** [review]

**Comment by nb-ohad** [comment]
@jackyalbo Why do we need the semaphore or pool controllers after the move to the operator. 
All this code should have been removed, or am I missing something

**Comment by jackyalbo** [comment]
@nb-ohad I did this PR as first minimal step for moving the responsibility to the operator - didn't want too many changes in both sides.  I will later do a proper cleanup.

**Comment by nb-ohad** [comment]
@jackyalbo  
Ok but not removing the semaphore will retain all the bugs that we currently have with regard to the semaphore.

File: src/server/system_services/pool_controllers.js [hunk 5]
```diff
@@ -159,21 +110,16 @@ class ManagedStatefulSetPoolController extends PoolController {
...
     async create(agent_count, agent_install_conf, agent_profile) {
         const pool_k8s_conf = await _get_k8s_conf({
-            statefulset_name: this._statefulset_name,
+            pool_name: this.pool_name,
             agent_count,
             agent_install_conf,
             ...agent_profile
         });
-        return yaml_utils.stringify(pool_k8s_conf);
+        return yaml.stringify(pool_k8s_conf, 6, 2);
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:122]: `yaml_utils.stringify()` handle special cases that `yaml.stringify` do not. 
Is there a reason to not using it?

File: src/server/system_services/pool_controllers.js [hunk 6]
```diff
@@ -78,78 +73,34 @@ class ManagedStatefulSetPoolController extends PoolController {
         if (delta === 0) return;
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:73]: I think you should not check the number of pod but read the status on the pvpool backing store in order to get the number to preform the scale.

File: src/server/system_services/pool_controllers.js (hunk 5 above)
Comment (jackyalbo) [reply src/server/system_services/pool_controllers.js:122]: it just didn't work in my case - I guess it handled specifically issues in the old statefulset format the was just not needed anymore. But anyway this review starting to be unrelevant as I'm changing the backingstore format to using secrets, so it will change again anyway

File: src/server/system_services/pool_controllers.js (hunk 6 above)
Comment (jackyalbo) [reply src/server/system_services/pool_controllers.js:81]: fixed

**Comment by jackyalbo** [comment]
fixed to kubestore instead of kube_utils

File: src/server/node_services/nodes_client.js [hunk 7]
```diff
@@ -324,19 +324,19 @@ class NodesClient {
 
         const { hosts } = await this.list_hosts_by_pool(pool_name, system_id, auth_token);
         const promise_list = hosts
-            .sort((host1, host2) => {
-                const host1_seq = Number(host1.name.match(/-(\d+)#/)[1]);
-                const host2_seq = Number(host2.name.match(/-(\d+)#/)[1]);
-                return host1_seq - host2_seq;
-            })
+            // .sort((host1, host2) => {
```
Comment (dannyzaken) [inline src/server/node_services/nodes_client.js:327]: any reason to remove this? if yes then just delete it

**Review by dannyzaken — APPROVED** [review]
just a minor comment

File: src/server/node_services/nodes_client.js (hunk 7 above)
Comment (jackyalbo) [reply src/server/node_services/nodes_client.js:327]: yes. we changed the naming convention... we don't have order any more... so sorting isn't helpful and not working anymore as well (the last part is just random string that can contain not just numbers)

Comment (jackyalbo) [reply src/server/node_services/nodes_client.js]: cleaned it up

File: src/server/kube-store.js [hunk 8]
```diff
@@ -128,7 +138,89 @@ class KubeStore {
...
+
+    async create_backingstore(new_store) {
+        await this._init();
+        const path = get_backingstores_path(this._k8s_namespace);
+        const { status_code, body } = await this._make_k8s_api_request('POST', path, new_store);
+        switch (status_code) {
+            case 201: {
+                return body;
+            }
+            case 404: {
```
Comment (nb-ohad) [inline src/server/kube-store.js:154]: I don't think you can a 404 for a POST operation, also why do you need to return the body in the case of create operation? ( the 201)

File: src/server/kube-store.js [hunk 9]
```diff
@@ -128,7 +138,89 @@ class KubeStore {
...
+        }
+    }
+
+    async delete_backingstore(name) {
+        await this._init();
+        const path = get_backingstores_path(this._k8s_namespace) + `/${name}`;
+        const { status_code, body } = await this._make_k8s_api_request('DELETE', path);
+        switch (status_code) {
+            case 200: {
+                return body;
```
Comment (nb-ohad) [inline src/server/kube-store.js:169]: I don't think delete operation returns a body. I think in this case you should return a bool,
true for 200 and false for 404 or other codes that we want to take care about. All other codes will default to throwing.

File: src/server/kube-store.js [hunk 10]
```diff
@@ -128,7 +138,89 @@ class KubeStore {
...
+            case 200: {
+                return;
+            }
+            default: {
+                throw new Error(`Could not patch backingstore, (status code: ${status_code}) got ${JSON.stringify(body)}`);
+            }
+        }
+    }
+
+    async create_secret(new_secret) {
```
Comment (nb-ohad) [inline src/server/kube-store.js:211]: See my comments regarding create operations above

File: src/server/kube-store.js [hunk 11]
```diff
@@ -128,7 +138,89 @@ class KubeStore {
...
+
+    async patch_backingstore(name, patch) {
+        await this._init();
+        const path = get_backingstores_path(this._k8s_namespace) + `/${name}`;
+        const { status_code, body } = await this._make_k8s_api_request('PATCH', path, patch);
+        switch (status_code) {
+            case 200: {
+                return;
+            }
+            default: {
```
Comment (nb-ohad) [inline src/server/kube-store.js:205]: I think you should take care of 404 in this case, in the case that the basking store you are trying to patch do not exists. So returning a bool make more sense.

File: src/server/system_services/pool_controllers.js [hunk 12]
```diff
@@ -68,88 +67,48 @@ class ManagedStatefulSetPoolController extends PoolController {
         dbg.log2(`ManagedStatefulSetPoolController::create: Pool ${this.pool_name} k8s configuration is`,
             JSON.stringify(pool_k8s_conf, null, 2));
 
-        await kube_utils.apply_conf(pool_k8s_conf);
-        return yaml_utils.stringify(pool_k8s_conf);
+        await KubeStore.instance.create_secret(secret_k8s_conf);
+        await KubeStore.instance.create_backingstore(pool_k8s_conf);
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:71]: Why not paralleling these operations? `Promise.all`

Also what happens if the secret failed but the backingsotre succedes. I think you should retry or at least bailout by deleting the backing store.

File: src/server/system_services/pool_controllers.js [hunk 13]
```diff
@@ -68,88 +67,48 @@ class ManagedStatefulSetPoolController extends PoolController {
...
         } from ${
-            pod_count
+            current_host_count
         } replicas to ${
             host_count
         } replicas`);
 
         if (host_count > 0) {
-            await kube_utils.patch_resource('StatefulSet', _statefulset_name, { spec: { replicas: host_count } });
+            await KubeStore.instance.patch_backingstore(this.pool_name, { spec: { pvPool: { numVolumes: host_count } } });
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:95]: You should return bool and handle the case where the backing store was not patched. for example, the backing store was deleted from k8s. In this case I would try to recreate the backing store (already patched)

File: src/server/system_services/pool_controllers.js [hunk 14]
```diff
@@ -68,88 +67,48 @@ class ManagedStatefulSetPoolController extends PoolController {
...
-                    dbg.log0(`ManagedStatefulSetPoolController::scale: waiting for pod ${pod_name} to be deleted`);
-                    await kube_utils.wait_for_delete('pod', pod_name, 15 * 60 * 1000);
-
-                    // Delete the pvc claimed by the pod.
-                    const pvc_name = `noobaastorage-${pod_name}`;
-                    dbg.log0(`ManagedStatefulSetPoolController::scale: deleting pvc ${pvc_name}`);
-                    return kube_utils.delete_resource('pvc', pvc_name);
-                })
-           );
+            await KubeStore.instance.delete_backingstore(this.pool_name);
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:97]: Again you need to check the return value in case the backing_store deletion failed and at least put something in the logs

File: src/server/system_services/pool_controllers.js [hunk 15]
```diff
@@ -68,88 +67,48 @@ class ManagedStatefulSetPoolController extends PoolController {
...
     }
 
-    async _list_pods() {
-        const escaped_statefulset_name = string_utils.escape_reg_exp(this._statefulset_name);
-        const pod_name_regexp = new RegExp(`^${escaped_statefulset_name}-\\d+$`);
-        const { items: pods } = await kube_utils.list_resources('pod', 'noobaa-module=noobaa-agent');
-        return pods.filter(pod => pod_name_regexp.test(pod.metadata.name));
+    async get_current_volume_number() {
+        const backingstore = await KubeStore.instance.read_backingstore(this.pool_name);
+        return backingstore.spec.pvPool.numVolumes;
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:111]: Do not read the spec. It does not say anything about the current state. you should read the status of the backing store  where the backing store should save the number of actual volumes (pods) that are up and running

File: src/server/system_services/pool_controllers.js [hunk 16]
```diff
@@ -159,21 +118,22 @@ class ManagedStatefulSetPoolController extends PoolController {
...
+            pool_name: this.pool_name,
             agent_count,
-            agent_install_conf,
             ...agent_profile
         });
-        return yaml_utils.stringify(pool_k8s_conf);
+        const secret_yaml = yaml.stringify(secret_k8s_conf, 6, 2);
+        const backstore_yaml = yaml.stringify(pool_k8s_conf, 6, 2);
+
+        return `${secret_yaml}---\n${backstore_yaml}`;
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:136]: Please use yaml_utils for this,  it can handle stringifying into a multi document YAML.
```
return yaml_utils.stringify([secret_k8s_conf, pool_k8s_conf])
```

File: src/server/system_services/pool_controllers.js [hunk 17]
```diff
@@ -271,84 +231,44 @@ class InProcessAgentsPoolController extends PoolController {
...
-        throw new Error('Invalid agent template: missing env variable definition named AGENT_CONFIG');
-    }
-
-    // Find the volume claim template.
-    const volume_claim_template = statefulset.spec.volumeClaimTemplates
-        .find(vct => vct.metadata.name === 'noobaastorage');
-    if (!volume_claim_template) {
-        throw new Error('Invalid agent template: missing volume claim template named noobaastorage');
-    }
+    const yaml_file = (await fs.readFileAsync(yaml_path)).toString();
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:236]: We moved to `fs.promises.readFile` instead, this fs.readFileAsync is deprecated/

File: src/server/system_services/pool_controllers.js [hunk 18]
```diff
@@ -271,84 +231,44 @@ class InProcessAgentsPoolController extends PoolController {
...
+    const backingstore = await yaml.parse(yaml_file);
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:237]: Please use yaml_utils, It fixes some of the problems with multi-document yamls.

File: src/server/system_services/pool_controllers.js [hunk 19]
```diff
@@ -271,84 +231,44 @@ class InProcessAgentsPoolController extends PoolController {
...
     }
 
-    return conf_template;
+    return backingstore;
+}
+
+async function _get_k8s_secret(params) {
+    const yaml_path = path.resolve(__dirname, '../../deploy/NVA_build/noobaa_pool_secret.yaml');
+    const yaml_file = (await fs.readFileAsync(yaml_path)).toString();
+    const secret = await yaml.parse(yaml_file);
```
Comment (nb-ohad) [inline src/server/system_services/pool_controllers.js:261]: See comments above regarding yaml_utils.

File: src/util/kube_utils.js [hunk 20]
```diff
@@ -69,7 +67,7 @@ function get_resource(resource_type, resource_name) {
 }
 
 function patch_resource(resource_type, resource_name, patch) {
-    return exec_kubectl(`patch ${resource_type} ${resource_name} -p='${JSON.stringify(patch)}'`, 'json');
+    return exec_kubectl(`patch ${resource_type} ${resource_name} --type merge -p='${JSON.stringify(patch)}'`, 'json');
```
Comment (nb-ohad) [inline src/util/kube_utils.js:70]: I thought that we decided to use kube_store, why did you introduce a change here. It may break old code that uses this util file. I would like us  to freeze this code until we move all of its call sites into using KubeStore instead.

As a note, all the other changes in this file are layout only changes. You can revert the whole file

File: src/server/system_services/pool_server.js [hunk 21]
```diff
@@ -767,37 +554,31 @@ async function delete_hosts_pool(req, pool) {
...
-    pool_scaling_sem.surround_key(pool.name, async () => {
-        if (host_count > 0) {
-            await nodes_client.instance()
-                .delete_hosts_by_pool(pool.name, req.system._id);
+    if (host_count > 0) {
+        await nodes_client.instance()
+            .delete_hosts_by_pool(pool.name, req.system._id);
+    }
+    dbg.log0(`delete_hosts_pool: removing pool ${pool.name} from the database`);
+    await system_store.make_changes({
```
Comment (nb-ohad) [inline src/server/system_services/pool_server.js:562]: You cannot remove from the DB before all the agents are removed. If you do so and the operator is failing for some reason the core will have agents connected that are not part of any pool. 
Removing the pool from the database be done as a result of an operation the operator should do when it verified that all pods are down

File: src/server/system_services/pool_server.js [hunk 22]
```diff
@@ -1215,12 +995,8 @@ function calc_hosts_pool_mode(pool_info, is_initialized, storage_by_mode, s3_by_
         .reduce((sum, val) => sum + val.count, 0);
     const activity_ratio = (activity_count / host_count) * 100;
 
-    const now = Date.now();
-    const init_timeout = system_store.data.systems[0].pools_by_name[pool_info.name].hosts_pool_info.init_timeout || now;
-
     return (is_managed && hosts.configured_count === 0 && 'DELETING') ||
-        (is_managed && !is_initialized && (now > init_timeout) && 'INITIALIZING_FAILED') ||
-        (is_managed && !is_initialized && 'INITIALIZING') ||
+        (is_managed && host_count === hosts_initializing && 'INITIALIZING') ||
```
Comment (nb-ohad) [inline src/server/system_services/pool_server.js:999]: This is not always correct, what if the operator should bring up only half of the pod (which means half of the agants) like in the case where it has no nodes to allocate to the pods. In this case the pool should still be in initializing state BUT only if this is the operation that started in the creation (this is why we had the initialize flag on the host_info, that you removed).

In the case of scaling it is ok because the pool might already be in use

**Review by nb-ohad — CHANGES_REQUESTED** [review]

File: src/server/system_services/pool_server.js [hunk 23]
```diff
@@ -542,27 +406,65 @@ async function scale_hosts_pool(req) {
         throw new RpcError('INVALID_POOL_TYPE', `pool ${pool.name} is not a hosts pool`);
     }
 
+    const pool_info = await read_pool(req);
```
[the remark this answers is not in the document]
Comment (jackyalbo) [reply src/server/system_services/pool_server.js:409]: we need to get the real number of attached nodes

File: src/server/system_services/pool_server.js [hunk 24]
```diff
@@ -542,27 +406,65 @@ async function scale_hosts_pool(req) {
...
         // Nothing to do.
         return;
     }
 
-    if (configured_host_count === 0) {
+    if (pool.mode === 'DELETING') {
         throw new RpcError('INVALID_POOL_STATE', `pool ${pool.name} is being deleted`);
     }
 
+    if (host_count < current_host_count) {
```
[the remark this answers is not in the document]
Comment (jackyalbo) [reply src/server/system_services/pool_server.js:422]: we decided not to allow scale down under the current amount of attached agents. configured holds the old wished count and host_count the new wished one

File: src/server/system_services/pool_server.js [hunk 25]
```diff
@@ -542,27 +406,65 @@ async function scale_hosts_pool(req) {
...
         }
     });
+}
+
+async function update_hosts_pool(req) {
+    const pool = find_pool_by_name(req);
+    if (!pool.hosts_pool_info) {
+        throw new RpcError('INVALID_POOL_TYPE', `pool ${pool.name} is not a hosts pool`);
+    }
+    const backingstore = await KubeStore.instance.read_backingstore(pool.name);
```
[the remark this answers is not in the document]
Comment (jackyalbo) [reply src/server/system_services/pool_server.js:465]: we decided that the operator will only let the server know that he should refresh his count and it will take it using kube_store

File: src/server/system_services/pool_server.js (hunk 21 above)
Comment (jackyalbo) [reply src/server/system_services/pool_server.js:562]: if it will fail it will throw an exception - we won't update the db

File: src/server/system_services/pool_server.js (hunk 22 above)
Comment (jackyalbo) [reply src/server/system_services/pool_server.js:999]: sounds better to me. Initializing was always a temporary step before nodes started to connect. if some has connected we will move to scaling as we are trying to get to the desired state but you can start working. Init-failed i this case sound harsh.

File: src/server/system_services/pool_server.js [hunk 26]
```diff
@@ -744,17 +526,22 @@ function delete_namespace_resource(req) {
...
         if (!account_roles.includes('operator')) {
             throw new RpcError(reason, 'Cannot delete pool');
         }
     } else if (reason) {
         throw new RpcError(reason, 'Cannot delete pool');
     }
 
+    if (!account_roles.includes('operator')) {
+        const pool_ctrl = create_pool_controller(req.system, pool);
+        await pool_ctrl.delete();
```
[the remark this answers is not in the document]
Comment (jackyalbo) [reply src/server/system_services/pool_server.js:542]: if it fails that backingstore won't get deleted not in the operator and not in the DB

File: src/server/system_services/pool_server.js [hunk 27]
```diff
@@ -542,27 +406,65 @@ async function scale_hosts_pool(req) {
...
+    if (pool.mode === 'DELETING') {
         throw new RpcError('INVALID_POOL_STATE', `pool ${pool.name} is being deleted`);
     }
 
+    if (host_count < current_host_count) {
+        throw new RpcError('INVALID_POOL_STATE', `can't scale down ${pool.name} hosts count to less than current connected hosts`);
+    }
+
+    const pool_ctrl = create_pool_controller(req.system, pool);
+    await pool_ctrl.scale(host_count);
```
[the remark this answers is not in the document]
Comment (jackyalbo) [reply src/server/system_services/pool_server.js:427]: exception - the db won't get updated

File: src/server/system_services/pool_controllers.js (hunk 14 above)
Comment (jackyalbo) [reply src/server/system_services/pool_controllers.js:97]: it will throw exception

File: src/server/system_services/pool_controllers.js (hunk 13 above)
Comment (jackyalbo) [reply src/server/system_services/pool_controllers.js:95]: it will throw exception

File: src/server/system_services/pool_controllers.js (hunk 12 above)
Comment (jackyalbo) [reply src/server/system_services/pool_controllers.js:71]: because we need the secret first. the order is important. 
if it will fail we will throw exception so the backingstore won't be created.

File: src/server/system_services/pool_controllers.js (hunk 15 above)
Comment (jackyalbo) [reply src/server/system_services/pool_controllers.js:111]: the operator is now in control - current state is not interesting - we just need to check if the operator and core holds different numbers and update the operator if so

File: src/server/system_services/pool_controllers.js (hunk 18 above)
Comment (jackyalbo) [reply src/server/system_services/pool_controllers.js:237]: it's a one document yaml - will reconsider if we get issues

File: src/server/system_services/pool_controllers.js (hunk 16 above)
Comment (jackyalbo) [reply src/server/system_services/pool_controllers.js:136]: it's a 2 document yaml - will reconsider if we get issues

File: src/util/kube_utils.js (hunk 20 above)
Comment (jackyalbo) [reply src/util/kube_utils.js:70]: will revert

File: src/server/system_services/pool_server.js [hunk 28]
```diff
@@ -583,136 +485,16 @@ async function scale_hosts_pool(req) {
...
-                            }]
-                        }
-                    }),
-                    pool_ctrl.scale(stable_host_count)
-                ]);
-                return;
-            }
+    // Update the host pool info.
+    dbg.log0(`update_hosts_pool: updating ${pool.name} host count from ${configured_host_count} to ${host_count}`);
+    return system_store.make_changes({
```
[the remark this answers is not in the document]
Comment (jackyalbo) [reply src/server/system_services/pool_server.js:490]: will be changed in next reconcile as the numbers don't match

**Review by nb-ohad — APPROVED** [review]
