### PR TITLE
Ohad fe 5.2 fixes

### LINKED ISSUE #5764: Audit log links don't work and UI is missing the previously exists "selected line" indication
### Environment info
- NooBaa Version: **5.2.0-d6fd801**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. Audit log links don't work

### Expected behavior
1.  links in the entity columns should link to the entity and links to accounts were not required

### Steps to reproduce
1. See audit log 

### More information - Screenshots / Logs / Other output
Oct-02-2019 16-02-48

### LINKED ISSUE #5769: User without permissions to buckets can delete/edit the buckets using the Management Console
### Environment info
- NooBaa Version: 5.2.0
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 **

### Actual behavior
1. Permissions given in the create/edit account process do not apply to the management console

### Expected behavior
1. Either apply permissions to the Management console or give all admin users a mandatory full S3 access 

### Steps to reproduce
1.

### PR DESCRIPTION
**Pull request by nb-ohad**
### Explain the changes
1.  Fix broken audit log links
2. Change code to use new container names
3. Enforce full s3 access for users with login access (both API and UI flow)

### Issues: Fixed #xxx / Gap #xxx
1. fixes #5764 
2. fixes #5769

### Testing Instructions:
1.

### CODE REVIEW

**Review by nimrod-becker — APPROVED** [review]

File: src/test/system_tests/sanity_build_test.js [hunk 1]
```diff
@@ -200,10 +200,9 @@ async function _create_accounts() {
     };
 
     const ac2 = {
-        name: "ac_login_all_buckets",
-        email: "ac_login_all_buckets@demo.com",
+        name: "ac_nologin_all_buckets",
```
Comment (nimrod-becker) [inline src/test/system_tests/sanity_build_test.js]: so why has_login: true?

File: src/test/system_tests/sanity_build_test.js [hunk 2]
```diff
@@ -215,20 +214,19 @@ async function _create_accounts() {
     };
 
     const ac3 = {
-        name: "ac_login_full",
-        email: "ac_login_full@noobaa.com",
+        name: "ac_nologin_full",
```
Comment (nimrod-becker) [inline src/test/system_tests/sanity_build_test.js]: why has_login:true?

**Review by nimrod-becker — APPROVED** [review]

**Review by nimrod-becker — APPROVED** [review]
