### PR TITLE
NSFS | NC | Avoid vacuumAndAnalyze on nc nsfs without db

### LINKED ISSUE #7735: Noobaa_nsfs service restarts due to panic on 2 of the protocol nodes
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

 rpm -qa |grep noobaa
noobaa-core-5.15.0-20240115.el9.x86_64

### Actual behavior
1.

you can observe that the nodes has the noobaa_nsfs restarts

[root@scale-13 log]# systemctl status noobaa_nsfs
● noobaa_nsfs.service - The NooBaa nsfs service.
     Loaded: loaded (/etc/systemd/system/noobaa_nsfs.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-01-18 11:11:30 CET; 56min ago
   Main PID: 3379876 (node)
      Tasks: 11 (limit: 48877)
     Memory: 134.2M
        CPU: 12.131s
     CGroup: /system.slice/noobaa_nsfs.service
             └─3379876 /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/nsfs.js

/var/log/noobaa.log
```
2024-01-18T11:11:15.587670+01:00 scale-13 node[3379340]: [/3379340] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: closing fd ...
2024-01-18T11:11:15.588164+01:00 scale-13 node[3379340]: [/3379340] ESC[36m  [LOG]ESC[39m CONSOLE:: init_rand_seed: seeding with 32 bytes
2024-01-18T11:11:16.416792+01:00 scale-13 node[3379393]: [/3379393] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: reading 32 bytes from /dev/ran
dom ...
2024-01-18T11:11:16.417865+01:00 scale-13 node[3379393]: [/3379393] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: got 32 bytes from /dev/random,
 total 32 ...
2024-01-18T11:11:16.418135+01:00 scale-13 node[3379393]: [/3379393] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: closing fd ...
2024-01-18T11:11:16.418616+01:00 scale-13 node[3379393]: [/3379393] ESC[36m  [LOG]ESC[39m CONSOLE:: init_rand_seed: seeding with 32 bytes
2024-01-18T11:11:28.320052+01:00 scale-13 node[649898]: [nsfs/649898] ESC[31m[ERROR]ESC[39m core.util.postgres_client:: postgres_client: T00000000
|Q00000001: failed with error: TypeError: Cannot read properties of undefined (reading 'query')    at _do_query ESC[90m(/usr/local/noobaa-core/ESC
[39msrc/util/postgres_client.js:250:37ESC[90m)ESC[39m    at PostgresTable.single_query ESC[90m(/usr/local/noobaa-core/ESC[39msrc/util/postgres_cli
ent.js:679:16ESC[90m)ESC[39m    at async Timeout.vacuumAndAnalyze [as _onTimeout] ESC[90m(/usr/local/noobaa-core/ESC[39msrc/util/postgres_client.j
s:700:13ESC[90m)ESC[39m
2024-01-18T11:11:28.321065+01:00 scale-13 node[649898]: [nsfs/649898] ESC[31m[ERROR]ESC[39m core.util.postgres_client:: vacuumAndAnalyze failed Ty
peError: Cannot read properties of undefined (reading 'query')    at _do_query ESC[90m(/usr/local/noobaa-core/ESC[39msrc/util/postgres_client.js:2
50:37ESC[90m)ESC[39m    at PostgresTable.single_query ESC[90m(/usr/local/noobaa-core/ESC[39msrc/util/postgres_client.js:679:16ESC[90m)ESC[39m    a
t async Timeout.vacuumAndAnalyze [as _onTimeout] ESC[90m(/usr/local/noobaa-core/ESC[39msrc/util/postgres_client.js:700:13ESC[90m)ESC[39m
2024-01-18T11:11:28.321881+01:00 scale-13 node[649898]: [nsfs/649898] ESC[31m[ERROR]ESC[39m CONSOLE:: PANIC: process uncaughtException TypeError:
Cannot read properties of undefined (reading 'query')    at _do_query (/usr/local/noobaa-core/src/util/postgres_client.js:250:37)    at PostgresTa
ble.single_query (/usr/local/noobaa-core/src/util/postgres_client.js:679:16)    at async Timeout.vacuumAndAnalyze [as _onTimeout] (/usr/local/noob
aa-core/src/util/postgres_client.js:700:13)
2024-01-18T11:11:30.718889+01:00 scale-13 node[3379838]: [/3379838] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
2024-01-18T11:11:30.719580+01:00 scale-13 node[3379838]: [/3379838] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
```

other protocol node 
[root@scale-11 log]# systemctl status noobaa_nsfs
● noobaa_nsfs.service - The NooBaa nsfs service.
     Loaded: loaded (/etc/systemd/system/noobaa_nsfs.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-01-18 11:11:30 CET; 1h 11min ago
   Main PID: 494409 (node)
      Tasks: 11 (limit: 48877)
     Memory: 196.5M
        CPU: 24.462s
     CGroup: /system.slice/noobaa_nsfs.service
             └─494409 /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/nsfs.js

```
2024-01-18T11:11:20.808074+01:00 scale-11 node[494208]: [/494208] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: closing fd ...
2024-01-18T11:11:20.808478+01:00 scale-11 node[494208]: [/494208] ESC[36m  [LOG]ESC[39m CONSOLE:: init_rand_seed: seeding with 32 bytes
2024-01-18T11:11:21.622053+01:00 scale-11 node[494251]: [/494251] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
2024-01-18T11:11:21.627069+01:00 scale-11 node[494251]: [/494251] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
2024-01-18T11:11:21.627234+01:00 scale-11 node[494251]: [/494251] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: closing fd ...
2024-01-18T11:11:21.627612+01:00 scale-11 node[494251]: [/494251] ESC[36m  [LOG]ESC[39m CONSOLE:: init_rand_seed: seeding with 32 bytes
2024-01-18T11:11:28.083436+01:00 scale-11 node[892579]: [nsfs/892579] ESC[31m[ERROR]ESC[39m core.util.postgres_client:: postgres_client: T00000000|Q00000001: failed with error: TypeError: Cannot read properties of undefined (reading 'query')    at _do_query ESC[90m(/usr/local/noobaa-core/ESC[39msrc/util/postgres_client.js:250:37ESC[90m)ESC[39m    at PostgresTable.single_query ESC[90m(/usr/local/noobaa-core/ESC[39msrc/util/postgres_client.js:679:16ESC[90m)ESC[39m    at async Timeout.vacuumAndAnalyze [as _onTimeout] ESC[90m(/usr/local/noobaa-core/ESC[39msrc/util/postgres_client.js:700:13ESC[90m)ESC[39m
2024-01-18T11:11:28.084854+01:00 scale-11 node[892579]: [nsfs/892579] ESC[31m[ERROR]ESC[39m core.util.postgres_client:: vacuumAndAnalyze failed TypeError: Cannot read properties of undefined (reading 'query')    at _do_query ESC[90m(/usr/local/noobaa-core/ESC[39msrc/util/postgres_client.js:250:37ESC[90m)ESC[39m    at PostgresTable.single_query ESC[90m(/usr/local/noobaa-core/ESC[39msrc/util/postgres_client.js:679:16ESC[90m)ESC[39m    at async Timeout.vacuumAndAnalyze [as _onTimeout] ESC[90m(/usr/local/noobaa-core/ESC[39msrc/util/postgres_client.js:700:13ESC[90m)ESC[39m
2024-01-18T11:11:28.085748+01:00 scale-11 node[892579]: [nsfs/892579] ESC[31m[ERROR]ESC[39m CONSOLE:: PANIC: process uncaughtException TypeError: Cannot read properties of undefined (reading 'query')    at _do_query (/usr/local/noobaa-core/src/util/postgres_client.js:250:37)    at PostgresTable.single_query (/usr/local/noobaa-core/src/util/postgres_client.js:679:16)    at async Timeout.vacuumAndAnalyze [as _onTimeout] (/usr/local/noobaa-core/src/util/postgres_client.js:700:13)
2024-01-18T11:11:36.668085+01:00 scale-11 node[494555]: [/494555] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
2024-01-18T11:11:36.677653+01:00 scale-11 node[494555]: [/494555] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
2024-01-18T11:11:36.677982+01:00 scale-11 node[494555]: [/494555] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: closing fd ...
2024-01-18T11:11:36.678439+01:00 scale-11 node[494555]: [/494555] ESC[36m  [LOG]ESC[39m CONSOLE:: init_rand_seed: seeding with 32 bytes
2024-01-18T11:11:38.083833+01:00 scale-11 node[494932]: [/494932] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
2024-01-18T11:11:38.086971+01:00 scale-11 node[494932]: [/494932] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: got 32 bytes from /dev/random, total 32 ...
2024-01-18T11:11:38.093470+01:00 scale-11 node[494932]: [/494932] ESC[36m  [LOG]ESC[39m CONSOLE:: read_rand_seed: closing fd ...

```

where as below one didn't run into this postgres (panic message) 

[root@scale-12 ~]# systemctl status noobaa_nsfs
● noobaa_nsfs.service - The NooBaa nsfs service.
     Loaded: loaded (/etc/systemd/system/noobaa_nsfs.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-01-18 08:48:16 CET; 3h 34min ago
   Main PID: 3996087 (node)
      Tasks: 11 (limit: 48877)
     Memory: 98.0M
        CPU: 53.449s
     CGroup: /system.slice/noobaa_nsfs.service
             └─3996087 /usr/local/noobaa-core/bin/node /usr/local/noobaa-core/src/cmd/nsfs.js

I didn't do any operations or max it could be due to not setting the region it failed ? 

### Expected behavior
1. noobaa_nsfs panic is not a good sign. 

### Steps to reproduce
1. Didn't do any specific command on the system , except try to create a bucket with s3 user account

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. Avoid vacuumAndAnalyze call on nc nsfs without db environment. (more places like sts_rest and namespace_montior calling system_store)

### Issues: Fixed #xxx / Gap #xxx
1. will fix https://github.com/noobaa/noobaa-core/issues/7735
2. make sts_rest and namespace_monitor work on nc nsfs without db.

### Testing Instructions:
1. manually change postgres_client.PostgresTable.constructor `setInterval(this.vacuumAndAnalyze, 86400000, this).unref();` to `setInterval(this.vacuumAndAnalyze, 1, this).unref();`
2. sudo  node src/cmd/nsfs.js

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

**Review by naveenpaul1 — APPROVED** [review]

File: src/cmd/nsfs.js [hunk 1]
```diff
@@ -8,17 +8,18 @@ require('aws-sdk/lib/maintenance_mode_message').suppress = true;
 const dbg = require('../util/debug_module')(__filename);
 if (!dbg.get_process_name()) dbg.set_process_name('nsfs');
 dbg.original_console();
-
+if (process.env.LOCAL_MD_SERVER !== 'true') {
```
Comment (jackyalbo) [inline src/cmd/nsfs.js:11]: add a comment for why we need this also to the code

**Review by jackyalbo — APPROVED** [review]
