### PR TITLE
fix list_namespace_bucket

### LINKED ISSUE #3671: List bucket for Gateway bucket fails if one of the namespace resources returns error
### Environment info
- Version: **1.13.0-844732c**
- Deployment: **AZURE**
- Customer: **QA**

### Actual behavior
1. when we have a namespace bucket and we are connecting several buckets, list is failing if one of the resources returns error.

### Expected behavior
1. list of object should return from all the active/live buckets.

### Steps to reproduce
1. Go to "Resource" -> "Add Cloud Resource" and add a connection (one with already files writing on it)
2. Add another connection "s3 compatible" that it's bucket doesn't connect to any agents 
3. Connect to cyberduck and try to list the Getway bucket
4. See that we fail.

### PR DESCRIPTION
**Pull request by romayalon**
### Explain the changes
1. Added a try catch phrase inside the function that is being sent to the ns_map function.
2. Inside the catch scope, checked if the error.code was noSuchBucket - if the answer is yes - continued the loop (return undefined), else throw the error.
3. After the map loop, filtered the undefineds from res. 
4. checked if res list is undefined / is empty -if res is empty - all the list_objects() function calls threw an error with error code noSuchBucket and need to throw it after all. else, return res.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #3671 

### Testing Instructions:
1.

### CODE REVIEW

File: src/sdk/namespace_merge.js [hunk 1]
```diff
@@ -25,9 +25,18 @@ class NamespaceMerge {
...
+        let res = (await this._ns_map(async function(ns) {
+            try {
+                let ns_objects = await ns.list_objects(params, object_sdk);
+                return ns_objects;
+            } catch (err) {
+                if (err.code === 'NoSuchBucket') return;
+                throw err;
+            }
+        })).filter(objects => objects);
+        if (!res || !res.length) throw new S3Error(S3Error.NoSuchBucket);
```
Comment (guymguym) [inline src/sdk/namespace_merge.js:38]: What about buckets with no objects?

Comment (romayalon) [reply src/sdk/namespace_merge.js:38]: great question - the call to list_objects() function on a bucket that doesn't contain any objects returns: { objects: [], common_prefixes: [], is_truncated: false, next_marker: undefined } and not just undefined..

Comment (guymguym) [reply src/sdk/namespace_merge.js:38]: Gotcha!

File: src/sdk/namespace_merge.js [hunk 2]
```diff
@@ -25,9 +25,18 @@ class NamespaceMerge {
     // OBJECT LIST //
     /////////////////
 
-    list_objects(params, object_sdk) {
-        return this._ns_map(ns => ns.list_objects(params, object_sdk))
-            .then(res => this._handle_list(res, params));
+    async list_objects(params, object_sdk) {
```
Comment (jeniawhite) [inline src/sdk/namespace_merge.js:28]: It is great that we attempt to fix list_objects but I understand that we have this problem in all of our lists and even other operations (why not fix them too?). 
This is why I've coded an exception in Namespace_Merge that will do what you are trying to do.
The thing is that I've coded this for RPC responses but you can use it for SDK errors as well.
Take a look at `const reply = await this._ns_map(ns => ns.delete_object(params, object_sdk), EXCEPT_REASONS);`
Notice that we have `EXCEPT_REASONS` and take a look at the logic behind it.
You can use the same thing in your change without coding a separate method with error handling.

File: src/sdk/namespace_merge.js [hunk 3]
```diff
@@ -25,9 +25,18 @@ class NamespaceMerge {
...
+        let res = (await this._ns_map(async function(ns) {
+            try {
+                let ns_objects = await ns.list_objects(params, object_sdk);
+                return ns_objects;
+            } catch (err) {
+                if (err.code === 'NoSuchBucket') return;
+                throw err;
+            }
+        })).filter(objects => objects);
```
Comment (jeniawhite) [inline src/sdk/namespace_merge.js:37]: This is a bit confusing to read. I would maybe advise to either use the isUndefined or even add a custom omit value in the return above. At least explain using a comment that even empty buckets have an object reply and you won't omit them.

File: src/sdk/namespace_merge.js (hunk 1 above)
Comment (jeniawhite) [inline src/sdk/namespace_merge.js:38]: Once again the `_throw_if_any_failed_or_get_succeeded` method in namespace_merge handles that case scenario if you call the ns_map with `EXCEPT_REASONS` as I've stated above.

File: src/sdk/namespace_merge.js (hunk 2 above)
Comment (romayalon) [reply src/sdk/namespace_merge.js:28]: Using _throw_if_any_failed_or_get_succeeded is not relevant in this case because of 2 cases:
1. Base case: The namespace bucket is using only one namespace resource and this only one is faulty (err= 'NoSuchBucket).
2. General case: All namespace resources of the namespace bucket are faulty (err= 'NoSuchBucket').
If i'll call your function, i'll get an empty array but for these cases I would like to throw the error 'NoSuchBucket'.

Comment (romayalon) [reply src/sdk/namespace_merge.js:28]: tl;dr:
This suggestion won't work because I would like to throw an error if **all** the iterations fails on "NoSuchBucket " and the suggested function omits the errors information and does not answer this need.

Comment (jeniawhite) [reply src/sdk/namespace_merge.js:28]:
```    _throw_if_any_failed_or_get_succeeded(reply_array, except_reasons) {
        const failed = this._get_failed_responses(reply_array, except_reasons);
        if (!_.isEmpty(failed)) throw _.first(failed);
        const succeeded = this._get_succeeded_responses(reply_array);
        // Since we did not have any success and all of the errors were except_reasons we rely on the first error.
        if (_.isEmpty(succeeded)) throw _.first(reply_array).error;
        return succeeded;
    }
```
1) Base case: The only one is faulty err= 'NoSuchBucket', failed is empty because you did except that error,  succeeded is empty because the only one failed, then you return throw _.first(reply_array).error which is the err= 'NoSuchBucket' - works.
2) General case: Same as first one, all are faulty and you ignore because you did except that error, succeeded is empty because all failed, so you return the first error which is err= 'NoSuchBucket'.
3) Another case: Several are faulty with NoSuchBucket and one has an actual problem, you will return this one bucket.
4) Several are faulty and one is succeeded: you will return the succeeded if all faulty are except reason.

What doesn't work? I'm trying to figure out what I'm missing.

Comment (romayalon) [reply src/sdk/namespace_merge.js:28]: **1-3: not a bug but it's not informative enough:**
When calling this function the returned error is not an S3 error and that leads for throwing InternalError instead of the specific S3Error with the specific message. 
4: **bug:** won't work if the succeeded one is empty, it will return the error and not an empty array.

**Review by jeniawhite — APPROVED** [review]
I would change `cast_error_flag` to a custom function that is passed when calling the method. This will allow the code to be more dynamic.
Also, we still have the same problem in other lists in the namespace_merge.
You've only fixed the list_objects.
