### PR TITLE
NC | CLI | Updated the CLI response to have more info when account/bucket has been deleted

### LINKED ISSUE #8200: NC | NSFS | CLI | Improve Response (To have Details)
### Environment info
- NooBaa Version: 5.17.0
- Platform: NC

### Actual behavior
1. Currently when an account is deleted or the response contains only the code `"code": "AccountDeleted"`.
2. Currently when a bucket is deleted or the response contains only the code `"code": "BucketDeleted"`.

### Expected behavior
1. Add to the response details about the account account name that was deleted.
2. Add to the response details about the bucket name that was deleted.

### Steps to reproduce
1. Use noobaa-cli and create an account and a bucket (look at the output).

### More information - Screenshots / Logs / Other output
This is useful when you create accounts and buckets in a loop and want to easily find the details of the deleted account/bucket.

### PR DESCRIPTION
**Pull request by aayushchouhan09**
### Explain the changes
1.  Improved the response to provide a clearer message about the operations.
2.  Now, the name of the object would also be printed in the response message for more info.

### Issues: Fixed #xxx / Gap #xxx
1. Fixed: #8200 

### Testing Instructions:
1. Try creating/deleting(or any other operation) on objects(account, bucket, etc.) using noobaa-cli and check the response returned.

- [X] Tests added

### CODE REVIEW

File: src/manage_nsfs/manage_nsfs_cli_responses.js [hunk 1]
```diff
@@ -31,7 +31,11 @@ class ManageCLIResponse {
                 code: this.code,
             }
         };
-        if (this.list || this.status) json.response.reply = typeof detail === 'string' ? JSON.parse(detail) : detail;
+        if (this.list || this.status) {
+            json.response.reply = typeof detail === 'string' ? JSON.parse(detail) : detail;
+        } else {
+            json.response.message = typeof detail === 'string' ? detail : `${detail}`;
+        }
```
Comment (shirady) [inline src/manage_nsfs/manage_nsfs_cli_responses.js:38]: I think you need to explain this change in a comment.
From what I understand you're going to add a `ManageCLIResponse.` to all the responses which are not `list` or `status`, when the change is currently only related to `ManageCLIResponse.AccountDeleted` and `ManageCLIResponse.BucketDeleted`.

In my opinion, and maybe others would think otherwise I would add a property of `delete` (like list and status) and make the change only under this condition. WDYT?

File: src/cmd/manage_nsfs.js [hunk 2]
```diff
@@ -259,7 +259,7 @@ async function delete_bucket(data, force) {
         }
         await native_fs_utils.folder_delete(bucket_temp_dir_path, fs_context_fs_backend, true);
         await config_fs.delete_bucket_config_file(data.name);
-        return { code: ManageCLIResponse.BucketDeleted, detail: '', event_arg: { bucket: data.name } };
+        return { code: ManageCLIResponse.BucketDeleted, detail: `Bucket ${data.name} has been successfully deleted.`, event_arg: { bucket: data.name } };
```
Comment (shirady) [inline src/cmd/manage_nsfs.js:262]: You can probably add a small line (as I assume we test the bucket deletion) to test the change in file: test_nc_nsfs_bucket_cli.test.js

File: src/cmd/manage_nsfs.js [hunk 3]
```diff
@@ -467,7 +467,7 @@ async function update_account(data) {
  */
 async function delete_account(data) {
     await config_fs.delete_account_config_file(data);
-    return { code: ManageCLIResponse.AccountDeleted, detail: '', event_arg: { account: data.name } };
+    return { code: ManageCLIResponse.AccountDeleted, detail: `Account ${data.name} has been successfully deleted.`, event_arg: { account: data.name } };
```
Comment (shirady) [inline src/cmd/manage_nsfs.js:470]: You can probably add a small line (as I assume we test the account deletion) to test the change in file: test_nc_nsfs_account_cli.test.js

File: src/manage_nsfs/manage_nsfs_cli_responses.js (hunk 1 above)
Comment (achouhan09) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:38]: We can add message property here.

File: src/cmd/manage_nsfs.js (hunk 2 above)
Comment (achouhan09) [reply src/cmd/manage_nsfs.js:262]: Sure.

File: src/cmd/manage_nsfs.js (hunk 3 above)
Comment (achouhan09) [reply src/cmd/manage_nsfs.js:470]: Sure.

File: src/manage_nsfs/manage_nsfs_cli_responses.js [hunk 4]
```diff
@@ -31,7 +31,11 @@ class ManageCLIResponse {
                 code: this.code,
             }
         };
-        if (this.list || this.status) json.response.reply = typeof detail === 'string' ? JSON.parse(detail) : detail;
+        if (this.list || this.status) {
+            json.response.reply = typeof detail === 'string' ? JSON.parse(detail) : detail;
+        } else {
+            json.response.message = typeof detail === 'string' ? detail : `${detail}`;
```
Comment (nadavMiz) [inline src/manage_nsfs/manage_nsfs_cli_responses.js:37]: what is the difference between reply and message?

Comment (nadavMiz) [inline src/manage_nsfs/manage_nsfs_cli_responses.js:37]: can you add tests for this change

Comment (achouhan09) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:37]: reply is of JSON type and message should be one liner string explaination for the operation

Comment (shirady) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:40]: Maybe you can add this as a comment.

Comment (shirady) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:40]: From what I know if the type is `object` then `${detail}` will look like: [object Object]
For example nodejs REPL:

> > let aa = {a: 1}
> > console.log(aa)
> { a: 1 }
> > console.log(`${aa}`)
> [object Object]

If you add a small test for this change as @nadavMiz you can check it.

Comment (achouhan09) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:40]: @nadavMiz could you please explain what kind of tests you are suggesting here. Also, I have already modified some tests please check.

Comment (achouhan09) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:40]: Sure.

Comment (nadavMiz) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:40]: I think the test you modified are good enough

Comment (achouhan09) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:40]: sure, thanks

File: src/manage_nsfs/manage_nsfs_cli_responses.js [hunk 5]
```diff
@@ -31,7 +33,12 @@ class ManageCLIResponse {
                 code: this.code,
             }
         };
-        if (this.list || this.status) json.response.reply = typeof detail === 'string' ? JSON.parse(detail) : detail;
+        if (this.list || this.status) {
+            json.response.reply = typeof detail === 'string' ? JSON.parse(detail) : detail;
+        }
+        if (this.message) {
+            json.response.message = typeof detail === 'string' ? detail : `${detail}`;
```
Comment (shirady) [inline src/manage_nsfs/manage_nsfs_cli_responses.js:40]: If `message` it a string, why not set as is?

File: src/manage_nsfs/manage_nsfs_cli_responses.js [hunk 6]
```diff
@@ -71,6 +78,7 @@ ManageCLIResponse.AccountCreated = Object.freeze({
 
 ManageCLIResponse.AccountDeleted = Object.freeze({
     code: 'AccountDeleted',
+    message: {}
```
Comment (shirady) [inline src/manage_nsfs/manage_nsfs_cli_responses.js:81]: @naveenpaul1 @romayalon 
I want to verify that it is fine to add the property in the response (I don't know if you've got it structure from Scale and I want to know we have the flexibility to add it).

File: src/cmd/manage_nsfs.js [hunk 7]
```diff
@@ -252,7 +252,7 @@ async function delete_bucket(data, force) {
         }
         await native_fs_utils.folder_delete(bucket_temp_dir_path, fs_context_fs_backend, true);
         await config_fs.delete_bucket_config_file(data.name);
-        return { code: ManageCLIResponse.BucketDeleted, detail: '', event_arg: { bucket: data.name } };
+        return { code: ManageCLIResponse.BucketDeleted, detail: `Bucket ${data.name} has been successfully deleted.`, event_arg: { bucket: data.name } };
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:255]: I don't think it makes sense to add a message on every bucket operation response, we should add a this to the manage_nsfs_cli_responses file and set message for every op, we do the same on manage_nsfs_cli_errors 
and please add to all operations and not only to bucket/account delete

**Review by romayalon — CHANGES_REQUESTED** [review]

File: src/cmd/manage_nsfs.js (hunk 7 above)
Comment (achouhan09) [reply src/cmd/manage_nsfs.js:255]: Please correct me if I am wrong, if we add message on every bucket operation(then it should be something general like `Account deleted successfully.`). Here, still we need to customize it to put account/bucket etc. name in the message description.
As per the issue, we want more info on which account/bucket etc. was deleted and not a general description.

Comment (romayalon) [reply src/cmd/manage_nsfs.js:255]: the bucket name/account can be added via the argument, this issue is just an example of a bigger problem and I don't see a reason for not solving it for all the cases

Comment (achouhan09) [reply src/cmd/manage_nsfs.js:255]: Sure, I will try apply this to all operations. Thanks

Comment (achouhan09) [reply src/cmd/manage_nsfs.js]: Updated the code, please check now. Thanks

File: src/manage_nsfs/manage_nsfs_cli_responses.js [hunk 8]
```diff
@@ -131,16 +148,19 @@ ManageCLIResponse.LoggingExported = Object.freeze({
 
 ManageCLIResponse.UpgradeSuccessful = Object.freeze({
     code: 'UpgradeSuccessful',
+    message: 'Upgrade completed successfully',
```
Comment (romayalon) [inline src/manage_nsfs/manage_nsfs_cli_responses.js:151]: Can you add to all the Upgrade functions Config Directory Upgrade prefix? for example - Config Directory Upgrade completed successfully etc

File: src/manage_nsfs/manage_nsfs_cli_responses.js [hunk 9]
```diff
@@ -150,25 +170,30 @@ ManageCLIResponse.UpgradeHistory = Object.freeze({
 
 ManageCLIResponse.ConnectionCreated = Object.freeze({
     code: 'ConnectionCreated',
+    message: 'Connection has been successfully created',
```
Comment (romayalon) [inline src/manage_nsfs/manage_nsfs_cli_responses.js:173]: I think that here as well maybe Notification Connection
@alphaprinz probably can help with this response details

File: src/manage_nsfs/manage_nsfs_cli_responses.js [hunk 10]
```diff
@@ -94,25 +105,30 @@ ManageCLIResponse.AccountList = Object.freeze({
 
 ManageCLIResponse.BucketCreated = Object.freeze({
     code: 'BucketCreated',
+    message: 'Bucket has been successfully created',
```
Comment (romayalon) [inline src/manage_nsfs/manage_nsfs_cli_responses.js:108]: I would put the 'successfully' in the end of the sentance

File: src/manage_nsfs/manage_nsfs_cli_responses.js [hunk 11]
```diff
@@ -18,17 +19,19 @@ class ManageCLIResponse {
...
         this.status = status;
         this.list = list;
+        this.message = message;
     }
 
     to_string(detail) {
         const json = {
             response: {
                 code: this.code,
+                message: detail.name ? `${this.message}: ${detail.name}` : this.message,
```
Comment (romayalon) [inline src/manage_nsfs/manage_nsfs_cli_responses.js:34]: does adding the detail after the message makes sense in all cases?
and also, do we always have detail and detail.name?

File: src/cmd/manage_nsfs.js [hunk 12]
```diff
@@ -252,7 +252,7 @@ async function delete_bucket(data, force) {
         }
         await native_fs_utils.folder_delete(bucket_temp_dir_path, fs_context_fs_backend, true);
         await config_fs.delete_bucket_config_file(data.name);
-        return { code: ManageCLIResponse.BucketDeleted, detail: '', event_arg: { bucket: data.name } };
+        return { code: ManageCLIResponse.BucketDeleted, detail: { name: data.name }, event_arg: { bucket: data.name } };
```
Comment (romayalon) [inline src/cmd/manage_nsfs.js:255]: are there more cases where we want to add detail?

File: src/manage_nsfs/manage_nsfs_cli_responses.js (hunk 8 above)
Comment (achouhan09) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:151]: Sure

File: src/manage_nsfs/manage_nsfs_cli_responses.js (hunk 10 above)
Comment (achouhan09) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:108]: I think I should do this for all the operations. Thanks

File: src/manage_nsfs/manage_nsfs_cli_responses.js (hunk 11 above)
Comment (achouhan09) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:34]: whenever we want to print the name of the object in the operation then only we are adding detail at the end of message otherwise only the set message would be printed for every operation

File: src/cmd/manage_nsfs.js (hunk 12 above)
Comment (achouhan09) [reply src/cmd/manage_nsfs.js:255]: for now I have added this in delete_account() and delete_bucket() operation only. We can print the name of object in message by setting the name property in detail(for any operation) otherwise the set message would be printed

File: src/manage_nsfs/manage_nsfs_cli_responses.js (hunk 11 above)
Comment (romayalon) [reply src/manage_nsfs/manage_nsfs_cli_responses.js:34]: the issue I see here is with accessing directly to detail.name while detail can be undefined

File: src/cmd/manage_nsfs.js (hunk 12 above)
Comment (romayalon) [reply src/cmd/manage_nsfs.js:255]: please fix all the cases in this PR **or** open another gap for the rest of the cases so we will handle it in the future

File: src/manage_nsfs/manage_nsfs_cli_responses.js (hunk 11 above)
Comment (achouhan09) [reply src/manage_nsfs/manage_nsfs_cli_responses.js]: Updated to optional chain. Thanks

File: src/cmd/manage_nsfs.js (hunk 12 above)
Comment (achouhan09) [reply src/cmd/manage_nsfs.js:255]: Sure, I will open gap if there are more operations.

Comment (achouhan09) [reply src/cmd/manage_nsfs.js:262]: @romayalon I just verified other then `connection_management` there is no need add details explicitly. I have updated it. Thanks

For every operation we are printing the name of the object in the message(the code parsed the name automatically if `detail.name` is defined).

**Review by romayalon — APPROVED** [review]
